### ISSUE TITLE
[Rider App] Cancellation UI update and Cancellation reasons change

### ISSUE THREAD

**Issue by tejkranthi** [nammayatri/nammayatri#1074]
## Design

Figma link: https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=58072%3A11094&t=OWYlVsorPJrLuOkL-1

The transitions are available in the Figma prototype and must be replicated.

## Requirement

When the rider is trying to cancel the ride, modification in UI must be made as per the design provided as per the following conditions:

1. When it has been more than 90 seconds since ride acceptance - first design
2. When the driver is within 200 metres of the pickup location - second design

If the rider still wants to go ahead with the cancellation, they must be shown the set of cancellation (the list has been updated with new reasons).

### Tracking Metric

- Rider cancellation rate - Currently at 14%

**Comment by tejkranthi** [comment]
CC: @Prithivirajkota

**Comment by tejkranthi** [comment]
@AmritpalSingh6749 
Reason codes and definitions:

**Change of plans**
Reason code: CHANGE_OF_PLANS
Description: No longer require a ride due to change in plans

**Got another ride elsewhere**
Reason code: GOT_ANOTHER_RIDE
Description: Cancelling as I got a ride on another app

**Driver is not moving**
Reason code: DRIVER_NOT_MOVING
Description: Driver location wasn’t changing on the map

**Wait time too long**
Reason code: WAIT_TIME_TOO_LONG
Description: Driver was taking too long to reach the pickup location

**Wrong pickup location**
Reason code: WRONG_PICKUP_LOCATION
Description: The pickup location entered was wrong

**Other**
Reason code: OTHER
Description: Some other reason.

CC: @Prithivirajkota

**Comment by Prithivirajkota** [comment]
Custom messages to be shown for few other situations,

- Driving is moving in opposite direction
             - Message: Driver might be taking an alternate route. Please contact the driver …..
- Driver is not moving at all
            - Message: Driver is not moving? Would you like to check with the driver before cancelling?
- Driver reached the location or is within 15m of the pickup location
            - Message: Driver is near your location. Please contact …..

@tejkranthi @AmritpalSingh6749
