### ISSUE TITLE
Taking more time (b/w 16-22 sec) to load when user tried to add contact

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1570]
#1569 

[Taking more time (b/w 16-22 sec) to load when user tried to add contact when ride is not assigned as well as when ride is assigned. Also when contact list is opened , if we press back button , it takes 4-6 sec for back press action to take place](https://drive.google.com/file/d/1NcMIAct-c66hq7olOnYj3sJlJ_5z_qBO/view?usp=sharing)

**Steps to reproduce -**
1. Log in to app
2. Click on Emergency contacts from Hamburger
3. Once the list is opened click back button

**Expected result-**
When user clicks on Emergency contacts, the contact list should not take more time to open

**Actual result-**
It is taking more time to open

**Comment by MercyQueen** [comment]
Work is already in progress for this issue.
