### ISSUE TITLE
Namma Yatri text is displaying instead of Yatri text in SOS screen

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1595]
#1594 

["Namma Yatri" text is displaying instead of "Yatri" text in SOS screen and also in call support pop up screen](https://drive.google.com/drive/folders/11kc5ouDr0AaZtPLSrUZujUDw0nYKU_Tb?usp=sharing)

**Steps to reproduce**
1. Launch the apk 
2. Login with valid credentials
3. Book a ride and accept it by driver 
4. In ride assigned screen tap SOS icon
5. Observe the screen and tap "call Namma Yatri support" option and observe the pop up screen 

**Expected Result:** 
The text in the option and pop up should be "Call Yatri support"

**Actual Result**
The text is "Namma Yatri" instead of "Yatri"

**Comment by tejkranthi** [comment]
Critical

**Comment by MercyQueen** [comment]
Fixed

**Comment by rohanrp179** [comment]
Retested successfully . Closing the issue
