### ISSUE TITLE
Back button is not displaying in mobile screen,OTP screen & and new user detail screen

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1596]
#1594 

[Back button is not displaying but when user clicking there it is going back in mobile screen,OTP screen and new user details screen  when user is onboarding.](https://drive.google.com/file/d/1j_1AFMGsKLr3swFtfsNP5ZPheTd93bP5/view?usp=sharing)

**Description**

**Steps to Reproduce** 
1.Launch the application
2.Enter mobile number
3.Click on continue
3.Observe the screen
4.Click on top left corner
5.Navigating to mobile screen page but back button icon is not displayed. 

**Expected Result**
Back button should display

**Actual Result**
Back button is not displaying

**Comment by tejkranthi** [comment]
Medium priority

**Comment by MercyQueen** [comment]
This is expected as we don't have the carousal view in Yatri. So we don't have any option of going back.

**Comment by MercyQueen** [comment]
Fixed

**Comment by krupal-14** [comment]
This issue is working fine
