### ISSUE TITLE
New location which is near to already saved favourites is not getting saved as favourites (Parent_Id-#1594)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1597]
#1594 

[If we try to save any new location as favourites, and if it is near to a location which is already saved into favourites, then the new location cannot be saved in favourites ](https://drive.google.com/file/d/18GIYI3dKrvzNtOZJ8zo_DkI3GNgZ9Q8v/view?usp=sharing)

**Steps to reproduce-**
1. Log in to app
2. Click on Favourites under hamburger
3. Save one location first
4. Now try to save another location which is near to already saved location

**Expected result-**
We should be able to save another location as well though it is near to already saved location

**Actual Result-**
If any location is already saved in favourites, then any other location near to that cannot be added to favourites

**Comment by tejkranthi** [comment]
Non-critical

**Comment by rohanrp179** [comment]
Closing this as this seems to be expected
