### ISSUE TITLE
User is able to tap resend option in OTP screen even in the disabled state

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1598]
#1594 

[User is able to tap resend option in OTP screen even in the disabled state](https://drive.google.com/file/d/1_Mu8QDdcJblpFG1L8E3iDasyw0v7LgKg/view?usp=sharing)

**Steps to reproduce**
1. Launch the apk and enter the mobile number and tap continue
2. In OTP screen, tap "resend" option continuously and observe the screen 

**Expected Result**
User should not be able to tap "resend" option in the disabled state

**Actual Result**
User is getting **limit reached try after sometime** toast message and is redirecting to **mobile number entering screen**.

**Comment by tejkranthi** [comment]
Non-critical

**Comment by MercyQueen** [comment]
I've fixed this.

**Comment by rohanrp179** [comment]
Working as expected. Closing the issue.
