### ISSUE TITLE
Mobile number auto detection is not happening while logging in to Yatri (Parent_Id-#1594)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1599]
#1594 

[When trying to log in to yatri, mobile numbers are not getting detected automatically](https://drive.google.com/file/d/1OVkSCdJRv0cR_C3d_wWUT_qdC4p1ot-O/view?usp=sharing)

**Steps to reproduce-**
1. Install the app
2. Click on the app icon from app list

**Expected result-**
When enter mobile number screen appears, the mobile number should be auto detected

**Actual Result-**
The mobile number is not getting auto detected

**Comment by tejkranthi** [comment]
Medium priority

**Comment by MercyQueen** [comment]
@rohanrp179 was any mail synced with the device

**Comment by rohanrp179** [comment]
@tejkranthi [Checked this feature as discussed. Logged in with personal email id. It is showing the contact number associated with it.](https://drive.google.com/file/d/10GU3TCoGMTrpowMWnhBHY9yAi22QzvHe/view?usp=sharing) 

But lets say if scenarios is, there can be many people whose email id would be created by someone else and they are not aware of the number associated with it. 

Can we have other functionality which will fetch current sims numbers from device and display as options?

**Comment by mohdshoaib18169** [comment]
expected

**Comment by tejkranthi** [comment]
@rohanrp179 As discussed, this is expected. You may go ahead and close this issue.

**Comment by rohanrp179** [comment]
Sure. Thank you @tejkranthi
