### ISSUE TITLE
Timer is flickering  and disappearing (Parent_Id-#1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1600]
#1594 

**Description** 
[Timer is flickering  and disappearing](https://drive.google.com/file/d/19MfWDrzfZat693cakkxArscbqVtp-Uk2/view?usp=sharing)
**Steps to Reproduce** 
1.Launch the application
2.Enter the new number
3.Observe the OTP screen & Timer

**Expected Result**
OTP timer should not flicker and disappear.

**Actual Result** 
OTP timer is flickering and disappearing

**Comment by tejkranthi** [comment]
Non-critical

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
Closing it . Working as expected
