### ISSUE TITLE
For rate card in yatri, if we are on next screen and press back button, the screen does not change for other varients

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1601]
#1594 
[For rate card in yatri, if we are on next page of Driver additions/Fare Update Policy, then if we press back button and go to rate card of another variant then we are on same page of previous variant ](https://drive.google.com/file/d/1zuc5pjVk_98rktSgmqsxixaFZigxQDGG/view?usp=sharing)

**Steps To Reproduce**
1. Log in to app
2. Select  a destination and come to Estimate screen
3. Click on 'i' button of one variant 
4. Click on Driver additions/Fare Update Policy
5. Press android back button
6. Now click on 'i' of some other variant

**Expected result**
When we click on another variant, first page should be shown and not the page where previous variant was there.

**Actual result**
It is showing page of previous variant if we click on any other variant

**Comment by tejkranthi** [comment]
Critical

**Comment by MercyQueen** [comment]
Fixed

**Comment by rohanrp179** [comment]
Retested successfully. Closing the issue
