### ISSUE TITLE
Description should be more.. text in delete request screen is not translated to malayalam

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1602]
#1594 

[Description should be more.. text in "request to delete account" page should be translated to malayalam](https://drive.google.com/file/d/1ykmdVASgrshAfXrI5qwEHajwhzEDUw02/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with valid credentials 
2. Change the language from english to malayalam
3. Click "hamburger" menu and click "help and support" page 
4. Tap on "request to delete account" option
5. Observe the text below the "reason for deleting account" text field 

**Expected result**
The respective content should be translated to malayalam

**Actual Result**
**error in getCommonEN** text is displaying

**Comment by tejkranthi** [comment]
Non-critical

**Comment by MercyQueen** [comment]
fixed

**Comment by rohanrp179** [comment]
Closing the issue
