### ISSUE TITLE
If we press android back when rate card is open for next screen then previous screen should be shown (Parent_Id-#1594)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1603]
#1594 
[If we click on Driver Additions/Fare Update policy and we go to next screen, if we press android back button we should go back to previous screen instead of pop up closing ](https://drive.google.com/file/d/1hBEhGQlAUULJGYAqWEdh95BhhWBLq3uv/view?usp=sharing)

**Steps to reproduce **
1. Log in to app
2. Select a destination and come to Estimate screen
3. Click on 'i' button of one variant
4. Click on Driver additions/Fare Update Policy
5. Press android back button

**Expected result**
When pressed android back button, we should go to previous screen like how it happens when we click on "Go Back" on same screen

**Actual result**
When pressed android back button, the pop up is closing

**Comment by tejkranthi** [comment]
Non-critical

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
Retested successfully . Closing the issue
