### ISSUE TITLE
In rate card, the title is not as per figma. (Its not centred)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1605]
#1594 
[In rate card, the title is not centred ](https://drive.google.com/drive/folders/1p-Fep2giA2_4GKhC1JLDMO_S4BO9bg1M?usp=sharing)

**Steps to reproduce**

1. Log in to app
2. Select a destination and come to Estimate screen
3. Click on 'i' button of one variant

**Expected result**
The title of rate card should be centred

**Actual result**
The title should be centred

**Comment by tejkranthi** [comment]
Non-critical

**Comment by MercyQueen** [comment]
fixed

**Comment by rohanrp179** [comment]
Retested successfully. Closing the issue
