### ISSUE TITLE
"Error in getCommonENerror" is displaying instead of malayalam text contents

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1606]
#1594 
["Error in getCommonENerror" is displaying instead of malayalam text contents in cancel ride pop up and reasons screen](https://drive.google.com/file/d/1hu5qyhsiEWWRTcaZP1zFaoCufVFHSGgw/view?usp=sharing)

**Steps to Reproduce**
1. Launch the applications and login with valid credentials 
2. Book for a ride and accept it by driver 
3. Tap on hamburger menu and change the language from english to malayalam 
4. In ride assigned screen, tap on "cancel ride" option

**Expected Result**
The text content "Driver has.." should be translated to malayalam and tap on "cancel ride" option >> The reasons and the reason descriptions should be translated to malayalam 

**Actual Result**
"Error in getCommonENerror" text is displaying in place of "driver has.." text content in **cancel ride / call driver options screen** and also in **cancel ride reason selection screen**

**Comment by tejkranthi** [comment]
Non-critical

**Comment by MercyQueen** [comment]
fixed
