### ISSUE TITLE
"Loading please wait" loader is not translated to malayalam (Parent_Id-#1594)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1609]
#1594 
["Loading please wait" loader is not translated to malayalam](https://drive.google.com/file/d/1Fe3RqvWTbDgrw3jyTTpbe1bhvhfJL-14/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials 
2. Tap on hamburger and change the language from english to malayalam
3. Go to all the modules and observe the "loader" screen

**Expected Result**
"Loading please wait" loader should be translated to malayalam

**Actual Result**
"Loading please wait" text in the loader is not translated to malayalam

**Comment by tejkranthi** [comment]
Non-critical

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
Retesting successful . Closing
