### ISSUE TITLE
If user log out of device with Malayalam language, if user log in it is changed to English (Parent_Id-#1594)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1611]
#1594 

[If user is chosen Malayalam language and user log out of session, if user log in back the language  change to English](https://drive.google.com/file/d/18DJUd5uVvCA-N8PHstsaG1l2vxDK4xX_/view?usp=sharing)

**Steps to reproduce **
1. Log in to app
2. Change language to Malayalam
3. Logout of session and log in again

**Expected result**
When user log in back, the session should be in same language in which is logged out if we are log in immediately 

**Actual result**
When user log in back, the new session is starting in English only irrespective of the language selected at time of log out

**Comment by tejkranthi** [comment]
Non-critical

**Comment by MercyQueen** [comment]
this is the expected behaviour.

**Comment by rohanrp179** [comment]
@tejkranthi is this expected? Because if user doesn't understand English at all and very comfortable to use native language only, then it will be not good User Experience for him.
Pls suggest you opinion here

**Comment by tejkranthi** [comment]
@rohanrp179 You are right. Ideally it should be the language selected by the user post-login. But, for now, we can let it pass. We need to fix this on Namma Yatri as well. Please document this to fix in upcoming releases.

**Comment by rohanrp179** [comment]
Sure.
@MercyQueen can we fix this in coming hotpush. Or shall we keep this for any Namma Yatri fix only?

**Comment by mohdshoaib18169** [comment]
expected

**Comment by rohanrp179** [comment]
@tejkranthi Closing this issue as it is said expected and can be fixed in NY
