### ISSUE TITLE
Cursor should disappear when user clicks on drop down (Parent_Id-#1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1612]
#1594 

**Description**
[Cursor should disappear when user clicks on drop down](https://drive.google.com/file/d/10mNI-6Sl6-ToWUix8Zt6KDfEJcy_uJVS/view?usp=sharing)

**Steps to Reproduce**
1.Launch the application
2.Enter valid mobile number & OTP
3.Enter name --> Click on gender drop down
4.Observe 

**Expected Result**
Cursor should disappear 

**Actual Result**
Cursor is not disappearing

**Comment by tejkranthi** [comment]
Non-critical

**Comment by mohdshoaib18169** [comment]
expected

**Comment by rohanrp179** [comment]
@tejkranthi is this expected?

**Comment by tejkranthi** [comment]
This is not expected behaviour. @mohdshoaib18169

**Comment by rohanrp179** [comment]
Sure.. Closing this issue on a count that will be fixed in other apk @tejkranthi
