### ISSUE TITLE
Auto icon is displaying in the no rides found screen 

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1613]
#1594 
[Auto icon is displaying in the sorry we could'nt find any rides screen ](https://drive.google.com/file/d/1ZyMOyp-gjb_X0K1eebB0enfQJnbmL3lw/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials
2. Search for a ride and wait until try again screen 

**Expected Result**
A car icon should display when no rides are found 

**Actual Result**
An auto icon is displaying

**Comment by tejkranthi** [comment]
Critical

**Comment by MercyQueen** [comment]
fixed.
