### ISSUE TITLE
Submit request should not happen with only digits as content (Parent_Id-#1594)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1615]
#1594 

[1.If we enter digits only for description while deleting account, it is getting submitted
2. The note shown below textfield "Description should be more than 10 characters" disappears after entered 6 characters or entered 6 spaces](https://drive.google.com/file/d/1uSSoOzskf90L4KHhcDkEr0CH3C-bbhxm/view?usp=sharing)

**Steps to reproduce **
1. Log in to app
2. Go to Help and Support from side menu
3. Click on "Request to delete account"
4. Enter digits only to submit the Request 
5. Now enter spaces or any character for 6-7 times

**Expected result**
1.If we enter only digits, the request should not be submitted. It is not useful to have a delete request description with only digits mentioned.
2. If we enter space and characters for 10 times then only the note, "Description should be more than 10 characters", should disappear and not before 

**Actual result**
1. It is allowing only digits to submit the request
2. The note should not disappear before we input 10 space and characters combination

**Comment by tejkranthi** [comment]
Non-critical

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
Working as expected. Closing the issue
