### ISSUE TITLE
Ride assigned screen is not displaying for the user after the ride is accepted by the driver

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1617]
#1594 
[Ride assigned screen is not displaying for the user after the ride is accepted by the driver](https://drive.google.com/file/d/1yw-25d9BcS_LEMlJI9Isobn7is5Jw3mk/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with the valid credentials
2. Search for a ride and minimize the application
3. Accept the ride by driver in second batch
4. Then maximize the user application

**Expected result**
User should view the ride assigned screen

**Actual result**
User is able to view the ride searching screen and after some time only, ride assigned screen is displaying

**Comment by tejkranthi** [comment]
Critical

**Comment by Sumedh-14** [comment]
@MercyQueen Whether this issue is fixed. If so can you please move it to "Ready" card

**Comment by ashkriti** [comment]
There is a delay for 2-3 seconds due to the API Latency.

**Comment by Sumedh-14** [comment]
This issue is fixed so closing this issue.
