### ISSUE TITLE
The car size is becoming smaller as we zoom in the map while tracking the user moment (Parent_Id-#1594)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1618]
#1594 

[1. The car size is reducing as we zoom in the map while  tracking the movement of user
2. The user experience of tracking is not as good as NY tracking after ride starts](https://drive.google.com/file/d/1EFUiOXLW_KW1igYkjXMh-uHO0VcKjJKR/view?usp=sharing)

**Steps to reproduce **
1. Book a ride and start ride using ride OTP
2. When driver movement starts observe the screen, the screen should zoom automatically. We have to zoom to have clear view
3. Also if we zoom in to the last point the size of car keep reducing

**Expected result**
1. The car size should be appropriate to map size as we zoom in 
4. The user experience can be same as NY user movement tracking

**Actual result**
1. The car size is reducing
2. The user experience is not good. If we have to track the user movement we have to zoom the map always

**Comment by tejkranthi** [comment]
Non-critical

**Comment by mohdshoaib18169** [comment]
@rohanrp179 , can increasing the vehicle size by some factor will solve the issue ?

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by mohdshoaib18169** [comment]
@MercyQueen , @rohanrp179 , Increased the size of the vehicle
