### ISSUE TITLE
Yatri logo and night time related text to be removed from invoice

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1620]
#1594 

[1. The yatri logo from invoice should be removed
2. The night charges related text should be removed form invoice pdf
[YATRI_RIDE_Wed, 12th Jul10.01 PM.pdf.pdf](https://github.com/nammayatri/nammayatri/files/12030764/YATRI_RIDE_Wed.12th.Jul10.01.PM.pdf.pdf)]

**Comment by tejkranthi** [comment]
Critical

**Comment by rohanrp179** [comment]
retested successfully
