### ISSUE TITLE
In about screen, "namma Yatri" link is displaying instead of "yatri" link (Parent_Id-#1594)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1623]
#1594 
[In about screen, "namma Yatri" link is displaying instead of "yatri" link](https://drive.google.com/file/d/1cwk6dvsd2Gu3LvpCNzu2lzzxRyHtSfqb/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials
2. Go to "about" screen and observe

**Expected Result**
In about screen, Yatri link should display

**Actual Result**
In about screen, Namma Yatri link is displaying

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Sumedh-14** [comment]
[When the language is changed to **malayalam** **"namma yatri"** link is displaying instead of **"Yatri"** and also the text content is not same in malayalam as in english for the "registered addresses" and "corporate addressss" ](https://drive.google.com/file/d/1qEot8O9-nAO5OMrEy49ZR1IebLSRvWpW/view?usp=sharing)

@MercyQueen

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
The text is as expected. Closing the issue
