### ISSUE TITLE
FCM notifications are not received when the driver sent any message to user after the ride is assigned (Parent_Id-#1594)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1625]
#1594 
[FCM notifications are not received for the user when the driver sent any message to user after the ride is assigned](https://drive.google.com/file/d/1UDZFaYDUr_EC-_kR_qLiKsG1Ua236fvt/view?usp=sharing) ( In Google Pixel)

**Steps to Reproduce**
1. Launch the application and login with valid credentials
2. Request a ride and accept it by driver 
3. Minimize or kill the user application and sent a message from driver 

**Expected Result**
FCM notifications should be received by the user 

**Actual Result**
User is not receiving FCM notifications

**Comment by tejkranthi** [comment]
Medium priority

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
Working as expected . Closing
