### ISSUE TITLE
When driver accepts ride from special zone jatri saathi OTP screen is displaying at user end. (Parent_Id-#1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1626]
#1594 

**Description**
[When driver accepts ride from special zone jatri saathi OTP screen is displaying at user end](https://drive.google.com/file/d/1kUy2_NjeeFsXEoIohSqLGS_qyFGbo798/view?usp=sharing)

**Steps to Reproduce**
1.Launch the application.
2.Login with valid credentials.
3..Book a ride from special zone(Cochin International airport).
4.Accept it from driver end.
5.Observe the user OTP screen

**Expected Result**
Yatri OTP screen should display.

**Actual Result**
Jatri saathi OTP screen is displaying

**Comment by tejkranthi** [comment]
Non-critical (since absence of BAP special zone case is handled).
CC: @MercyQueen

**Comment by guptamanav422** [comment]
fixed

**Comment by rohanrp179** [comment]
Closing
