### ISSUE TITLE
OTP screen is changing after killing/Minimizing and  relaunching the user apk. (Parent_Id-#1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1628]
#1594 
**Description** 
When user book a ride from special zone and driver accept the ride.after killing and relaunching  the user applications user is getting  namma yatri otp screen.

**Steps to Reproduce.**
1.Launch the application.
2.Login with valid credentials.
3.Book a ride from special zone(cochin international airport).
4.Driver accept the ride.
5.Jaatri Saathi OTP screen is displaying.
6.Kill and relaunch the user application.
7.Observe the otp screen. 

**Expected Result** 
OTP screen should not change

**Actual Result**
OTP screen is changing.

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by guptamanav422** [comment]
fixed

**Comment by rohanrp179** [comment]
Closing it as it is retested successfully
