### ISSUE TITLE
Messages which has been received and sent in the chat screen are not displaying when the app is relaunched (Parent_Id-#1594)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1631]
#1594 
[Messages which has been received and sent in the chat screen are not displaying when the app is relaunched](https://drive.google.com/file/d/1ehKy8YzMdz2DgTXXxwqysOErR-qvKdF_/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials 
2. Book for a ride and accept it by driver
3. Go to chat screen and sent any message from user to driver and vice versa
4. Minimize the application 
5. Relaunch the application after some time and go to chat screen and observe

**Expected Result**
Previous messages should display 

**Actual Result**
Previously sent messages are not displaying

**Comment by tejkranthi** [comment]
Critical

**Comment by MercyQueen** [comment]
@Sumedh-14 is it reproducing every time?

**Comment by Sumedh-14** [comment]
yes @MercyQueen

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
[Now the message are coming but lagging by 1-2 sec. Is it ok? ](https://drive.google.com/file/d/18FdMgay_c21WkvjMIFYMUWiwGcndrYfe/view?usp=sharing)
@tejkranthi

**Comment by tejkranthi** [comment]
@MercyQueen Is this a API latency issue? If yes, we can skip.

**Comment by MercyQueen** [comment]
@PraveenGongada can you please help here. I think its not an API  Latency issue. Delay is expected right?

**Comment by PraveenGongada** [comment]
Delay of 1-3 sec will be there to load the messages

**Comment by rohanrp179** [comment]
ok on comment of Dev, closing the issue @tejkranthi
