### ISSUE TITLE
User is not able to book a ride from special location(cochin international airport ) even though the driver is nearby. (Parent_Id-#1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1636]
#1594 
**Description**
User is not able to book ride even though the driver is nearby.

**Steps to Reproduce**
1.Launch the application.
2.Login with valid credentials.
3. Try to Book a ride.
4. Observe the user screen.

**Expected Result**
User should able to book a ride.

**Actual Result**
User is not able to book a ride

**Comment by tejkranthi** [comment]
Non-critical (since absence of BAP special zone case is handled).
CC: @MercyQueen

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by guptamanav422** [comment]
fixed

**Comment by guptamanav422** [comment]
fixed

**Comment by rohanrp179** [comment]
The previous issue is not observed. Closing the issue
