### ISSUE TITLE
Chat messages are not focusing on current message in user apk (Parent_Id-#1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1640]
#1594 
**Description**
[Chat messages are not focusing on current message in user apk](https://drive.google.com/file/d/1zfyzyD28kEvV0sHHkw7n32wVMpUES_sy/view?usp=sharing)

**Steps to Reproduce**
1.Launch the apk
2.Login with valid credentials 
3.Book a ride
4.Driver accept the ride
5.Chat between driver and customer 
6.Wait for sometime
7.Again start chatting
8.Observe in user screen

**Expected Result**
Current chat should be focused

**Actual Result**
Current messages are not focusing

**Device** 
Google pixel (Android 13)

**Comment by tejkranthi** [comment]
Non-critical

**Comment by rohanrp179** [comment]
@mohdshoaib18169 Can you comment here if this is fixed or deferred
cc- @tejkranthi

**Comment by mohdshoaib18169** [comment]
It just taking time to auto focus , after few seconds it will automatically auto focus the new messages ,
So its deferred @rohanrp179

**Comment by rohanrp179** [comment]
Closing it
