### ISSUE TITLE
Inaccurate date and time in the driver image is displayed even though when time is network provided. (Parent_Id-#1649)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1653]
#1649 

[If we make time different than network time, the inaccurate image will be displayed. If we start the network back, the same image is over-shown on other functionalities](https://drive.google.com/file/d/1iDRxbxUrQQ-cGgk3z0wpW5oVnb_V1YBn/view?usp=sharing)

**Steps to reproduce**
1. Change the time from network to manual
2. Try to open the app and login
3. Once the inaccurate image is shown, again change the timing to network time from manual
4. Repeat this 2-3 times
5. Now keep the time to network only and try to login.

**Expected result**
The inaccurate image shuold be shown only when network time and device time is not same

**Actual result**
The inaccurate image is shown over other functionality’s

**Comment by guptamanav422** [comment]
Fixed

**Comment by rohanrp179** [comment]
Closing as this feature is on. hold
