### ISSUE TITLE
The selected Gender is not highlighted in the radio button options (Parent_Id-#1649)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1660]
#1649 
[The selected Gender is not highlighted in the radio button options](https://drive.google.com/file/d/1HhLEvOwPeul1pX6xY49ecWz7i6gl-3Cm/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with valid credentials
2. Go to personal details 
3. Under gender tap "edit" option and select a gender
4. tap on "confirm"
5. Go back to homescreen
6. Again go to personal details page 
7. Tap "Edit" option under gender

**Expected result**
The selected gender should be highlighted 

**Actual result**
The selected gender is not highlighted

**Comment by Rajaprabhu-Natrajan** [comment]
Closing this issue as it is working fine
