### ISSUE TITLE
Driver is not getting intial chat suggestions both at before pickup as well as at pickup (Parent_Id-#1649)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1663]
#1649 
**Description**
[Driver is not getting intial chat suggestions both at before pickup as well as at pickup](https://drive.google.com/file/d/1VYnCbv7aHii505TAGF6-2thaJC2HVoBI/view?usp=sharing)

**Steps to Reproduce.**
1.Launch the driver apk.
2.Login with valid credentials. 
3.Accept the ride.
4.Open Chat screen in driver apk.

**Expected Result**
Driver should get initial chat suggestions.

**Actual Result** 
Driver is not getting initial chat suggestions.

**Device Details**
Vivo Y21(Android 12)

**Comment by PraveenGongada** [comment]
Fixed in #1668

**Comment by krupal-14** [comment]
Retested working fine
