### ISSUE TITLE
Driver overlay messages is displaying even though user cancels the ride (Parent_Id-#1649)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1664]
#1649 
**Description**
[Driver overlay messages is displaying even though user cancels the ride ](https://drive.google.com/file/d/1Wqav95QKBdDRYkCyzJwUxNTlQqR2F8Rn/view?usp=sharing)

**Steps to produce**
1.Launch the driver apk
2.Login with valid credentials 
3.Accept the ride
4.Minimize driver apk
5.Send message from user
6.Driver received message overlay
7.Cancel the ride from user
8.Observe  the driver screen

**Expected Result**
Driver message overlay should disappear 

**Actual Result**
Driver message overlay is not disappearing 

**Device details**
Vivo Y21(Android 12)

**Comment by PraveenGongada** [comment]
Fixed in #1668

**Comment by krupal-14** [comment]
Retested working fine
