### ISSUE TITLE
NYP<added driver location deviation service bug> <Functionality is not working as expected> (Parent_Id-#1649)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#1666]
#1649 

**When log show "Deviation_Count", We should get TRUE in no_of_deviation (bpp.ride)**
This functionality should show TRUE is driver app found with any Deviation_count. 

**To Reproduce**
-> Book a ride from A to B.
-> Start the Ride at A.
-> End the Ride at A. 
-> Validate the deviation_count in Android side logs. 
->  Validate the bpp.ride table. 
-> Validate the column (noofdeviation) for ended Ride. 

**Expected behavior**
Should show "TRUE" as Deviation_count should validated. 
**Screenshots**

**App (please complete the following information):**
 - Device: [all
 - OS: [all]
 - Version [all]

**Additional context**

**Comment by soumyajit2304** [comment]
https://github.com/nammayatri/nammayatri/pull/1669

**Comment by krupal-14** [comment]
As we have Retested the fix. Not working as expected so we are re-opening this issue. @soumyajit2304 @aryan-13
