### ISSUE TITLE
Unable to add image in android 13 (Parent_Id-#1649)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1673]
#1649 
**Description :**
["Unable to add image in android 13 even after enable all the permission, asking permission
"" Please alow permission to capture image"""](https://drive.google.com/file/d/1lsp9seI2jBetIOhSVevB6k24-umeidpb/view?usp=sharing)

**Steps to reproduce:**
1. Assign ride
2. Click on help and support
3. Click on lost and found
4. Select one ride
5. Add image
6. Verify

**Expected** : Camera/ gallery option should open

**Actual** : Showing permission message
**Device tested** : Android 13 - Samsung M53

**Comment by aryan-13** [comment]
Fixed

**Comment by Sumedh-14** [comment]
It is working fine and so marking it as closed 

https://drive.google.com/file/d/1B6IHBCmfwtiE_QBHWKWBL9ukvynUlox2/view?usp=sharing

**Comment by johnruban-4050** [comment]
Retested and working fine as expected in Pixel 6A

**Comment by krupal-14** [comment]
Not able to upload image in Android 11  Device-Redmi 9A.
