### ISSUE TITLE
Previous chats are getting clear when driver kills and relaunch apk (Parent_Id-#1649)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1677]
#1649 

[Previous chats are getting clear when driver kills and relaunch apk- ratio - (03/05)](https://drive.google.com/file/d/1c9VSOn4jf_ojwPYvg6KStQmM0ifGM0JW/view?usp=sharing)

**Steps**:
1. Assign ride
2. Send messages from driver and user side
3. Wait some time 
4. Kill and reluanch driver apk
5. Open chat
6. Verify chat screen

**Expected** : Old chats should display 

**Actual** : Chats are getting cleared

**Device tested**: All Devices

**Comment by PraveenGongada** [comment]
fixed in #1668

**Comment by krupal-14** [comment]
Retested and working fine as expected in Pixel 6A
