### ISSUE TITLE
"In-accurate Date & Time" screen is coming in profile screen, help and support screen. (Parent_Id-#1649)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1678]
#1649 
["In-accurate Date & Time" screen is coming in profile screen, help and support screen.](https://drive.google.com/file/d/1_ppRVeApOSpPG0sILpUZAxh_qQnzEgGr/view?usp=sharing)

**Steps to reproduce**
1. Change device timing
2. Open the application
3. Again change to correct time and date
4. Tap on Profile, Help and support

**Expected Result**
"In-accurate Date & Time" screen should not get

**Actual Result**
"In-accurate Date & Time" screen is coming in profile screen, help and support screen.

**Comment by guptamanav422** [comment]
Fixed
