### ISSUE TITLE
driver is keep on getting "In-accurate Date & Time" screen even device time is correct also (Parent_Id-#1649)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1680]
#1649 
[driver is keep on getting "In-accurate Date & Time" screen even device time is correct also](https://drive.google.com/file/d/15rV9sWq7CLCWrZldx9B8IAqW1_VHbp2s/view?usp=sharing)

Steps to reproduce
1. Change device timing
2. Open the application
3. Again change to correct time and date 
4. On observe the app

Expected Result
Driver should not get "In-accurate Date & Time" screen when device time is correct

Actual Result
driver is keep on getting "In-accurate Date & Time" screen even device time is correct also

**Comment by guptamanav422** [comment]
Fixed
