### ISSUE TITLE
Yatri app is crashed twice (Parent_Id-#1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1681]
#1594 
**Description**
[yatri app is crashed twice]
(1.https://console.firebase.google.com/u/0/project/jp-beckn-dev/crashlytics/app/android:net.openkochi.yatri.debug/issues/b674ae7b9970d80d2056bf7051daf46d?time=last-hour&sessionEventKey=64B1167B03A700016B22BB78106BAB2A_1834051010262703902

2.https://console.firebase.google.com/u/0/project/jp-beckn-dev/crashlytics/app/android:net.openkochi.yatri.debug/issues/08167e47cf7c518e98859819a57c7f5f?time=last-hour&sessionEventKey=64B116AB02D000016CC7BB78106BAB2A_1834051341482161638)

[1st crash image](https://drive.google.com/file/d/1u4VyyMFDiY5M_I8tVkdbSr04dBTN0kRI/view?usp=sharing)
[2nd crash iamge ](https://drive.google.com/file/d/1hEa7WHNYX0Fdvf5FNqieTM_EQ7MCMZGg/view?usp=sharing)

When crashed user is in personal details page.

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
No crashes found. Closing the issue
