### ISSUE TITLE
In cancel ride screen if we do android back press some times getting Empty rides and some times screen is refreshing (Parent_Id-#1649)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1683]
#1649 
[In cancel ride screen if we do back press some times getting Empty rides and some times screen is refreshing](https://drive.google.com/file/d/1HhatD_2KrMxiYnEEUkb8_QwmaekWYmaX/view?usp=sharing)

**Steps to reproduce**
1. Launch the application
2. Tap on My rides
3. Tap on Completed rides
4. Tap on Android back press

**Expected Result**
It should come to home screen

**Actual Result**
In cancel ride screen if we do android back press some times getting Empty rides and some times screen is refreshing.

**Comment by AlluGowthami28** [comment]
@aryan-13 Why this issue not fixed?

**Comment by aryan-13** [comment]
Its fixed now
