### ISSUE TITLE
Polyline is disappearing when user try to add favourites in ride assigned / started state(Parent_Id-#1594)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1690]
#1594 
[Polyline is disappearing when user try to add favourites in ride](https://drive.google.com/file/d/1-vr-R3pYR7TyC8SzsD_UUsuD7l3F9Fvd/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with valid credentials initiate one ridesearch by user
2. Assign / start a ride by driver
3. verify the polyline
4. Click on hamburger menu
5. Add favourites through set on map
6. Navigate back to ride screen
7. Verify Polyline

**Expected Result**
Polyline should display 

**Actual Result**
Polyline is not displaying

**Comment by mohdshoaib18169** [comment]
@rohanrp179 , is it going for few seconds or permanently ?

**Comment by mohdshoaib18169** [comment]
@Sumedh-14 , its going for some moment only , it will come within 20 seconds due to api callback

**Comment by rohanrp179** [comment]
@mohdshoaib18169 [The polyline is not coming back within 20 seconds if we perform above steps. It is coming back when ride is assigned. 
Can you fix this issue when ride is assigned and added favourite from set on map ](https://drive.google.com/file/d/1B0lh1QDKcqsQ5zadIycXsqu_qX-bLNRL/view?usp=sharing)

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by rohanrp179** [comment]
Working as expected. Closing it
