### ISSUE TITLE
For driver more than 500 m away, cancel ride message is giving error message text (Parent_Id- #1594)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1702]
#1594 

[When user is cancelling the ride, and if driver is more than 500 m distance then error message is reflected on top](https://juspay.slack.com/files/U04HT9NBMQW/F05H4E2JL13/23-07-15-21-56-32.mp4)

**Steps to reproduce**
Log in to app
Book a ride
Driver should be more than 500 m away
Cancel the ride

**Expected result**
The message should not contain any error message text

**Actual**
It is showing error message

**Comment by MercyQueen** [comment]
Fixed

**Comment by rohanrp179** [comment]
Closing it as retested successfully
