### ISSUE TITLE
Report An issue - When click on Call support center, it's not showing proper number  (Parent_ID-#1649)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1725]
#1649 
[Report An issue - When click on Call support center, it's not showing proper number](https://drive.google.com/file/d/1BQcx963R1ji2xEbB1ffi2eNu5HrMaFTE/view?usp=sharing)

Step to reproduce:
1. launch the app
2. click on help & support 
3. Click on Report an Issue
4. Click Call support center
5. Observe the issue

Expected Result:-
Call support center number should be shown correctly

Actual Result:-
It's not showing proper number in the dial pad

reproduce rate: 5/5

Device - Oppo F7

**Comment by aryan-13** [comment]
Will be fixed in CUG
