### ISSUE TITLE
 While refresh Loader is displaying continuously (Parent_Id-#1649)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1729]
#1649
After the Page is refresh the loader is displaying continuously

Steps to reproduce :
Assign ride
Click on help and support icon
Tap on lost and found
Refresh the page and Verify

Expected :
Loader should not display continuously

Actual :
Loader is displaying continuously

Device tested : Android 13 - Pixel 6A

https://github.com/nammayatri/nammayatri/assets/137036742/3d274efc-ed34-4c09-aa8c-8cdb8b8c7953

**Comment by aryan-13** [comment]
@johnruban-4050 Not reproducible

**Comment by johnruban-4050** [comment]
@aryan-13 In emergency contacts -> Tap on add emergency contacts -> Scroll down and then scroll up and observe

**Comment by johnruban-4050** [comment]
Issue still exist
