### ISSUE TITLE
When user click on Message text field for new message to input manually, the last message should be shown when keypad is up (Parent_Id-#1594)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1791]
#1594 

[When user clicks on Message text field to enter text using keyboard, when keyboard is up, the last message sent should also go up. Here we have to scroll up to check the message](https://drive.google.com/file/d/18BQJswvmR9VLsWSLeej9-nI29Xp_Cfc8/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Book a ride
3. Do some message exchange so that message need scrolling to read first and last message
4. Now click on Message textfield to input manually

**Expected result**
When keyboard is up, the last message also should be up

**Actual result**
The last message is not going up when keyboard is up.

**Comment by rohanrp179** [comment]
This can be fixed and send directly to CUG @mohdshoaib18169 @MercyQueen

**Comment by Akash2172** [comment]
This issue exists in Namma Yatri as well so we will fix in that
cc : @tejkranthi

**Comment by rohanrp179** [comment]
Sure . Closing it as this is in prod of NY
