### ISSUE TITLE
Some of the cancel reason text is cropping while cancelling the ride (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1804]
#1803 

[Some text which gives reason of cancellation are cropping](https://drive.google.com/file/d/1b-T9bPA5-Im38WCMHe1ZsDrMhKkNGFTw/view?usp=sharing)

[Hindi text, the Ookar is cropped](https://drive.google.com/file/d/1hUDwIci508_oo26vr0u1V5iI2iduWMbr/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Book a ride
3. Now cancel a ride and choose all options (reason of cancellation)

**Expected result**
The text should not crop

**Actual result**
Text is cropping

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
It is working fine.

**Comment by rohanrp179** [comment]
This issue was fixed in last build but again coming in this build. @MercyQueen @Rohit4997 

[Some text which gives reason of cancellation are cropping](https://drive.google.com/file/d/1b-T9bPA5-Im38WCMHe1ZsDrMhKkNGFTw/view?usp=sharing)

[Hindi text, the Ookar is cropped](https://drive.google.com/file/d/1hUDwIci508_oo26vr0u1V5iI2iduWMbr/view?usp=sharing)

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
