### ISSUE TITLE
OTP timer should not flicker or it should start from 30 sec [Parent_Id-1803]

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1805]
#1803 
**Description** 
[OTP timer should start from 30sec when user go back to mobile number screen and clicking on continue.](https://drive.google.com/file/d/1RtZJUjY2kZXmY3-TIkYK3r5pYiohkM1v/view?usp=sharing)

**Steps to reproduce**
1.Launch the  apk.
2.Enter Mobile number.
3.Enter wrong OTP.
4.Go back .
5.Click on continue.
6.Observe the OTP timer.

**Expected Result**
OTP timer should start from 30 sec when user click on continue and OTP timer should not filcker.

**Actual  Result**
OTP timer is not starting from 30 sec and it is flickring.

**Comment by krupal-14** [comment]
Retested working fine.

**Comment by MercyQueen** [comment]
Fixed.
