### ISSUE TITLE
The ballon stick shown on taxi stand of special zone is not aligned properly (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1806]
#1803 

[The ballon stick denoting the taxi stand for spec location is not properly aligned. ](https://drive.google.com/file/d/14F7TZvUmvPDYgyY9coZBz3jni3SOjsXT/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Select source as any of spec zone
3. Select any destination

**Expected result**
The ballon stick should be properly aligned to the taxi stand point

**Actual result**
It is not

**Comment by Rohit4997** [comment]
Deferred

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Issues is still exist moving it to backlog

**Comment by MercyQueen** [comment]
@krupal-14 can you please attach screenshot for this.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
Closing
