### ISSUE TITLE
Remove text is cropping on Favourites (Parent_Id- 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1810]
#1803 

[Remove text is cropping in Favourites screen ](https://drive.google.com/file/d/1DwnoDYhQI9OM3tm6_IhTqvNR57X23eM6/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Save some location with large name
3. Go to Favourites 

**Expected result**
The remove text should not crop

**Actual result**
It is cropping to next line

**Comment by MercyQueen** [comment]
Fixed.
