### ISSUE TITLE
The vehicle image is not shown on Ride OTP screen (Parent_ID - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1811]
#1803 

[The vehicle image is not shown on Ride OTP screen](https://drive.google.com/file/d/1QAspHNMJDLSAVjavZSXmK-XyG1ziFTyc/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Book a ride

**Expected result**
The vehicle image should be shown

**Actual result**
It is not shown

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Car symbol is not displaying in OTP screen @MercyQueen

**Comment by johnruban-4050** [comment]
Retested and working fine as expected 
![WhatsApp Image 2023-07-31 at 4 14 23 PM](https://github.com/nammayatri/nammayatri/assets/137036742/9db689e0-30cc-4fd4-a3c8-fdcfb4565dd5)
