### ISSUE TITLE
Some numbers are cropped if contact name is lengthy (Parent_Id- 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1812]
#1803 

[Some numbers are cropped if contact name is lengthy](https://drive.google.com/file/d/1CL0dGl1O-QmpfJwsGAGs1viFni3V2XDt/view?usp=sharing)

**Steps to reproduce**
Log in to app
Select source as any of spec zone
Select any destination

**Expected result**
The number should not crop

**Actual result**
It is cropping

**Comment by krupal-14** [comment]
It is working fine
