### ISSUE TITLE
Image is not displaying when user clicks on cancel ride(Parent_id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1814]
#1803 
**Description**
[Image is not displaying when user clicks on "cancel ride"](https://drive.google.com/file/d/1cUOE3d8f-q1Ml-mx1S9ycb29V4o2CmjL/view?usp=sharing)

**Steps to Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride. 
4.Confirm the ride.
5.Click on cancel ride.
6.Observe  the screen.

**Expected Result**
Image should display.

**Actual result** 
Image is not displaying.

**Comment by johnruban-4050** [comment]
Retested and working fine as expected 
![WhatsApp Image 2023-07-31 at 4 16 13 PM](https://github.com/nammayatri/nammayatri/assets/137036742/2f6f6582-0498-421d-8a2e-810f036585ae)
