### ISSUE TITLE
In app chat message are sent or received twice (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1815]
#1803 

[Message are sent or received twice](https://drive.google.com/file/d/1JHTaFymmrwNR1PJt5mnMuBmfEzblzoOn/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Book a ride
3. Send or receive message from in app chat

**Expected result**
The message should be sent or received only once

**Actual result**
It is happening twice

**Comment by krupal-14** [comment]
Retested working fine.
