### ISSUE TITLE
Spacing is more in remove emergency contacts screen(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1816]
#1803 
**Description**
[Spacing is more in remove emergency contacts screen](https://drive.google.com/file/d/1-bNT_DKlEOWKfiWG9PhpEDoIgBxPkuw5/view?usp=sharing)

**Steps to Reproduce**
1.Launch the apk
2.Login with valid credentials.
3.Click on hamburger. 
4.Click on emergency contacts.
5.Click on add emergency contacts
6.Add contacts .
7.Click on remove 
8.Observe  the screen spacing is more.

**Expected Result** 
Spacing should not be that  much.

**Actual Result** 
Spacing is more.

**Comment by MercyQueen** [comment]
Fixed.
