### ISSUE TITLE
Yatri sathi symbol is not displaying(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1818]
#1803 
**Description** 
[Yatri sathi symbol is not displaying in About screen.](https://drive.google.com/file/d/1JiFM7OwDTlhkhvd0F-zzJj-yB4htVG1o/view?usp=sharing)

**Steps to Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Click on hamburger.
4.click on About 
5.Observe the screen.

**Expected Result** 
Yatri sathi symbol should display

**Actual Result** 
Yatri sathi symbol is not displaying.

**Comment by johnruban-4050** [comment]
Retested and working fine as expected 
![WhatsApp Image 2023-07-31 at 4 17 59 PM](https://github.com/nammayatri/nammayatri/assets/137036742/659af8d5-df76-4288-803f-bb5d17a5c4ba)
