### ISSUE TITLE
In Invoice, the Rupee symbol is shown twice (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1819]
#1803 

[In Invoice, the Rupee symbol is shown twice](https://drive.google.com/file/d/1YWQjDybYJ7ME738J2g-zkFUJ7ZdbECwn/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Go to My rides
3. Select a ride and download invoice

**Expected result**
The Rupee symbol should come only once

**Actual result**
It is coming twice

**Comment by MercyQueen** [comment]
Fixed. It will be updated it ipa release
