### ISSUE TITLE
Invoice File name is displaying as NY_Ride File(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1821]
#1803 
**Description** 
[Invoice File name is displaying as NY_Ride File](https://drive.google.com/file/d/17P9zIyEQ-BiIsQSiCK7VxLps8ZhVIWoU/view?usp=sharing)

**Steps to Reproduce**
1.Launch the apk
2.Login with valid credentials 
3.Book a ride.
4.Complete a ride.
5.Click on Hamberger
6.Click on My ride
7.Click on Particular ride-->View Invoice -download
8.Obsereve the file name.

**Expected Result** 
The file name should be in the name of Yatri sathi.

**Actual Result**
The file name is int he name of Namma yatri.

**Comment by MercyQueen** [comment]
Fixed.
