### ISSUE TITLE
When location is outside Kolkata, the Location unserviceable error for Hindi is wrong (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1822]
#1803 

[Hindi translation of live is wrongly presented](https://drive.google.com/file/d/1lZ_WT_NSou4Mz5VwHPsYcR0ZKBzbQAzy/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Make sure the location of device is in unserviceable area
3. Change the language to Hindi

**Expected result**
The translation of live from English to Hindi should be 'Sakriya' (सक्रिय)

**Actual result**
The translation means we stay in Kolkata

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
The word live is written as लाइव in app here. Closing the issue
