### ISSUE TITLE
For special zone OTP ride, In app track functionality is not useful (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1824]
#1803 

[For special zone OTP ride, In app track functionality is not useful as there is not driver location information available to track the route](https://drive.google.com/file/d/1EhGPw7thTOZg6S4CMNI2oElxpy7tCSrj/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Book a ride for Spec zone OTP

**Expected result**
When spec zone OTP is shown, the in app tracking is not helpful. As there is not driver confirmed.

**Actual result**
The in app tracking is shown

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
In app functionality is removed. Closing it

**Comment by rohanrp179** [comment]
@MercyQueen This was fixed earlier, now it is again showing up.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Now in-app tracking is removed.
