### ISSUE TITLE
On Ride OTP screen , Text "is" is not translated to Hindi or Bengali (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1825]
#1803 

[Text "is" is not translated to Hindi or Bengali](https://drive.google.com/file/d/1IeDvi21KUzM3_Ur-jcxLznKu4w4-RyeD/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Book normal ride

**Expected result**
When language is changed to Hindi or Bengali, text "is" should not come

**Actual result**
It is coming

**Comment by MercyQueen** [comment]
Fixed.
