### ISSUE TITLE
In app chat message are not sent with the language it is selected for (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1826]
#1803 

[If language is chosen Hindi or Bengali, and if app chat that language messages are clicked, the message is going in English only](https://drive.google.com/file/d/14URIsfrSYhiWw6x-eSZq2PSWhqrNITJM/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Book a ride
3. Go to in app chat
4. Change the language
5. Send a suggestion message

**Expected result**
If suggested message is other than English, then when message is sent, it should not be in English

**Actual result**
It is shown in English only

**Comment by PraveenGongada** [comment]
It is expected for now
