### ISSUE TITLE
Car icon is missing when user try to track the ride movement once ride starts (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1827]
#1803 

[Car icon is missing when user try to track the ride movement once ride starts](https://drive.google.com/file/d/1E8XCDGIh8ELtY2wp3SsUwlSqgtIJS9Zm/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Book a ride
3. Start a ride

**Expected result**
When driver movement is tracked, the car icon should not be missing

**Actual result**
The car icon is missing

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
Car is shown after ride is assigned. Closing the issue
