### ISSUE TITLE
If repeat ride is performed for any spec zone source, the Taxi stands are not plotted properly (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1828]
#1803 

[If repeat ride is performed for any spec zone source, the Taxi stands are not pointed properly ](https://drive.google.com/file/d/1_yMoWleGbWJT3pBr0iITsAA4rANtMIXL/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Complete a spec zone ride first
3. Then click Repeat ride for previously completed spec zone ride

**Expected result**
When repeat ride is done for spec zone, the taxi stands should be plotted properly

**Actual result**
They are not

**Comment by MercyQueen** [comment]
fixed

**Comment by rohanrp179** [comment]
Working as expected. Closing the issues

**Comment by krupal-14** [comment]
@MercyQueen As it is working in rohan device but not working propely in iphone se so i am reopening it.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Retested the above bug, working as expected.
