### ISSUE TITLE
Update profile on Home screen banner is not disappearing even after updating the profile details (Parent_Id - 1594)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1832]
#1594 

[Complete your profile to update personal details tag on Home screen, is not disappearing after profile is updated and ride is completed](https://drive.google.com/file/d/1AwBUPJJSHOQ6X4Q1o1NHrvNk-jZAri3d/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Click on Update Profile banner and update personal details
3. Complete a ride
4. Close the app and launch again

**Expected result**
The update profile screen should not appear again once the personal details are updated

**Actual result**
The banner is not disappearing

**Comment by mohdshoaib18169** [comment]
fixed
