### ISSUE TITLE
Namma Yatri text is displaying in yatri "Rate driver" screen(Parent_Id-1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1841]
#1594 
**Description**
[Namma Yatri text is displaying in yatri "Rate driver" screen](https://drive.google.com/file/d/10lGnZmPf9pw8EnSBqXgSGYrBwFEq5Y31/view?usp=sharing)

**Steps to Reproduce**
1.Launch the apk.
2.login with valid credentails.
3.Book a ride
4.complete a ride
5.obsereve the rate driver screen

**Expected result**
Yatri Text should be there in the place of Namma Yatri.

**Actual Result**
Namma yatri text is displaying

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by johnruban-4050** [comment]
Retested and working fine as expected in CUG

cc @krupal-14
