### ISSUE TITLE
Where to?" is disappearing when user cancel the ride search (Parent_Id-1594)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1843]
#1594 
["Where to?" is disappearing when user cancel the ride search ](https://drive.google.com/file/d/1Hdb2XNpWRPxriSYRFJQZ9Ze2xmuNc4vd/view?usp=sharing)

**Steps to reproduce:**
1. Search for a ride
2. Click on cancel the ride
3. Click on cancel popup twice
4. Verify the error message
5. Verify where to? in home screen

**Expected**: Where to should display
**Actual:** Where to is not displaying

**Comment by rohanrp179** [comment]
As this issue is there in NY and we are saying we will fix it there. Closing the issue here
@tejkranthi @Vinaykm999
