### ISSUE TITLE
Update button is disabled even though all fileds are filled(Parent_id-1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1845]
#1594 
DESCRIPTION
[Update button is disabled even though all fileld are filled](https://drive.google.com/file/d/1njIdWrbkJ6RA7ak4-EfgaAJ-MFgfEVje/view?usp=sharing)

Steps to Reproduce 
1.Launch the apk.
2.login with valid credentials.
3.Click on hamburger -->Profile.
4.Just edit both email,name &gender.
5.Obsereve the screen.

Expected Result
Update button should be enabled.

Actual Result
Update button is disabled.

**Comment by johnruban-4050** [comment]
Retested and working fine in CUG 

cc @krupal-14
