### ISSUE TITLE
Allow AC taxi to take Non AC ride flow is not working for Special Zone (Parent_Id- 1854)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1857]
#1854
[Allow AC taxi to take Non AC ride flow is not working for Special Zone](https://drive.google.com/file/d/1TLwp3NGFSBGzILImVubZwXIjEsU-GwTy/view?usp=sharing)

Step to reproduced:-
1. Launch the app
2. Search the ride for special zone
3.  User receiving the OTP
4.  Enter OTP on AC taxi driver for non AC ride
5.  Observer the issue

Expected Result:-
AC taxi driver should able to accept non ac ride 

Actual Result:-
AC taxi driver not able to accept the non ac ride. It's shown error toast "Error Occurred" is displayed.

Reproduced rate - 5/5

Device - Oppo F7 (Android 10)

**Comment by Rohit4997** [comment]
Not related

**Comment by Rajaprabhu-Natrajan** [comment]
This issue is still persists on CUG also. As discussed you said it's a backend issue. So kindly assign this issue to concern developer.
