### ISSUE TITLE
In Ride Request Popup timer is not reducing ((Parent_id-1854)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1858]
#1854 
**Description** -
Timer is not reducing in Ride request popup

**Steps to Reproduce**
1.Launch the APK.
2.Login with valid credentials.
3.Book a ride in user APK 
4.And Observe the Ride request popup in Driver APK

**Expected -** 
Timer Progress bar should reduce according to seconds

**Actual -** 
Timer is not reducing in Ride request popup 

https://github.com/nammayatri/nammayatri/assets/137036742/97a31821-2b20-4330-854f-d011cbc22c8b

**Comment by Rohit4997** [comment]
Not related

**Comment by johnruban-4050** [comment]
@Rohit4997  Can you please assign this to respective person?
