### ISSUE TITLE
Sent messages are not displaying in chats for driver after the app is killed and relaunched(Parent_Id-#1854)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#1859]
#1854 
[Already sent messages are not displaying](https://drive.google.com/file/d/1BqW2gMwIUKU8niMsOboUMUIxEJEk0DBa/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with valid credentials
2. Assign a ride 
3. Send a message from customer to driver 
4. Kill  and relaunch the driver application and go to chats

**Expected Result**
Already sent messages should display 

**Actual Result**
Already sent messages are not displaying

**Comment by Rohit4997** [comment]
Not related
