### ISSUE TITLE
Add Driving License Screen - "Re-enter driving license" field name is displayed wrong (Parent_ID- #1854)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1860]
#1854 
[Add Driving License - "Re-enter driving license" field name is displayed wrong ](https://drive.google.com/file/d/1GX7MOWWMDuUYyyrkiAOyLC3q8fpIPxqz/view?usp=sharing)

Step to reproduced:-
1. Launch the app
2. Enter new driver number
3.  User in Add DL screen
4. verify the "Re-enter driving license" field
and observe the issue

Expected Result:-
"Re-enter driving license" field name should show correctly

Actual Result:-
"Re-enter driving license" field name is displayed wrong

**Comment by Rohit4997** [comment]
This is expected
