### ISSUE TITLE
"Call" button is not properly aligned in Emergency Help screen (Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1862]
#1803 
**Description** 
[Call button is not properly aligned ](https://drive.google.com/file/d/1lGczmtQAGrFlVlse9DU6K1e-lAt8Nsx5/view?usp=sharing)

**Steps to reproduce**
1.Launch the application .
2.Login with valid credentials .
3.Choose bengali language 
4.Book a ride.
5.Click on SOS icon 
6.Observe the screen.

**Expected Result**
Call text should be proper.

**Actual  Result** 
Call text is not proper

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,working fine.
