### ISSUE TITLE
User is not receiving any FCM's(parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1865]
#1803 
**Description**
[User is not receiving any FCM's](https://drive.google.com/file/d/1jkLihP6hjUxXtm8tfvjjC4o7UQl8SJ8l/view?usp=sharing)

**Steps To Reproduce**
1.Launch the application.
2.Login with valid credentials .
3.Book a ride.
4.Observe  the screen.

**Expected Result**
User should receive the FCM's.

**Actual Result**
user is not receiving any FCM's.

**Comment by Rohit4997** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine
