### ISSUE TITLE
On boarding images are not displaying when user launch the app very first time (Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1870]
#1867 
[1. On boarding images are not displaying when user launch the app very first time
2.In Enter mobile screen back arrow missing on the top of the application](https://drive.google.com/file/d/1SLXl2XeU2cJEgOcjQvxqtbsNe7CKYDzF/view?usp=sharing)

**Steps to reproduce**
1. Install the app
2. Launch the app and observe screen

**Expected Result**
Directly Enter mobile number screen is coming

**Actual Result**
On boarding images were not displayed

**Comment by Vignesh-772** [comment]
Expected

**Comment by AlluGowthami28** [comment]
@Vignesh-772 Why this is expected? The app on-boarding should be same as Namma Yatri right?

**Comment by AlluGowthami28** [comment]
Working fine.
