### ISSUE TITLE
<JSP><Aadhar flow not been validated as for new onboarded number /status API showing Aadhar is verified>#1854

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#1871]
#1854 
**Aadhar flow not been validated as for new onboarded number /status API showing Aadhar is verified**
While onboarding new number successfully, it is not showing "Aadhar card" details flow on Home screen.

**To Reproduce**
-> Enter new number.
-> Enter DL details && upload DL photo/not upload DL photo.
-> Enter RC details && upload RC photo/not upload RC photo.
-> Validate the Onboarding.
-> Validate Home Screen.
-> Observe the Issue.

**Expected behavior**
User should able to validate the "Aadhar details" flow.

**Screenshots**

**App (please complete the following information):**

**Additional context**
--> For new onboarded number also, /status API shows "Aadhar Verified" as true where as in DB, Onboarded number is not been entered. 
driverId: 972aab7c-0cc3-4b20-aea1-5e38d478c96d
driver Number: 8340834444

**Comment by Rohit4997** [comment]
@ashishsingh101  Can you check this?

**Comment by 123ajay1994** [comment]
Hi @ashishsingh101 I have checked the fix for this in CUG, Unable to validate the fix. 
Step performed: 
-> Unlinked the Aadhar from dashboard. 
-> Enabled the Driver by adding dummy DL & RC from Dashboard. 
-> Log in with credential. 
-> Observed the fix from the Home screen. 

Expected: Should show the Aadhar details flow. 
Actual: Not able to validate the Aadhar details flow. 

cc: @Rohit4997 
[https://drive.google.com/file/d/1fln-3aqx6ty8UHkERfCuP8jMUG0cqH_U/view?usp=sharing](url)

**Comment by 123ajay1994** [comment]
![Screenshot 2023-07-25 at 6 07 24 PM (1)](https://github.com/nammayatri/nammayatri/assets/128033831/ccbf4aba-28dd-4f29-8b18-15c43661dbe7)

@AshishSaini25 I have checked the logs for the CUG BPP app as well, number is not having aadhar linked but have status as "VALID. This issue seems from backend. Please check.
cc: @ashishsingh101
