### ISSUE TITLE
Auto_Rickshaw image is not there in "Choose your rides" Screen(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1872]
#1867 
[1. Auto_Rickshaw image is not there in "Choose your rides" Screen
2. Remaining vehicle variant asserts are not clear(Images look like blur)](https://drive.google.com/file/d/1K4QXHZaToHR_Mm-x8P3VzkLdKUOqhniR/view?usp=sharing)

**Steps to reproduce** 
1. Launch the application 
2. Select source and destination
3. Observe the "Choose your ride" Screen

**Expected result**
Auto Icon should be there and remaining variants images should be clear

**Actual Result**
Auto icon missing and remaining variants images not clear

**Comment by Vinaykm999** [comment]
Working fine
