### ISSUE TITLE
Rate card not found for Auto rickshaw vehicle variant(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1874]
#1867 
[Rate card not found for Auto rickshaw vehicle variant](https://drive.google.com/file/d/1PaCNZcjCdE8N98RbSMxJ5WVN8F2OKeXm/view?usp=sharing)

**Steps to reproduce**

1. Launch the application
2. Select source and destination
3. Tap on rate card of Auto rickshaw and observe

**Expected result**
For Auto rickshaw rate card should be there

**Actual Result**
No rate card found for Auto rickshaw.

**Comment by krupal-14** [comment]
Retested,working fine
