### ISSUE TITLE
In rate card Driver addition (optional) chart is missing for all variants(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1875]
#1867 
[In rate card Driver addition (optional) chart is missing for all variants](https://drive.google.com/file/d/15swkX-QHfm2uuXPGmKnzkPJi6fGCDzZ-/view?usp=sharing)

**Steps to reproduce**

1. Launch the application
2. Select source and destination
3. Tap on any rate card and observe

**Expected result**
Driver addition chart should be there in rate card.

**Actual Result**
Driver addition chart is missing in rate card.

**Comment by AlluGowthami28** [comment]
@PraveenGongada For auto rickshaw same issue is there. Kindly fix this isssue.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine.
