### ISSUE TITLE
Share ride button is not there before or after starting the ride(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1880]
#1867 
[Share ride button is not there before or after starting the ride](https://drive.google.com/file/d/10YjIm3coYYcuBxT1DsMLMG8nSlEqhqwA/view?usp=sharing)

**Steps to reproduce**

1. Launch the application
2. Select source and destination
3. Search for a ride
4. Once ride got assigned observe OTP screen

**Expected result**
Share ride button should be there in OTP screen, and next screen

**Actual Result**
Share ride button is not there before or after starting the ride

**Comment by Vignesh-772** [comment]
Share ride Option is not enabled for Yatri

**Comment by PraveenGongada** [comment]
Expected
