### ISSUE TITLE
Cancellation of ride is not reflecting in user ipa, when driver cancel the ride (Parent_id_1867)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1881]
#1867
Cancellation of ride is not reflecting in user ipa, when driver cancel the ride

Steps
1. Launch the application and login with valid credentials 
2. Search for ride in user app and accept in driver app
3. Before start ride - Cancel ride from driver side and observe the screen in User app

Expected - 
Ride should cancel immediately in user side also

Actual -
Cancellation of ride is not reflecting in user apk, when driver cancel the ride

Attachment link - https://drive.google.com/file/d/1OjHHrVCh4r1cXZtIIOUkwbeCW3tNxRaE/view?usp=drive_link

**Comment by Vignesh-772** [comment]
Is it possible to add logs

**Comment by Vinaykm999** [comment]
![Screenshot 2023-07-26 at 3 37 01 PM](https://github.com/nammayatri/nammayatri/assets/131981246/4ea3ee2f-81b2-42f4-94e4-718f7334fba5)
![Screenshot 2023-07-26 at 3 38 02 PM](https://github.com/nammayatri/nammayatri/assets/131981246/bf2641a1-b316-4e24-8b0b-75aee4c851f5)

@Vignesh-772 Attached logs, kindly check.
