### ISSUE TITLE
In ride search screen below the car animation text is missing(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1883]
#1867 
[1. In ride search screen below the car animation text is missing
2. Animation not aligned at the centre of the screen](https://drive.google.com/file/d/1MX7jGucPRa8v2j6LMdQxcCUA0LFJFXuf/view?usp=sharing)

**Steps to reproduce**

1. Launch the application
2. Select source and destination
3. Search for a ride and observe he screen

**Expected result**
1. In ride search screen below the car animation text should be there.
2. Animation should aligned at the centre of the screen.

**Actual Result**
1. In ride search screen below the car animation text is missing.
2. Animation not aligned at the centre of the screen.

**Comment by Vignesh-772** [comment]
It is expected
