### ISSUE TITLE
Help and support button is missing in Ride Completed screen(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1884]
#1867 
[Help and support button is missing in Ride Completed screen](https://drive.google.com/file/d/1vpMwbMhoqp1AYv8uLzylp-vF56RkY5Ja/view?usp=sharing)

**Steps to reproduce**

1. Launch the application
2. Select source and destination
3. Search for a ride
4. Complete a ride and observe the Ride completed screen

**Expected result**
Help and support button should be there in Ride Completed screen

**Actual Result**
Help and support button is missing in Ride Completed screen

**Comment by Vignesh-772** [comment]
#1906 duplicate issue

**Comment by prakharritik** [comment]
The link in the code was wrong.

**Comment by Vinaykm999** [comment]
Working fine
