### ISSUE TITLE
End Ride Screen - Fare Updated Text is not correct as per figma (Early ride end case and Ride was longer case as well)(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1888]
#1867 
[End Ride Screen - Fare Updated Text is not correct as per figma (Early ride end case and Ride was longer case as well)](https://drive.google.com/file/d/1deVMCbi5egtoyMb1RGnlybOVWlt7EmXM/view?usp=drive_link)

**Steps to reproduce**
1. Start the ride and End ride after some time
2. Observe the End Ride Screen 

**Expected Result**
Text format - "Your fare has been updated as your ride was 
1.2 km shorter"

**Actual Result**
Text Should be same as per figma

**Comment by prakharritik** [comment]
This is already discussed with the designers. Design needs to be updated.

**Comment by AlluGowthami28** [comment]
@prakharritik Kindly defer this issue.
