### ISSUE TITLE
In early ride end case instead of rating pop-up screen, user should get "Did you face any issues?" pop-up and Total flow is missing(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1889]
#1867 
[In early ride end case instead of rating pop-up screen, user should get "Did you face any issues?" pop-up and Total flow is missing.](1. https://drive.google.com/file/d/1o2tD0bzjOX3He2eUjg1rr0ex8AHXcUDb/view?usp=sharing
Figma link : https://drive.google.com/file/d/1aM93-CkxS5pcc_w0WdDcv0dl-R8PP2Z0/view?usp=sharing)

**Steps to reproduce**
1. Start the ride and End ride the ride before reaching to destination
2. Observe the Ride Completed screen

**Expected Result**
User should get "Did you face any issues?" pop-up

**Actual Result**
In early ride end case instead of rating pop-up screen user should get "Did you face any issues?" pop-up

**Comment by Rohit4997** [comment]
Not Implemented from backend.
For more information Please check with @sidsethujuspay

**Comment by sidsethujuspay** [comment]
This feature is not implemented yet. Why are we testing this?

**Comment by AlluGowthami28** [comment]
@Rohit4997 Kindly defer this issue.
