### ISSUE TITLE
User is able to save other states location by using locate on map(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1890]
#1867 
[User is able to save other states location by using locate on map](https://drive.google.com/file/d/1l5NBBH2XnDLbRJxMTyux67WBEQvXp4Vx/view?usp=sharing)

**Steps to reproduce**
1. Launch the application
2. Tap on Hamburger 
3. Tap on Favourites 
4. Tap on set on map
5. Select any location out of Kerala and save the location

**Expected result**
User not allowed to save the out of Kerala

**Actual Result**
User is able to save other states location by using locate on map

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
@MercyQueen Although it is not adding any favourite location outside kerala. But not giving appropriate error message.

https://github.com/nammayatri/nammayatri/assets/132905061/94e102a2-b28f-4266-9ee8-5adb7d2bcfb2

**Comment by MercyQueen** [comment]
User will get a UI saying location unserviceable. Fixed.

**Comment by rohanrp179** [comment]
Working as expected... Closing the issue
