### ISSUE TITLE
Polyline is disappearing when user try to add favourite in on-ride (Parent_ID- #1867)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1891]
#1867
[Polyline is disappearing when user try to add favourite in on-ride](https://drive.google.com/file/d/1KVoy9fQoDs2snG4SUDtPu63v4UVzHSuv/view?usp=sharing)

**Steps**: 
1. Launch user application
2. Request and assign a ride
3. Click on hamburger menu >>favourite 
4. Click on add new favourite 
5. Select set on map
6. Navigate back to home screen
7. Verify polyline

**Expected**: Polyline should not disappear 
**Actual**: Polyline is disappearing

**Comment by MercyQueen** [comment]
fixed - @kapilJhalani1
