### ISSUE TITLE
Waiting time per minute charge is not showing in ride details and invoice (Parent_ID- #1867)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1893]
#1867
[Waiting time per minute charge is not showing in ride details and invoice](https://drive.google.com/file/d/19-AJMPl9qAtX7wsJiyul9A9mZFuvY_74/view?usp=sharing)

**Steps:**
1. Launch user application 
2. Assign ride
3. Click on i have arrived in driver side
4. Wait till 5 minutes
5. Start ride
6. End ride
7. Verify price in ride details 
8. Waiting time per minute fare is updating but not showing in ride details and invoice

**Expected**: Waiting time per minute fare should display

**Comment by Vignesh-772** [comment]
check whether it is sent from backend

**Comment by Vinaykm999** [comment]
![Screenshot 2023-07-26 at 5 50 46 PM](https://github.com/nammayatri/nammayatri/assets/131981246/a5787c52-517e-4252-ba06-0862a36a4ff2)
Not sowing it in backend.

**Comment by prakharritik** [comment]
@Vinaykm999 can you please post it in beckn-backend channel. We are not getting the waiting charges in the API response.

![Image](https://github.com/nammayatri/nammayatri/assets/60786008/11916c61-d8bd-483e-9edb-f7196c257f29)

**Comment by MercyQueen** [comment]
@JanhaviSoni can you please look into this issue.

**Comment by JanhaviSoni** [comment]
@Vinaykm999 @MercyQueen we are not sending it from backend. It won't get displayed
