### ISSUE TITLE
Driver is not getting ride request in Cochin airport(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1894]
#1867 
[Driver is not getting ride request in Cochin airport](https://drive.google.com/file/d/1szeX_YDlWvQf4dVAv5-hRL2yzhCwiryk/view?usp=sharing)

**Steps to reproduce**
1. Select source as Cochin airport
2. Select destination 
3. Select variant and observe the screen

**Expected result**
Driver should get rid request

**Actual Result**
Driver is not getting ride request in Cochin airport

**Comment by prakharritik** [comment]
@AlluGowthami28 can you please check this once in postman. If it is reproducing there as well, then please post it in beckn-backend channel.

**Comment by AlluGowthami28** [comment]
Working fine.
