### ISSUE TITLE
Wait timer should not display after the ride has been started(Parent_ID_#1902)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1905]
**#1902** 
As per figma Wait timer should not display after the ride has been started 

**Steps-**
Search for ride
Tap on "ive arrived" in driver APK
Then wait time will start 
And enter the OTP and observe the driver screen

**Expected -**
Wait time should not display once the ride is started

**Actual -** 
After the ride is started then Wait time is displaying 

https://github.com/nammayatri/nammayatri/assets/137036742/720578f1-b81c-464b-8f2a-669a77eb239e

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by johnruban-4050** [comment]
@mohdshoaib18169 As per the comments it should be there right but in this shared APK wait timer is not displaying after the ride is started.(https://drive.google.com/file/d/1_zluTtB0mfqDuyO5Dk_XiVtTrQUH4Kah/view?usp=drive_link)

**Comment by mohdshoaib18169** [comment]
@johnruban-4050 , it should not be there
