### ISSUE TITLE
Contact support icon is not showing in  ride completed  as per figma(Parent_ID- #1867)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1906]
**#1867** 
[Contact support icon is not showing in  ride completed  as per figma](https://drive.google.com/file/d/1uCeIQkK3vg8TaJSCCueZhJMB-3OCPZP3/view?usp=sharing)

**Steps:** 
1. Open user application 
2. Complete ride
3. Verify ride completed screen in user app
4. verify contact support icon

**Expected:**
Contact support icon should display as per figma

**Figma screenshot** 
<img width="872" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/20ef3618-88d0-47fe-a756-abd58767a05c">

**Comment by krupal-14** [comment]
Retested by @Vinaykm999, Working fine
