### ISSUE TITLE
Inaccurate date and time - Map timing is not updated after change the device timing (Parent_ID- #1902)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1907]
#1902 
[Inaccurate date and time - Map timing is not updated after change the device timing](https://drive.google.com/file/d/1GGbJ3Q8WH7xSDpG5ask7_pE2HnYkxuH3/view?usp=sharing)

Step to reproduced:-
1. Launch the app
2. Change the device time & date inaccurate through manually set
3. Then click on launch the app
4. Inaccurate date and time screen is displayed
5. Then changed to current time 
6. Map time is not update.

Expected Result :-
Map timing should be update after driver reset the time

Actual Result:-
Map timing is not updated after driver reset the time

**Comment by guptamanav422** [comment]
fixed

**Comment by aryan-13** [comment]
Can we close this issue if its fixed? @Rajaprabhu-Natrajan

**Comment by johnruban-4050** [comment]
Retested and working fine as expected 

cc @krupal-14  @Rajaprabhu-Natrajan
