### ISSUE TITLE
Hindi Text is wrong in inaccurate date & Time screen(Parent_Id-1902) 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1908]
#1902 
**Description**
[Hindi Text is wrong in inaccurate date & Time screen](https://drive.google.com/file/d/16MSkogwB5CttxtaQk21A8BsRVbWkjjtT/view?usp=sharing)

**Steps to Reproduce**
1.Launch the application.
2.Login the valid credentials.
3.Change the date & time.
4.Observe the in accurate date & time screen.

**Expected result**
Hindi Text Should be proper.

**Actual result**
Hindi Text is wrong.

**Comment by guptamanav422** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested working fine
