### ISSUE TITLE
Date & time inaccurate screen is not properly aligned in kannada language(Parent_Id-1902)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1910]
#1902 
**Description**
[Date & time inaccurate screen is not properly aligned in kannada language](https://drive.google.com/file/d/197WGVcoO2rA4jtsScwyv8F4nuYmIFrow/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application.
2. login with valid credentials.
3. Choose the language to kannada.
4. Change the date & time.
5. Observe the inaccurate date & time screen.

**Expected result**
The inaccurate date & time should be properly aligned.

**Actual result**
The inaccurate date & time should be properly aligned.

**Comment by guptamanav422** [comment]
FIXED

**Comment by krupal-14** [comment]
Not aligned properly

**Comment by johnruban-4050** [comment]
Retested and working fine as expected in CUG

https://github.com/nammayatri/nammayatri/assets/137036742/f0d8708f-d61e-42ef-a07d-0b0757c785e2
