### ISSUE TITLE
Wait timer is displaying wrong(Parent_ID_#1902)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1911]
#1902 

**Steps-**

1. Search for ride and tap on "ive arrived" in driver apk
2. Then the wait time will display then cancel the ride 
3. And once again search for the ride and enter the OTP without tapping on "ive arrived"
4. And Observe the Screen

**Expected -**
Wait time should display correctly

**Actual -**
Previous ride Wait time is displaying in current ride even though the wait time is not enabled (PFA)

**Attachments -** 
https://drive.google.com/file/d/1MS9kZ9-iF2Mg0EZ_qt6auplNKL28Cvbr/view?usp=drive_link

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by johnruban-4050** [comment]
Working fine as expected (https://drive.google.com/file/d/1DuHbqmJBcP3w-IBJym7IY18ltSFR5FJc/view?usp=drive_link)
