### ISSUE TITLE
Dotted lines are not showing in ride details screen (Parent_ID- #1867)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1912]
#1867
Dotted lines are not showing in ride details screen

**Steps:** 
1. Complete one ride
2. Verify in ride details screen

<img width="616" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/e30b60bb-f0e2-4741-8a63-bad962ff1dee">

**Expected:** Doted lines should display

**Comment by MercyQueen** [comment]
Deffered.
