### ISSUE TITLE
Wait Timer Image is not displaying (Parent_Id-1902)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1913]
**#1902** 
Wait Timer Image is not displaying 

**Steps-**
1. Search for ride and tap on "ive arrived" in driver apk
2. Then the wait time will display and tap on I icon and observe the screen
 
**Expected -** 
Wait timer image should display

**Actual -** 
Wait timer image is not displaying 
![markup_1000000518](https://github.com/nammayatri/nammayatri/assets/137036742/c693cf64-46b5-4462-81e0-acbd503feb68)

**Comment by mohdshoaib18169** [comment]
fixed

**Comment by johnruban-4050** [comment]
Retested and working fine as expected 
![Screenshot_20230726-214800](https://github.com/nammayatri/nammayatri/assets/137036742/30f60405-ea98-42b6-b97d-88eefbe1db3f)
