### ISSUE TITLE
"Ive arrived" UI is not as per figma (Parent_ID_#1902)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1914]
#1902 
"Ive arrived" UI is not as per figma

Steps
1. Access the application and login with valid credentials 
2. Search for ride and accept the ride 
3. And Observe the Start Ride Screen 

Expected - 
"Ive Arrived" UI is not as per figma

![Screenshot_20230725-204241](https://github.com/nammayatri/nammayatri/assets/137036742/2c67f431-49a4-4782-8a97-5644483eaa5e)

**Comment by mohdshoaib18169** [comment]
default

**Comment by johnruban-4050** [comment]
As per the figma it should be updated

**Comment by mohdshoaib18169** [comment]
its a part of different PR which is not yet merged

**Comment by mohdshoaib18169** [comment]
@witcher-shailesh , bro can you comment here or close this issue

**Comment by witcher-shailesh** [comment]
for now this can be merged @johnruban-4050 , updated designs will come in upcoming changes
