### ISSUE TITLE
Map Timing is not updating when we set the correct time(Parent_Id-1902) 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1915]
#1902 
Description
[Map timing is not updating even though driver set the correct time](https://drive.google.com/file/d/13pLakBX00pXwLHmPDH5ETH_LnB6X-uHd/view?usp=sharing)

Steps to Reproduce
1.Launch the application.
2.Login with Valid credentials.
3.Change the date & time.
4.Wait for 2 min.
5.Update the time to actual real time.
6.Observe the Map update time.

Expected Result
map timer should update.

Actual result
Map timer is not updating.

Note-Even though the time is not updating driver is getting ride request.

And as soon as driver set the real time **map time is not updating and in the logcat location API it is not calling**

**Comment by guptamanav422** [comment]
fixed

**Comment by krupal-14** [comment]
Retested working as expected
