### ISSUE TITLE
Wait timer I icon UI Should be more large (Parent_ID_#1902)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1916]
#1902 

**Steps**
1. Access the application and login with valid credentials
2. Search for ride and accept the ride
3. And Observe the Start Ride Screen

**Expected -**
Wait Time i icon UI should be more large

**Actual -** 
Wait Time i icon UI is is too small 
![Screenshot_20230725-193916](https://github.com/nammayatri/nammayatri/assets/137036742/a4285ff4-ae75-4f8e-b8a7-51bdf5a94670)

**Comment by mohdshoaib18169** [comment]
Icon size is this much only

**Comment by johnruban-4050** [comment]
Can We make this icon Bigger if possible?

**Comment by johnruban-4050** [comment]
As discussed it is fine for now so im closing this
