### ISSUE TITLE
Getting Special zone Yatri saathi OTP screen when user search from kochi airport(Parent_ID- #1867)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1917]
#1867 
[Getting Special zone Yatri saathi OTP screen when user search from kochi airport
](https://drive.google.com/file/d/1rHYp1xcCMtDR3x-M_Bm_MbvSo8SljSXb/view?usp=sharing)

**Steps:**
1. Request ride from kochi airport
2. Verify the screen

**Comment by rohanrp179** [comment]
Working fine. Closing It
