### ISSUE TITLE
"No drivers available at this moment" toast not visible for even 1sec(Parent_ID- #1867)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1922]
#1867 
["No drivers available at this moment" toast not visible for even 1sec](https://drive.google.com/file/d/1uj2X2d5w28as2MdptFR1Y5Fa3HDVrcH7/view?usp=sharing)

**Steps to reproduce**
1. Launch the application
2. Select source and destination
3. Search for a ride

**Expected result**
Toast at least visible for 3-5sec

**Actual Result**
"No drivers available at this moment" toast not visible for even 1sec

**Comment by Vignesh-772** [comment]
It is expected in new toast. This case should have been tested with the toast feature itself.

**Comment by AlluGowthami28** [comment]
This is working fine android. This thing was tested early now we are having issue in ios.

**Comment by AlluGowthami28** [comment]
Issues still there in ios.

**Comment by MercyQueen** [comment]
@AmritpalSingh6749 can you please look into this issue.
