### ISSUE TITLE
HatchBack - Rate card content is displayed wrong (Parent_Id-#1867) 

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1923]
#1867 
[HatchBack - Rate card content is displayed wrong](https://drive.google.com/file/d/1bfOhSEUYbwhJiocd2wc5KVUseMoHHqy5/view?usp=sharing)

Step to reproduced:-
1. launch the app
2. Search the ride
3. Get the estimation
4. verify the Rate card of Hatch back 

Expected result:-
The Min fare kilometer should start from 5 km but it's start from 4 km

Actual result:-
The Min fare kilometer is start from 4km. 

reproduce rate - 5/5

Device - iPhone XR( V 16)

<img width="807" alt="Screenshot 2023-07-26 at 1 33 52 PM" src="https://github.com/nammayatri/nammayatri/assets/134508712/330ca455-5acf-4990-afe1-04058d14e03a">

**Comment by MercyQueen** [comment]
Fixed.

**Comment by johnruban-4050** [comment]
@MercyQueen  Rate card -> "Min Fare Upto 5km" Cost is displaying wrong

**Comment by MercyQueen** [comment]
It should be 140 only. @tejkranthi can you please confirm here.

**Comment by tejkranthi** [comment]
The expected price is Rs. 140 upto 5 km (it was updated recently). @johnruban-4050 There's no problem here.

**Comment by krupal-14** [comment]
@tejkranthi It will be great if this fare is update in the figma as well.
Retested,Working fine.
