### ISSUE TITLE
"Active booking exist" toast message is coming blank in ipa (Parent_ID- #1867)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1925]
#1867 
**[Active booking exist toast message is coming blank in ipa](https://drive.google.com/file/d/17xhKzDxerTcTTvvzrOa4TP1VSZpw7B_4/view?usp=sharing)**

**Steps:** 
1. Search ride
2. Accept ride from driver and cancel ride from user 
3. Verify the toast message

**Actual result :** Toast message is showing blank

**Expected :** Active booking exist text should display

**Comment by krupal-14** [comment]
Retested working fine
