### ISSUE TITLE
Customer Call or Any other call before it's started "Was your call successful?" pop up is displayed (Parent_ID - #1867)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1926]
#1867 
[Customer Call or Any other call before it's started "Was your call successful?" pop up is displayed](https://drive.google.com/file/d/1tlngTbdnvo90opbXO-uvY8e2ZzOq_foV/view?usp=sharing)

Step to reproduced:-
1. Launch the app
2. Book a ride
3. Click on emergency help.
4. Click on Call emergency centre / Call yatri Support
5. Click Call support / Dail 112
6. Observe the issue

Expected Result:-
Call should trigger first after call was ended then only "Was your call successful?" pop up  should displayed.

Actual result:-
Before call started "Was your call successful?" pop up is displayed.

reproduce rate-5/5

Device - iPhone XR(16)

**Comment by Vignesh-772** [comment]
Expected
