### ISSUE TITLE
<Y><Ride Feedback><Text is "help us to improve Namma yatri experience" Instead of Yatri> <Parent Id: #1867>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#1934]
#1867 
**Describe the bug**
Ride Feedback screen Text is "help us to improve Namma yatri experience" Instead of Yatri.

**To Reproduce**
-> Complete one ride.
-> Validate the Feedback Screen.
-> tap on start.
-> Validate the text. 
-> Observe the issue.
**Expected behavior**
Text should be "help us to improve Yatri experience"
**Screenshots**
![IMG_0084](https://github.com/nammayatri/nammayatri/assets/128033831/5728eeb9-67aa-4fd5-af26-d92ae92bdb7d)

**App (please complete the following information):**

**Additional context**

**Comment by prakharritik** [comment]
Added Strings To merchants.

**Comment by johnruban-4050** [comment]
Retested and working fine as expected 
![WhatsApp Image 2023-08-04 at 6 14 55 PM](https://github.com/nammayatri/nammayatri/assets/137036742/31bc20e3-70e8-4875-9bce-8b1253c8dd5f)
