### ISSUE TITLE
Popup is disappearing when user tap on remove emergency contact popup(Parent_ID- #1867) 

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1935]
#1867

**[Popup is disappearing when user tap on remove emergency contact popup
](https://drive.google.com/file/d/1w1o_1xnt_bksY0EhVfMxk1EC4EO9pd1E/view?usp=sharing)**

**Steps:** 
1. Launch ipa
2. Click on hamburger menu
3. Click on emergency contact and add 3 contacts
4. Click on remove contact
5. verify the remove contact popup
6. Tap on above the popup
7. Verify

Expected: Popup should not close when user tap on the popup, if user tap on outside the popup it should go

**Comment by prakharritik** [comment]
Fixed by configuring backgroundclickable property.

**Comment by Vinaykm999** [comment]
Working fine
