### ISSUE TITLE
Menu bar is hiding when user tap on profile logo image (Parent_ID_1867)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1940]
#1867 

Menu bar is hiding when user tap on profile logo image

Steps - 
1. Access the Application
2. Tap on Menu Icon and tap on Profile image Logo and observe

**Expected -** 
Menu Bar Should not hide

**Actual -** 
Menu bar is hiding when user tap on Profile logo image

https://github.com/nammayatri/nammayatri/assets/137036742/34f9e3c4-a5d3-4799-877d-0c803ec80203

**Comment by prakharritik** [comment]
Added onclick on image.

**Comment by krupal-14** [comment]
Retesed,Working fine
