### ISSUE TITLE
Malayalam language - Cancel Ride options text are cropped . It's not displayed properly (Parent_ID - #1867)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1941]
#1867 
[Cancel Ride options text are cropped in the ride screen . It's not displayed properly](https://drive.google.com/file/d/1tX0ArVmelPlbgpTdKBrJfMJwGrQSgEwO/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Choose malaayalam
3. Book the ride 
4. Click Cancel ride 
5. Choose any cancel ride option
6. Observer the text

Expected Result:-
Text should not cropped

Actual Result:-
Test are cropped. it's not displayed properly 

Reproduce rate - 5/5

Device - Iphone XR (16)
![IMG_0089](https://github.com/nammayatri/nammayatri/assets/134508712/4c3d518a-0a41-4223-82f4-54cafaec4a5a)
![IMG_0090](https://github.com/nammayatri/nammayatri/assets/134508712/3ea6f327-7f95-49c2-bf9d-89cd689f461f)

**Comment by prakharritik** [comment]
![Image](https://github.com/nammayatri/nammayatri/assets/60786008/d655c913-b058-4f10-91da-7d730fca4724)

Fixed

**Comment by krupal-14** [comment]
Retesed @Rajaprabhu-Natrajan,  Working fine
