### ISSUE TITLE
Go to settings button displaying in hindi but driver chooses kannada language in inaccurate date & time screen(Parent_Id-1902)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1954]
#1902 
**Description** 
[Go to settings button displaying in hindi but driver chooses kannada language in inaccurate date & time screen](https://drive.google.com/file/d/19E_xj4Qlr_8VV0-qBadmGRfU8WgSHyVa/view?usp=sharing)

**Steps to Reproduce**
1.Launch the application.
2.Login with valid credentials.
3.Choose kannada language.
4.Change the date & time.
5.observe the inaccurate Date &Time screen  

**Expected Result**
Go to setting button should be in kannada.

**Actual Result**
Go to setting button is in hindi language.

**Comment by guptamanav422** [comment]
FIXED

**Comment by johnruban-4050** [comment]
Retested and working fine in CUG

cc @Rajaprabhu-Natrajan
