### ISSUE TITLE
Inaccurate date & time screen -  "Go to setting" CTA is displayed in different language (Parent_ID-#1902)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1956]
#1902 
[Inaccurate date & time screen -  "Go to setting" CTA is displayed in different language](https://drive.google.com/file/d/1-K919yTBCquHeiCVIiwUQQo0GZqyOtqm/view?usp=sharing)

Step to reproduce:-
1.  Launch the app
2. Set Inaccurate date & time
3. Verify CTA button 
4. Observe the issue

Expected Result:-
 "Go to setting"CTA button  should displayed based on which language driver is chosen.
Actual Result:-
 "Go to setting" CTA button displayed in different language. 
![Screenshot_2023-07-27-14-04-38-95_e59db0565d3dc5de047672455dd79cdf](https://github.com/nammayatri/nammayatri/assets/134508712/681abd20-5caf-465e-88aa-ee742e965b7a)

 
![IMG_20230727_001341](https://github.com/nammayatri/nammayatri/assets/134508712/8d934d4f-35e5-469c-a78c-1534681493a2)

**Comment by johnruban-4050** [comment]
Retested and working fine in CUG 

cc @Rajaprabhu-Natrajan
