### ISSUE TITLE
After ride was stared poly line are not displayed in the user side.(Parent_Id -#1803)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1960]
#1803 
[After ride was stared poly line are not displayed in the user side](https://drive.google.com/file/d/1t73KZ1m8TullbS1Cs96W-fTtys0zVPX_/view?usp=sharing)

Step to reproduced:-
1. Launch the app
2. Book a ride
3. Polly line are not displayed

Expected Result:-
Polly line should be displayed.

Reproduced rate - 5/5

Device - iphone xr(16)

**Comment by MercyQueen** [comment]
Not able to reproduce.

**Comment by johnruban-4050** [comment]
@MercyQueen Issue Still present in IPA can you please check 

https://github.com/nammayatri/nammayatri/assets/137036742/5ca1a97b-331e-4157-9dd6-f7db03135227

**Comment by MercyQueen** [comment]
This issue is because of driver's fake GPS.

**Comment by MercyQueen** [comment]
@krupal-14 @Sumedh-14 is this issue still there?

**Comment by krupal-14** [comment]
@MercyQueen  this issue was there in backlog state only.

**Comment by MercyQueen** [comment]
This issue is because of driver's fake GPS.
