### ISSUE TITLE
Before call was started "Was your call successful" pop is displayed.(Parent_Id-1803)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1962]
#1803 
[Before call was started "Was your call successful" pop is displayed](https://drive.google.com/file/d/1_0UjNOEdXKFqInHPbqsNCZSmnMxrHI3C/view?usp=sharing)

Step to reproduced:-
1.launch the app
2. Book the ride
3. click on emergency icon
4. click call option 
5.observer the issue

Expected result:-
Pop up should display after the call was successfully end

reproduced rate - 5/5

Device- iPhone XR(16)

**Comment by MercyQueen** [comment]
Expected.
