### ISSUE TITLE
Update button is enable even though name field is blank(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1963]
#1803 
**Description**
[Update button is enable even though name field is blank in user profile screen](https://drive.google.com/file/d/1XROKkti2OpRzSuqg1d-Puk9gkjcKq1Dw/view?usp=sharing)

**Steps To reproduce**
1.launch the application.
2.Login with valid credentials.
3.Go to user profile.
4.Enter valid email-id.
5.Clear name.
6.Observe the update button.

**Expected Result**
Update button should be disable.

**Actual Result**
update button is enable.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
