### ISSUE TITLE
OTP timer should start from 30 when user enter new number (Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1964]
#1803 
Description
[OTP timer should start from 30sec when user enter new number](https://drive.google.com/file/d/1_IYclKq0r0EcaS8LEdY4Cvja0o-jaONI/view?usp=sharing)

Steps To Reproduce
1.Launch the application.
2.Enter valid mobile number-->enter wrong otp-->wait until otp timer is less then 10sec
3.Click Back button--> edit mobile number.
4.Click on Continue.
5.Observe the OTP timer 

Expected Result
OTP Timer should start 30sec.

Actual Result
OTP timer is not starting from 30sec.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested, working fine.
