### ISSUE TITLE
"Was your call successful" pop up is shown early than expected (Parent_Id - 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1967]
#1803 

[If we are calling Emergency/Contact support/112, then "Was call successful" pop up is appearing before we move to dialer screen/dialing](https://drive.google.com/file/d/1Vmaehbw_IvdaHkj27KQRQu2AbCye_0fR/view?usp=sharing)

**Steps to reproduce **
1. Log in to app
2. Book a ride
3. Click on SOS
4. Click on any Emergency contact/Contact support/112

**Expected result**
When the call option is shown with number, the pop up "Was you call successful" should not come

**Actual result**
It is showing early.

**Comment by krupal-14** [comment]
As dev comment, closing this issue
