### ISSUE TITLE
Dotted line is not displaying when user clicking on in-app tracking(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1968]
#1803 

**Description**
[Dotted line is not displaying when user clicking on in-app tracking](https://drive.google.com/file/d/1UQmkm5ziFjfOUnLTv4FJzMO4EgZOHd01/view?usp=sharing)

**Steps To Reproduce**
1.Launch the application.
2.Login with valid credentials.
3.Book a ride.
4.Start a ride.
5.Click on in-app tracking.
6.observe the screen.

**Expected Result**
Dotted line should display.

**Actual Result**
Dotted line is not displaying.

**Comment by MercyQueen** [comment]
Instead of dotted line we have straight line for IOS.

**Comment by Vinaykm999** [comment]
we are getting straight line, as per dev comment i'm resolving this issue
