### ISSUE TITLE
No messages Text is displaying in ride search screen when user is not getting any rides(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1970]
#1803 
**Description**
[No messages Text is displaying when user is not getting any rides](https://drive.google.com/file/d/1pJjkaEHOs6sN-5SOaQkE7Iwu8wgCo1nu/view?usp=sharing)

**Steps To Reproduce**
1.Launch the application.
2.Login with valid credentials.
3.Search for a ride.
4.Observe the ride search screen 

**Expected Result**
User should get some text messages when user is not getting any rides.

**Actual Result**
User is not getting any messages text when user is not getting any rides.

**Comment by MercyQueen** [comment]
expected.

**Comment by krupal-14** [comment]
As dev comment it is expected,closing issue.
