### ISSUE TITLE
blank screen is displaying when user clicks on add emergency contacts.(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1971]
#1803 
**Description**
[blank screen is displaying when user clicks on add emergency contacts.](https://drive.google.com/file/d/1T9mGSvkOkyw_-bDPAQaXGCHJym0CrNlV/view?usp=sharing)

**Steps To Reproduce**
1.Launch the application.
2.Login with valid credentials.
3.Book a ride.
4.start a ride.
5.Click on sos icon.
6.Click on emergency contacts.
7.Click on add emergency contacts.
8.Observe the screen.

**Expected Result**
Contacts list should open.

**Actual Result**
Blank screen is displaying.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,working fine.
