### ISSUE TITLE
Chat enabled FCM's is not displaying in the user end(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1974]
#1803 
**Description**
[Chat enabled FCM's is not displaying in the user end](https://drive.google.com/file/d/1Aff5BvOG3HJncgYEPjCmCNI5cquE4pV2/view?usp=sharing)

**Steps To Reproduce**
1.Launch the application.
2.Login with valid credentials.
3.Book a ride.
4.Observe the user received FCM's.

**Expected Result**
User should receive all FCM's.

**Actual Result**
User is not receiving all the FCM's

**Comment by MercyQueen** [comment]
Expected. In iOS we don't have service so this is expected.

**Comment by krupal-14** [comment]
As dev comment it is expected, closing the issue
