### ISSUE TITLE
Favourite location naming text box is not properly aligned in Bengali & Hindi language’s (Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1976]
#1803 
**Description**
[Favourite location screen is not properly aligned](https://drive.google.com/file/d/1HOi1JXUAQVpQxyx0nLSZLlY_4e3uEwIv/view?usp=sharing)

**Steps to Reproduce**
1.Launch the application.
2.Login with valid credentials.
3.Click on hamburger.
4.Click on favourites-->Add favourite location.
5.Select location-->Click on favourites-->While entering the name for that favourite  location observe.

**Expected Result**
Favourite location naming text box should properly aligned.

**Actual Result**
Favourite location naming text box is not properly aligned.

**Comment by MercyQueen** [comment]
Expected.

**Comment by krupal-14** [comment]
@MercyQueen user cannot see what he/she typing i think this should be fix.

**Comment by vinod96424** [comment]
Tested, working fine in iOS XR
