### ISSUE TITLE
Jaatri saathi symbol is displaying in Share app pop-up(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1978]
#1803 
**Description**
[Jaatri saathi symbol is displaying in Share app pop-up](https://drive.google.com/file/d/1lmzFx7Yj3utmNFN1u-MYUKZWlrZmbF6Z/view?usp=sharing)

**Steps to Reproduce**
1.Launch the application.
2.Login with valid credentials .
3.Book a ride.
4.start a ride.
5.Observe the pop-up.

**Expected Result**.
Yatri saathi symbol should display.

**Actual Result**
Jaatri saathi symbol is displaying.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working as expected
