### ISSUE TITLE
"Total paid" Hindi Text is cropping in Invoice Page(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1979]
#1803 
**Description**
["Total paid" Hindi Text is cropping in Invoice Page](https://drive.google.com/file/d/10QItSZ24MEnfT83TjcJbhI7p-fHrr7hs/view?usp=sharing)

**Steps To Reproduce**
1.Launch the application.
2.Login with valid credentials.
3.Click on hamburger -->MY Rides-->View Invoice 
4.Observe the screen.

**Expected Result**
Text should not crop

**Actual result**
Text is cropping.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine.
