### ISSUE TITLE
Distance more than 500 m is not in red color for destination field (Parent_Id - 1980)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1981]
#1980 

[When user search for some location using auto suggestion, the distance more than 500 m not showing in red color for destination field](https://drive.google.com/file/d/1EPbbKFfIbfEzMyN_Elq0_TI7fSqWIDdO/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Search for location in source and destination

**Expected result**
Distance more than 500 m should be shown in red color

**Actual result**
It is not shown

**Comment by ashishsingh101** [comment]
@rohanrp179 this is expected, it should be only for source > 500 m

**Comment by rohanrp179** [comment]
Sure. Closing this as this is expected
