### ISSUE TITLE
Customer feedback screen not as per figma(Parent_id-#1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1982]
#1980 
[1. Instead of "Rate your experience"  **Rate your ride with_Driver name** is there in figma
2. Driver profile icon is missing
3. In figma background there is no **Ride Completed** screen
4. Place holder text is incorrect as per figma](App screen shot: https://drive.google.com/file/d/1fPe_FcNH7cmcGqkvtWE1wnu6-xdA4amt/view?usp=sharing
Figma screen shot: https://drive.google.com/file/d/1yZMicKqZhnZa1GBbbM82vd9G0aqEibBf/view?usp=sharing)

**Steps to reproduce** 
1. Launch the application 
2. Search for a ride 
3. Complete a ride
5. Observe the end ride screen

**Expected Result**
Customer feedback screen should be as per figma.

**Actual Result**
1. Instead of "Rate your experience"  **Rate your ride with_Driver name** is there in figma
2. Driver profile icon is missing
3. In figma background there is no **Ride Completed** screen
4. Place holder text is incorrect as per figma

**Comment by ashishsingh101** [comment]
@aryan-13

**Comment by aryan-13** [comment]
Fixed

**Comment by Sumedh-14** [comment]
Still the issue is present in the apk shared on [31/07]


![Image](https://github.com/nammayatri/nammayatri/assets/60838760/3459ead1-d652-4652-8485-42addb32c5c6)





![Image](https://github.com/nammayatri/nammayatri/assets/60838760/9fa0afe6-92dc-4b2c-a2e0-4868df479ec6)
