### ISSUE TITLE
When dynamic Lottie ends , try again screen is not appearing if we minimise and open the app during ride search (Parent_Id - 1980)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1983]
#1980 

[When user minimise the app during ride search and open again ,though the line ends, we are not getting try again option ](https://drive.google.com/file/d/1EV8tCkEGJFOfLEQCSZuj9PjaHcEMoEbP/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Search for ride and minimise the app
3. Open the app after 30-50 sec

**Expected result**
If line ends , we should get try again search.

**Actual result**
When line ends, it is starting again from where it was started, when we opened the app after minimising it.

**Comment by ashishsingh101** [comment]
@rohanrp179 what was the duration for the whole process from searching to try again screen in this case ?

**Comment by rohanrp179** [comment]
@AshishSaini25 Not observed the total time duration but only noticed the diff in lottie line... It is reproducible everytime

**Comment by ashishsingh101** [comment]
@rohanrp179  can you check the time as well

**Comment by ashishsingh101** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Retested, working as expected.
