### ISSUE TITLE
Source field is shown with comma if ride search is done from current location (Parent_Id - 1980)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1984]
#1980 

[When ride is searched from current location , the address is not reflecting on Ride otp screen in source](https://drive.google.com/file/d/1Edus_aSK1V_RjZe2Vg519b7OkZhjV7dl/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Search for a ride from Current location

**Expected result**
On Ride OTP screen, the source and destination address should be shown

**Actual result**
The source address is not shown.

**Comment by ashishsingh101** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
