### ISSUE TITLE
Driver Pickup charge is missing in Rate card(Parent_Id - 1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1985]
#1980 
[Driver Pickup charge is missing in Rate card](https://drive.google.com/file/d/1mHb_3VDDPk-AUbAKM70VCvUk5G1AdO83/view?usp=sharing)

**Steps to reproduce** 
1. Launch the app 
2. Select source and destination
3. Tap on rate card and observe 

**Expected Result**
Driver Pickup charge should be there in rate card.

**Actual Result** 
Driver Pickup charge is missing in Rate card.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Sumedh-14** [comment]
The issue is fixed and so closing the issue.
