### ISSUE TITLE
End ride 3 star suggestion pill is not according to figma(Parent_Id-1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1986]
#1980
**Descritption**
[End ride 3 star suggestion pill is not according to figma](https://drive.google.com/file/d/1ef2qY5GojAoXk7sLDu4jGxVU6gaouvBP/view?usp=sharing)

[Figma ](https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=61198-19125&mode=design&t=fYnWdaRYU3fNtjZX-0)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride.
4.Start a ride.
5.End a ride.
6.Give 3 stars observe the suggestion pills.

**Expected result**
suggestion pills should be according to figma.

**Actual Result**
suggestion pill is not according to figma.

**Comment by aryan-13** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine.
