### ISSUE TITLE
Call Support is not working in Ride Completed Screen (Parent_ID_#1980)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1987]
**#1980** 

In Ride Completed Screen Call & Support Button is not working 

**Steps -**
1. Access the application and Login with valid credentials
2. Search and Complete one Ride
3. Observe the Ride Completed Screen (Call & Support Button)

**Expected -** 
Call & Support Button should work

**Actual -** 
Call & Support Button is not working 

https://github.com/nammayatri/nammayatri/assets/137036742/11fad3b1-a0d6-4c91-adc3-e5df0409840b

**Comment by ashishsingh101** [comment]
@Rohit4997

**Comment by ashishsingh101** [comment]
Fixed

**Comment by Sumedh-14** [comment]
This issue is fixed in the APK shared on 31/07 and hence closing the issue
