### ISSUE TITLE
User app not coming back to RefreshState when we minimise app more than 30sec(Parent_Id - 1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1988]
#1980 
[User app not coming back to RefreshState when we minimise app more than 30sec](https://drive.google.com/file/d/12BXY8quAsTDMqbJ6yeffH4GppvvWq3mu/view?usp=sharing)

**Steps to reproduce** 
1. Launch the app
2. Tap on Hamburger 
3. Minimise the app more than 30 sec
4. Open the app and observe 

**Expected Result**
User app should come back to RefreshState when we minimise app more than 30sec

**Actual Result**
User app not coming back to RefreshState when we minimise app more than 30sec

**Comment by ashishsingh101** [comment]
@Rohit4997

**Comment by Vinaykm999** [comment]
Hey @Rohit4997 earlier we used re-fresh in each and every screen right?

**Comment by Rohit4997** [comment]
> Hey @Rohit4997 earlier we used re-fresh in each and every screen right?

@Vinaykm999 It was causing google maps API calls that's why we removed

**Comment by Vinaykm999** [comment]
okay, As per dev comments, i am closing this issue
