### ISSUE TITLE
User application is getting crashed - 2(5) (Parent_id-#1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1989]
#1980 

[User application is getting crashed](https://drive.google.com/file/d/1LPoUbg-ZNRH4OT3fnV0j9vml4Rvq5Z1o/view?usp=sharing)

**Steps:**
1. Launch the application
2. Search for a ride
3. Minimise the user app
4. Wait for 3+ minute 
5. Open minimised user app
6. Verify

**Actual :** application crashed

**Comment by ashishsingh101** [comment]
@Vinaykm999 I think it's not crash but the app got stuck on splash screen

**Comment by Vinaykm999** [comment]
![image (19)](https://github.com/nammayatri/nammayatri/assets/131981246/0000147c-19d7-43ef-b3a9-9bfe20256277)
Kindly check this screenshot.
@ashishsingh101

**Comment by ashishsingh101** [comment]
Fixed

**Comment by Sumedh-14** [comment]
This issue is fixed in the apk shared on 31/07 and hence closing the issue
