### ISSUE TITLE
Ride Completed Screen - UI Issue (Parent_ID_#1980)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1990]
**#1980** 

**UI Issues**
1. Rate your experience text is different from figma
2. Driver Image is not displaying 
3. Bottom space is more compared to figma 

**Steps -**
 1. Access the application
 2. Search for ride and complete a ride 
 3. And Observe the ride completed screen

**Figma**
https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=61198-19125&mode=design&t=YgE17VJyws82nVbL-0 

![markup_1000000560](https://github.com/nammayatri/nammayatri/assets/137036742/a01f1f3f-59da-4708-ac06-119a5e3e552c)

**Comment by ashishsingh101** [comment]
@aryan-13

**Comment by aryan-13** [comment]
Fixed. We don't have driver profile image yet

**Comment by johnruban-4050** [comment]
Point 1 & 3 is working fine as expected

**Comment by johnruban-4050** [comment]
@SrinivasNaikB Can you please confirm for the point 2

**Comment by Rohit4997** [comment]
@johnruban-4050  If the image is not there than the space will be empty only
We can't show dummy Image there
Please confirm with the designers once

**Comment by johnruban-4050** [comment]
@Rohit4997 As discussed with Sreedeep the image should display if the driver is not having any image then it should display the default image in the mentioned screen

cc @Vinaykm999 @krupal-14

**Comment by Rohit4997** [comment]
> 

@aryan-13

**Comment by ashishsingh101** [comment]
Fixed
