### ISSUE TITLE
End ride Suggestions pills are incorrect in kannada language(Parent_Id-1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1991]
#1980 
**Description**
[End ride Suggestions pills are incorrect in kannada language](https://drive.google.com/file/d/1OgmiGtBDrKpcJE8YqZiZZn95JVeePxDB/view?usp=sharing)

**Steps To Reproduce** 
1.Launch the apk.
2.Login with valid credentials .
3.Select the language as kannada.
4.Book a ride.
5.End a ride.
6.Observe the suggestion pill.

**Expected Result**
All end ride suggestion pills should be correct.

**Actual Result**
End ride suggestion pills not correct.

**Comment by aryan-13** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine.
