### ISSUE TITLE
When MG road drop point is getting selected, there is delay of 1-2 sec to move radio button from Residency to road to MG road radio button (Parent_Id - 1980)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1993]
#1980 

[When user select One plus as source, the ballon mark goes to MG road pickup but the radio button takes 1-2 sec to go to MG road radio button. This is clearly visible the delay and cannot miss](https://drive.google.com/file/d/1-BClhaTQa24NgbsAz380By4o_bw5Swqp/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Search for One Plus Brigade road from source
3. Select any destination

**Expected result**
It should not be noticeable when Radio button moves from one pick up point to another

**Actual result**
It is coming with 1-2 sec delay which is noticeable

**Comment by ashishsingh101** [comment]
Expected

**Comment by ashishsingh101** [comment]
also we added debounce so this is expected

**Comment by ashishsingh101** [comment]
and debounce we are using to reduce call of placeName API

**Comment by Vinaykm999** [comment]
As per dev comment, resolving the above issue
