### ISSUE TITLE
Brigade road pickup points is not showing when user select source from suggestions (Parent_id-#1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#1994]
#1980
[Brigade road pickup points is not showing when user select source from suggestions](https://drive.google.com/file/d/1BzYAc7D01HpdgXv79FxOgbUMV9Fa4Oid/view?usp=sharing)

**Steps:**
1. Open apk
2. Search source as brigade road and select from suggestions 
3. Select destination address 
4. Verify confirm location
5. Navigate screen towards up
6. Verify shape file

**Expected :** Pickup location on 2 points should display along with brigade shape

**Comment by ashishsingh101** [comment]
Expected

**Comment by Vinaykm999** [comment]
As per dev comment i'm closing this issue
