### ISSUE TITLE
User is getting "goto selected pickup point" text in normal pickup zone(Parent_id-#1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#1995]
#1980 
[1. User is getting "goto selected pickup point" text in normal pickup zone ](https://drive.google.com/file/d/1Qv5LWIlCmAmAO9HOQ0QOsg-KrKSFTfR8/view?usp=sharing)

**Steps to reproduce** 
1. Tap on where to?
2. Select destination from locate on map in special zone
3. Tap on confirm drop location and observe confirm pickup location screen

**Actual Results** 
User is getting "goto selected pickup point" text in normal pickup zone 

**Expected Results**
User should not get "goto selected pickup point" text in normal pickup zone

**Comment by ashishsingh101** [comment]
Fixed

**Comment by Rajaprabhu-Natrajan** [comment]
retested done. It's working fine.
