### ISSUE TITLE
In  Map enhancement the tool tip is not displayed as per figma.(Parent_Id-#1980)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#1996]
#1980 
[In Map enhancement the tool tip is not displayed as figma(https://drive.google.com/file/d/1uv2u8Ha68IpsUHCxZB4RF1KjSxF14GXy/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Search the special location
3. look the enhancement map 
4. point the location
5. verify the tool tip

Expected Result:-
Tool tip should display as per figma

Actual Result:-
It's  not displayed as per figma.
![Screenshot_2023-07-28-16-16-25-96_88a774e4ba75b7addb8b842e78164a94](https://github.com/nammayatri/nammayatri/assets/134508712/eeb194ae-b9ca-43ad-8765-4729dec8cdd1)

Figma image:-
<img width="383" alt="Screenshot 2023-07-28 at 4 34 54 PM" src="https://github.com/nammayatri/nammayatri/assets/134508712/50f896e3-4dc2-49c9-a6b5-a2c784ef5b9b">

Reproduce rate - 5/5

Device - Oppo F7 (10)

**Comment by ashishsingh101** [comment]
@Rajaprabhu-Natrajan by tool tip you mean lable ?
