### ISSUE TITLE
Searched Suggestion is not Showing while entering the searched data in Source (Parent_ID_#1980)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#1998]
**#1980** 

In Source - Searched Keyword Suggestion is not showing while entering the data

**Steps -**
1. Access the application
2. Navigate to Source and Enter any data (Ex - Type Nexus and observe the screen)

**Expected -** 
Searched Keyword Suggestions should display in Source

**Actual -** 
Searched Keyword Suggestion is not displaying

https://drive.google.com/file/d/11N8OAogHmWPH3NvovmUMk803FKRM8iQ_/view?usp=drive_link

**Comment by ashishsingh101** [comment]
Fixed

**Comment by krupal-14** [comment]
fixed
