### ISSUE TITLE
If invoice is downloaded from ride details from User feedback screen, most of the fields like Ride Id and time is missing (Parent_Id - 1980)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#1999]
#1980 

[If invoice is downloaded from ride details from User feedback screen, most of the fields like Ride Id and time is missing](https://drive.google.com/file/d/1-K_SBAqV6yBwSR6aT0ZhaY8Lo6Dv1yAe/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Start the ride and end
3. Click on Ride details on user feedback screen

**Expected result**
User should see all the details of invoice

**Actual result**
User is not able to see ride id, time etc

**Comment by ashishsingh101** [comment]
Fixed
