### ISSUE TITLE
Special Location tag is displayed for Normal location also.(Parent_Id-#1980)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2000]
[Special Location tag is displayed for Normal location also](https://drive.google.com/file/d/1Dudt7lv4N9uGhj8ynx8bv9OFtQ6KyQZH/view?usp=sharing)

Step to reproduced:-
1. Launch the app
2. Enter Source as Special location & Destination as Normal location 
3. Search the ride 
4. Special tag is displayed on Confirm location screen
5. Then do it as vice versa
6. observer the issue 

Expected Result:-
Normal location special tag should not displayed
 Actual Result:-
Normal location special tag is displayed

Reproduce rate - 5/5

Device - Oppo F7 (10)

**Comment by ashishsingh101** [comment]
Fixed
