### ISSUE TITLE
Hindi Language - Feedback Pills should displayed in Hindi only(Parent_ID-#1980)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2001]
[Hindi Language - Feedback Pills should displayed in Hindi only](https://drive.google.com/file/d/1bwt06b4zJhrgJMOSkhiKKZhPbbXei8qz/view?usp=sharing)

Step to reproduce:-
1. Launch the app with hindi language
2.Book the ride
3. End the ride
4. Click on Feedback 
5. Observe the issue

Expected Result:-
Feedback pills should be displayed in hindi language

Actual Result:-
Feedback pills is displayed in English after user selected hindi language

Reproduce rate - 5/5

Device - Oppo F7(10)

**Comment by aryan-13** [comment]
Fixed
