### ISSUE TITLE
Selected suggestions pills are getting deselect when user click on back arrow or click on out of the poupup (Parent_id-#1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2003]
#1980
[Selected suggestions pills are getting deselect when user click on back arrow or click on out of the poupup](https://drive.google.com/file/d/144QL6I-y3XhvrjKyLr1v82TgIBPgR4-N/view?usp=sharing)

Steps: 
1. Start ride
2. End ride
3. Verify ride complete screen
4. Rate 3 star
5. Select suggestion pills
6. Click on out side suggestions popup/Back arrow 
7. again click on the 3 star
8. Verify suggestion pill

Actual: Previously selected suggestion pills are getting deselect

**Comment by ashishsingh101** [comment]
Expected

**Comment by Vinaykm999** [comment]
@ashishsingh101 No, If the user selects all 5 suggestions and accidentally click on outside the popup, selected suggestions should persist until user deselect

**Comment by Vinaykm999** [comment]
@SrinivasNaikB 
Could you please confirm the above mentioned issue, as dev are saying mentioned it as expected.

**Comment by Vinaykm999** [comment]
Working fine
