### ISSUE TITLE
Reply option is not left aligned as per figma (Parent_id-#1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2004]
#1980
[Reply option is not left aligned as per figma](https://drive.google.com/file/d/1x6BXdX9zihDXbjF8Sea0mL73j89b8N8Y/view?usp=sharing)

**Steps**:
1. Start ride
2. Minimise user apk
3. Send message from driver
4. Verify notification in user
5. Reply option is not left aligned

**Expected**: Reply should be left aligned
<img width="872" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/6a9afb51-e3e9-429a-9b27-be5602afb3e3">

**Comment by ashishsingh101** [comment]
Expected

**Comment by Vinaykm999** [comment]
@SrinivasNaikB Could you please confirm the above issue as expected?

**Comment by krupal-14** [comment]
closing this issue as per dev comment.
