### ISSUE TITLE
Auto icon and tracking is missing when ride is started from one of the two Brigade road points using Auto assign (Parent_Id - 1980)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2006]
#1980 

[Auto icon and tracking is missing when ride is started from one of the two Brigade road points using Auto assign](https://drive.google.com/file/d/1-M87-lA8NAloFmdrCprQy4zcFFrL8cJd/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Choose any one point from brigade road as source
3. Select ride using Auto assign

**Expected result**
Auto icon and tracking to pickup should be shown 

**Actual result**
It is not shown for Brigade road both gates

**Comment by ashishsingh101** [comment]
Fixed
