### ISSUE TITLE
Unable to confirm the ride (Quote confirm)when ride selected from special location (Brigade road/nexus mall) - (Parent_id-#1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2007]
#1980
[Unable to confirm the ride (Quote confirm)when ride selected from special location (Brigade road/nexus mall)](https://drive.google.com/file/d/1x8pr2ngrizT9ssxZPV-JPhz6c_ZFHb3z/view?usp=sharing)

**Steps**:
1. Request ride from special location, source as special location
2. Select Multiple driver option
3. Accept ride from driver
4. Select quote confirm by user
5. Verify 
6. Wait for 10 seconds and observe 
7. Kill and relaunch app
8. verify

**Actual** : Confirm action is not happening, post 10 sec also ride is not assigning

**Comment by Sumedh-14** [comment]
User is able to confirm the ride in both the special zones and hence closing the issue
