### ISSUE TITLE
Hindi translation of one of the word is wrong. It should be 'जल्दी' instead of 'जड़ली' (Parent_Id - 1980)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2008]
#1980 

[Hindi translation of one of the word is wrong. It should be 'जल्दी' instead of 'जड़ली' ](https://drive.google.com/file/d/1-O_cpuY1D7HHWOXyOQ3d4YqeSr4jJYLg/view?usp=sharing)

**Steps to reproduce**
1. Log in to app
2. Start the ride
3. Go to in app chat (Choose Hindi Language )

**Expected result**
The words should be properly translated as shown in title

**Actual result**
They are not translated as shown in title

**Comment by ashishsingh101** [comment]
Fixed

**Comment by johnruban-4050** [comment]
Retested and working fine as expected  

cc @rohanrp179 
![Screenshot_20230801-131227](https://github.com/nammayatri/nammayatri/assets/137036742/f4c110d3-f262-49dd-abf7-b22a20e1b584)
