### ISSUE TITLE
Message fcm should disapper when user clicks on replay button.(Parent_Id-1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2011]
#1980 
**Description**
[Message FCM should disappear when user clicks on replay button.](https://drive.google.com/file/d/1H_I7PUEYdWnH0USwQTvmzmVPPMGOcDvR/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride.
4.Minimize the user apk.
5.Send message from driver.
6.User receives message -->click on replay.
7.The message FCM should disappear.

**Expected Result**
The message FCM should disappear when user clicks on replay button. 

**Actual Result**
The message FCM is not disappearing. 

Note: Usually  that FCM will be there for 7 sec on the home screen of mobile.
But if we click on replay button that FCM should disappear.but it is still displaying for 7 sec.

**Comment by ashishsingh101** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine
