### ISSUE TITLE
Loader is displaying continuously while adding Emergency contacts (Parent_ID_1980)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2012]
**#1980** 
Loader is displaying continuously while adding emergency contacts 

**Steps** - 
1. Access the application
2. Navigate to emergency contacts and tap on add 
3. In Contacts listing screen (Scroll down and then scroll upwards and observe the screen)

**Expected** - 
Loader should not display continuously 

**Actual** - 
Loader is displaying continuously

https://drive.google.com/file/d/1ZyEbHFl-G6p707vsyaFHmyPBrFEuUIlC/view?usp=drive_link

**Comment by ashishsingh101** [comment]
Fixed
