### ISSUE TITLE
Source location is getting changed in special zone, Location is changing to out of the kolkata location and giving city limits error message (Parent_Id - 1803) 

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2062]
#1803
[Source location is getting changed in special zone, Location is changing to out of the kolkata location and giving city limits error message ](https://drive.google.com/file/d/1trecx8Y7oWpKw2pnFpS2ifQEd0ZxzWTn/view?usp=sharing)

**Steps**: 
1. Open YS ipa
2. Click on current location
3. Enter source address as kolkata railway station
4. Destination as kolkata
6. Check source address

**Actual**: Source address is changing to out of the city 

**Device:** 

1. iPhone SE - IOS-16.3
2. iPhone 13 -  IOS -16.5.1 (c)

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested ,working fine
