### ISSUE TITLE
Getting error occurred when we select ride from special location  (Parent_Id - 1803)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2063]
#1803
[Getting error occurred when we select ride from special location  and after try again user is getting blank OTP](https://drive.google.com/file/d/19Fb3dv1KO9yTGaSo8wnWxDugiE3WHzXv/view?usp=sharing)

**Steps:**

1.  Open ipa
2. Click on current location
3. Enter source address as kolkata and clear
4. Select again source as railway station
5. Destination as kolkata
6. Search for a ride
7. Verify no driver available
8. Enter source address as kolkata and clear
9. Select again source as railway station
10. Destination as kolkata
11. Search for a ride
12. Select AC varient
13. Verify error occured(Quote does not exist)
14. Retry ride search
15. Accept the ride request from driver
16. Verify blank OTP in user

**Actual :** Getting error occurred when we select ride from special location  and after try again user is getting blank OTP

**Device:**

iPhone SE - IOS-16.3

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Issue is still there moving it to backlog

**Comment by MercyQueen** [comment]
fixed.

**Comment by Vinaykm999** [comment]
Retested, working fine.
