### ISSUE TITLE
In Confirm Pickup location - Touch area should be less (Multiple Location) (Parent ID #1803)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2065]
**#1803** 

In Confirm Pickup location - Touch area should be less (Multiple Location) 

**Steps** -
- Access the application
- Book for ride 
- Source Location - Special Location (Ex - Howrah Railway Station)
- Destination - Any Location (Ex. Kolkata)
- Navigate to Confirm Pickup location and Observe 

**Expected** - 
User Should be able to select only with radio button

**Actual** -
User is able to select with the full layout

https://github.com/nammayatri/nammayatri/assets/137036742/9735d37e-10c2-4625-a869-618fe35e251d

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retesed, Working fine.
