### ISSUE TITLE
French language is coming in yatri sathi home screen(parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2070]
#1803 
**Description**
[France language is coming in yatri sathi home screen](https://drive.google.com/file/d/1ZmoaHHku_gMWptxnUrBeweXijMFXd5Bh/view?usp=sharing)

**Steps to Reproduce**
1.Launch the apk.
2.Login with valid credentials in device 1
3. login with the same number in different number in device 2
4. Verify the French language in device 1.

**Expected Result**
Perticular number should logout from device 1.

**Actual result**
French language is displaying in device 1.

**Comment by MercyQueen** [comment]
fixed.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested ,Working fine
