### ISSUE TITLE
Driver can accept the OTP from user who is in different special location(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2071]
#1803 
**Description**
[Driver can accept the OTP from user who is in different special location](https://drive.google.com/file/d/1aGaIb3qNOBixn1B4Sn5oS8WkJuBW_L3k/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride from special location 1.
4.driver is in different  special location 2.
5.Enter the OTP in driver end.

**Expected Result**
If driver is not there in that particular special location OTP should not accept.

**Actual Result**
Ride is starting even though driver is in different special location.

**Comment by MercyQueen** [comment]
Expected for now. As restriction is not added from backend.
