### ISSUE TITLE
Late pick-up is displaying as late drop-off in kannada end ride suggestion pills(Parent_Id-1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2078]
#1980 
**Description**
[Late pick-up is displaying as late drop in end ride suggestion pills](https://drive.google.com/file/d/1chsci-ItPa0IxRJaS_xfHwhseJbzBd7c/view?usp=sharing)
[Figma](https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=12738-667&mode=design&t=ATK0pBTvMbFRqJ7D-0)

Steps To Reproduce
1.Launch the apk.
2.login with valid credentials.
3.Book a ride.
4.start a ride.
5.end a ride.
6.observe the late pick-up suggestion in kannada.

Expected result
It should be late pick-up in kannada.

Actual Result
Late drop-off in place of late pick-up.

**Comment by Vinaykm999** [comment]
Working as expected
