### ISSUE TITLE
In "my rides" screen rides are not according to time(Parent_Id-1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2087]
#1980 
**Description**
[In "my rides" screen rides are not according to time](https://drive.google.com/file/d/1L44VaUQkrVA_EmROnRMtk5UVqJZIMCup/view?usp=sharing)

**Steps to Reproduce**
1.Launch the apk.
2.Login with valid credentials 
3.Take some few rides cancel some rides
4.Then observe my rides screen.

**Expected Result**
New rides should come 1st.

**Actual result**
New rides are not coming 1st.

**Comment by ashishsingh101** [comment]
will fix this in upcoming release

**Comment by ashishsingh101** [comment]
Fixed
