### ISSUE TITLE
Messages are not receiving to user when app is in Background state (Parent_Id - 1980)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2091]
**#1980** 

[Message are not receiving to user when app is in Background state](https://drive.google.com/file/d/1T7USKGthMsbUVMKTLyD9dPtge0kJdyrb/view?usp=drive_link)

**Steps -**
1. Book Ride and make User APK to Background State 
3. And Drop a message to user
4. Observe the screen of User APK

**Expected -**
Message should display in user (Notification) 

**Actual -**
Message are not displaying to user 

**Note** - 
1. Notifications are enabled in settings
2. Message are displaying once the user apk is opened

**Device** - Google Pixel 6A (Android 13)

**Comment by ashishsingh101** [comment]
@johnruban-4050 can you check notification permission for this device

**Comment by ashishsingh101** [comment]
@johnruban-4050 we checked and its not user side issue, some backend issue is there

**Comment by ashishsingh101** [comment]
issue is not related to user app

**Comment by johnruban-4050** [comment]
@ashishsingh101 Can you please help here that whom need to assign for this
