### ISSUE TITLE
Unable move the driver to "Online" status- it's showing "Something went wrong" toast (Parent_id-#2096)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2097]
#2096 
[Driver App - Unable move the driver to "Online" status- it's showing "Something went wrong" toast](https://drive.google.com/file/d/1JhE7Y-7i9jI_ZYdrxZ0L_lDmGlz402Wj/view?usp=sharing)

Step to reproduced:-
1. Launch the app
2. Enter Driver number
3. Try to pay the amount
4. Payment  was pending
5. Try to move Offline to Online
6.  Observe the issue

Expected Result:-
Driver can able to move offline to Online

Actual Result:-
Driver unable to move on to online.

Reproduce rate - 5/5

Device - Oppo F7(10)
<img width="1633" alt="Screenshot 2023-08-01 at 8 56 59 PM" src="https://github.com/nammayatri/nammayatri/assets/134508712/5c8298db-2285-4d6a-960e-dfadc2918efe">

**Comment by Vignesh-772** [comment]
If payment is pending backend will not allow to change to online. In logs I could see that payment status api gave status a pending.

**Comment by Vignesh-772** [comment]
Expected

**Comment by AlluGowthami28** [comment]
@Vignesh-772 @Rohit4997 Instead of showing "Something went wrong try again" toast, can we show proper error message like "Please complete your payment to move online"

**Comment by AlluGowthami28** [comment]
@ashishsingh101 @aryan-13

**Comment by JanhaviSoni** [comment]
we are sending error from backend
