### ISSUE TITLE
For new driver stars are displaying in driver profile screen &it is cropped also(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2098]
#2096 
**Descritption**
[For new driver stars are displaying in driver profile screen](https://drive.google.com/file/d/194YMddI2vujnngVvUiHv_db-KOpo77g4/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Upload DL & RC.
4.Click driver profile.
5.Observe the profile screen driver stars

**Expected Result**
For new drivers starts should not display.

**Actual Result**
For new driver stars are displaying.

**Comment by Vignesh-772** [comment]
Fixed

**Comment by vinod96424** [comment]
issue not resolved

**Comment by vinod96424** [comment]
Stars are cropped.

**Comment by AlluGowthami28** [comment]
Working as expected.
