### ISSUE TITLE
Customer support number is not displaying in dailer pad ( Parent_ID_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2099]
#2096

[Customer support number is not displaying in dailer pad when driver click on call support centre
](https://drive.google.com/file/d/1j-_7dbFL53YasNw1L_sJHF5Pi5S_J19D/view?usp=sharing)
**Steps**: 
1. Launch driver apk
2. Enter new driver number
3. Enter OTP
4. Click on Help
5. Click on call support centre
6. Verify Dailer pad

**Expected**: 
Dailer pad should display customer support number

**Actual** : Dailer pad is not displaying customer number

**Devices tested:**  Google pixel 6a

**Comment by AlluGowthami28** [comment]
Working fine.
