### ISSUE TITLE
My Profile -> Driver Details UI Issues (Parent_ID_ -#2096)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2101]
**#2096** 

**Issues -**
1. Edit Profile Icon is not displaying
2. Vehicle Icon is not displaying
3. Summary - **"Earned on YS"** text is not displaying
4. Summary - Ratings should display properly
5. Summary - Text should display as "Trips Completed" instead of "Trip Completed"
6. Summary - Should display the overall Kms instead of Months
7. Summary - Displaying as Namma Yatri in JS
8. Missed Opportunities - **I icon** is missing in both Cancellation rate and earnings missed
9. Missed Opportunities - **₹** Symbol is missing in Earnings missed
10. Badges Section are missing 
11. About me - **Hometown & Hobbies** are missing

**Steps -** 
1. Access the application
2. Login with valid credentials
3. Navigate to My Profile page and observe
![markup_1000000599](https://github.com/nammayatri/nammayatri/assets/137036742/900b0283-d9c4-438c-8cb4-1ab5b09d8388)

**Comment by Rohit4997** [comment]
Fixed

**Comment by Rohit4997** [comment]
Whatever info is there we need to show that only
Badages and Hometown & Hobbies are not coming from backend

**Comment by johnruban-4050** [comment]
@Rohit4997 

1. Edit Profile Icon is not displaying - **Expected**
2. Vehicle Icon is not displaying - **Expected**
3. Summary - "Earned on YS" text is not displaying - **Working**
4. Summary - Ratings should display properly - **Working**
5. Summary - Text should display as "Trips Completed" instead of "Trip Completed" - **Working**
6. Summary - Should display the overall Kms instead of Months - **Working**
7. Summary - Displaying as Namma Yatri in JS - **Working**
8. Missed Opportunities - I icon is missing in both Cancellation rate and earnings missed - **Still Exist**
9. Missed Opportunities - ₹ Symbol is missing in Earnings missed - **Working**
10. Badges Section are missing - **Backend**
11. About me - Hometown & Hobbies are missing - **Backend**


Point 8 - issue Exist
