### ISSUE TITLE
Settings - Booking Options Sections are not clickable (Parent_ID_#2096)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2102]
**#2096** 
**Booking options Sections are not clickable**

**Steps -**
1. Access the application
2. Navigate to My Profile -> Settings
3. Tap on Booking Options and Observe

**Expected -**
Booking options Sections should be clickable

**Actual -** 
Booking options Sections are not clickable

https://github.com/nammayatri/nammayatri/assets/137036742/2ac70c22-89e1-44ad-b899-d8724a10efea

**Comment by AlluGowthami28** [comment]
Working as Expected.
