### ISSUE TITLE
When driver clicks on Add Rc, fresh Add RC screen should display(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2103]
#2096 
**Description** 
[When driver clicks on Add Rc, fresh Add RC screen should display](https://drive.google.com/file/d/1Hstjb5fu23_6IAgyUg7diFxzoJJRhNRQ/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Click on driver profile.
4.Click on vehicle al details.
5.click on Add Rc
6.Observe the  screen.

**Expected Result**
New vehicle registration screen should display.

**Actual Result**
Old Vehicle registration screen and old data is displaying.

**Comment by Rohit4997** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Working as expected.
