### ISSUE TITLE
Unable to Test muiltiple RC flow (Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2104]
#2096 
**Description** 
[Whole RC flow is not according to figma](https://drive.google.com/file/d/1Hstjb5fu23_6IAgyUg7diFxzoJJRhNRQ/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.login with valid credentials.
3.Click on driver profile.
4.Click on vehicle details.
5.Click on Add Rc button.
6.New Add registration screen should display.

**Expected Result**
New add RC screen should display then only we can validate add multiple Rc flow

**Actual result**
Old vehicle registration screen is displaying and old data is displaying so cannot validate entire multiple RC flow.

**Comment by PraveenGongada** [comment]
Older rc flow is expected

**Comment by AlluGowthami28** [comment]
@PraveenGongada If new design yet to implement, can you defer this bug.

**Comment by ashishsingh101** [comment]
@AlluGowthami28 making it as ready, can you make it as done since its part of new feature and not a bug

**Comment by krupal-14** [comment]
Hence the new design has not been implemented, Closing this issue
