### ISSUE TITLE
My profile - Vehicle Details - Summary should not displayed(Parent_ID-#2096)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2105]
#2096 
[My profile - Vehicle Details - Summary should not displayed](https://drive.google.com/file/d/1NWfz2uEMN4LB7Q5tmFnxlfliEIdjvRts/view?usp=sharing)

Step to reproduced:-
1. Launch the app
2. Onboard new driver
3. Click on Profile
4. Click on Vehicle details

Expected Result:-
1.Summary option should not shown 

Actual Result:-
Summary option is shown default. refer figma

**Comment by Rohit4997** [comment]
Fixed

**Comment by Rohit4997** [comment]
@Rajaprabhu-Natrajan  Please check this link as well 
https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=61387%3A15698&mode=design&t=eXqFmqo5bZ9cZbWv-1

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine.
