### ISSUE TITLE
Driver is re-directing to app permission screen after uploading 2nd/3rd RC(Parent_id-2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2106]
#2096 
[Driver is re-directing to app permission screen after uploading 2nd/3rd RC( watch video from 3min)](https://drive.google.com/file/d/1T0KiYq4shcNyfjANyb1g64HPx1Fk5U-C/view?usp=sharing)

**Steps to reproduce**
1. Launch the app
2. Tap on add RC
3. Upload RC and observe the screen

**Actual Result**
It should go to Vehicle details screen

**Expected Result**
Driver is re-directing to app permission screen after uploading 2nd/3rd RC

**Comment by Vignesh-772** [comment]
Expected 

In background rc is getting verified so it is going to permission screen

**Comment by AlluGowthami28** [comment]
@aryanguptaSG After uploading RC it should go to profile screen as per figma.
https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=67553-18082&mode=design&t=GaSsO4jl2ArUid7v-0
