### ISSUE TITLE
Driver is unable to call another driver/customer support number to activate RC(Parent_ID-#2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2109]
#2096
[Driver is unable to call another driver/customer support number to activate RC](https://drive.google.com/file/d/1_TTVnQJH0eGe1KNKz_Q8V3mM3T7rItmj/view?usp=sharing)

**Steps to Reproduce** 
1. Launch the app go to vehicle details screen
2. Tap on edit RC (That RC should already activated in other driver)
3. Tap on Activate
4. Tap on call driver/call customer and observe the screen

**Actual Result**
Driver is unable to call another driver/customer support number to activate RC

**Expected Result**
Driver should re-direct to dial screen.

**Comment by Vignesh-772** [comment]
call driver will make a api call to backend and backend will connect to cloud telepony the call to driver . in second case ir id fixed

**Comment by AlluGowthami28** [comment]
Working as expected.
