### ISSUE TITLE
Background action is happening when Edit RC option popup is enabled (parent_id_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2110]
#2096
[Background action is happening when Edit RC option popup is enabled ](https://drive.google.com/file/d/14sowHTa7joA8LZrLDW7nVsRqXC97MyV8/view?usp=sharing)

**Steps:** 
1. Open driver apk
2. Upload multiple RC
3. Click on My profile icon
4. Click on Vehicle Details
5. Click on Edit RC
6. Verify Edit popup enabled
7. Click on background 
8. Verify

**Actual**: Background screen is not freezing

**Expected**: Background should be freeze when edit popup enabled

**Comment by AlluGowthami28** [comment]
Working as expected.
