### ISSUE TITLE
Ride Start screen UI is not as per figma(Parent_id-#2096)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2111]
#2096 
[Ride Start screen UI is not as per figma](https://drive.google.com/file/d/1ivheVaUjRSHyoi6phdTNZpTN7ais5VBc/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Search the ride
3. Ride Start screen
4. Observe the issue

Expected Result:-
Ride Start screen should be display as per figma

Actual Result:-
Ride Start screen is not shown as figma

Reproduce rate - 5/5

Device - pixel 6A

**Comment by vinod96424** [comment]
working fine
