### ISSUE TITLE
Summary Section is not according to figma(Parent_id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2112]
#2096 
**Description**
[Summary Section is not according to figma(](https://drive.google.com/file/d/1PrLwA_nxvAdR8p-jJpfW6IUej42EX-Fo/view?usp=sharing)
[Figma](https://drive.google.com/file/d/1E76Yk6fCmMC5aRfoJmdwZHYglNQhdq8L/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials .
3.Click on driver profile.
4.Observe the summary.

**Expected Result**
Summary Section should be according to figma.

**Actual result**
Summary section is not according to figma.

**Comment by Rohit4997** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Issue resolved.
