### ISSUE TITLE
Edit Sections - Vehicle Number is not displaying (Parent_ID_#2096)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2113]
**#2096** 

Edit Section - Vehicle Number is not displaying

**Steps -** 
Access the Application
Login with Valid Credentials
Navigate to My Profile ->  Vehicle details -> Edit RC
And Observe the Screen

**Expected -** 
Vehicle Number should display in edit Rc

**Actual -** 
Vehicle Number is not displaying 

![markup_1000000603](https://github.com/nammayatri/nammayatri/assets/137036742/33eb3560-427e-4867-a947-67fd26b7bc5e)

**Comment by Rohit4997** [comment]
Fixed

**Comment by vinod96424** [comment]
Working fine
