### ISSUE TITLE
Driver is able to deactivate all RC at a time (parent_id_2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2115]
#2096 
[Driver is able to deactivate all RC at a time ](https://drive.google.com/file/d/1NPHEHCHOpRwNsA-sDeD6lzug6SZDE-wl/view?usp=sharing)

**Steps to reproduce**
1. Tap on edit RC
2. Tap on deactivate 
3. And observe the status

**Expected Result**
At least one RC should be in active

**Actual Result**
Driver is able to deactivate all RC at a time

**Comment by PraveenGongada** [comment]
Expected

**Comment by AlluGowthami28** [comment]
@PraveenGongada can we get PM approval for this ?

**Comment by aryanguptaSG** [comment]
expected for now

**Comment by krupal-14** [comment]
As dev commented,closing this issue
