### ISSUE TITLE
Any Error message is not showing when driver upload existing RC (parent_id_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2116]
#2096 
[Any Error message is not showing when driver upload existing RC](https://drive.google.com/file/d/10BenL_mQOmPr0JKmPAFVls5KoSUMU5XU/view?usp=sharing)

Steps: 
1. Upload Previously uploaded RC
2. Verify Grant us following access screen
3. Select all and Allow access
4. Verify home screen
5. Verify RC

**Actual**: Error message is not showing

**Expected** : Error message should display if user upload existing RC

**Comment by PraveenGongada** [comment]
No Error message is coming from backend

**Comment by Rohit4997** [comment]
@PraveenGongada If it is ready can you mark it as ready?

**Comment by PraveenGongada** [comment]
Marking it as deferred cause no error message from backend

**Comment by JanhaviSoni** [comment]
RCAlreadyUpdated -> Just "No action required. Vehicle RC is already linked to driver." and 400

**Comment by hkmangla** [comment]
This should not throw any error. Closing this.
