### ISSUE TITLE
<JSP><Profile-Screen><Driver "vehicle details shows 'Auto Rickshaw' & Booking option have main varient as 'Sedan'> # parent_id_2096

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2119]
#2096 
**Describe the bug**
Driver "vehicle details shows 'Auto Rickshaw' & Booking option have main varient as 'Sedan

**To Reproduce**
-> Tap on My Profile
-> Tap on  Vehicle details
-> Validate the Vehicle type
-> Tap on setting
-> Tap on Booking details
-> Validate the main varient
**Expected behavior**
Vehicle varient should be Sedan

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://drive.google.com/file/d/1mHREud_FfpQoumAH6Tm7tm6qKyMuxmq2/view?usp=sharing)

**App (please complete the following information):**

**Additional context**

**Comment by 123ajay1994** [comment]
Is there any status for this?

**Comment by AlluGowthami28** [comment]
Working as expected.
