### ISSUE TITLE
User is getting 3 vehicle variants (Sedan,SUV and Hatch back ) for Ac vehicle variant(Parent_id-#2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2120]
#2096 
[User is getting 3 vehicle variants (Sedan,SUV and Hatch back ) for Ac vehicle variant](https://drive.google.com/file/d/1UW-tCpN8HlYVcKkQ-BphR9lbwnYwCgMT/view?usp=sharing)

**Steps to reproduce** 
1. Launch the app
2. Select source and destination and observe the screen

**Actual result**
User is getting 3 vehicle variants (Sedan,SUV and Hatch back ) for Ac vehicle variant

**Expected Result**
User should get Sedan variant for all 3 Ac variants.

**Comment by AlluGowthami28** [comment]
@MercyQueen @Rohit4997 User is getting duplicate variants(Sedan 2 times).
![Screenshot_20230807-171216_Yatri Sathi](https://github.com/nammayatri/nammayatri/assets/139038923/16911c8b-4d7f-44ab-ab27-17c05c3a8145)

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine
