### ISSUE TITLE
English language sub text is showing in kannada in driver about me screen (parent_id_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2121]
#2096
[English language sub text is showing in kannada in driver about me screen](https://drive.google.com/file/d/1ybRyvJfbLbxreqXLMq8osjIsBI3Eu2LK/view?usp=sharing)

**Steps**:
1. Open my profile in driver apk
2. Click Add on language 
3. verify english language 
4. Verify sub text in English language

**Actual**:
Kannada font is showing in english language 

**Expected**: 
English font only should be there

**Comment by Rohit4997** [comment]
Fixed

**Comment by vinod96424** [comment]
Working fine
