### ISSUE TITLE
Language Is selected in English but In FCM im getting in Different Language(Parent_ID_#2096)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2122]
**#2096** 
Language Is selected in English but In FCM Im getting in Different Language

**Steps -** 
1. Access the Application
2. Login with valid credentials

**Expected -**
FCM Should display in Selected Language

**Actual -** 
FCM is displaying in Other language instead of English

https://github.com/nammayatri/nammayatri/assets/137036742/5706d1c0-44ae-449f-81e0-0149dd7175ec

**Comment by Rohit4997** [comment]
It will be updated when the service is restarted
