### ISSUE TITLE
Hometown and Hobbies option is not showing in about screen in driver (parent_id_2096) 

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2123]
#2096
Hometown and Hobbies option is not showing in about screen in driver 

**Steps**:
1. Open my profile in driver apk
2. Verify About me

**Expected**: Hometown and Hobbies options are not showing as per figma

<img width="1357" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/4977bfed-40cc-4d11-9781-8ee300582e8d">

![Screenshot_20230801-233504](https://github.com/nammayatri/nammayatri/assets/131981246/43f2bf35-1731-4241-a384-e25d9dbbe13f)

**Comment by Rohit4997** [comment]
@Vinaykm999  There things we are not getting from backend
Marking it as deffered

**Comment by JanhaviSoni** [comment]
Initially when driver is created we don't send hometown we send only in updateDriver api if the driver updates it

**Comment by Vinaykm999** [comment]
As per dev comments not sending home town and hobbies, so am resolving this.

cc: @MercyQueen @JanhaviSoni
