### ISSUE TITLE
Activate RC - Vehicle Registration number should display (Parent_ID_#2096)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2124]
**#2096** 
Activate RC - Vehicle Registration number should display 

**Steps -**
1. Access the Application
2. Login with Valid Credentials
3. Navigate to My Profile -> Vehicle Details -> Edit RC -> Activate RC
4. And Observe the Screen

**Expected -**
Vehicle Registration number should display in Activate RC Popup

**Actual -**
Vehicle Registration number is not displaying in Activate RC Popup

**Credential - 7904541664**

![markup_1000000611](https://github.com/nammayatri/nammayatri/assets/137036742/01abf0d8-8bdc-4ba4-bddf-b901ae8ef8d2)

**Comment by AlluGowthami28** [comment]
Working fine.
