### ISSUE TITLE
When driver adding multiple RC, Rc added successfull screen is not displaying(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2125]
#2096 
**Description**
[When driver adding multiple RC, Rc added successful screen is not displaying](https://drive.google.com/file/d/1gMT8aamM0Dwhqvrt7rQb8qa0vj3pouQe/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.login with valid credentials .
3.Click on profile.
4.Click on vehicle details.
5.Click on add RC.
6.Enter valid details.
7.Click on Next.
8.Observe the screen

**Expected Result**
RC Added successful screen should display.

**Actual result**
Grant us following access screen is displaying.

**Comment by AlluGowthami28** [comment]
@PraveenGongada Why this is expected? Driver should go to RC added successfully screen right? If this design not yet implemented please move this bug to deferred state.

**Comment by krupal-14** [comment]
@PraveenGongada any update on this

**Comment by aryanguptaSG** [comment]
currently we don't need to show

**Comment by ashishsingh101** [comment]
since its a part of new feaature so showing toast message for now

**Comment by krupal-14** [comment]
As per dev comment,closing this issue.
