### ISSUE TITLE
<JSP><vehicle details screen><Summary should not be there according to Figma & User need to Scroll up for "add RC"> # parent_id_2096

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2127]
#2096 
**Describe the bug**
Summary should not be there according to Figma & User need to Scroll up for "add RC

**To Reproduce**
-> Log in to Home screen
-> Tap on Profile
-> Tap on Vehicle details 
-> Validate the "Summary"
-> Validate "Add RC" after scrolling up the Screen.

**Expected behavior**
Summary should not be at "Vehicle details" and "Add RC" should be at front. 

**Screenshots**
https://drive.google.com/file/d/1xuMZDHzGH1DRDCJu4T2Fb7JmwrP8x85K/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by AlluGowthami28** [comment]
Working as expected.
