### ISSUE TITLE
Added alternative number is not displaying when driver clicked on edit (Parent_id_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2133]
#2096

[Added alternative number is not displaying when driver clicked on edit](https://drive.google.com/file/d/1t5BdOwUnTpfwcPBX9EXdJJHH0551ttDR/view?usp=sharing)

**Steps:**
1. Open driver apk
2. Add alternative number
3. Click on edit icon
4. Click on edit
5. Verify number field

**Actual**: Added alternative number is disappearing 

**Expected**: Added number should not get disappear

**Comment by aryan-13** [comment]
Expected

**Comment by vinod96424** [comment]
@aryan-13 Instead of clearing the number, Can we show the digits

**Comment by ashishsingh101** [comment]
Fixed

**Comment by Sumedh-14** [comment]
Retested on 17/08, the added alternative number is displaying and hence closing the issue
