### ISSUE TITLE
<JSP><end ride screen><end screen UI is not according to Figma > # parent_id_2096

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2135]
#2096 
**Describe the bug**
end screen UI is not according to Figma.

**To Reproduce**
-> Make a ride booking
-> Enter the OTP and start ride.
-> Validate the End Ride Screen

**Expected behavior**
<img width="444" alt="Screenshot 2023-08-02 at 12 52 57 AM" src="https://github.com/nammayatri/nammayatri/assets/128033831/5a0d972a-b747-448f-a9ca-60fba39dd718">

**Screenshots**
![Screenshot_20230802_003534](https://github.com/nammayatri/nammayatri/assets/128033831/62199af3-aaf6-4985-bdc2-863204bf83b9)

**App (please complete the following information):**

**Additional context**

**Comment by 123ajay1994** [comment]
Is there any status for it?

**Comment by AlluGowthami28** [comment]
Working as expected.
