### ISSUE TITLE
<JS DRIVER> Vehicle details are not displaying when driver chooses bengali language (Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2139]
#2096 
**Description**
[Vehicle details are not displaying when driver chooses bengali language](https://drive.google.com/file/d/1NlSXqtgv7p_nuLbrVjmBxrjerBAsaMeo/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Click on driver profile.
4.Click on setting.
5.click on language -->choose bengali language->click on update button
6.click On vehicle details.
7.Observe the screen.

**Expected  result**
All contents should display.

**Actual Result**
Vehicle Contents are not displaying.

**Comment by Vignesh-772** [comment]
There is no vehicle linked to the number you shared.

**Comment by krupal-14** [comment]
@Vignesh-772  RC is already linked with that number. As this issue is still there so moving this issue to backlog state.

**Comment by ashishsingh101** [comment]
Fixed

**Comment by krupal-14** [comment]
Restesed,Working fine.
