### ISSUE TITLE
<JSP><Profile Screen><Navigating to Setting Screen after active/deactive the RC> #parent_Id 2096

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2147]
#2096 
**Describe the bug**
Navigating to Setting Screen after active/deactive the RC

**To Reproduce**
-> Log in to application
-> Tap on profile Screen
-> Tap on setting 
-> Change the language 
-> Tap on Back
-> Tap on edit
-> make active/deactive RC
-> Observe the issue 

**Expected behavior**
Should come Profile screen instead of setting screen
**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://drive.google.com/file/d/1v25RIqaCdQp8rKYTQbSH324_6JiDJnzO/view?usp=sharing)

**App (please complete the following information):**

**Additional context**

**Comment by 123ajay1994** [comment]
Is there any status for it?

**Comment by AlluGowthami28** [comment]
Still issue existing.

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1ki86DA5L_voGc19f1Mw9eXlYmlhub_r0/view?usp=sharing

Issue has been fixed, So marking it as "Closed".
