### ISSUE TITLE
<JS USER>Polyline is disappearing when user kills and relaunch the application (parent_id_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2148]
#2096
[Polyline is disappearing when user kills and relaunch the application](https://drive.google.com/file/d/1Mrp-3Ec-SlgJ8qML1b0_AXlepoD_lWfH/view?usp=sharing)

**Steps:**
1. Launch user apk
2. Search ride
3. Assign the ride
4. Verify polyline
5. Kill and relaunch user apk
6. Verify polyline

Expected: Polyline should not disappear

**Comment by ashishsingh101** [comment]
Fixed

**Comment by Vinaykm999** [comment]
retested, working fine
