### ISSUE TITLE
<Major Issue><JSP><MultipleRC><2 drivers are activated at once with same RC > #Parenet_UD: 2096

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2149]
#2096 
**Describe the bug**
2 drivers can be activated same time with same RC

**To Reproduce**
-> take 2 drivers(D1 & D2)
-> Link D1 with R1 & R2 and make R1 "activated"
-> Link D2 with R2 only and make R2 activated
-> Deactivate R2 from D2 and Activate R2 from D1
-> Try to activate R2 from D2 again
-> If got "Already linked with another driver" than Make R1 activated in D1 and than activate R2 in D2
-> try to make R2 activate in D1 and observe the issue.

**Expected behavior**
same RC should not be activated at same time in 2 different drivers until one driver should deactivate.

**Screenshots**
https://drive.google.com/file/d/1t2astvyXmzfaD0LWmg-Gktv00DB5GrcB/view?usp=sharing

**App (please complete the following information):**

**Additional context**
a. Driver who's RC got Activated at first only be able to get the ride.
b. Both (D1 & D2) driver will not be able to unlink the RC. Will get 500 error.
D1  number: 9380353333
D2 number: 9898009898
Same RC : WB23E8127
https://drive.google.com/file/d/1OMKYRtcdwvNuh0IgnlI3t_yP0XYObsaX/view?usp=sharing

**Comment by Rohit4997** [comment]
@123ajay1994  I think the condition has changed here
@MercyQueen  @Vignesh-772  Can you check this?

**Comment by aryanguptaSG** [comment]
backend issue .

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1pC99xmUlv61ZZokQQqkXBmOV0RGcmy3I/view?usp=sharing

This issue has been fixed, Checked with 2 New Drivers along with 1 New RC.So marking it as "Done"
