### ISSUE TITLE
When driver is anywhere other than our app, he is not receiving overlay message sent by customer chat message(Parent_id-2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2154]
#2096 
[When driver is anywhere other than our app, he is not receiving overlay message sent by customer chat message. ](https://drive.google.com/file/d/10MIRYmrh3AFl2q8YN7Jm5pKUG4f4wxuJ/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application
2. Accept a ride 
3. Minimise the driver app
4. Send message from user side and observe the driver screen

**Actual Result**
Driver is not getting Message Overlay

**Expected Result**
Driver should get Message Overlay

**Comment by PraveenGongada** [comment]
Expected

**Comment by AlluGowthami28** [comment]
Working fine.
