### ISSUE TITLE
Languages know selected values are cleared after change the user preferred language(Parent_Id-#2096)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2155]
#2096 
[Languages know selected values are cleared after change the user preferred language](https://drive.google.com/file/d/139Bfb9LZQIrnn-ZNu9Y77_FmaXurwyDM/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Click My profile
3. Click language know
4. select some languages
5. Save it
6. Click on Settings
7. Change the language preference
8. Save it
9. observe the issue on Language know

Expected Result:-
Language know count should displayed

Actual Result:-
Language know count is not displayed

Reproduce rate - 5/5

Device - iQOO G5(13)
![Screenshot_20230802_125042](https://github.com/nammayatri/nammayatri/assets/134508712/67ed932d-4217-4e2b-844f-6dfd7e74f999)
![Screenshot_20230802_125014](https://github.com/nammayatri/nammayatri/assets/134508712/066adbab-9c79-4946-9587-7569eed768b2)

**Comment by Rohit4997** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
@Rohit4997 If we change driver language, after kill and re-launch the app known languages getting disappeared.
https://drive.google.com/file/d/1WqQ1-pT5BZLwt3ZSsNC7Ftkj2F8f6d4n/view?usp=sharing

**Comment by AlluGowthami28** [comment]
Working as expected.

**Comment by krupal-14** [comment]
This issue is working fine @Rajaprabhu-Natrajan
