### ISSUE TITLE
In App chat user side suggestion not disappear after selected it(Parent_id-#2096)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2156]
#2096 
[In App chat user side suggestion display default after selected it](https://drive.google.com/file/d/1S6gwbExcVJ-4U8aRKHhPXowtE4LZNO9V/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Book the ride
3. In app chat
4. Click on suggestion
5. Observe the issue

Expected Result -
Suggestion messages are should disappear once it selected. Once got reply from the driver then only it's should shown

Actual Result -
Suggestion messages are still displayed 

Device -Oppo F7
reproduce rate - 5/5

**Comment by AlluGowthami28** [comment]
Working as exepectd.
