### ISSUE TITLE
Profile screen - "Rated by user" text is default displayed in English after user choose the different language. And For new user Empty data is displayed "on Namma Yatri "(Parent_Id-#2096))

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2157]
#2096 
[1.Profile screen - Rated by user text is default displayed in English after user choose the different language. 
2.And For new user Empty data is displayed "on Namma Yatri "](https://drive.google.com/file/d/19GpinDg-DRRX8Wv_P65k3x7Xsd97QA-M/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Login with driver
3. Click on profile
4. Change the language in Bengali / Hindi
5.  verify the "Rated by user" text 
6. Observe the issue

Expected Result-
"Rated by user" text should displayed based on what language the user was selected the preferred language

2. For new user Empty data is displayed "on Namma Yatri
Step to reproduce:-
1. Launch the app
2. Login with new driver
3. Click on profile
4.  Namma Yatri text is displayed with empty data
5.  Observe the issue

Expected Result:_
Namma Yatri text and data should display as per figma.
<img width="566" alt="Screenshot 2023-08-02 at 1 44 00 PM" src="https://github.com/nammayatri/nammayatri/assets/134508712/fda433cb-2373-42f5-99d5-6657616a14f3">

![Screenshot_20230802_134601](https://github.com/nammayatri/nammayatri/assets/134508712/661c9377-e7de-4abf-a5b1-5d550c489650)

**Comment by Rohit4997** [comment]
Fixed

**Comment by Rajaprabhu-Natrajan** [comment]
@Rohit4997 Still the issue is exist. And Also below issue are newly added
1. Driver Details screen - "Namma" Bonus text is displayed. Need to remove "Namma" text
2. Vehicle Details screen - After change the language from English to Bengali or Hindi. Still it's displayed on English

Refer scr
1.     ![Screenshot_2023-08-07-19-05-03-05_243052e3b0489b74115aa8c08ea8cae1](https://github.com/nammayatri/nammayatri/assets/134508712/3988a8db-25ca-4f77-997b-878234e0cc00)
eenshot:-

2.  https://drive.google.com/file/d/1kccKWBTRQ2z3_g_AePKAvN0Q1t7xU7PP/view?usp=sharing

**Comment by krupal-14** [comment]
Restesed working fine. @Rajaprabhu-Natrajan
