### ISSUE TITLE
In special zone green pickup pointer size is increasing when user kill and re-launch the app(Parent-id-2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2158]
#2096 
[In special zone green pickup pointer size is increasing when user kill and re-launch the app](https://drive.google.com/file/d/1bYKs8ImfM_Kvv2tYoh_7FXAw-UJ0aq94/view?usp=sharing)

**Steps to reproduce** 
1. Launch the app
2. Book ride in special zone
3. Kill and re-launch the application

**Actual Result**
In special zone green pickup pointer size is increasing when user kill and re-launch the app.

**Expected Result**
In special zone green pickup pointer size should not increasing when user kill and re-launch the app.

**Comment by ashishsingh101** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Still issue is there.

**Comment by aryanguptaSG** [comment]
fixed

**Comment by johnruban-4050** [comment]
Retested and working fine as expected
