### ISSUE TITLE
Blocker for payment - Payment is failing at driver side(Parent-id_2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2161]
#2096 
[Payment is failing at driver side](https://drive.google.com/file/d/19GVWPkBrxPA4ihekxXDFc3yASNBrdx96/view?usp=sharing)

**Steps to reproduce** 
1. Launch the payment pending driver app
2. Select any one payment option and pay

**Actual Result** 
Payment is failing at driver side.

**Expected Result**
Payment should successful.

**Comment by AlluGowthami28** [comment]
@Rohit4997 @Vignesh-772 
**Payment is failing at driver side.** 
Once payment is done through hub app, driver need to kill and re-launch the app and again need to tap on pay now, then driver is getting previously transaction success.
https://drive.google.com/file/d/1S2usVFn3ONMbcxNI6l0IiuvWcZsB637m/view?usp=sharing

**Comment by AlluGowthami28** [comment]
Payment not getting success for first time, we need to do 2 or 3 times then only it is getting success.

**Comment by ashishsingh101** [comment]
FIxed

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
