### ISSUE TITLE
User is getting "Thank you for writing us" screen while tapping on "view details" in my rides screen(Parent_id-2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2162]
#2096 
[User is getting "Thank you for writing us" screen while tapping on "view details" in my rides screen](https://drive.google.com/file/d/1l6L9Y-Fvtg18uk9uy8tGpkG2nm3v5pFj/view?usp=sharing)

**Steps to Reproduce**
1. Tap on My rides
2. Tap on view details of cancelled ride 
3. Submit some feed back
4. Tap on android back press
5. Tap on view details of completed ride.

**Actual result**
User is getting "Thank you for writing us" screen while tapping on "view details" in my rides screen.

**Expected result**
User should not get "Thank you for writing us" screen while tapping on "view details" in my rides screen.

**Comment by Vignesh-772** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Working as expected.
