### ISSUE TITLE
Rate Card -> Hatchback -> Min Fare Upto 5km Cost is displaying wrong (Parent_ID_#2164)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2172]
#2164 
Rate Card -> Hatchback -> Min Far Upto 5km Cost is displaying wrong 

**Steps -**
1. Access the application
2. Search for Ride
3. In Ride Estimates - Tap on i icon and Observe

**Expected -** 
As per Figma Cost Should display ₹150 

**Actual -** 
Cost is displaying as ₹140

**Figma -**
https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=66394-21707&mode=design&t=xVJAkaqH6nt1f5Bl-0

![markup_1000000636](https://github.com/nammayatri/nammayatri/assets/137036742/499ae3e9-b9c7-4272-b61e-3dd9d636836b)

**Comment by Anuragini-2506** [comment]
expected

**Comment by johnruban-4050** [comment]
@tejkranthi Please confirm the above mentioned point

**Comment by tejkranthi** [comment]
This is the correct pricing as per the DB. However, driver pickup charges must be 0.

CC: @Anuragini-2506

**Comment by johnruban-4050** [comment]
As per the comments im closing this
