### ISSUE TITLE
SUV -> Rate Card is different Compared with figma (Parent_ID_#2164)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2174]
#2164 
For SUV - Rate Card is different Compared with figma

**Steps -** 
Access the application
Search for Ride
In Ride Estimates - Tap on i icon and Observe

Expected -
Rate Card should display as per figma

Actual - 
Rate Card Costs are not displaying as per figma

![Screenshot_20230802-192727](https://github.com/nammayatri/nammayatri/assets/137036742/e26b3f8b-1606-4fc6-97b8-415a0a09e4bd)

**Comment by Anuragini-2506** [comment]
expected

**Comment by johnruban-4050** [comment]
@tejkranthi Please confirm the above mentioned point

**Comment by tejkranthi** [comment]
@johnruban-4050 This is the correct pricing as per the DB. However, Driver pickup charges must be 0.

CC: @Anuragini-2506

**Comment by Anuragini-2506** [comment]
The pickup charges are not coming from the backend ( in the fareBreakup ) - backend issue
