### ISSUE TITLE
Bottom nav Bar are not displaying as per figma (Parent_ID_#2164)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2190]
**#2164** 
Bottom nav Bar are not displaying as per figma

**Steps -** 
1. Access the Application
2. Observe the Bottom nav Bar

**Expected -** 
It should display as per figma

**Actual -**
It is not

**Figma -**
https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=66394-19342&mode=design&t=24wDfQQ9y93eADPW-0

![markup_1000000640](https://github.com/nammayatri/nammayatri/assets/137036742/f16c42ac-8906-4be8-ba24-dc372b1b40b2)

**Comment by Anuragini-2506** [comment]
expected. ( contest is not yet launched in yatri )

**Comment by johnruban-4050** [comment]
As this issue is expected so im closing this
