### ISSUE TITLE
Yatri Driver splash screen is not accroding to figma(Parent_Id-2164)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2195]
#2164 
**Descritpion**
[Yatri Driver splash screen is not accroding to figma](https://drive.google.com/file/d/1m3gNqwXv_hL1cLXYqyW0ja6Rd0CBmCER/view?usp=sharing)
[Figma](https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=66394-19342&mode=design&t=YmUyb7IWKSp6LUHh-0)

**Steps To Reproduce**
1.Launch the application.
2.Observe the splash.

**Expected Result**
Splash screen should be according to figma.

**Actual Result**
Splash screen is not according to figma.

**Comment by Anuragini-2506** [comment]
Please refer the splash screen with the new logo. The splash screen is changed. ( refer splash screen with black background )

**Comment by johnruban-4050** [comment]
Retested and working fine as expected 

https://github.com/nammayatri/nammayatri/assets/137036742/04ba688b-da1e-4bdf-a353-5b7f4f0163bb
