### ISSUE TITLE
User - Malayalam - Rate Card of Auto Rickshaw is messed (Parent_Id-#2164)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2197]
#2164
[Malayalam - Rate Card of Auto Rickshaw is messed](https://drive.google.com/file/d/1TvNhfPVpI57zwHkQEEVbxLcciuA7PaVJ/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Choose malayalam language
3. Search the ride
4. Get Estimation
5. Click on Info icon of Auto Rickshaw

Expected Result:-
Rate card of auto rickshaw should display correctly

Actual Result:-
Rate card of auto rickshaw is not displayed properly

Reproduce rate - 5/5

Device - Oppo F7

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine now.
