### ISSUE TITLE
Getting "Includes pickup charges 10rs" is showing in driver ride request popup, when user search for a car ride (Parent ID_2164)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2198]
#2164 
[Getting "Includes pickup charges 10rs" is showing in driver ride request popup, when user search for a car ride](https://drive.google.com/file/d/1lxNw63dXAAHiE3BlKyNJH_jN_0Af710t/view?usp=sharing)

Steps: 
1. Open both apk
2. Request for a car ride
3. Verify driver request popup

Expected: For car should not show include pickup charges 10rs
Actual :10 rs is sowing in ride request popup

**Comment by Rajaprabhu-Natrajan** [comment]
Restested done. It's working fine

![Image](https://github.com/nammayatri/nammayatri/assets/134508712/4ded7c0d-ff6b-41cc-86e7-88f9f9a662b9)
