### ISSUE TITLE
Malayalam - Home screen - Location map update text is not alignment properly(Parent_id-#2164) (DRIVER)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2199]
#2164 
[Malayalam - Home screen - Location map update text is not alignment properly](https://drive.google.com/file/d/1FZN1EVQD-l-Nh-aOCxoQPLU5qGi2E3UI/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Choose Malayalam lang
3. Verify the text and observe the issue

Expected Result:-
Text should aligned properly.

Actula Result:-
Text are not aligned properly

**Comment by johnruban-4050** [comment]
Retested and working fine as expected
![Screenshot_20230807-154453](https://github.com/nammayatri/nammayatri/assets/137036742/5e129bcd-d95d-4e9f-a405-149f4e28a476)
