### ISSUE TITLE
In start ride screen "Fare and distance" not aligned properly and Waiting time coming in driver app(parent-id-2164)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2203]
#2164
[1. In start ride screen/End ride screen "Fare and distance" not aligned properly
2. Waiting time is coming in driver app](1. https://drive.google.com/file/d/1QdaiEeyIV6FJ3lmqjB6OA0wxO0c7a3iu/view?usp=sharing
 2. https://drive.google.com/file/d/1UuHur7jyic2ZcvWLUH7Z_Tbk0xVZKAml/view?usp=sharing)

**Steps to Reproduce**
1. Accept a rid request and observe the screen

**Actual Result**
In start ride screen "Fare and distance" not aligned properly.

**Expected Result**
In start ride screen "Fare and distance" should align properly.

**Comment by johnruban-4050** [comment]
Retested and working fine as expected 
![Screenshot_20230807-133439](https://github.com/nammayatri/nammayatri/assets/137036742/2707700b-34bb-49b7-b23a-17d1c0dd2c27)
![Screenshot_20230807-134658](https://github.com/nammayatri/nammayatri/assets/137036742/823d733c-27e2-4c42-818e-d8c1a4220505)
