### ISSUE TITLE
Auto Rickshaw Logo is not displayed on Ride Details screen(Parent_Id-#2164)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2204]
#2164 
[Auto Rickshaw Logo is not displayed on Ride Details screen](https://drive.google.com/file/d/1QHZTfU1a0snoI5g-RTsMd_AFRTvAqEjA/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Ride details Screen for auto rickshaw driver
3. Verify the logo

Expected Result:-
1. Auto Rickshaw logo should be displayed

Actual Result:-
Yellow Car logo is displayed

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Rajaprabhu-Natrajan** [comment]
Issue still exist.

**Comment by Vinaykm999** [comment]
Working fine
