### ISSUE TITLE
Driver is getting old Yatri Logo in about screen & All the toast messages(Parent ID_2164)

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#2205]
#2164
Description:
Driver is getting old Yatri Logo in about screen & All the toast messages

Steps to reproduce:
1. Launch the driver application
2. Login with valid credentials
3. Tap on profile screen & then About
4. Observe the logo

Expected result:
New Yatri logo should come & also should get new logo in all the toast messages

Actual result:
Old Yatri logo is displaying & also getting old logo on every toast message
![Screenshot_2023-08-03-17-00-26-200_net openkochi yatripartner debug](https://github.com/nammayatri/nammayatri/assets/129082995/a1524736-43e9-4c8e-af63-47eaf84f6691)
![Screenshot_2023-08-03-17-05-25-580_net openkochi yatripartner debug](https://github.com/nammayatri/nammayatri/assets/129082995/0111d74f-3b7e-41e7-96cb-e804fb601859)
![Screenshot_2023-08-03-17-18-24-851-edit_net openkochi yatripartner debug](https://github.com/nammayatri/nammayatri/assets/129082995/12d8d30b-db34-48c8-b7ed-2214878c21b5)

**Comment by johnruban-4050** [comment]
Retested and working fine as expected
![Screenshot_20230807-142321](https://github.com/nammayatri/nammayatri/assets/137036742/e3d33fa1-ce28-404d-9c24-f7fb71304d31)
![Screenshot_20230807-142401](https://github.com/nammayatri/nammayatri/assets/137036742/00712bae-1214-4b47-abb4-beba7690898b)
![Screenshot_20230807-142528](https://github.com/nammayatri/nammayatri/assets/137036742/0c722c2e-657e-4970-9f19-de63d0af6a4f)
