### ISSUE TITLE
In App chat user side suggestion not disappear after selected it(driver side)(Parent-id-2164)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2206]
#2164 
[In App chat user side suggestion not disappear after selected it](https://drive.google.com/file/d/1WNoWtswSTkkPv2qa0jTLDtr88tcEwaFU/view?usp=sharing)

**Step to reproduce**

Launch the app
Book the ride
In app chat
Click on suggestion
Observe the issue

**Expected Result **
Suggestion messages are should disappear once it selected. Once got reply from the driver then only it's should shown

**Actual Result **
Suggestion messages are still displayed

**Comment by johnruban-4050** [comment]
Issue still exist. 

https://github.com/nammayatri/nammayatri/assets/137036742/17a650d7-6bfa-481d-a4d2-a7154539bd0d

**Comment by johnruban-4050** [comment]
Minimize the app for 30 seconds and observe the issue

**Comment by johnruban-4050** [comment]
After the app is minimized the chat screen is freezed

https://github.com/nammayatri/nammayatri/assets/137036742/cd870437-b053-4ff8-8625-fc47b709c1c7

**Comment by johnruban-4050** [comment]
Working fine as expected in CUG
