### ISSUE TITLE
Ride Details screen showing empty when it loading(Parent_ID-#2164)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2207]
#2164 
[Ride Details screen showing empty when it loading](https://drive.google.com/file/d/1QHZTfU1a0snoI5g-RTsMd_AFRTvAqEjA/view?usp=drive_link)

Step to reproduce:-
1. Launch the app
2. Click on home screen 
3. Click on Rides option in bottom menu bar
4. Observe the issue

Expected Result:-
Ride Details should be display properly

Actual Result:-
Ride Details are not displayed.

Reproduce rate - 4/5

**Comment by Anuragini-2506** [comment]
Backend

**Comment by johnruban-4050** [comment]
retested and working fine as expected
