### ISSUE TITLE
Yatri Driver Application is navigating to namma yatri by clicking on link in about page(Parent ID_2164)

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#2208]
#2164 
[Issue link](https://drive.google.com/file/d/1ANPXKT0sng098-1ifarokUVMYyIr4Ifz/view?usp=sharing)
Steps to reproduce:
1. Launch the Yatri Driver application 
2. login with valid credentials
3. Go to about screen
4. Tap on the links on about screen and observe

Expected result:
User should be navigating to Yatri Application

Actual result:
User is navigating to namma yatri application

**Comment by johnruban-4050** [comment]
Retested and working fine as expected
