### ISSUE TITLE
Getting we made you offline and Searching for GPS, even after turning on both(Parent ID_2164)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2209]
#2164
[Getting we made you offline and Searching for GPS, even after turning on both](https://drive.google.com/file/d/1DmPlqjwUec8yLZ6GbnFx0WQ3WCpkTazU/view?usp=sharing)

Steps:
1. Install yatri partner apk
2. Enter driver number
3. Verify notification

Expected: We should get those notification only Network and GPS turned off

**Comment by Anuragini-2506** [comment]
not able to reproduce

**Comment by Rajaprabhu-Natrajan** [comment]
Still I can able to reproduce it @Anuragini-2506 . - So I reopen this bug 



cc: @Vinaykm999

**Comment by johnruban-4050** [comment]
Retested and working fine as expected in Pixel so im closing this
