### ISSUE TITLE
Malayalam - Driver Feedback Pils are not aligned properly(Parent_ID-#2164)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2210]
#2164 
[Malayalam - Driver Feedback Pils are not aligned properly](https://drive.google.com/file/d/1eAlBpXnqYbCapWPLzS1sIWyHNNCFJyOf/view?usp=sharing)

Step on reproduce:-
1. Launch the app
2. Book the ride
3. End the ride
4. Feedback screen
5. Click on Feedback pils
6. Observe the issue

Expected result:-
Feedback screen should display properly

Actual result:-
Feedback screen is not display properly

Reproduce rate - 5/5

**Comment by tejkranthi** [comment]
Not critical

**Comment by Vinaykm999** [comment]
working fine
