### ISSUE TITLE
Showing "Namma Yatri" text in Yatri driver application (Parent ID_2164)

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#2214]
#2164 
Steps to reproduce:
1. Go to Help & Support in Yatri driver application
2. Tap on Lost and found
3. click on " I don't know which ride" and observe the screen

Expected result:

User should be able to see Yatri text in issue raising screen

Actual result:

User is getting Namma Yatri text

![Screenshot_2023-08-03-17-15-47-843-edit_net openkochi yatripartner debug](https://github.com/nammayatri/nammayatri/assets/129082995/2c8544fa-f851-496d-a9c4-63a4ea88a4b8)

**Comment by johnruban-4050** [comment]
Retested and working as expected
![Screenshot_20230808-000851](https://github.com/nammayatri/nammayatri/assets/137036742/a0dbb1c8-9dff-4cd2-b91e-45c7b9dc8ba1)
