### ISSUE TITLE
Driver is getting "Yatri partner" text instead of  "Yatri Driver" in all the locations (Parent ID_2164)

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#2217]
#2164 

Steps to reproduce:
1. Launch the Yatri Driver application
2. Observe the language select screen, permission screen & few other screens also

Expected result:

User should be able to see "Yatri Driver" text instead of Yatri Partner text as we have updated the name in splash screen

Actual result:
Driver is getting "Yatri partner" text instead of  "Yatri Driver" in all the locations

![Screenshot_2023-08-03-17-13-29-996-edit_net openkochi yatripartner debug](https://github.com/nammayatri/nammayatri/assets/129082995/df539797-16e5-45f9-af3a-dfd4f1e1aea3)

![Screenshot_2023-08-03-17-34-56-563-edit_net openkochi yatripartner debug](https://github.com/nammayatri/nammayatri/assets/129082995/5d39a067-b449-4fbd-8f4d-7e470473fd85)
![Screenshot_2023-08-03-17-17-35-149-edit_com google android permissioncontroller](https://github.com/nammayatri/nammayatri/assets/129082995/2f46b902-8781-40a3-b826-364fed7474b0)

**Comment by johnruban-4050** [comment]
Retested and working fine as expected in CUG
