### ISSUE TITLE
Driver - Booking option is not as per the figma (Parent ID_2164)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2221]
#2164 
[Driver - Booking option is not as per the figma](https://drive.google.com/file/d/1pXyV67xuKnSukRakjI5X5Zun5TKod79h/view?usp=sharing)

**Steps**:
1. Login with driver number
2. Click on hamburger menu
3. Click on booking option
4. Verify

**Actual** : Check box is left aligned

<img width="997" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/81591483-cdd6-420e-9b90-4b4df77075a1">

**Comment by johnruban-4050** [comment]
Retested and working as expected 
![Screenshot_20230808-014422](https://github.com/nammayatri/nammayatri/assets/137036742/d1f64959-ae52-4ff1-820c-43169aa2a025)
