### ISSUE TITLE
Wait time is disappearing when user lock his/her device (Parent_id_1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2238]
#1980 
[Wait time is disappearing when user lock his/her device and also sometimes time is varying in driver and user device after lock ](https://drive.google.com/file/d/1FBXZj_NDxUzYrFaaZqLKScPq5AEeTQPT/view?usp=sharing)

Steps:
1. Request for a ride
2. Accept aa ride
3. Click on i have arrived
4. Lock user device and wait for 2min
5. Unlock user device
6. Check waiting time
7. Kill and relaunch user apk
8. verify waiting time

Expected: waiting time should not drop/disappear

**Comment by ashishsingh101** [comment]
will fix this in next hotpush

**Comment by ashishsingh101** [comment]
Fixed
