### ISSUE TITLE
user carousel screen is not according to figma(Parent_Id-1867)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2241]
#1867 
**Description** 
[user splash screen is not according to figma](https://drive.google.com/file/d/1pT-Kvtq_Dhbim7s0G3_Yz2NLjOpePYpB/view?usp=sharing)

**Steps To Reproduce**
1.Launch the ipa.
2.Observe the user carousel screen.

**Expected result**
It should be according to figma.

**Actual result**
It is not according to figma.

**Comment by MercyQueen** [comment]
this is the new design. For Yatri both auto and cab would be visible. Hence, this is expected.

**Comment by rohanrp179** [comment]
closing
