### ISSUE TITLE
Image is not displaying when user wants to cancel the ride(User choosed auto varient)(Parent_Id-1867)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2242]
#1867 
Description 
[Image is not displaying when user wants to cancel the ride(User choosed auto varient](https://drive.google.com/file/d/1pz7meunbVbl0XcRn8KMCg21zB9YGOujV/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials .
3.book a ride.
4.Click on cancel ride.
5.Observe the screen

Expected result
Image should display.

Actual Result
Image is not displaying .

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
dulicate
