### ISSUE TITLE
Double click on current location is zooming in (Parent_Id - 1867)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2243]
https://github.com/nammayatri/nammayatri/assets/138564517/f690d4f4-4184-4812-a97f-8443169b956d

#1867 

If we double click on Current location while saving favourites , the map zoom in 

**Steps**
1. Log in to app
2. Go to Add favourites 
3. Select Choose on map to select location
4. Double click on Current location

**Expected result**
The map should not zoom in if we double click on current location

**Actual result**
It is zooming in

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
It is working as expected. Closing the issue
