### ISSUE TITLE
The in app chat messages are sent thrice while sharing or receiving the messages (Parent_Id - 1867)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2244]
#1867 

The in app chat messages are sent thrice while sharing or receiving the messages

**Steps**
1. Log in to app
2. Book a ride
3. Send or receive in app chat messages

**Expected result**
It should be sent only once

**Actual result**
It is sent 3 times

https://github.com/nammayatri/nammayatri/assets/138564517/03d57911-1813-419f-bb27-714cf8a56683

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
Working as expected. Closing the issue
