### ISSUE TITLE
User is not getting Any FCM(Parent_Id-1867)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2247]
#1867 
**Description** 
[User is not getting message FCM](https://drive.google.com/file/d/1c5qtG9XJQNygPBYQHodQZ8H_1fRKGP3L/view?usp=sharing)

**Steps To Reproduce**
1.Launch the application .
2.Login with valid credentials .
3.Book a ride.
4.Kill the user apk.
5.Send Message  from driver.
6.Observe the user apk.

**Expected Result**
User should get Message FCM.

**Actual Result**
User is not getting Message FCM.

Note:After some ride user is not getting any FCM's related to ride assigned,ride started,ride ended.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Fixed,Working fine.
