### ISSUE TITLE
If auto ride is assigned, if user click on Cancel ride, the auto image is missing (Parent_Id - 1867)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2248]
#1867 

If auto ride is assigned, if user click on Cancel ride, the auto image is missing

**Steps**
1. Log in to app
2. Book a auto ride
3. Click on Cancel ride

**Expected result**
The auto icon should display

**Actual result**
It is not displaying any image 

https://github.com/nammayatri/nammayatri/assets/138564517/015e1704-27c1-45f1-8ec9-1b9e09bbea39

**Comment by MercyQueen** [comment]
fixed.

**Comment by rohanrp179** [comment]
@MercyQueen If we cancel the ride for auto rickshaw, the auto shown in image is same like NY. But auto image used for yatri is black color auto rickshaw. We need black color auto rickshaw image while we click on cancel ride

**Comment by MercyQueen** [comment]
@tejkranthi is the image fine for now or should we get it replaced?

**Comment by tejkranthi** [comment]
Can you share a screenshot?

**Comment by tejkranthi** [comment]
@rohanrp179 The green and yellow illustration is fine. We can go ahead.

**Comment by rohanrp179** [comment]
@tejkranthi So will we be changing this in future or we are ok with this only?

**Comment by tejkranthi** [comment]
We will change it in the coming updates.

**Comment by rohanrp179** [comment]
Sure @tejkranthi . Closing it
