### ISSUE TITLE
When ride is assigned and user kill and reopen the app again, then splash screen is not shown loading properly (Parent_ID - 1867)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2249]
#1867 

When ride is assigned and user kill and reopen the app again, then splash screen is not shown loading properly

**Steps**
1. Log in to app
2. Book a ride
3. Before starting ride, kill and reopen the app

**Expected result**
Whenever we reopen the app, the splash screen should work as always

**Actual result**
The splash screen is not loading as usual

https://github.com/nammayatri/nammayatri/assets/138564517/fc9e3910-7611-419f-b576-830b6853d78a

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
Working as expected. Closing the issue
