### ISSUE TITLE
The auto image should be visible completely above the resignation number plate (Parernt_Id 1867)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2250]
#1867 

The auto image should be visible completely above the resignation number plate

**Steps**
1. Log in to app
2. Book a auto ride
3. Start a ride

**Expected result**
The auto image should be visible completely

**Actual result**
Some part of the auto image is covered with registration number plate
![IMG_0352](https://github.com/nammayatri/nammayatri/assets/138564517/b4bdba80-d872-45b3-881d-5cbfdf6a470d)

**Comment by MercyQueen** [comment]
expected.

**Comment by rohanrp179** [comment]
closing as this is expected
