### ISSUE TITLE
User is not getting carousel screen(Parent_Id-1867)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2262]
#1867 
**Description** 
[User is not getting carousel screen](https://drive.google.com/file/d/1L60Hf4-GU1vyoZoP9kx_SwkTs1zqewUo/view?usp=sharing)

**Steps To Reproduce**
1.Launch the App.
2.Observe the screen.

**Expected Result**
User should get the carousel screens.

**Actual Result**
User is getting blank screen.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retesed,working fine
