### ISSUE TITLE
When user is logging out, previous login phone number is displaying in enter mobile number screen.(Parent_Id-1867)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2266]
#1867 
Description 
[When user is logging out, previous login phone number is displaying in enter mobile number screen.](url)

Steps To Reproduce
1.Launch the app.
2.Login with valid credentials .
3.Logout from current user.
4.Observe the enter mobile number screen.

Expected result 
Enter Mobile number textbox shoud be blank.

Actual result
Previous login number is therein enter mobile number textbox .

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,working fine
