### ISSUE TITLE
When user is clicking on chat icon OTP screen is displaying(Parent_Id-1867)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2269]
#1867 
**Description** 
[When user is clicking on chat icon OTP screen is displaying](https://drive.google.com/file/d/1ER7u_7jRep2YB2py4SESygmu6ghMcYG6/view?usp=sharing)

**Steps To Reproduce**
1.Launch the app.
2.Login with valid credentials.
3.Book a ride.
4.Minimize the user app for a min.(Do it for multiple times)
5.Open the app.
6.Click on Message icon(As soon as app launched).
7.observe the screen.

**Expected Result**
Chat screen should display.

**Actual result**
OTP screen is displaying.

Note:The possibility of this issue is 3/10.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retesed, working fine
