### ISSUE TITLE
Driver - Malayalam - Cross Button Ui is not aligned (Parent_ID_#2164)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2272]
**#2164** 

**Malayalam - Cross Button Ui is not aligned** 

**Steps -** 
1. Access the application
2. Navigate to Menu -> Help & Support -> Lost and found -> I dont know which ride -> Voice record
3. Observe the screen

**Expected -** 
It should aligned properly

**Actual -**
It is not

![Screenshot_20230807-164434](https://github.com/nammayatri/nammayatri/assets/137036742/8f578fb9-f00a-4d52-a667-210caea2487f)

**Comment by prakharritik** [comment]
![Image](https://github.com/nammayatri/nammayatri/assets/60786008/e4941f34-6e2c-492e-8739-2dee76aed76e)

Fixed.

**Comment by johnruban-4050** [comment]
Retested and working fine as expected
