### ISSUE TITLE
User App - During ride search the Tip pop is not displayed(Parent_id-2283)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2284]
#2283 
[User App - During ride search the Tip pop is not displayed](https://drive.google.com/file/d/1NC1FaPRZ9qALOI3Du4eTD3swVbCrie5f/view?usp=sharing)

Step to reproduce:-
1. launch the app
2.  Search the ride
3. After sometime Tip pop up should shown
4. Observe the issue

Expected Result:-
Tip pop up screen should be displayed 

Actual Result:-
Tip Pop up is not displayed.

Reproduce rate - 5/5

**Comment by aryanguptaSG** [comment]
@Rajaprabhu-Natrajan it is already fixed . it will be merged soon in master .
