### ISSUE TITLE
Driver is not getting any error message while uploading activated RC again(Parent-id-2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2285]
#2096
 [Driver is not getting any error message while uploading activated RC again](https://drive.google.com/file/d/1ihLO93e22HUhSyljs3aN50520BfvlVfA/view?usp=sharing)

**Steps to Reproduce**
1. Update one RC and make it active.
2. Tap on add RC
3. Update same RC and observe the screen.

**Actual Result**
Driver is not getting any error message while uploading activated RC again

**Expected Result**
Driver should get error message while uploading activated RC again.

**Comment by aryanguptaSG** [comment]
Backend is not sending error message . same issue #2371

**Comment by JanhaviSoni** [comment]
RCAlreadyUpdated -> Just "No action required. Vehicle RC is already linked to driver." 400
