### ISSUE TITLE
Two messages are sent & received in user end(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2289]
#1803 
**Description**
[Two messages are sent & received in user end](url)

**Steps To Reproduce**
1.Launch the app.
2.Login with valid credentials.
3.Book a ride.
4.Minimize the user app for 10 min.
5.Open the app.
6.Click on message icon.
7.send or receive messages.

**Expected result**
Only one message should receive or sent.

**Actual result**
Two messages are sent and receiving.

**Comment by MercyQueen** [comment]
@Sumedh-14 @krupal-14 is this issue still existing?

**Comment by krupal-14** [comment]
@MercyQueen  This issue was in backlog state only from last time

**Comment by MercyQueen** [comment]
Fixed.
