### ISSUE TITLE
Call Support Centre is not navigating to dialer screen (Parent_ID_#2283)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2304]
**#2283** 
**Call Support Centre is not navigating to dialer screen**

**Steps -** 
1. Access the application
2. Navigate to Add Driving License -> Help -> Call support centre
3. Observe the screen

**Expected -** 
It should navigate to dialer screen

**Actual -**
It is not

https://github.com/nammayatri/nammayatri/assets/137036742/1fea862f-c1d7-4890-870e-3c09dcc8b50b

**Comment by Rajaprabhu-Natrajan** [comment]
Reopened --> It's not fixed
After click Call support then it's navigate wt's up app 

Link ---> https://drive.google.com/file/d/1v1_RGfyITF8HRVPXgAHJCXw8Mk5Vfm8r/view?usp=sharing

**Comment by Vignesh-772** [comment]
Expected

**Comment by johnruban-4050** [comment]
Since this is expected marking it as closed
