### ISSUE TITLE
<JS DRIVER>When driver opens the app driver directly navigating to the enter mobile number screen(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2363]
#2096 
**Description**
[When driver opens the app driver directly navigating to the enter mobile number screen](https://drive.google.com/file/d/1aoVN6s-m4jlIyy1CYqkvrbO9mvhM6neY/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Observe the screen.

**Expected result**
Driver should navigate to the Welcome screen.

**Actual Result**
Driver directly navigating to the  enter mobile screen.

**Comment by krupal-14** [comment]
@ashishsingh101 why this issue is in invalid state . Can u plz explain.

**Comment by ashishsingh101** [comment]
@krupal-14 we are not able to reproduce

**Comment by krupal-14** [comment]
@ashishsingh101 It is reproducing , So moving back to backlog
