### ISSUE TITLE
The radio buttons on welcome screen and language screen are not to right most of page. (Parent_Id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2364]
#2096 

The radio buttons on welcome screen and language screen are not to right most of page. There is little space which is not given in figma

![Screenshot_20230810-132629](https://github.com/nammayatri/nammayatri/assets/138564517/28fb46b2-b579-49be-b4a2-a6bfdcd29b7f)

![Screenshot_20230810-130642](https://github.com/nammayatri/nammayatri/assets/138564517/dffc24de-7a7f-408d-8c4f-0a0188647e1b)

**Comment by S-PRAVINKUMAR** [comment]
Done

**Comment by krupal-14** [comment]
Retesed,Working fine.
