### ISSUE TITLE
The languages like Kannada, Tamil and Telugu are irrelevant for Yatri sathi app (Parent_Id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2365]
#2096 

The languages like Kannada, Tamil and Telugu are irrelevant for Yatri sathi app. Need to remove

Steps-
1. Log in to app
2. Go to Profile
3. From About me, click on Add

![Screenshot_20230810-132620](https://github.com/nammayatri/nammayatri/assets/138564517/762eb4ad-fed0-4615-8bf3-28983257a832)

**Comment by witcher-shailesh** [comment]
No need to remove, we can keep it.
