### ISSUE TITLE
Tamil language in language section for Yatri sathi app is irrelevant  (Parent_Id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2366]
#2096 

Tamil language in language section for Yatri sathi app is irrelevant 

Steps
1. Login to app
2. Go to profile section
3. Go to Settings
4. Click on Languages 

![Screenshot_20230810-135902](https://github.com/nammayatri/nammayatri/assets/138564517/6bf8ece0-9319-4199-a527-264d36d0e639)

**Comment by aryanguptaSG** [comment]
check design
