### ISSUE TITLE
Driver is navigating to driver profile when driver clicking back from Vechicle details(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2367]
#2096 
**Description**
[Driver is navigating to driver profile when driver clicking back from Vechicle details](https://drive.google.com/file/d/1QbEpYeM2K9y7LvUc043zmXZNO0iSHuCE/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Click on profile.
4.Click on vehicle Details .
5.Click on Add RC .
6.Click on back and observe.

**Expected Result**
Driver should navigate back to vehicle details screen.

**Actual result**
driver is navigating to driver details screen.

**Comment by aryanguptaSG** [comment]
fixed .

**Comment by Sumedh-14** [comment]
Retested on 17/08/2023, The issue is fixed and hence closing this issue
