### ISSUE TITLE
Driver - Back Button is not working when user select on Tamil language while login (Parent_ID_#2096)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2368]
**#2096** 
**Driver - Back Button is not working when user select on Tamil language while login**

**Steps -**
1. Access the application
2. Select Tamil Language and it navigate to Enter Mobile number screen
3. Then Tap on Back button and observe

**Expected -** 
It should navigate to language select screen

**Actual -**
It is not

https://github.com/nammayatri/nammayatri/assets/137036742/5ca3d56c-8696-49af-a1d4-2940a8d73c3c

**Comment by aryanguptaSG** [comment]
fixed .

**Comment by krupal-14** [comment]
Tamil language has been removed so closing this issue.
