### ISSUE TITLE
Same RC when added twice, appropriate message is not displayed (Parent_Id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2371]
#2096 

[When driver is trying to upload the RC which is already linked to his account, then he is not getting any kind of error saying that this RC is already linked to your account ](https://drive.google.com/file/d/11_3sJl89WbITtNDbK05J7U9EqUmgE3FJ/view?usp=sharing)

Steps-
1. Log in to app
2. Go to profile
3. Go to Vehicle details
4. Now try to add the RC which is already linked to this driver account

Expected-
If already linked RC is tried to add by driver, then driver should be shown appropriate error message something like "This is already linked to your accout"

Actual-
It is not giving any error

**Comment by ashishsingh101** [comment]
Backend is not sending error message

**Comment by JanhaviSoni** [comment]
RCAlreadyUpdated -> Just "No action required. Vehicle RC is already linked to driver." 400

**Comment by rohanrp179** [comment]
no further advancement
