### ISSUE TITLE
i button is missing in Missed Opportunities section(parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2372]
#2096 
**Description** 
[i button is missing ](https://drive.google.com/file/d/1-ALj-dsjWJJ7V3Z2uz2c9DqbPs6udRI_/view?usp=sharing)
[Figma](https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=67553-17754&mode=design&t=hQIGDoQzPgBy9FZg-0)

**Steps To Reproduce** 
1.Launch the apk.
2.Login with valid credentials.
3.Click on driver profile.
4.Observe the missed opportunity .

**Expected Result**
i button should display.

**Actual Result.**
i button is not display.

**Comment by AlluGowthami28** [comment]
Issue still existing.

**Comment by Akash2172** [comment]
same issue exists in #2101 so moving it to ready, #2101 is kept in backlog only

**Comment by krupal-14** [comment]
It is a duplicate of #2101 , So moving it to done
