### ISSUE TITLE
When driver tries to add any RC other than West Bengal, he is able to fill all the details and is Next button is Enabled (Parent_Id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2373]
#2096 

[When driver tries to add any RC other than West Bengal, he is able to fill all the details and is Next button is Enabled](https://drive.google.com/file/d/11bPP8dMaqKamY1tvydITNjXXXRFnaCX3/view?usp=sharing)

Steps-
1. Log in to app
2. Go to Vehicles details under settings
3. Click on Add RC
4. Use RC other than West Bengal registration

Expected- 
When all the details are filled, Next button should not be enabled

Actual-
The Next button is enabled

**Comment by ashishsingh101** [comment]
Ready

**Comment by rohanrp179** [comment]
This is not fixed.  Retesting Failed @ashishsingh101 
Reopening. 

https://drive.google.com/file/d/13df2wT9aF-4CFi2DIbLs91lvtyrgewDj/view?usp=sharing

**Comment by aryanguptaSG** [comment]
fixed

**Comment by krupal-14** [comment]
Retesed,Working fine
