### ISSUE TITLE
When RC is inactive in driver profile, the vehicle type is shown as Auto Rickshaw . The same RC if is active, the type shown is different (Parent_Id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2376]
#2096 

[When RC is inactive in driver profile, the vehicle type is shown as Auto Rickshaw . The same RC if is active, the type shown is different ](https://drive.google.com/file/d/11bjyNs8jNkmBp1P6XEs6OE3TWVoPpRl6/view?usp=sharing)

Steps -
1. Log in to app
2. Go to Vehicles details under profile section
3. Check the vehicle type mentioned for Inactive RC
4. Active this RC

Expected-
The variant  Auto Rickshaw should not be shown

Actual-
The variant  Auto Rickshaw is shown and when the same RC is made active then vehicle type is made different. This is not accepted.

**Comment by ashishsingh101** [comment]
Fixed

**Comment by rohanrp179** [comment]
Type section for inactive RC's is removed. Hence no longer type issue for inactive RC's 
Closing the issue
