### ISSUE TITLE
Driver -> Languages Spoken -> Bangla Language is not showing properly (Parent_ID_#2096)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2379]
**#2096** 

**Driver -> Languages Spoken -> Bangla Language is not showing properly** 

**Steps -**
1. Access the application
2. Navigate to My Profile -> Driver Details -> About me -> Languages spoken (Select Bangla)
3. Observe the screen

**Expected -** 
Selected Language should display properly

**Actual -** 
It is not

![markup_1000000795](https://github.com/nammayatri/nammayatri/assets/137036742/58a1d22d-7792-4830-b521-4c9ea4457a1f)

**Comment by krupal-14** [comment]
Retested,working fine
