### ISSUE TITLE
Driver -> Update button should disable when data are not present (Parent_ID_#2096)

### ISSUE THREAD

**Issue by johnruban-4050** [nammayatri/nammayatri#2383]
**#2096** 
**Driver -> Update button should disable when data are not present** 

**Steps -** 
1. Launch the apk.
2. Login with valid credentials.
3. click on driver profile.
4. Add alternate number and then remove the added number
5. Then Again tap on add and then observe the screen

**Expected -** 
Update button should disable

**Actual -** 
Update Button is enabled

https://github.com/nammayatri/nammayatri/assets/137036742/0c277f90-8172-4bae-82e5-94e6ce7e957b

**Comment by witcher-shailesh** [comment]
It's fine for now, will fix in subsequent releases.

**Comment by ashishsingh101** [comment]
Fixed

**Comment by Sumedh-14** [comment]
Retested on 17/08, still the issue exists, 
PFA below, 
https://drive.google.com/file/d/129Ru63xeNdjUoGOMQw-S-FIeNBpH3S4P/view?usp=sharing

**Comment by krupal-14** [comment]
Restested,working fine
