### ISSUE TITLE
<JSP><comma should be there in 3rd place and 5th place of digits in Driver details - Summary screen as per Figma>(Parent_Id-2096)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2384]
#2096 
**comma should be there in 3rd place and 5th place of digits in Driver details - Summary screen as per Figma

**To Reproduce**
- Open the application
- Tap on Profile
-Validate the issue only when driver has completed rides and have values.

**Expected behavior**
![image (4)](https://github.com/nammayatri/nammayatri/assets/128033831/f41d7d39-0aee-45e5-aa16-f5f0472101e2)

**Actual Screenshots**
![Screenshot_20230810_174230](https://github.com/nammayatri/nammayatri/assets/128033831/79f9193f-e945-4193-980c-c4299167d051)

**App (please complete the following information):**

**Additional context**

**Comment by witcher-shailesh** [comment]
It's fine for now, will fix in subsequent releases.

**Comment by aryanguptaSG** [comment]
fixed

**Comment by Sumedh-14** [comment]
Retested on 17/08, still the issue exists, 

PFA below,  
https://drive.google.com/file/d/19d8mtXhMAH2z2MH9W8ztDnSycT5muWJH/view?usp=sharing

**Comment by aryanguptaSG** [comment]
fixed

**Comment by krupal-14** [comment]
Rested,working fine.
