### ISSUE TITLE
<JSP><In case of "RC active on another driver", having issue as Toast is not coming when call driver -> redirected to home screen> (Parent_Id-2096)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2391]
#2096 

**Describe the bug**
In case of "RC active on another driver", having issue as Toast is not coming when call driver -> redirected to home screen
**To Reproduce**
- Tap on Profile Icon. 
- Tap on Vehicle details
- Tap on Edit RC.
- Try to Activate RC
- Validate the pop up (if RC is active in other Driver)
- Tap on call driver
- Validate Place call and tap on it. 
- Observe the issue

**Expected behavior**
<img width="261" alt="Screenshot 2023-08-10 at 6 23 44 PM" src="https://github.com/nammayatri/nammayatri/assets/128033831/709fe86a-7b7a-417c-8341-cc03e26f474a">
**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://drive.google.com/file/d/1fVipHVZwfYVR3tWjlNmHLxCSrHxoUn3F/view?usp=sharing)

**App (please complete the following information):**

**Additional context**

**Comment by witcher-shailesh** [comment]
Calling option we will be minimizing usage. It's fine for now, will fix in subsequent releases.

**Comment by ashishsingh101** [comment]
Fixed

**Comment by 123ajay1994** [comment]
@ashishsingh101 I have checked the Fix, Currently the Toast is "Please wait while we connect you with the Driver" and in Figma, it is "Your call request has been Placed". 
Can you confirm if we consider the Current toast.
https://drive.google.com/file/d/1pzsGD6Qlpi_VQXuIdvi1mAbYKGW7xBF6/view?usp=sharing

**Comment by ashishsingh101** [comment]
@123ajay1994 will update the toast

**Comment by 123ajay1994** [comment]
@ashishsingh101 sure, thanks for update. As discussed, moving it to backlog.

**Comment by 123ajay1994** [comment]
"Your call request has been Placed" Toast validated, marking it as "Done".
