### ISSUE TITLE
<JS USER> Content is missing in language section(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2396]
#2096 
**Description**
[Content is missing in language section](https://drive.google.com/file/d/1DWctqvhwWCOSIo8MlhSSU9PHqueBkM7v/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Click on Hamburger.
4.Click on language.
5.Observe the user screen.

**Expected Result**
Language content should not miss.

**Actual Result**
Language Content is missed.

**Comment by aryanguptaSG** [comment]
fixed

**Comment by krupal-14** [comment]
Retesed,Working fine.
