### ISSUE TITLE
<JS_USER><Showing 'Invalid Number' error massage by only selecting Country code of Bangladesh>(Parent_Id-2096)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2400]
#2096 

**Describe the bug**
'Invalid Number' error massage displayed by only selecting Country code of Bangladesh in starting screen

**To Reproduce**
- Launch the user application. 
- Tap on Country code and select Bangladesh. 
- Observe the Issue.

**Expected behavior**
Should not throw error massage as user have not entered any number.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://drive.google.com/file/d/1vnfuMpnqLktkXMdJoOtCnEt3SV7FZwlC/view?usp=sharing)

**App (please complete the following information):**

**Additional context**

**Comment by S-PRAVINKUMAR** [comment]
this is fixed. but with in another PR.

**Comment by johnruban-4050** [comment]
Retested and working fine as expected
