### ISSUE TITLE
Driver App -- Driver details screen Chips carousel are not displayed on user selected language and also broken sometime when Kill & relaunch(Parent_id-#2096)

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2412]
#2096 
Driver App -- Driver details screen Chips carousel are not displayed on user selected language and also broken sometime when Kill & relaunch(https://drive.google.com/file/d/1Pr1KIh1T2Qn7LRR9u6Bk4fkVxGk5aqHS/view?usp=sharing)

Step to reproduce:-
1. launch the app
2. Click on profile
3. Choose the different language on settings
4. verify the Chips carousel
5. Observe the issues.

Expected Result - 
Chips carousel need to display properly and Should shown user selected language
https://drive.google.com/file/d/1Pr1KIh1T2Qn7LRR9u6Bk4fkVxGk5aqHS/view?usp=sharing

**Comment by Sumedh-14** [comment]
Retested on 17/08/2023. Issue is fixed
