### ISSUE TITLE
Texts are missing in the driver profile screen (Parent_Id - 2096)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#2481]
#2096 
[Texts are missing in the driver profile > driver details screen ](https://drive.google.com/file/d/1xcJYlbGKHbrrJbatfT4JtU4iQ8ztXQ32/view?usp=sharing)

**Steps to reproduce**
1. Launch the apk and login with valid credentials
2. Go to my profile > driver details screen and observe the screen

**Expected Result**
All the assets should display in the screen

**Actual Result**
"Earned on YS" text and "on YS" text in "x months on YS"  is missing in the cards carousel.

**Comment by aryanguptaSG** [comment]
config . @ashishsingh101

**Comment by krupal-14** [comment]
Retested,Working fine
