### ISSUE TITLE
English text on Welcome screen and in Language section under settings, is not translated to Bengali Text (Parent_Id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2482]
#2096 

English text on Welcome screen is not translated to Bengali Text
![Screenshot_20230817-121424](https://github.com/nammayatri/nammayatri/assets/138564517/aebd8fbd-84e6-473b-9908-91da5220ca7d)

**Comment by rohanrp179** [comment]
Also there in Language section under settings

**Comment by ashishsingh101** [comment]
Fixed

**Comment by rohanrp179** [comment]
Closing it as working as expected..

**Comment by rohanrp179** [comment]
This was fixed in master but not reflecting in CUG @ashishsingh101
