### ISSUE TITLE
Call Customer support link is not working On Add RC page in One plus (Parent_Id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2484]
#2096 

Call Customer support link is not working On Add RC page in One Plus

Steps-
1. Log in to app
2. Go to profile section -> Vehicle Details -> Add RC
3. Click on Help
4. Click on Call Support Centre 

Expected result-
The dialler screen should open

Actual-
No action is taken place

https://github.com/nammayatri/nammayatri/assets/138564517/52a40df6-5200-4aad-ab37-1464488a7f3d

**Comment by ashishsingh101** [comment]
Fixed

**Comment by rohanrp179** [comment]
As discussed, Can you explain in detail why this is expected so that i can close it @ashishsingh101

**Comment by JanhaviSoni** [comment]
Expected, It will work fine in PROD

**Comment by rohanrp179** [comment]
Closing this as this will work in prod and not in master
