### ISSUE TITLE
The cursor is displaying at the beginning of the added alternate number when trying to edit the added alternate number(Parent_Id - 2096)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#2487]
#2096 
[The cursor is displaying at the beginning of the added alternate number when trying to edit the added alternate number(Parent_Id - 2096)](https://drive.google.com/file/d/1dbmSg4tFxQbU12wzgQX_sC8gsZQgpmvB/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with valid credentials
2. Go to My profile > tap on the added alternate mobile number 
3. Tap on "edit" option 
4. In alternate number edit page, observe the cursor 

**Expected Result**
The cursor should display at the end of the digits 

**Actual Result**
The cursor should display at the beginning of the digits

**Comment by rohanrp179** [comment]
Fixed
