### ISSUE TITLE
On Add RC page, if we click above Upload Registration Certificate text , then Upload RC action is taken place. (Parent_Id 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2489]
#2096

[On Add RC page, if we click above **Upload Registration Certificate** text , then Upload RC action is taken place.](https://drive.google.com/file/d/13fCMW71gEtQjlXXxh6M1qX8_P6jADDVd/view?usp=sharing)

Steps-
1. Log in to app
2. Click on Add RC under Vehicles details under driver profile
3. Click on empty space above **Upload Registration Certificate** text

Expected result-
No action should take place

Actual result-
It is acting for action Upload RC

**Comment by aryanguptaSG** [comment]
fixed

**Comment by rohanrp179** [comment]
Need fix here. Can we have touch area limited to as mentioned in image here @ashishsingh101 

https://drive.google.com/file/d/14BFgVeJmE6Z7LyHU3IY7N3Dd_3F8CIjW/view?usp=sharing

**Comment by rohanrp179** [comment]
@aryanguptaSG

**Comment by aryanguptaSG** [comment]
fixed

**Comment by rohanrp179** [comment]
Fixed . Closing it
