### ISSUE TITLE
Cancellation rides are not displaying in cancelled section(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2492]
#2096 

**Description**
[Cancellation rides are not displaying in cancelled section](https://drive.google.com/file/d/1cyww2-gkHjkkAxIvUkkN05ay52g09mBO/view?usp=sharing)

**Steps To Reproduce**
1.launch the apk.
2.Login with valid credentilas.
3.Cancel some rides fromboth user & driver end.
4.validate in rides-->canceled section

**Expected Result**
cancel Rides should display in that section

**Actual Result**
Cancel rides are not displaying in cancelld section.

**Comment by aryanguptaSG** [comment]
we are getting empty list . backend issue .
