### ISSUE TITLE
When driver moves from Completed section to Canceled section under Rides, the date should come back to default 'Today' (Parent_Id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2493]
#2096 

[When driver moves from Completed section to Canceled section under Rides, the date should come back to default Today..](https://drive.google.com/file/d/13i9vYt7WJzqmN0h7Oz6et4PrzBUUdJev/view?usp=sharing)

Steps-
1. Log in to app
2. Go to Rides
3. Change the date from today to any previous day
4. Now click on Cancelled section

Expected result-
The date should show Today

Actual result-
It is showing the date which was selected when driver was in Completed section

**Comment by aryanguptaSG** [comment]
fixed

**Comment by rohanrp179** [comment]
Fixed. Closing the issue
