### ISSUE TITLE
Back button is not working in help & support section(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2500]
#2096 
**Description**
[Back button is not working in help & support section](https://drive.google.com/file/d/1PaWJ6wly_f8ito-DJNHt7rXGO-fHkuAH/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials .
3.Click on help & support-->Click on ride related->upload pictures.
4.Click on back button.

**Expected Result**
back button should work.

**Actual  Result**
Back button is not working

**Comment by Vinaykm999** [comment]
Retested, Working fine
