### ISSUE TITLE
back button flow is not working in help & support section(Parent_id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2501]
#2096 
Description
[back button flow is not working in help & support section](https://drive.google.com/file/d/1ZopO_7c1i9k1Cwq1SiH5vVD8msUWtKuR/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials .
3.Click on help & support section
4.Click on lost & found-->Click on particular ride.
5.Click on  soft back button
6.Expected screen is not displaying.

Expected Result
back button should work  as expected.

Actual Result
Back button flow is not as expected.

Note: It is happening in all 4 sections of help & support.

**Comment by aryanguptaSG** [comment]
fixed

**Comment by krupal-14** [comment]
Retesed,working fine
