### ISSUE TITLE
Update button should be disable when driver didnt select gender option (Parent_ID_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2502]
#2096 
[Update button should be disable when driver didn’t select gender option ](https://drive.google.com/file/d/1dqdRGIpDMUucFhvhCLulq5z0Z8wDiBpc/view?usp=sharing)

Steps:
1. Login driver apk
2. Open driver profile
3. Click on add gender
4. Verify update button
5. click on update without selecting any option
6. Verify

**Comment by krupal-14** [comment]
Rested,working fine
