### ISSUE TITLE
alternative number cannot be added error message is showing and update button is enabled without entering any number (Parent_ID_2096))

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2503]
#2096 

**Steps**:

1. Launch driver apk
2. Navigate to driver profile screen
3. Click on add alternative number
4. verify update button
5. Click on update button
6. Verify error message 

**Actual** : Update button is enabled

**Tested Device**: Samsung - Android 13

**Comment by Vinaykm999** [comment]
Issue still exist, moving it open state.

**Comment by Akash2172** [comment]
@Vinaykm999 Can u please provide with a video or steps to reproduce

**Comment by Vinaykm999** [comment]
@Akash2172 [Attaching video, kindly check](https://drive.google.com/file/d/1hA2hHwYnf64xX4tj02WhoEwOA3R0ykUR/view?usp=sharing)

**Comment by Vinaykm999** [comment]
now we are not getting **Error messag,e** but update button is enabled without entering mobile number. this issue exist @Akash2172

**Comment by Akash2172** [comment]
Thanx @Vinaykm999 will fix that

**Comment by rohanrp179** [comment]
Fixed.
