### ISSUE TITLE
Payment pop up for driver is showing wrong date for previous ride taken (Parent_id - 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2519]
#2096 

[Driver has not taken any rides previous to 17th Aug but for him the payment pop up shows that payment is pending for ride taken on 16 Aug](https://drive.google.com/file/d/14A3AQTdWbzoMh-LVMYlqmz32anlO4NMP/view?usp=sharing)

Expected-
The pending payment date should be shown when ride has taken

Actual-
It is showing date when ride is not taken

<img width="1542" alt="Screenshot 2023-08-18 at 12 31 22 PM" src="https://github.com/nammayatri/nammayatri/assets/138564517/6133b348-0702-430e-8e35-7cc5499248bc">

**Comment by 0utkarsh** [comment]
This is a design issue. It is a window for which driver fee is calculated, not a date. We need to change this. cc : @hemantmangla

**Comment by rohanrp179** [comment]
closing as no further action happned
