### ISSUE TITLE
When driver click on Offline option, tabs "Go Offline" and "Go Silent" tabs are not same in size. (Parent_Id 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2556]
#2096 

When driver click on Offline option, tabs "Go Offline" and "Go Silent" tabs are not same in size. "Go Offline" tab is smaller than "Go Silent"

Steps
1. Log in to app
2. Click on Offline on Home screen

Expected-
Both tabs should look same in size and length

Actual-
They are not same in length

![IMG_20230821_114031](https://github.com/nammayatri/nammayatri/assets/138564517/2c3bed0a-f3c2-4638-8b7c-d07c2daa601a)

**Comment by Akash2172** [comment]
Expected

**Comment by Akash2172** [comment]
This is kept bigger on purpose so that they go silent instead of offline

**Comment by rohanrp179** [comment]
Go Silent is already highlighted , so i thing there is not need to have diff length of tabs. 
Can you get approval from designers here ? @Akash2172 
cc- @ashishsingh101

**Comment by Srdp208** [comment]
<img width="560" alt="Screenshot 2023-08-22 at 1 59 23 PM" src="https://github.com/nammayatri/nammayatri/assets/127218467/dadec42e-869a-4a33-b185-094cd2f0c749">

This is expected; the primary button width is kept more on purpose for biasing the user action.

**Comment by rohanrp179** [comment]
closing as this is expected
