### ISSUE TITLE
<JP Driver> Confirm & changes button is enable in booking options even though  driver not selected any vehicle variant(Parent_Id-2096))

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2560]
#2096 
**Description** 
[Confirm &changes button is enable in booking options even though  driver not selected any vehicle variant](https://drive.google.com/file/d/1aRrST4tfh4mqFzg4xscXRvIXyu4jBokN/view?usp=sharing)

**Steps To Reproduce**
1.Launch the app.
2.Login with valid credentials .
3.Click on driver profile-->Setting -->Booking options.
4.Select vehicle variant observe the confirm & changes button.
5.Deselect the vehicle variant Observe the confirm & changes button.

**Expected Result**
"Confirm & changes" button should be disable if driver deselect the value.

**Actual Result**
"Confirm & changes" button is enable even though vehicle variant deselect .

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
