### ISSUE TITLE
<JP Driver>Back button is not working in All 4 sections of help and support screen(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2561]
#2096 
**Description**
[Back button is not working in App related & Fare related Issues screen](https://drive.google.com/file/d/1eEOLP37IIYXMk_5Eeub8AOiAKyId6Wls/view?usp=sharing)

**Steps To Reproduce**
1.Launch the apk.
2.Login with valid credentials.
3.Click on help & support.
4.Click on app related issues or fare related issues
5.Try to click both back button(App back button & android back button).
6.Observe the screen.

**Expected Result**
Back button is not working.

**Actual Result**
Back button should work.

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
