### ISSUE TITLE
Message icon is not displaying in banner(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2570]
#1803 
**Description**
[Message icon is not displaying banner](https://drive.google.com/file/d/1lr2IZ4lx3sGiHT1FO-RVikEPTrgeTnsu/view?usp=sharing)

**Steps To Reproduce**
1.Launch the ipa.
2.Login with valid credentials.
3.Book a ride.
4.Receive a message from driver.
5.Observe the banner.

**Expected result**
message icon should display.

**Actual Result**
Message icon is not displaying.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retesed,Working fine.
