### ISSUE TITLE
Invoice is downloading by the name of Namma yatri(Parent_Id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2577]
#1803 
Description
[Invoice is downloading by the name of Namma yatri](https://drive.google.com/file/d/1HH_HQnOz1udx3RqWCebqlZ35pmucdwEw/view?usp=sharing)

Steps To Reproduce
1.Launch the app.
2.Login with valid credentials .
3.Book a ride.
4.Complete the ride.
5.Navigate to my ride-->Click on particular ride-->Click on view invoice
6.Download the invoice -->Observe the title of downloaded file

Expected Result
Merchant name should be yatri saathi

Actual Result
Merchant name is namma yatri.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,working fine
