### ISSUE TITLE
The searched contact results in "add emergency contacts" screen is not cleared when tapping on "x" icon in the search bar(Parent_id - #1803)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#2587]
#1803 
[The searched contact results in "add emergency contacts" screen is not cleared when tapping on "x" icon in the search bar ](https://drive.google.com/file/d/18mTnsaWzkxJU3XKAVtUyeRgFpgjCpfgJ/view?usp=sharing)

**Steps to reproduce**
1. Launch the apk and login with valid credentials 
2. Tap on hamburger menu and Go to emergency contacts screen
3. Tap on "Add emergency contacts" option at the bottom of the screen
4. At the top "search Contacts" search bar search for any contacts 
5. Once the results are displaying tap on the "x" icon in the search bar and observe the issue 

**Expected Result**
The search query should be cleared and also the result should be cleared and all the contacts should display 

**Actual Result**
The entered search query is cleared but the results are still displaying

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine
