### ISSUE TITLE
Old jatri saathi symbol is displaying in take share app pop-up(Parent_id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2588]
#1803 
**Description**
[Old jatri saathi symbol is displaying in take share app pop-up](https://drive.google.com/file/d/1SOh2xOEwFPpHlUUHSjayyzTdwc-1z2Pp/view?usp=sharing)

**Steps To Reproduce**
1.Launch the app.
2.Login with valid credentials .
3.Book a ride.
4.Observe this pop-up 

**Expected Result**
New yatri saathi symbol should display.

**Actual result**
Old jatri saathi symbol is displaying.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,working fine
