### ISSUE TITLE
The Green dot indicating the pickup point in a special zone is larger than usual (Parent_Id - 1803)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#2590]
#1803 
[The Green dot indicating the pickup point in a special zone is larger than usual ](https://drive.google.com/file/d/1H_0SKMpkViFptvW-Ujls3cpCvLutYtJZ/view?usp=sharing)

**Steps to reproduce**
1. Launch the apk and login with valid credentials
2. Search for any ride in a special zone and observe the pickup point in "confirm pickup location" screen

**Expected Result**
The green dot indicating the Pick up point should display for all the special zone 

**Actual Result**
The green dot size is displaying larger than usual

**Comment by MercyQueen** [comment]
Fixed.
