### ISSUE TITLE
"Yatri Saathi" logo displaying in the about screen is smaller(Parent_Id - 1803)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#2592]
#1803 
["Yatri Saathi" logo displaying in the about screen is smaller](https://drive.google.com/file/d/1DFkOh0knSJ-yGUjajyzRkkPt-m9Uddq3/view?usp=sharing)

**Steps to Reproduce**
1. Launch the apk and login with valid credentials 
2. Tap on hamburger menu and go to "about" screen 

**Expected Result**
In about screen, "yatri saathi" logo and the contents should display as per figma 

**Actual Result**
"Yatri Saathi" logo is displaying smaller than usual

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine. So I closed this issue.

![Image](https://github.com/nammayatri/nammayatri/assets/134508712/554c8ba3-2e8f-43d4-ad76-685ecc9a561c)
