### ISSUE TITLE
The toast message text is not translated to Bangla/Hindi(Parent_Id 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2594]
#2096 

[The text is not translated to Bangla/Hindi](https://drive.google.com/file/d/14tFkvNxlt6ZIrJKvgv8r5gi--iiXAgDl/view?usp=sharing)

Steps-
1. Log in to app
2. Go to RC screen
3. Try to delete already active RC

Expected-
The toast message should be in respective language Bangla/Hindi

Actual-
It is in English

**Comment by aryanguptaSG** [comment]
expected , since backend is sending this error message

**Comment by rohanrp179** [comment]
We need this error to be specific to language which we have chosen. @aryanguptaSG 
Can you tag respective dev from backend here @aryanguptaSG @ashishsingh101

**Comment by rohanrp179** [comment]
closing as not response
