### ISSUE TITLE
<YSP> The text is not translated to Bangla/Hindi for View payments history(Parent_id 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2595]
#2096 

[The text is not translated to Bangla/Hindi for View payments history](https://drive.google.com/file/d/14tRlvpfdSWgGTfk5QZaS5shMPRHyGk5M/view?usp=sharing)

Steps-
1. Log in to app
2. Click on Rides
3. Click on View payment history (Language should be other than English)

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
