### ISSUE TITLE
Confirm Changes button is enable even though the user didn’t perform any action in favourite location screen(Parent_Id-1803) 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2599]
#1803 
**Description**
[Confirm Changes button is enable even though the user didn’t perform any action in favourite location screen](https://drive.google.com/file/d/1ckZQcoZ6f7927eie9aT6aYrrmmGXn2Mg/view?usp=sharing)

**Steps To Reproduce**
1.Launch the App.
2.Login with valid credentials.
3.Click on Hamburger.
4. Click on favourites.
5. Click on any one favourite location.
6. observe the confirm changes button.

**Expected Result**
Confirm changes button should not be enabled if user didn’t perform any actions.

**Actual Result**
Confirm Changes button is enable even though  user didn’t perform any action.

**Comment by MercyQueen** [comment]
Fixed. Initially it would be disabled and if any change is made then it would be enabled

**Comment by krupal-14** [comment]
Retesed,working fine
