### ISSUE TITLE
<YS><Enter mobile number Screen><selecting any country code - shows "invalid mobile number" error, should show while entering invalid mobile number>ParentId: 2096

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2625]
#2096 

**Describe the bug**
selecting any country code on "Enter Mobile number" screen shows "invalid mobile number" error, should show while entering invalid mobile number.
**To Reproduce**
- Launch the Application.
- Validate "Enter mobile number" screen.
- Tap on drop down.
-Select any country code.
- Validate the error message.

**Expected behavior**
 should show while entering invalid mobile number.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://drive.google.com/file/d/1H0VFqXTWhSv2-EL5cqjHgThKmhFnjkjk/view?usp=sharing)

**App (please complete the following information):**

**Additional context**

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by johnruban-4050** [comment]
Retested and working fine as expected
