### ISSUE TITLE
<YS USER> Getting tip option for user and also tip with try again (Parent_ID_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2631]
#2096 
[Getting tip option for user and also tip with try again](https://drive.google.com/file/d/1CFlMaSwEfD6XlljRcbCWMk0qPqJcd63F/view?usp=sharing)

**Steps**:
1. Request for a ride
2. Wait for 30 seconds
3. Verify tip option

**Expected**: Tip option should not display

**Actual:** Tip is showing and try again with tip also showing

![Screenshot_20230823_132424_Yatri Sathi](https://github.com/nammayatri/nammayatri/assets/131981246/e1174a84-64df-4908-a60e-fc888cf0b76a)

**Comment by aryanguptaSG** [comment]
expected . we enabled tip for YS also .

**Comment by johnruban-4050** [comment]
As per the Comments I closing this issue
