### ISSUE TITLE
<JS USER> confirm & save button is disable in add favourite screen (Parent_id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2633]
#2096 
**Description**
[ confirm & save button is disable in add favourite screen](https://drive.google.com/file/d/1MMS-roMzO78KAP_1iXiGmVU7jcs4w7qV/view?usp=sharing)

**Steps To Reproduce**
1.Launch the app.
2.Login with valid credentials.
3. Click on hamburger.
4. Click on favourites.
5. click on add favourite location.
6. Enter valid location click on home(But some address must added to home tag already)  
7. will get the error message like home tag is already present.
8. So just change the tag name to work.
9. observe the confirm & save button

**Expected result**
Confirm & save button should be enable.

**Actual Result**
Confirm & save button is disable.

**Comment by ashishsingh101** [comment]
Fixed

**Comment by rohanrp179** [comment]
working fine
