### ISSUE TITLE
<JS USER>In user estimate screen two Sedan Ac vehicle variant is displaying(Parent_id_2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2639]
#2096 
**Description**
[In user estimate screen two Sedan Ac vehicle variant is displaying](https://drive.google.com/file/d/1g2pE8PO7iG1rVu_0bUmkNABJMF2vCweK/view?usp=sharing)

**Steps To Reproduce**
1.Launch the app.
2.Login with valid credentials.
3.Book a ride.
4.Observe the estimate screen.

**Expected Result**
Ac taxi & Non Ac taxi Only two vehicle variant should display. 

**Actual Result**
two sedan Ac vehicle variant is displaying.

**Comment by rohanrp179** [comment]
Closed as working fine
