### ISSUE TITLE
<JS USER> Message FCM will not disapper even though user clicked on replay button(Parent_Id-2096)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2644]
#2096 
**Description**
[ Message FCM will not disapper even though user clicked on replay button](https://drive.google.com/file/d/1_toe93qzRfvJ-jG6yu7sn0SP31BLcrgS/view?usp=sharing)

**Steps To Reproduce**
1.Launch the App.
2.Login with valid credentials.
3.Book a ride.
4.Minimise the user apk.
5.Send message from drivef.
6.Click on Replay button 
7 .Observe that FCM.

**Expected Result**
When user clicks on Replay button the FCM should disappear.

**Actual Result**
Even though user clicks on replay button the Fcm is not disappearing.

**Comment by aryanguptaSG** [comment]
fixed .

**Comment by johnruban-4050** [comment]
Issue Still exist

**Comment by aryanguptaSG** [comment]
it is fixed but not merged yet .

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine
