### ISSUE TITLE
<JS USER> Source location is showing blank for Hindi and bengali language (Parent_ID_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2647]
#2096

[Source location is showing blank for Hindi and bengali language](https://drive.google.com/file/d/1ZTpYRTzm3y-f9lrwSjAABRD_ThbuDkJv/view?usp=sharing)

**Steps**:
1. Change language to hindi or benali
2. Select Destination from recent search in home screen
3.  Do ride search
4. Accept ride
5. verify source location

**Comment by johnruban-4050** [comment]
Retested and working fine as expected
