### ISSUE TITLE
The Bangla translation of English is missing (Parent_id 1803)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2654]
#1803 

The Bangla translation of English is missing
![IMG_0384](https://github.com/nammayatri/nammayatri/assets/138564517/3dac3c25-fdef-4460-852b-7b662f6710bd)

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine. So I close this issue.
