### ISSUE TITLE
<JSP USER>Selected suggestion pills are getting deselected after clicking outside the popup(Paent_ID_2096)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2655]
#2096 
[Selected suggestion pills are getting deselected after clicking outside the popup](https://drive.google.com/file/d/17u7w5xR4tRcdwgZ8b_9QMkuvhxm6i-zk/view?usp=sharing)

**Steps**:
1. Finish the ride
2. Select 3-4-5 star
3. Select suggestion pills
4. Click on outside the popup
5. Select the same star rating which given previously 
6. verify suggestion pills

**Actual**: selected pills are getting deselected

**Comment by aryanguptaSG** [comment]
fixed

**Comment by Vinaykm999** [comment]
working fine, hence am resolving this.
