### ISSUE TITLE
<YS user> User login screen issues(parent -id-1803)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2656]
#1803 
[User login screen issues](https://drive.google.com/file/d/1V4XX6-gOMxAiP-Nbz5vadYoziSbC0U5t/view?usp=sharing)

1. Country code layout hiding the phone number and Continue button
2. There is no get otp via WhatsApp button
3. User is getting Invalid number error message when user start entering first digit.
4. Continue button not enabling when user select Bangladesh country
5. selecting any country code - shows "invalid mobile number" error, should show while entering invalid mobile number

**Comment by MercyQueen** [comment]
fixed.

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine.
