### ISSUE TITLE
Special location ride flow is working as normal ride flow(Parent_id-1803)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2662]
#1803 
**Description**
[Special location ride flow is working as normal ride flow](https://drive.google.com/file/d/1N-a0NtopHQukCCyN_WtYtHl17cp2cUYT/view?usp=sharing)

**Steps To Reproduce**
1.Launch the app.
2.login with valid credentials. 
3.Click on current location choose howrha railway station from favourites .
4.Choose any normal location from favourites.
5.Observe the screen.  

**Expected Result**
Special location ride flow is different.

**Actual result**
Special location ride flow is happening like normal ride flow.

**Comment by MercyQueen** [comment]
Fixed.
