### ISSUE TITLE
Yatri sathi logo is small in about screen(parent-id-1803)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2663]
#1803 
[Yatri sathi logo is small in about screen](https://drive.google.com/file/d/153j1_qdzTwmGdL74mt7AGgPeJBxM-SDH/view?usp=sharing)

**Steps to reproduce**
1. Launch the application
2. Tap on Hamburger
3. Tap on about and observe the logo

**Actual Result**
Yatri sathi logo is small in about screen

**Expected Result**
Yatri sathi logo should be in proper size.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
