### ISSUE TITLE
User unable to save in side the west bengal by using locate on map(Parent-id-1803)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2666]
#1803 
[User unable to save in side the west bengal by using locate on map](https://drive.google.com/file/d/1WNkN7C_eH73xRTwSgxiJ3Uty8qbSQ5SL/view?usp=sharing)

**Step to reproduce**
1. Launch the application
2. Tap on Hamburger 
3. Tap on Favourites 
4. Tap on add favourite 
5. Tap on set on map
6. Select any location in West Bengal 

**Actual Result**
User unable to save in side the west bengal by using locate on map

**Expected Result**
User is able to save in side the west bengal location by using locate on map

**Comment by MercyQueen** [comment]
![Image](https://github.com/nammayatri/nammayatri/assets/55204010/ccae4019-7626-4dfa-b22c-1dfc2f874c69)

This location in out of Kolkata and is unserviceable.

**Comment by krupal-14** [comment]
As per dev comment,Closing this issue
