### ISSUE TITLE
<YS User> In try again screen auto icon is there.(parent-id-2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2678]
#2096 
[In try again screen auto icon is there](https://drive.google.com/file/d/1zun_BNNMIc89r7IOgrZbBWz57yCj7aT9/view?usp=sharing)

**Steps to reproduce** 
1. Search for a ride 
2. Wait until try again screen and observe 

**Actual Result** 
In try again screen auto icon is there

**Expected Result**
In try again screen auto icon should not be there.

**Comment by S-PRAVINKUMAR** [comment]
@AlluGowthami28 not able to reproduce that

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine
