### ISSUE TITLE
<YS user> User is getting "No drivers found toast" When user cancel estimates(parent-id-2096)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2683]
#2096 
[User is getting "No drivers found toast" When user cancel estimates](https://drive.google.com/file/d/11BQ4LSSgkxkQL_xVkRifjKG0avi9KZEc/view?usp=sharing)

**Steps to reproduce**
1. Select source and destination
2. Confirm the pickup
3. And tap on cancel estimates and observe the toast

**Actual Result**
User is getting "No drivers found toast" When user cancel estimates

**Expected Result**
User should not get "No drivers found toast" When user cancel estimates

**Comment by ashishsingh101** [comment]
Ficed

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
