### ISSUE TITLE
User- When Spec location source and its destination are chosen by Select on map, the gate name will stay for 2-3 sec while searching destination(Parent-id 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2692]
#2096 

[When Spec location source and its destination are chosen by Select on map, the gate name will stay for 2-3 sec while searching destination](https://drive.google.com/file/d/11jx3JLyWeBTZrijYfphmli4DdFdIZULW/view?usp=sharing)

Steps-
1. Log in to app
2. Click on Current location and click set on map
3. Choose  Spec location
4. Click on set on map and choose destination

Expected- 
when moved away from gate point, the gate name tag should disappear

Actual-
It is not disappearing

**Comment by ashishsingh101** [comment]
Expected, since we added debounce for api calls while scrolling on map it will be updated only when user is idle for atleast 200ms and api call is done

**Comment by rohanrp179** [comment]
but it is more time than 200 ms and it is clearly visible that the gate name tag is persisted for 1-2 sec. @ashishsingh101 , still this is expected ?

**Comment by rohanrp179** [comment]
no response
