### ISSUE TITLE
User- When trying to log in using whats app, when clicked on Resend OTP, OTP is received by text message (Parent_Id 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2696]
#2096 

[When trying to log in using whats app, when clicked on Resend OTP, OTP is received by text message ](https://drive.google.com/file/d/11tAOr3vL4iXDEuuuI9x781agzt33pqXO/view?usp=sharing)

Steps-
1. Launch the app
2. Enter mobile number and click log in via whatsapp
3. Wait for 30 sec and click Resend OTP

Expected-
When Resent OTP pressed, OTP should be sent to whats app if while log in time whats app option is choosn

Actual- 
It is sending normal text message

**Comment by S-PRAVINKUMAR** [comment]
backend issue

**Comment by rohanrp179** [comment]
no further advancement
