### ISSUE TITLE
User- When user try tip search , the search loader should start from beginning (Parent-id 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2702]
#2096 

[When user try tip search , the search loader should start from beginning ](https://drive.google.com/file/d/11zNwx4U-oGy5Jeby2agNEQGB4xjkthVl/view?usp=sharing)

Steps
1. Log in to app
2. Search for a ride
3. When tip option shown, search with tip

Expected-
when searched with tip option, the loader should start from beginning 

Actual-
Loader is continuing from its previous state

**Comment by S-PRAVINKUMAR** [comment]
@rohanrp179  expected only

**Comment by rohanrp179** [comment]
closing as this is expected
