### ISSUE TITLE
User- The in app tracking on ride OTP screen does not show Google maps like on screen after ride started(Parent id 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2703]
#2096 

[The in app tracking on ride OTP screen does not show Google maps like on screen after ride started](https://drive.google.com/file/d/12-gdJ_HUvzGSsj7SSXljKRdzhqLDxfiL/view?usp=sharing)

Steps-
1. Log in to app
2. Assign a ride
3. Click on in app tracking
4. Start the ride and click on in app tracking

Expected-
Google maps option is required on ride OTP screen also

Actual-
It is shown only after ride is assigned. It is not shown on ride OTP screen

**Comment by S-PRAVINKUMAR** [comment]
Expected
