### ISSUE TITLE
User-On Home screen, when user click on back press for save as favourite pop up , the app is closing (Parent_Id 2096)

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2704]
#2096 

[On Home screen, when user click on back press for save as favourite pop up , the app is closing](https://drive.google.com/file/d/12003-7mN5Xq_HbrnwzQvwhG42TkDo8Ol/view?usp=sharing)

Steps-
1. Log in to app
2. (Make sure there is at least one recent search) click on heart shape in front of recent search
3. When pop up opens click on back press to close keypad
4. Press back press one more time

Expected-
When step 4 is done, pop up should go

Actual-
App is closing

**Comment by aryanguptaSG** [comment]
fixed

**Comment by rohanrp179** [comment]
no further advancement
