### ISSUE TITLE
<04_09_2023><NYU><IPA><Location Confirmaton sc><Location Confirmation screen is not working><Parent_ID-1980>

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2877]
[Location Confirmation map screen is not working](https://drive.google.com/file/d/1seNf_6nBeESooDKgh3ThASDwy1vv09hc/view?usp=sharing)

Step to reproduce : -
1. Start the app
2. Launch the app
3. Search the location
4. Click on Confirm pickup location
5. Click on Map.
6. Observe the issue

Expected result - User able move the map from confirm pick location screen

Reproduce rate - 5/5

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
