### ISSUE TITLE
<04/09/23><NYU><Android><Talkback> Mobile number in talkback is not saying properly <Parent_ID_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2879]
#1980 
[ Mobile number in talkback is not saying properly ](https://drive.google.com/file/d/1SuFfFUaVdEWmeCRs0CLvQ6h4CgLYFcJV/view?usp=sharing)
 
 Steps:
 1. Launch apk
 2. Click on hamburger menu
 3. Navigate to number option in profile
 4. Verify the talkback for mobile num
 
 **Expected**: Talkback should say in mobile number format

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
working fine, hence closing this
