### ISSUE TITLE
<04_09_2023><NYU><IPA><Language selection screen><Language selection screen is displayed empty><Parent_ID-1980>

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2882]
[Language screen displayed empty](https://drive.google.com/file/d/1kqJD8DlE9goPLu-8NpNvXSJDt-k_nnpT/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Click on profile 
3. Click on Language selection
4. Observe the issue

Expected - Language selection options are need to displayed.

Reproduce rate - 5/5

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,working fine
