### ISSUE TITLE
<04/09/23><NYP><IPA><RideSerach><Pick up points not scrolling down and focusing automatically><Parent_Id-1980>>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2883]
#1980 
[Pick up points not scrolling down and focusing automatically](https://drive.google.com/file/d/1L3tpxl1fVXCpXXkmb8Vh1ZuOAWEvMov7/view?usp=sharing)

Steps To Reproduce
1.Launch the ipa.
2.Login with valid credentials.
3.Initiate ride with special loaction.
4.select 3rd location and observe the drop down.

expected result
the selected pick up location should  automatically scroll down & focus.

Actual result
it is not scrolling down & focusing.

**Comment by krupal-14** [comment]
Any update on this issue @MercyQueen

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Wokring fine
