### ISSUE TITLE
04/09/23_NY_IPA_In Emergency contact screen, "Was your call Successful" pop up coming before than expected_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2888]
#1980 

Was your call successful pop up is coming before call is happned.

Steps-
1. Assign a ride
2. Go to emergency contact
3. Click on any emergency call

Expected-
"Was your call Successful" pop up should come after driver come back from dial screen

Actual-
This pop up is coming before driver is moved to dialler screen

https://github.com/nammayatri/nammayatri/assets/138564517/1a5dcafd-eb19-436f-9b3e-75b89a55285f

**Comment by MercyQueen** [comment]
@S-PRAVINKUMAR can you take this up.

**Comment by S-PRAVINKUMAR** [comment]
@MercyQueen  sure

**Comment by krupal-14** [comment]
Any update on this @S-PRAVINKUMAR

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by rohanrp179** [comment]
working fine
