### ISSUE TITLE
04/09/23_NY_IPA_Call driver option before cancelling the ride is not shown_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2889]
#1980 

When user want to cancel the ride, call driver option is missing

Steps-
1. Assign a ride
2. Click on cancel ride on Ride OTP screen

Expected-
When tried to cancel the ride, Call driver option should pop up

Actual-
It is directly taking to choose reason before cancelling

https://github.com/nammayatri/nammayatri/assets/138564517/9e1fc11a-b175-48e3-ba77-6e2694b4456f

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested ,working fine
