### ISSUE TITLE
<04/09/23><NY><ANDROID><Accessibility><While opening Menu, the profile have both close and open audio for menu list><Parent_Id-1980>>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2894]
#1980 
**Describe the bug**
While opening Menu, the profile have both close and open audio for menu list.

**To Reproduce**
- open the Manu list
- swipe and select the profile
- validate the Audio. 

**Expected behavior**
Audio should be only instructing for Closing menu list.

**Screenshots**
(https://drive.google.com/file/d/1Z3QiUEmvpP6vYFFZRx2fh6G3CiTVU2T4/view?usp=sharing)

**App (please complete the following information):**

**Additional context**

**Comment by Vinaykm999** [comment]
Working fine, hence resolving this.
