### ISSUE TITLE
04/09/23_NY_IPA_Chat banner on Ride OTP screen is disappearing after kill and reopen the app_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2896]
#1980 

Chat banner on Ride OTP screen is disappearing after kill and reopen the app

Steps-
1. Assign a ride
2. Be on Ride OTP screen
3. Send in app chat message from driver side
4. When chat banner comes on Ride OTP screen, kill and reopen the app

Expected-
After reopening, the chat banner should be there

Actual-
The banner is disappearing 

https://github.com/nammayatri/nammayatri/assets/138564517/e3ee94b5-a93b-4dc3-ac16-2e167f559c19

**Comment by MercyQueen** [comment]
@PraveenGongada  is this expected?

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,working fine.

**Comment by rohanrp179** [comment]
Reopening the issue. @krupal-14 pls attach the video as discussed
