### ISSUE TITLE
<04/09/23><NY><ANDROID><Accessibility><without any confirm location,Audio says "Confirming location" on Confirm Pickup screen><Parent_Id-1980>>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2897]
#1980 

**Describe the bug**
Audio is saying "Confirming location" in Screen State mode on Confirm Pickup screen without any confirm location

**To Reproduce**
- select source and destination
- swipe to get audio for different buttons
- validate "Confirm pick up" button
- swipe again
- Validate the State of screen and audio 

**Expected behavior**
Audio of "Confirming location" should only come when we select "Confirm Pickup".
**Screenshots**
https://drive.google.com/file/d/1Or-xVd4V0k9HVDAVIchYf7Yp4-K2d2n9/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by Vinaykm999** [comment]
Working fine. hence resolving this
