### ISSUE TITLE
04/09/23_NY_IPA_Under Help and Support, current successful ride is showing as cancelled_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2899]
#1980 

[Under Help and Support, current successful ride is showing as cancelled when user visit to cancelled ride details from "View all rides" and then again visit details of current ride via Help and support](https://drive.google.com/file/d/1VxTyTAQEzCCnlTZX3bE1RfmoaUEHTtlE/view?usp=sharing)

Steps-
1. Complete a successful ride
2. Go to Help and support
3. Click "Report an issue with this Trip"
4. Observe that below trip price it will be "Paid by Cash"
5. Go to previous screen and click on "View All Rides"
6. Click on "View Details" of any cancelled ride 
7. Go back to Help and support screen by pressing back press
8. Now repeat step 3

Expected-
When step 8 is done, "Paid by Cash" should display below trip price

Actual-
It is showing "Cancelled"

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retesed,Working fine
