### ISSUE TITLE
04/09/23_NY_Android_Talkback not reading ride id digit by digit_1980 

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2916]
#1980 
Talkback not reading ride id digit by digit

**Steps to reproduce** 
1. Complete a ride
2. Tap on My rides
3. Tap on view details
4. Tap on ride and listen voice

**Actual Result**
Talkback not reading ride id digit by digit.

**Expected Result**
Talkback should read ride id digit by digit.

**Comment by Vinaykm999** [comment]
Working as expected
