### ISSUE TITLE
04/09/23_NY_IPA_Talkback_Lets go when disabled is not read as disabled on  new profile set up screen_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#2920]
#1980 

[Lets go when disabled is not read as disabled on  new profile set up screen](https://drive.google.com/file/d/1krneoa2nF4J6KSI7gYmm5VPL6VpE4SBT/view?usp=sharing)

Steps-
1. Login with new number
2. When reached on new profile set up screen, go to Lets go when it is disabled

Expected-
It should read out as disabled when it is disabled

Actual -
It is not reading out as disabled when it is.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Rajaprabhu-Natrajan** [comment]
It's working Fine
