### ISSUE TITLE
<04/09/23><NY><ANDROID><Accessibility><Audio saying "Chat with driver" from "Call driver" screen><Parent_Id-1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2927]
#1980 

**Describe the bug**
Audio saying "Chat with driver" from "Call driver" screen
**To Reproduce**
-Confirm a ride
-Swipe to the call option
-Swipe and validate the layout and audio
**Expected behavior**
Either audio should not be there or it should minimise the pop up screen.

**Screenshots**
https://drive.google.com/file/d/1UaQlhpEw2Yr4js3eI1ItmLm83C6LW4r7/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by aryan-13** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
working as expected.hence closing this
