### ISSUE TITLE
<04_09_2023><NYU><IPA><Chat screen- Driver Call><When Talk back feature is 'ON' Call Driver Using is not focusing after click directly><Parent_ID-1980>

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2928]
[When talk back feature is 'ON' Call driver using is not focusing after click directly](https://drive.google.com/file/d/1Y56yu1vScLszTOUPp-iJpccV9P9VYyce/view?usp=sharing)
Step to reproduce:-
1. Launch the app
2. Search the ride
3. Assign the ride 
4. Click on Call driver icon on In app chat
5. "Call Driver Using" pop up is not able to click directly

Expected:-
Call Driver using pop up should focused when user swipe and directly click on it 

Reproduced rate - 5/5

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine.
