### ISSUE TITLE
04/09/23_NY_IPA_talkback_Ride OTP screen is not expanding &collapse _1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#2929]
#1980 
[Ride OTP screen is not expanding &collapse](url)

Steps To Reproduce
1.Turn on the talkback.
2.Launch the ipa.
3.Login with valid credentials.
4.Assign a ride.
5.Observe the otp screen.

Expected Result
OTP screen should expand & collapse.

Actual Result
OTP screen is not Expanding & collapsing.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine. hence resolving this.
