### ISSUE TITLE
05/09/2023_NYU_Android_(customer side UI changes)_Ride assigned & Ride Started - "Pay by cash.." text is not displayed as per figma_Parent_Id_1980

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#2943]
[Ride Assigned nd Ride Started screen - "Pay by cash.." text is not displayed as per figma](https://drive.google.com/file/d/1FSjFRZyBraF9pIYaiz1u8xIyEbxrIreP/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2.  Book the ride
3. verify the "Pay by Cash/UPI" text 
4. Verify the Auto icon
5. Verify the "Live Stat" Chips 
6. Observe the issue

Expected Result:-
1., Pay by cash/ UPI text is not as per figma.
2. Auto icon is not displayed properly
3. "Live Stats" Chips design also not displayed properly. 

Screenshot - https://drive.google.com/file/d/1FSjFRZyBraF9pIYaiz1u8xIyEbxrIreP/view?usp=sharing

**Comment by KiranBKL** [comment]
Live Stats one is expected

**Comment by Rajaprabhu-Natrajan** [comment]
It's Working as expected
