### ISSUE TITLE
05/09/23_NY_Android_ customer side UI changes_On otp screen text is different compared with figma_1980

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#2944]
#1980 
[1. 2 mins Away text should be in green colour
2. Pay by Cash/UPi text should be there instead of cash/ Use UPI app ](https://drive.google.com/file/d/1mV7JT0jmYPZlRSv3_1TFunSpLHTmcx4g/view?usp=sharing)

**Steps to reproduce** 
1. Launch the application 
2. Book a ride and observe the screen

**Actual Result**
1. 2 mins Away text  in black colour
2. cash/ Use UPI app should not be there

**Expected Result**
1. 2 mins Away text should be in green colour
4. Pay by Cash/UPi text should be there instead of cash/ Use UPI app

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine.
