### ISSUE TITLE
<06/09/23><YSD><ANDROID><popup for RC Status><Pop Up do not have Any Image><Parent_Id-2096>>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2993]
#2096 

**Describe the bug**
Pop Up do not have Any Image

**To Reproduce**
- Log in 
- Make sure RC should be deactivated
- back to home screen
- Validate the Image.

**Expected behavior**
Pop Should have Image.

**Screenshots**
https://drive.google.com/file/d/1ugOiClJA57RFjDzHsDLIpqCjW-yLBmDU/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
