### ISSUE TITLE
<06/09/23><YSD><ANDROID><Vehicle details screen- Activate RC pop up><tapping outside of box should close the "Activate RC" ><Parent_Id-2096>>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#2995]
#2096 

**Describe the bug**
tapping outside of box should close the "Activate RC"

**To Reproduce**
- Validate the Activate RC Pop up
- tap on "vehicle Details" 
- tap on " Activate RC" 
- Validate bottom pop up box 
- tap on the main screen and validate the Issue. 

**Expected behavior**
Should minimise the bottom pop up. 

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://drive.google.com/file/d/1iOr94vspFoWYUph0Nk3SMQ8c9tcvHNXo/view?usp=sharing)

**App (please complete the following information):**

**Additional context**

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine
