### ISSUE TITLE
07/09/23_NY_ANDROID_When user or driver side , enter the suggestion text "Call me, you're unreachable " . It is only displayed "Call me, you" on receiver side._1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3015]
#1980 
[When user or driver side , enter the suggestion text "Call me, you're unreachable " . It is only displayed "Call me, you" on receiver side](https://drive.google.com/file/d/1KqHqh1txvRmIzbNvd_KVbYBoQQJJHMQd/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.login with valid credentials.
3.Chat between user & driver.
4.Send message by typing it

Expected result
Typed message should display properly.

Actual Result
Typed message is not displaying properly.

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine
