### ISSUE TITLE
<07/09/23><YSU><ANDROID><Ride Feedback Screen><Tapping on Submit Feedback Screen getting covered from pop up Keypad><Parent_Id-2096>>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3025]
#2096 

**Describe the bug**
Tapping on Submit Feedback Screen getting covered from pop up Keypad

**To Reproduce**
-Complete the Ride. 
- Select the rating start. 
- Validate the Feedback Box and tap on it. 
- Validate the Pop up keypad and Issue. 

**Expected behavior**
- Writing box should be visible along with Keypad. 

**Screenshots**
![Screenshot_20230907_180241 (1)](https://github.com/nammayatri/nammayatri/assets/128033831/97fe118d-6f75-40a3-b7aa-d70d06e97f12)

**App (please complete the following information):**

**Additional context**

**Comment by ashishsingh101** [comment]
Fixed, we can check in CUG

**Comment by Rajaprabhu-Natrajan** [comment]
It's  working fine
