### ISSUE TITLE
<07/09/23><NYP><ANDROID><Purple Rides><When user logged in as Blind low vision but it's logged in as Other disability user> <Parent_Id-1980>

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3027]
[When user logged in as Blind low vision but it's logged in as Other disability user](https://drive.google.com/file/d/1WIdDgXQAyM57mH7RxSpFIzqXjnqYnDyA/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2.  Logged in as blind low vision in user side
3. Book the ride 
4.  In driver side displayed as other disability 

Numbers - 9952793803 & 9952793804 (Both number declared as blind low vision). Backend it's displayed correct only issue on frontend side.
 
Expected result:-
Blind low vision category changes should be display.

Reproduce rate - 5/5

**Comment by Vinaykm999** [comment]
working fine
