### ISSUE TITLE
<07/09/23><NYP><ANDROID><Purple Rides><"Customer may need assistance" popup content text font size is differ from figma> <Parent_Id-1980>

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3030]
["Customer may need assistance" popup - Content text font size is differ from figma.]()

Step to reproduce:-
1. Launch the app
2. Book the ride from user side
3. verify the driver side
4. Click on learn more option 
5. Customer may need assistance popup is displayed
6. Observe the issue

Expected result - Font size of the content is not as per figma.

**Comment by MercyQueen** [comment]
Fixed. Cross Checked the font size it is fine for primary text. And fixed for secondary text.

**Comment by krupal-14** [comment]
Retested,working fine.
