### ISSUE TITLE
07/09/23_NYP_Android_PurpleRide_Learn more pop-up when driver at pickup is not translated correct in kannada_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3032]
#1980 
[Learn more pop-up when driver at pickup is not translated correct in kannada..... deaf](https://drive.google.com/file/d/1TAGQX0LhX5o61zCWKexvpz7e-vFvckJA/view?usp=sharing)

[kannada translation is wrong for locomotor disability in top center of ride start screen at pick up.....locomotor disability ](https://drive.google.com/file/d/1BeFSn3WyLwbStnEHtyO0gwNzs0bKlc9P/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Driver chooses kannada language.
4.Accepted a accessibility ride.
5.Came at pickup-->Clicked on learn more-->Observe

Expected Result
Translations should be correct.

Actual Result
Transitions are not correct.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
rested,Working fine.
