### ISSUE TITLE
08/09/23_NYP_Android_PurpleRides_Hindi translation is wrong in end ride screen_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3040]
#1980 
[Hindi translation is wrong in end ride screen when user has locomotor disability ](https://drive.google.com/file/d/12t1PplteatnfX0LXjRN8JsJOslkbbHUs/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.:Login with valid credentials.
3.Book a ride.
4.Observe the top center tab message.

Expected result
 Hindi translation should be correct.

Actual result
Hindi translation is wrong.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,working fine.
