### ISSUE TITLE
08/09/23_NYP_Android_PurpleRide_Completed accessibility rides are not displaying in my rides screen_1980 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3042]
#1980 
[Completed accessibility rides are not displaying in my rides screen](https://drive.google.com/file/d/1X8lDxkWf_ohW6GyXoY5x_Krvx_p_iR7M/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Accept  rides.
4.complete rides.
5.Observe the my rides screen by selecting todays date.

Expected Result
All completed rides should display.

Actual result
Completed rides are not displaying in my rides screen.

Note: date picker is also not displaying in driver choosed language.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Issue is still exist

**Comment by Vinaykm999** [comment]
Working fine
