### ISSUE TITLE
<08/09/23><NY><Android><Talkback><Purple Rides><Reading previous screen data in learn more on accessibility pop-up> <Parent_Id-1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3058]
#1980 
[Reading previous screen data in learn more on accessibility pop-up](https://drive.google.com/file/d/18Y_aGKc6pn5-rflG23qCmPg1e4y2KqqI/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Go to user profile
4.Click on assistance required (Learn how namma yatri caters to your needs)

Expected Result
Talk back should focus on the pop-up text.

Actual Result
Reading previous screen text.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
