### ISSUE TITLE
<08/09/23><NYU><ANDROID><Talkback><Purple Rides><Not reading the gender drop down in my profile> <Parent_Id-1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3060]
#1980 
[Not reading the gender drop down in my profile](https://drive.google.com/file/d/1D1cTVqWb8J7-TjFy0MrsVrNYcaMEzKs8/view?usp=sharing)

Steps To Reproduce
1.launch the apk.
2.Login with valid credentials.
3.Go to my profile.
4.Edit the profile-->Navigate to the gender drop down and observe.

Expected Result
It should focus and read the gender drop down

Actual result
It is reading previous screen text

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested ,working fine.
