### ISSUE TITLE
<08/09/23><NY><ANDROID><Talkback><Purple Rides><Not focusing on special assistance pop-up & reading previous screen text in the 1st loop>> <Parent_Id-1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3062]
#1980 
[Not focusing on special assistance pop-up & reading previous screen text in the 1st loop](https://drive.google.com/file/d/1FADyYqhG1pEMpmLE-UfcF3zd6DpTLnMB/view?usp=sharing)

Steps To reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Go to my profile--edit profile-->Click on disability yes
4.Observe the screen.

Expected result
Not focusing on the special assistance pop-up and reading previous screen pop-up

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine.
