### ISSUE TITLE
08/09/23_NYU_Android_PurpleRides_talkback_Not reading the disability pop-up correctly _1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3082]
#1980 
[Not reading the disability pop-up correctly](https://drive.google.com/file/d/1fXnLThKgbICl-B6jKQM6MUfm_Qj_rGiI/view?usp=sharing)

Steps To reproduce
1.Launch the apk.
2.login with valid credentials.(With blind disablity)
3.Listen to the pop-up text.

Expected Result
should reading the text properly.

Actual result
Not reading the text properly.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,working fine.
