### ISSUE TITLE
<11_09_2023><NYU><ANDROID><Disability_Popup><Descriptive text is hiding after tap on Yes<Parent_ID-1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3098]
#1980 
[**Descriptive text is hiding after tap on Yes**](https://drive.google.com/file/d/1t4-4AJnFC0l2mt_7_B3TRFctzf6YzWIy/view?usp=sharing)

Steps:
1. Onboard new user
2. be on just one thing screen
3. select are you a person with disability field as yes
4. Verify descriptive text
5. Opening popup automatically without selecting lets go button

**Expected**: As per figma descriptive text should be visible.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
