### ISSUE TITLE
<11_09_2023><NYP><ANDROID><Purple _Ride><Call icon is enabled for deaf user when chat screen is open<Parent_ID-1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3102]
#1980 

[Call icon is enabled for deaf user when chat screen is open](https://drive.google.com/file/d/1ZxostI8ZPoX9re9S7X-ZXpNNxMYZwQOR/view?usp=sharing)

Steps:
1. Accept ride for deaf user
2. Verify call icon in Start ride screen
3. Open chat 
4. Verify call icon

Actual: Call icon is disabled in Start ride screen and enabled in chat screen

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retesed,Working fine.
