### ISSUE TITLE
<13_09_2023><NYP><ANDROID><Purple _Ride>Exotel number is not showing in dailer pad when driver click on call support in user rating screen <Parent_ID-1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3148]
#1980 
[Exotel number is not showing in dailer pad when driver click on call support in user rating screen ](https://drive.google.com/file/d/1hVg1wNmi6loOBVopcwhSx386-TAJ3fx4/view?usp=sharing)

Steps:
1. Launch driver apk
2. Finish ride
3. be in user rating screen
4. Click on call support icon
5. verify dailer pad

Actual": Dailer pad is showing empty screen
Expected: Dailer pad should show exotel number

**Comment by Vignesh-772** [comment]
Expected in master
