### ISSUE TITLE
<13/09/23><NYP>Android><PurpleRide>There is more Space before the mobility icon at the top header after the ride is assigned><Parent_Id-1980>

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3149]
#1980 
[Space is more before the mobility icon at the top header when compared with  figma after the ride is assigned](https://drive.google.com/file/d/1cE1ZkRN4Jc_vQPosN_NEhVKAfyixgh53/view?usp=sharing)

**Steps To Reproduce** 
1. Launch the application and login with valid credentials 
2. Initiate a ride from the user and accept it by the driver 
3. Verify the screen at the top and observe the issue 

**Expected Result**
The space before the mobility icon should be same as in figma 

**Actual Result** 
The space is more when compared to figma

**Comment by MercyQueen** [comment]
This is expected.

**Comment by Vinaykm999** [comment]
As per dev comment we are resolving this
@kavya-shree-s
