### ISSUE TITLE
<13_09_2023><NYP><ANDROID><Purple _Ride>Sound horn Customer assistance popup should display when driver Click on I've arrived<Parent_ID-1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3150]
#1980 
[Sound horn Customer assistance popup should display when driver Click on i've arrived
](https://drive.google.com/file/d/1RRVSyIlNFdgh84JOnGtvPtsbDlwmm-CK/view?usp=sharing)

**Steps:**
1. Launch apk
2. Accept the ride got from accessibility user
3. Click on learn more
4. Verify popup
5. Move to pickup location
6. Click on I've arrived
7. Wait for 10-15sec
8. Click on learn more
9. Verify popup 

**Expected**: Please sound horn once at pickup popup should display after click on i've arrived

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
working fine
