### ISSUE TITLE
<13_09_2023><NYP><ANDROID><Purple _Ride>Chat screen is opening when blind user clicks through chat notification<Parent_ID-1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3152]
#1980 
[Chat screen is opening when blind user clicks through chat notification
](https://drive.google.com/file/d/1LT-dJgeQcBM29XDsjwdUqltJBT4nmmvP/view?usp=sharing)

**Steps**:
1. Open driver apk
2. Accept the ride having blind accessibility 
3. Send message from user
4. Click on the chat fcm from driver
5. Verify chat screen

**Actual**: Chat screen is opening

**Comment by MercyQueen** [comment]
expected. the chat button is just greyed out on click of it now driver will get a pop .

**Comment by Vinaykm999** [comment]
closing this issue
