### ISSUE TITLE
<13/09/23><NYP><ANDROID><Purple Rides><Driver ride completed screen is not according to figma> <Parent_Id-1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3153]
#1980 
Hindi translation is wrong for end ride screen.

![Screenshot_20230913_183112](https://github.com/nammayatri/nammayatri/assets/132905061/ea9a9bd1-040f-4336-b4f1-e9d52e3219e8)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Accept a ride.
4.Complete a ride.
5.Observe the ride completed screen.

Expected Result
Purple ride is should translated properly in hindi.

Actual Result
Purple ride is not translated properly in hindi.

**Comment by MercyQueen** [comment]
fixed.

**Comment by Vinaykm999** [comment]
Working fine
