### ISSUE TITLE
<13/09/2023><NYP><PurpleRides><"Call support center" icon is missing in the ride completed screen(Parent_Id-1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3163]
#1980 
["Call support center" icon is missing in the ride completed screen](https://drive.google.com/file/d/1G3tqMadHONnejRZj1My7obutO1EU9WQG/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials > Change the language to tamil
2. Complete one ride
3. Observe the ride completed screen 

**Expected Result**
All the assets and the screen should display as per figma

**Actual Result**
"Call support center" icon is missing

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
