### ISSUE TITLE
<13/09/2023><NYP><PurpleRides><"Cancel" text in the endride screen is cropped in tamil language(Parent_Id - 1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3164]
#1980 
["Cancel" text in the endride screen is cropped in tamil language](https://drive.google.com/file/d/1Yz--fgpkeJCfBM2reLaqEHTB28-SDRuf/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credential
2. Change the language to tamil 
3. Initiate a ride by the customer and accept it by the driver 
4. Start the ride and tap on "end ride" 
5. Observe the "cancel" button in the endride screen

**Expected Result**
"Cancel" text should properly display 

**Actual Result**
"Cancel" text is cropped.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
