### ISSUE TITLE
<14/09/23><NYP><Android><Go To><Text correction in Add go to location screen><Parent id 1980>

### ISSUE THREAD

**Issue by Vinod2803** [nammayatri/nammayatri#3175]
#1980 

Steps to reproduce:

1. Launch the application
2. Tap on Go-To button
3. Observe the add location screen

Expected result:
1. Text should be in capital letters like "No Go-To Locations Added Yet" 
2. Button text should be "Add New Go To Location"
As per figma
Actual result:
1. text says "No Go-To locations added yet"
2. Button text says "Add Location"

Repro:5/5

![Screenshot_20230914_121154](https://github.com/nammayatri/nammayatri/assets/141636849/20b391cc-00d4-4fbd-a1a6-ac8d0a88acd6)
<img width="253" alt="Screenshot 2023-09-14 at 12 21 17 PM" src="https://github.com/nammayatri/nammayatri/assets/141636849/fe4e6f8f-1ae2-4ed1-af79-120d5cb346c1">

**Comment by Rajaprabhu-Natrajan** [comment]
Reopen ---> Still this issue happening 

Text should be in capital letters like "No Go-To Locations Added Yet". --> Still is not fixed


![Image](https://github.com/nammayatri/nammayatri/assets/134508712/be22722a-efa3-4061-833a-10fe1096750d)

**Comment by Rohit4997** [comment]
@AlluGowthami28  Text is in capital letters only.
`Go-To` will be like this only

**Comment by krupal-14** [comment]
Retested, Working fine.
