### ISSUE TITLE
<14/09/23><NYP><Android><Go To><Bugs is add location screen><Parent id 1980>

### ISSUE THREAD

**Issue by Vinod2803** [nammayatri/nammayatri#3176]
#1980 

Steps to reproduce:

1. launch the application
2. Go to Profile>Settings>Go to Locations
3. Add the address and observe the screen

Expected result:

1. Home icon should be displayed
2. Edit icon should be displayed
3. Two different addresses shouldn't contain same tag as "Home"

Actual result:

1. Home icon is not displaying
2. Edit icon is not displaying
3. User can able to give same tag for 2 different addresses

Repro: 5/5

![Screenshot_20230914_124048 (1)](https://github.com/nammayatri/nammayatri/assets/141636849/a842d62c-aceb-4665-90b2-3cb3f252478c)

**Comment by Rohit4997** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
@Rohit4997 
1. Edit option is not there as per figma.
2. **Add Another Location** button text should be title case as per figma

![image](https://github.com/nammayatri/nammayatri/assets/139038923/d598e99e-ef91-4d08-899e-97fc538d2402)

**Comment by Rohit4997** [comment]
> @Rohit4997
> 
>     1. Edit option is not there as per figma.
> 
>     2. **Add Another Location** button text should be title case as per figma
> 
> 
> ![image](https://user-images.githubusercontent.com/139038923/270351709-d598e99e-ef91-4d08-899e-97fc538d2402.png)

@AlluGowthami28  Currently we are not allowing driver to edit the location.
This was already discussed why we are again raising it?

**Comment by AlluGowthami28** [comment]
@Rohit4997 about edit option okay, What about button text.

**Comment by Rohit4997** [comment]
> @Rohit4997 about edit option okay, What about button text.

This I fixed

**Comment by AlluGowthami28** [comment]
Issue fixed
