### ISSUE TITLE
<14/09/23><NYP>Android><Go To><There is a glitch while navigating to Go to locations><Parent id 1980>

### ISSUE THREAD

**Issue by Vinod2803** [nammayatri/nammayatri#3179]
#1980 

[There is a glitch while navigating to Go to locations](https://drive.google.com/file/d/1PFkVxuHMoO5FZJ9iR_7kaYK9lcHarU6A/view?usp=sharing)
Steps to reproduce:

1. Launch the application 
2. Go to Profile>Settings
3. Tap on Go to locations and observe

Expected result:

Glitch shouldn't be there while navigating to another screen

Actual result:

There is a glitch while navigating to Go to locations

Repro:5/5

**Comment by AlluGowthami28** [comment]
@Rohit4997 @Vinod2803 
Some other glitch is there mentioned in this ticket 
https://github.com/nammayatri/nammayatri/issues/3367
hence this ticket is closing.
