### ISSUE TITLE
<14/09/23><NYP><Android><Go To><Application is crashing while adding the go to location><parent id 1980>

### ISSUE THREAD

**Issue by Vinod2803** [nammayatri/nammayatri#3181]
#1980 

Steps to reproduce:
1. Launch the application
2. Go to Profile>Settings>Go to locations
3. Try to add the locations

Expected result:

Application shouldn't crash

Actual result:

Application is crashing while adding the go to location

Repro: happened only one time in Vivo device- Vivo Y20G-Android 13

<img width="1253" alt="Screenshot 2023-09-14 at 2 01 32 PM" src="https://github.com/nammayatri/nammayatri/assets/141636849/02b9780c-ff01-4a39-8745-6e2bc781e7c5">

**Comment by Rohit4997** [comment]
@Vinod2803 I'm not able to reproduce from above steps
Please mention device details
frequency of crash
And try give more detailed info.

**Comment by Vinod2803** [comment]
@Rohit4997 I have added all the info in the ticket "**Repro**" step. kindly check.

**Comment by Rohit4997** [comment]
@AlluGowthami28 @krupal-14  This I have fixed and moved to ready, Then why this fix is not validated?
