### ISSUE TITLE
<14/09/23><NYP><Android><Go To><Go To icon is disappearing Once the user uses Go to option 2 times in a day><parent id>

### ISSUE THREAD

**Issue by Vinod2803** [nammayatri/nammayatri#3185]
#1980 

Steps to reproduce:

1. launch the application
2. Enable the Go to option and use 2 times in a day and observe the Home screen

Expected result:

Go to button should be Grayed out and should show 0

Actual result:

Go To icon is disappearing after completing the 2 rides

Repro:5/5

![Screenshot_20230914_154512](https://github.com/nammayatri/nammayatri/assets/141636849/863ef68e-6059-4fd3-95ac-3478e0facc3e)

**Comment by Rohit4997** [comment]
Fixed
