### ISSUE TITLE
14/09/23_NYP_Android_Go To_New Ongoing issues from Help and Support are shown at last _Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3186]
#1980 

[New Ongoing issues from Help and Support are shown at last. ](https://drive.google.com/file/d/16nkaAjRChosEWKA_7KdSzjp85zOjeqJ-/view?usp=sharing)

Steps-
1. Log in to app
2. Go to Help and support
3. Click on Ongoing issues (Create few issues first to see this option)

Expected-
The newly created issue should be shown on top

Actual-
Newly created issue is shown at bottom

**Comment by Rohit4997** [comment]
Not related

**Comment by rohanrp179** [comment]
no response
