### ISSUE TITLE
<14/09/23><NYP><Android><Go To><Bugs in ride request pop up><parent id 1980>

### ISSUE THREAD

**Issue by Vinod2803** [nammayatri/nammayatri#3187]
#1980 

Steps to reproduce:

1. Launch the application
2. Enable the Go to option
3. Search for the ride
4. Observe the ride riquest pop up

Expected result:

1. "Go To" button should be on right side as per figma
2. When we apply customer tip, the banner should be as per figma

Actual result:

1. "Go To" button is displaying on left side 
2. When we apply customer tip, the banner is not showing as per figma

Repro:5/5

![Screenshot_20230914_142101](https://github.com/nammayatri/nammayatri/assets/141636849/95df108a-689f-4381-94e8-5300a691d918)

**Comment by Rohit4997** [comment]
@krupal-14  Figma is not updated
Please check here [https://www.figma.com/file/EXIHjZ0cvbAmYlzBcIbiDW/Accessibility-Updates-for-Namma-Yatri?type=design&node-id=1-3142&mode=design&t=C2LdWyJ3O6tBXKyj-4](url)
