### ISSUE TITLE
14/09/23_NYP_Android_Go To_Accept Go To and Go To tag need to be in app specific language_Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3193]
#1980 

[Accept Go To and Go To tag need to be in app specific language ](https://drive.google.com/file/d/17J0-4FiKp3PEGg3cC5g37aRnTBR3axci/view?usp=sharing)

Steps-
1. Log in to app
2. Choose any language other than English
3. Activate Go To
4. Observe the Ride request pop up

Expected-
The Accept Go To and Go To tag should be in app specific language 

Actual-
It is in English only

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine.
