### ISSUE TITLE
14/09/23_NYP_Android_Go To_Go Home should come to pop up instead of Ok Got it when 30 min time is over_Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3195]
#1980 

[Go Home should come to pop up instead of Ok Got it when 30 min time is over](https://drive.google.com/file/d/17QG5yJKKE-VKezOtM-4s9e9MVzi9g9wu/view?usp=sharing)

Steps-
1. Log in to app
2. Active Go To
3. Wait for 30 min

Expected- 
Go Home is expected instead of Ok Got it on pop up received after 30 min time over of Go to

**Comment by Rohit4997** [comment]
Needs to be updated in figma

**Comment by Sumedh-14** [comment]
Design is updated in the figma as well as "ok Got it". Hence closing the issue, 

https://drive.google.com/file/d/1Pecmsx3lhK-1JyEjpHpaGaVM2sGIYG8S/view?usp=sharing

Figma attachment, 

<img width="219" alt="Screenshot 2023-10-03 at 8 35 08 PM" src="https://github.com/nammayatri/nammayatri/assets/60838760/c539d5d0-bd54-4d34-a883-b65455933ac5">
