### ISSUE TITLE
14/09/23_NYP_Android_Go To_Cancel prevention pop up is not as per figma _Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3197]
#1980 

[Cancel prevention pop up is not as per figma. Buttons should be Cancel anyway and Go back](https://drive.google.com/file/d/17Qqy2vpqqKAyQQWClJ-UHviFcdwmpSfF/view?usp=sharing)

Steps-
1. Log in to app
2. Accept Go To ride
3. Click on Cancel ride from driver side

Expected-
Cancel anyway and Go back buttons are expected as per figma

Actual-
Continue and Go Back buttons are given

**Comment by Rohit4997** [comment]
Design will be modified.

**Comment by AlluGowthami28** [comment]
@Prithivirajkota Can you please confirm which design is final one.

**Comment by rohanrp179** [comment]
Closing this as no much clarity on this part
