### ISSUE TITLE
<14/09/2023><NYP><PurpleRides><Ride list is showing empty and also date is showing in tamil language>(Parent_Id - 1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3206]
#1980 
[
Ride list is showing empty and also date is showing in tamil language even driver selected english language ](https://drive.google.com/file/d/1ckN4YuEpyHdKCC_a1MM_BGS43uHY8CP5/view?usp=sharing)

**Steps**:
1. Launch apk
2. Click on rides
3. verify completed rides
4. Click on date 
5. Select previous date
6. Again select today’s date
7. Verify rides

**Actual**: Rides are showing empty and also dates are showing in tamil language

**Comment by MercyQueen** [comment]
fixed.

**Comment by Vinaykm999** [comment]
Working fine
