### ISSUE TITLE
<14/09/2023><NYP><PurpleRides><Chat popup is not as per figma for blind user>(Parent_Id - 1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3207]
#1980 

Chat popup is not as per figma

**Steps**:
1. Launch the apk
2. Assign the blind disability ride
3. Click on Chat icon
4. verify the popup

**Actual**: Popup is showing call to customer CTA
**Expected** : It should show got it as per figma

<img width="1161" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/e5d9de36-f490-4714-971b-79f91b461d67">
<img width="929" alt="Screenshot 2023-09-14 at 9 01 39 PM" src="https://github.com/nammayatri/nammayatri/assets/131981246/4e69a28f-f026-49d3-85cc-c5693cfdcdd5">

**Comment by MercyQueen** [comment]
Fixed.
