### ISSUE TITLE
<14/09/23><NYP><Android><PurpleRide><In ride request pop-up accessibility ride tag is not language specific><parent id 1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3208]
#1980 
[In ride request pop-up accessibility ride tag is not language specific](url)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Observe the accessibility tag in ride request popup

Expected Result
driver should get that tag in driver selected langauge.

Actual result
Driver is not getting in specific langauge.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
