### ISSUE TITLE
15/09/23_NYP_Android_Go To_After ride cancellation, the Go To count is not reducing _Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3215]
#1980

[When driver cancel 3 times back to back Go To rides, his Go To is not becoming 0.](https://drive.google.com/file/d/18ceDJkd9q74mK1muU576kWpXRoiWLYYr/view?usp=sharing)

Steps-
1. Log in to app
2. Assign a Go To ride and cancel for 3 times consecutively from driver end (All 3 Go To Ride Cancellation)

Expected-
As first cancellation is buffer, for next to Go To rides cancellation , the count should become zero

Actual-
The count is becoming zero to 4th Go To ride cancellation

**Comment by Rohit4997** [comment]
It will be shown after 2 back to back cancellations
For more info Please check whit @ratnadeep-99

**Comment by rohanrp179** [comment]
closing as this is expected
