### ISSUE TITLE
15/09/23_NYP_Android_Go To_After Go To count becomes zero, the required pop up is not shown _Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3216]
#1980 

[When Go To count becomes zero, the below pop up is not shown](https://drive.google.com/file/d/18rsi2cznpUySviGo-VNvEfIv9NORpOEk/view?usp=sharing)

Steps-
1. Log in to app
2. (When Go To count remaining is 1) Cancel Go To Ride from driver side so Go To count will become zero

Expected-
<img width="508" alt="Screenshot 2023-09-15 at 3 37 29 PM" src="https://github.com/nammayatri/nammayatri/assets/138564517/d7f2a2f2-7c4c-4d94-ad4f-dffed7275a43">

Actual-
No Pop up is shown or taking too much time to show the pop up

**Comment by Rajaprabhu-Natrajan** [comment]
Reopen the issue:- 

1. "Try again tomorrow" text is not displayed in the pop up.
2.  Zero text is should display as numeric value '0'


![Image](https://github.com/nammayatri/nammayatri/assets/134508712/9cf88b70-6040-4a63-817f-2776be75de80)
