### ISSUE TITLE
<15/09/23><NYP><Android><Go To><Go-To locations left : 3 - showing wrong in kannada font><Parent id 1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3218]
#1980 
Go-To locations left : 3 - showing wrong in kannada font

Steps:
1. Launch the driver apk
2. Change language to kannada
3. Click on settings
4. Click on Go To Location 
5. Verify Go - To location left : 3 in kannada

Expected: It should get change

<img width="528" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/870c1fb5-0cd2-4485-949c-f968fef89c79">

**Comment by Rohit4997** [comment]
@Vinaykm999  Please give correct translation here?

**Comment by Rajaprabhu-Natrajan** [comment]
Still this issue
Kannada translate should be ---> ಉಳಿದಿರುವ ಗೋ-ಟು ಸ್ಥಳಗಳು :(number)

**Comment by AlluGowthami28** [comment]
Issue fixed
