### ISSUE TITLE
15/09/23_NYP_Android_Go To_Title is missing and font size is smaller than shown in figma _Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3219]
#1980 

Title is missing and font size is smaller than shown in figma

Steps-
1. Activate Go To
2. Wait for 30 min to get the pop up

Expected-
The pop up should have title and should have font same like figma

Actual-
The pop up has not title and font is smaller than figma design

![Screenshot_20230915-155156](https://github.com/nammayatri/nammayatri/assets/138564517/611d9956-c967-4fd3-b042-30542d388a9d)

**Comment by Sumedh-14** [comment]
Validated the above issue in the APK shared on Oct 3. The issue is fixed. 

PFA below, 
https://drive.google.com/file/d/1Pecmsx3lhK-1JyEjpHpaGaVM2sGIYG8S/view?usp=sharing
