### ISSUE TITLE
<15/09/23><NYP><Android><Go To><"Report Issue" text and "Go-to" text is not translated to the selected language><Parent id 1980>

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3224]
#1980 
["Report Issue" text and "Go-to" text is not translated to the selected language](https://drive.google.com/file/d/13U3d-z2E5proS2oHcchDBF3NVKJg9OGh/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials 
2. Change the language from english to some other language
3. Come to home screen and observe 

**Expected Result**
All the text content should be changed to the selected language 

**Actual Result**
Texts in the goto icon and issue report icons are displaying in english

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
