### ISSUE TITLE
<14/09/23><NYP><Android><Go To><Removed spelling is wrong in remove go to feature><Parent id 1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3226]
#1980 
Removed spelling is wrong in remove go to feature

**Steps**:
1. Enable goto feature
2. Delete go to location, when go to is not active
3. Verify toast message

**Actual**: Removed spelling is wrong
<img width="855" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/d7fc35ce-eadd-4fe0-9ba1-3299948be8e4">

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
