### ISSUE TITLE
<15/09/23><NYP><Android><Go To><"Enable Go-To" text and "know more" option is not displaying in the Go-To locations screen><Parent id 1980>

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3232]
#1980 
["Enable Go-To" text is not displaying in the "Go-To" locations screen when the language is selected as tamil](https://drive.google.com/file/d/1fWIRLF5smOdexu4Y6rfWes7bKBt2CRvd/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials 
2. Select the language as tamil 
3. Tap on "go-to" icon and observe the screen 

**Expected Result**
All the text content should display 

**Actual Result**
"Enable Go-To" text and "know more" option is not displaying in the Go-To location screen

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine.
