### ISSUE TITLE
15/09/23><NYP><Android><Go To><When a "go-to" location is removed, then the toast message which is displaying is translated wrongly in tamil><Parent id - 1980>

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3234]
#1980 
[When a "go-to" location is removed, then the toast message which is displaying is translated wrongly in tamil](https://drive.google.com/file/d/1OP3ok1zDOTMC-A1crSrDiPtArtVqddHZ/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with valid credentials and change the language to tamil
2. Go to driver profile > Go-to locations 
3. Remove any added go-to locations

**Expected Result**
The toast message should be translated correctly

**Actual Result**
The toast message is not translated correctly

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine.
