### ISSUE TITLE
<15/09/23><NYP><Android><Go To><When adding the Go-To location, "Home" tag name is not translated correctly in tamil><Parent id 1980>

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3237]
#1980 
[When adding the Go-To location, "Home" tag name  and  "Add tag" text is not translated correctly in tamil](https://drive.google.com/file/d/1UU8UZy-N-fL0z8QPdv0Dh3uEuaOtZ2A9/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with valid credentials 
2. Change the language to "tamil" 
3. Go to driver profile > Go-To locations > Select any location via current location or select location on map option 
4. Observe the issue in the adding locations in "Go-to location" screen 

**Expected Result**
"Home" tag and "add tag" text should be translated correctly in tamil. 

**Actual Result**
"Home" tag name and "add tag" text is not translated correctly

**Comment by Rohit4997** [comment]
This is coming from backend

**Comment by Rajaprabhu-Natrajan** [comment]
This issue is still existing. Kindly assign to concern developer

Home should be translated to "இல்லம்"
Add Tag should be translated to "குறியீடு சேர்க்கவும்"

**Comment by Rohit4997** [comment]
> This issue is still existing. Kindly assign to concern developer
> 
> Home should be translated to "இல்லம்" Add Tag should be translated to "குறியீடு சேர்க்கவும்"

@Rajaprabhu-Natrajan  Here the tag is also a part of information sharing from frontend to backend.
Iike the address can't be translated to any language. It is different from customer side tag.

"குறியீடு சேர்க்கவும்" This I have fixed

**Comment by Sumedh-14** [comment]
@Rohit4997 validated the above fix in the APK shared on Oct 3. As mentioned, the "add tag" text issue is fixed.
 But for the text "Home" it is not translated correctly. 
 The text "Home" should be translated as "இல்லம்". "முகப்பு பக்கம்" is not the proper word for "home" tag name. 
 
 If the "home" text is from backend. @ratnadeep-99 Can you look into this issue? 
 
 PFA below, 
 
 https://drive.google.com/file/d/1OlgChwOsAfGVRFK6iO9bi6DF-OXf4-XG/view?usp=sharing

**Comment by Rohit4997** [comment]
@Sumedh-14  Home can not be translated
