### ISSUE TITLE
26/09/23_NYP_APK_Go-To_Go-To location name is not properly translated in kannada_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3390]
#1980 
[Go-To location name is not properly translated in kannada](https://drive.google.com/file/d/1RVqqK1ooQlrGHbVVIy4dDglMgQE7OHn3/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Go to driver profile--Settings.
3.The Go-to locations tag is not correct in kannnada language.

Actual Result
it should translate properly

Expected Result
It is not transalating properly.

**Comment by Rohit4997** [comment]
@krupal-14  Can you give the correct translation for this ?

**Comment by AlluGowthami28** [comment]
Issue Resolved.
