### ISSUE TITLE
26/09/23_NYP_APK_Go-To_Adding go-to location screen layout is not correct_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3391]
#1980 
[Go-To_Adding go-to location screen layout is not correct](https://drive.google.com/file/d/1YuLp8f3srfBc0eGqLmhVNxx5UlLn-m6-/view?usp=sharing)

Steps To reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Navigate to driver profile-->setting
4.Change the language to kannada.
5.Click on go-to location
6.Click on add go-to location.
7.Observe the screen.

Expected Result
Screen layout should be proper.

Actual Result
Screen layout is not proper.

**Comment by AlluGowthami28** [comment]
Issue fixed
