### ISSUE TITLE
27/09/23_YSP_Android_Jatri sathi name is shown instead of yatri sathi_2096

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3405]
#2096

Jatri sathi name is shown instead of yatri sathi on ride completed screen for driver

![Screenshot_2023-09-27-14-37-51-805_in juspay jatrisaathidriver debug](https://github.com/nammayatri/nammayatri/assets/138564517/17b5266a-fddd-4fee-a3fb-c55722b38e86)

**Comment by MercyQueen** [comment]
Fixed.
