### ISSUE TITLE
05/10/23_NYP_Android_Go To_When 'Home' keyword is auto filled, 'H' should be upper case _Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3496]
#1980 

When 'Home' keyword is auto filled, 'H' should be upper case 

Steps-
1. Log in to app (Note- No Go To location is saved as Home label)
2. Try to add any location.

Expected-
When Home text is auto filled the 'H' should be upper case

Actual-
'h' is lower case

https://github.com/nammayatri/nammayatri/assets/138564517/83c52562-cdab-4ab0-9baf-95de5c12cd22

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine.
