### ISSUE TITLE
05/10/23_NYP_Android_Go To_When Go To is disabled due to cancellation, after completing 30 min Validity expired pop up is shown _Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3500]
#1980 

[When Go To is deactivated due to cancellation, after completing 30 min of Go To activation Validity expired pop up is shown as usual](https://drive.google.com/file/d/1Cj4ai2_Ylmh2NXeWxUMxaxblahhAnB_g/view?usp=sharing)

Steps-
1. Activate Go To
2. Cancel two rides so that Count will be reduced and Go To will be disabled
3. Once 30 min of Go To activation is over, validity expired pop up is shown

Expected-
Validity Expired pop up should not come when Go To is disabled due to cancellation 

Actual-
The pop up is shown once 30 min gets over

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
