### ISSUE TITLE
06/10/23_NY_iPA_While autosuggestions are searched, the loader is cropped _Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3515]
#1980 

1. While autosuggestions are searched, the loader is cropped
2. Line b/w Select on map and Current location

Steps-
1. Log in to app
2. Search for a ride

Expected-
1. The loader should not be cropped
2. The line between Select on map and current location should be complete

Uploading RPReplay_Final1696599915.MP4…

**Comment by krupal-14** [comment]
The line between Select on map and current location should be complete.
This issue is still there so reopening.

**Comment by ashkriti** [comment]
fixed
