### ISSUE TITLE
06/10/23_NY_iPA_Height alignment is not as per figma for location denied pop up _Parent Id - 1980 

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3516]
#1980 

Height alignment is not as per figma for location denied pop up

Steps-
1. Login to app for first time after installaion
2. Deny location permissions 

Expected-
The height and width should be as per figma

![IMG_0137](https://github.com/nammayatri/nammayatri/assets/138564517/91c03a91-2ec3-4815-a9d3-79bf01f6bb19)

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
