### ISSUE TITLE
06/10/23_NY_iPA_Auto icon is missing on ride OTP screen_Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3517]
#1980 

Auto icon is missing on ride OTP screen

Steps-
1. Log in to app
2. Assign a ride

Expected-
Auto icon should be visible

![IMG_0139](https://github.com/nammayatri/nammayatri/assets/138564517/16cdc460-0f37-4e3f-b956-a91eba7b7913)

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
