### ISSUE TITLE
06/10/23_NY_iPA_Contact support icon is missing on Ride completed screen_Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3519]
#1980 

Contact support icon is missing on Ride completed screen

![IMG_0142](https://github.com/nammayatri/nammayatri/assets/138564517/8144f0ed-cdac-4c5d-a755-04d1bb8814d7)

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
