### ISSUE TITLE
06/10/23_NY_iPA_While saving favourites, if for the first time we open app and use Select on map, map is not properly zoomed in_Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3521]
#1980 

[While saving favourites, if for the first time we open app and use Select on map, map is not properly zoomed in](https://drive.google.com/file/d/1ePG6OwShWo9BCg4CWbancnTyg-TsoMSx/view?usp=sharing)

Steps-
1. Open app freshly(App should not be open before opening)
2. Try to save favourites using Select on map

Expected-
The map should be properly zoomed

Actual-
The map is not properly zoomed in

**Comment by S-PRAVINKUMAR** [comment]
@dhruvSHA256  can you check this

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
