### ISSUE TITLE
06/10/23_NY_iPA_When user is cancelling the ride, Call driver pop up is not shown_Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3524]
#1980 

[When user is cancelling the ride, Call driver pop up is not shown](https://drive.google.com/file/d/18_TqkwOM9ykVRgmEjU0RLi1YWCO0xlci/view?usp=sharing)

Steps-
1. Log in to app
2. book a ride
3. Cancel the ride

Expected-
When clicked on cancel, the call driver pop up should come

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine
