### ISSUE TITLE
06/10/23_NY_iPA_Auto icon is missing in map tracking before and after ride start_Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3528]
#1980 

Auto icon is missing in map tracking before and after ride start

Steps-
1. Log in to app
2. Book a ride
3. Observe before and after starting the ride

Expected-
The auto icon should be shown 

![IMG_0146](https://github.com/nammayatri/nammayatri/assets/138564517/4adafef3-9c77-4b7e-b255-70d68a3ac7c0)

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
