### ISSUE TITLE
10/10/23_NYP_Android_Profile Image_ Blocker Issue-- Capture of Selfie is not happening & not navigating to next expected screen_Parent Id - 1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3571]
#1980 
**Describe the bug**
--Capture of Selfie is not happening & not navigating to next expected screen

**To Reproduce**
- Launch the application
- Tap on nudge mark/tap on profile icon
- give the permission
- try to take selfie and observe the issue

**Expected behavior**
- Selfie should be taken and user should navigate to expected screen depending on Selfie(valid/invalid)

**Screenshots**
https://drive.google.com/file/d/1cd6tCuQI2B6qKDhRvUIqIQtguxOe18oK/view?usp=sharing

**App (please complete the following information):**
 - Device: Mi , Oppo A3s
 
 - Version Android 9

**Additional context**
happened in Android version <10

**Comment by rohanrp179** [comment]
working fine. Checked in android 8.1
