### ISSUE TITLE
10/10/23_NYP_Android_Profile Image_In Rdemi devices white screen is displaying when driver trying to take selfie _Parent Id - 1980

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3572]
(In Rdemi devices white screen is displaying when driver trying to take selfie)[https://drive.google.com/file/d/1FLHBmnv0j9N-93bPZS83cUwHUkFZYNel/view?usp=sharing]

Step to reproduce:-
1. Launch the app
2. Click on profile icon in home page
3. Click on profile image.
4. Camera screen is displaying white 
Note - It's only happening on redmi device

Video reference - https://drive.google.com/file/d/1FLHBmnv0j9N-93bPZS83cUwHUkFZYNel/view?usp=sharing

**Comment by Rohit4997** [comment]
Need to check for the specific device
