### ISSUE TITLE
10/10/23_NYP_Android_Profile Image_a. Once denying the permission, it is on the same screen only; b. Trying to take again selfie, it is not asking permission again_Parent Id - 1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3574]
#1980 

**Describe the bug**
a. Once denying the permission, it is on the same screen only.
b. Trying to take again selfie, it is not asking permission again.

**To Reproduce**

**Expected behavior**
a. should navigate back to Previous profile screen.
b. should show pop up of permission again

**Screenshots**
https://drive.google.com/file/d/1ixvVIEY90728dG-L4JkA3207RhWG28w2/view?usp=sharing

**App (please complete the following information):**
 all devices

**Additional context**

**Comment by Rohit4997** [comment]
Fixed

**Comment by rohanrp179** [comment]
When denied permission second time, it does not allow to take selfie. Only way out is to clear storage or reinstall the app. Expected ?
@Rohit4997

**Comment by Rohit4997** [comment]
> When denied permission second time, it does not allow to take selfie. Only way out is to clear storage or reinstall the app. Expected ? @Rohit4997

@rohanrp179  android do not ask permission if you deny 2 or more than 2 times

**Comment by rohanrp179** [comment]
Ok. Closing the issue
