### ISSUE TITLE
10/10/23_NYP_Android_Profile Image_In Samsung galaxy A51 device taking to much time to upload _Parent Id - 1980

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3579]
(In Samsung galaxy A51 device taking to much time to upload )[https://drive.google.com/file/d/1QVRDmbVwqhlG34yxFC4lSYFaIsR7sp6V/view?usp=sharing]

Step to reproduce:-
1. Launch the app
2. Click on profile in Home page
3. Take selfie on Samsung device 
4. After click on capture button
5. It's take 5 to 6 secs to Capturing the image 

https://drive.google.com/file/d/1QVRDmbVwqhlG34yxFC4lSYFaIsR7sp6V/view?usp=sharing

**Comment by Rohit4997** [comment]
Added loader

**Comment by Sumedh-14** [comment]
Working fine
