### ISSUE TITLE
10/10/23_NYP_Android_Profile Image_Driver is getting old captured image when current captured image upload fails _Parent Id - 1980

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3580]
Driver is getting old captured image when current captured image upload fails[https://drive.google.com/file/d/11M4NuxYA9d0SC8MO6C8tyLlVFGUS2nyA/view?usp=sharing]

Step to reproduce:-
1. Launch the app
2. Click on profile in home screen
3. Upload profile picture 
4. Got verification failed screen
5. Click back button or arrow
6. Then click profile again
7.  Click on Capture button again
8.  pervious error screen is displayed

video reference - https://drive.google.com/file/d/11M4NuxYA9d0SC8MO6C8tyLlVFGUS2nyA/view?usp=sharing

**Comment by rohanrp179** [comment]
Fixed. Closing it
