### ISSUE TITLE
10/10/23_NYP_Android_Profile Image_Capture Images are storing in local storage is this expected? _Parent Id - 1980

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3581]
Captured Images are storing in local storage is this expected?

Step to reproduce:-
1. Launch the app
2. Click on profile 
3. Click on profile upload
4. Click on capture button
5. Click back without upload the image
6. That images are stored in the local storage
Is it expected?

**Comment by AlluGowthami28** [comment]
Working as expected.
