### ISSUE TITLE
13/10/23_NYP_Android_GOTO_Add_Go To_location count is displayed wrong _Parent Id - 1980

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3635]
[Android_Add_Go To_location count is displayed wrong](https://drive.google.com/file/d/1McjnPycvEYhimYItxgQh_yy22Z9Z-HyP/view?usp=sharing)

Step to reproduce :-
1. Launch the app
2. Click on profile 
3. Click on setting icon
4. Click on Add Goto location
5. Remove goto location 
6. Then Add goto location
7.   Observed the issue.

Actual result - Remaining count is displayed wrong
Result result - Remaining goto location count should display correctly

**Comment by Rohit4997** [comment]
@Rajaprabhu-Natrajan  Not able to reproduce

**Comment by rohanrp179** [comment]
No further advancement
