### ISSUE TITLE
13/10/23_NYP_Android_GOTO_In Clear Due popup , some code text are displayed_Parent Id - 1980

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3636]
Clear Due popup , some code text are displayed(https://drive.google.com/file/d/19Vac1Gk1Pc6HPjwRL0bOAeiQBpT1tXUZ/view?usp=sharing)

Step to reproduce:-
1. Launch the application
2. log in with due pending account
3. Clear due pop up is displayed
4. Observe the issue 

Actual result - Code text are displayed.
Expected - Unwanted code text should not displayed. Should display content as per figma

**Comment by Rohit4997** [comment]
@Rajaprabhu-Natrajan this issue is already reported in current release testing APK
 Can you link this issue to that ?
