### ISSUE TITLE
13/10/23_NYP_Android_GOTO_Cancellation popup- Cancellation text spelling is wrong_Parent Id - 1980

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3639]
GOTO_Cancellation popup- Cancellation text spelling is wrong(https://drive.google.com/file/d/1qpnAb5olLcnZQoypD8F33COfLH3vM3at/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Book the ride with goto
3. Click cancel ride from driver side
4. Goto reduce popup is displayed
5. observe the issue
Actual - Cancellation text spelling is wrong
Expected - Cancellation text spelling should display correctly

**Comment by Rohit4997** [comment]
@Rajaprabhu-Natrajan  This is as per figma
