### ISSUE TITLE
13/10/23_NYP_Android_Go-To_ Still Go-To rides left pop-up okay button is not properin kannada language _Parent Id - 1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3640]
#1980 
[Still Go-To rides left pop-up okay button is not proper in kannada language](https://drive.google.com/file/d/1M8vYRkzEKYChHi799KWZP8TDtB2_QP4p/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Take a Go-To ride & complete it.
4.Observe the pop-up in kannada.

Expected Result
 Text should be proper in kannada

Actual Result
Text is proper in kannada.

**Comment by Rohit4997** [comment]
@krupal-14  Give Kannada translations then
