### ISSUE TITLE
<16/10/23><NY><Android><Home page - Scroll up & down empty black screen is displayed<Parent id 1980>

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3671]
[Home page - Scroll up & down empty black screen is displayed](https://drive.google.com/file/d/16AMPxWhi_hUvpgf2VN_pEZVw3lited34/view?usp=sharing)

Step to reproduce:-
1. Launch the app
2. Scroll Up & down the screen 
3. Black screen is displayed on top of the screen
4. And space between "Where to ?" and "pickup: Current Location " is not as per figma.

![Image](https://github.com/nammayatri/nammayatri/assets/134508712/20e79cc1-32e4-46d4-a6dd-644765b74ec3)

Actual result - After scroll up & down NY logo and some other things are not displayed. and space between "where to" and "pickup" is not as per figma

Expected result - After scroll up & down the home page content should display properly.And "where to" and "pickup" should as per figma

Device - Redmi Note 7

**Comment by Vinaykm999** [comment]
Working fine
