### ISSUE TITLE
16/10/23_NY_Ridesearch_Android_Location recenter icon is missing in homescreen(Parent_Id - 1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3674]
#1980 

[Location recenter icon is missing in homescreen](https://drive.google.com/file/d/1UBFz2WJiLZS5AytoJLpN1UvXakYPGLcE/view?usp=drive_link)

**Steps to reproduce**
1. Launch the application and login with valid credentials 
2. Observe the homescreen

**Expected Result**
All the assets should display as per figma

**Actual Result**
Location Recenter icon is missing in homescreen

**Comment by aryan-13** [comment]
Fixed

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
