### ISSUE TITLE
16/10/23_NY_IPA_RideSeach_ Pickup locatuion green dot is not according to figma_parent-id_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3680]
#1980
[Pickup location green dot is not according to figma](https://drive.google.com/file/d/157vWYCN4KIdVZCyyelD43suTXpUaBlEX/view?usp=sharing)

Steps To Reproduce
1.Launch the ipa & observe

Expected Result
Pick up location pointer should be according to figma

Actual Result
Pick up location pointer is not according to figma.

**Comment by aryan-13** [comment]
Expected

**Comment by krupal-14** [comment]
Retested,Working fine
