### ISSUE TITLE
16/10/23_NY_IPA_RideSeach_ Welcome to Namma Yatri text is missing as per figma_parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3681]
#1980 

Text is missing as per figma
1. Your suggested destinations and recent rides sentece should be completely seen
2. #beopen #choose opoen text missing

![IMG_0151](https://github.com/nammayatri/nammayatri/assets/138564517/b116ed8f-28be-45a4-bd31-c122bfec10e1)

**Comment by aryan-13** [comment]
Expected

**Comment by krupal-14** [comment]
Retested,Working fine
