### ISSUE TITLE
<16/10/23><NY><Android><Tip option is not coming after 30 seconds and also for try again <Parent id 1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3684]
#1980 
[Tip option is not coming after 30 seconds and also for try again 
](https://drive.google.com/file/d/1vMqV0VX84BWMDww-B_7bYWSG7dst2MVv/view?usp=sharing)
Steps:
1. Search  for a ride
2. wait for 30 second
3. Verify tip option
4. Wait same ride search till try again popup 
5. verify tip with try again

Actual: Tip option is not showing for try again as well after 30 sec of ride

**Comment by aryan-13** [comment]
@Anuragini-2506 Please update here once this is resolved

**Comment by Anuragini-2506** [comment]
fixed

**Comment by Vinaykm999** [comment]
Working fine
