### ISSUE TITLE
16/10/23_NY_Android_Home Screen_The Home screen design not as per figma(Parent_Id - 1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#3685]
#1980
1. Current location assert colour is different from figma
2. Padding is more between Current location and where to layouts
3. Recenter is missing 
4. Bottom layout is different 
5. Welcome to Namma yatri sub text should be title case.

![Screenshot_20231016-133300_Namma Yatri](https://github.com/nammayatri/nammayatri/assets/139038923/6c75bafb-2fc1-48fb-9b4d-85822be479b0)

**Comment by aryan-13** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Working as expected.
