### ISSUE TITLE
16/10/23_NY_IPA_RideSeach_ There is unexpected gap bw Pickup and where to tabs_parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3687]
#1980 

There is unexpected gap bw Pickup and where to tabs

![IMG_0153](https://github.com/nammayatri/nammayatri/assets/138564517/f1f3296d-7d3e-47f6-976a-90a114c1accf)

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
