### ISSUE TITLE
16/10/23_NY_Android_Home Screen_Complete your profile banner is not coming for incomplete profile user(Parent_Id - 1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#3689]
#1980
[Complete your profile banner is not coming for incomplete profile user](https://drive.google.com/file/d/1fSIXsfADDfA5syWTf3uviSIYpVON4hvp/view?usp=sharing)

**Expected Result** 
Banner should come for incomplete user.

**Actual Result**
Complete your profile banner is not coming for incomplete profile user

**Comment by aryan-13** [comment]
Disability banner is the current one being displayed, if it is not filled then it'll be visible. There is no complete your profile banner as of now.
