### ISSUE TITLE
16/10/23_NY_IPA_RideSeach_ While scrolling down, there is white gap at end which is not moving_parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3691]
#1980 

While scrolling down, there is white gap at end which is not moving

https://github.com/nammayatri/nammayatri/assets/138564517/ae54abc0-cff0-441d-95d9-45af37ec5eae

**Comment by aryan-13** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,working fine
