### ISSUE TITLE
16/10/23_NY_IPA_RideSeach_ Auto assigne and choose multiple drivers radio buttons are taking time to select_parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3692]
#1980

[Auto assign and choose multiple drivers radio buttons are taking time to select](https://drive.google.com/file/d/10tw2e86F3v4S9SMoIqF4m5nMq7sZVr5b/view?usp=sharing)

**Comment by aryan-13** [comment]
@S-PRAVINKUMAR Can you updated this issue once its fixed

**Comment by krupal-14** [comment]
Retested,Working fine.
