### ISSUE TITLE
16/10/23_NY_ANDROID_RideSeach_Margin is more b/w Current location and Where to? banner_parent-id_1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3693]
#1980 
**Describe the bug**
Margin is more b/w Current location and Where to? banner. 

**To Reproduce**
Launch the Application 
Drag down the screen 
observe the issue 

**Expected behavior**
as per figma

**Screenshots**
![margin](https://github.com/nammayatri/nammayatri/assets/128033831/a5109f3c-5f03-4577-b732-486da967ad05)

**App (please complete the following information):**

**Additional context**

**Comment by krupal-14** [comment]
Retested,Working fine
