### ISSUE TITLE
16/10/23_NY_Android_RideSeach_Tapping on Where to Takes Time to navigate to Ride search Screen (Vivo) Android Issue _parent-id_1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3694]
#1980 
**Describe the bug**
Tapping on Where to Takes Time to navigate to Ride search Screen (Vivo)

**To Reproduce**
-open the application
- Tap on where to and observe the time

**Expected behavior**
Should navigate to RideSearch Screen without delay

**Screenshots**
https://drive.google.com/file/d/1BnipREiEmGaniJ7FxtVsHIExepvytO_q/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by aryan-13** [comment]
Fixed

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1cQcAgNYA05GbTz2-alm3ptE0CBDianOB/view?usp=sharing

taking less now so marked it as Done.
