### ISSUE TITLE
16/10/23_NY_IPA_RideSeach_ The auto image is of yatri shown in cancel prevention pop up _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3695]
#1980 

The auto image is of yatri shown in cancel prevention pop up. It should be yellow and green

![IMG_0156](https://github.com/nammayatri/nammayatri/assets/138564517/c2f471a7-f547-4f22-af5f-ff8d1ae9f2e9)

**Comment by aryan-13** [comment]
@Anuragini-2506 Can you check and update this

**Comment by Anuragini-2506** [comment]
fixed

**Comment by krupal-14** [comment]
Still issue exist .moving it to backlog

**Comment by aryan-13** [comment]
Fixed
