### ISSUE TITLE
16/10/23_NY_Android_Home Screen_Current location and Hamburger are missing in home screen (Parent_Id - 1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#3696]
#1980 
[Current location and Hamburger is missing in home screen](https://drive.google.com/file/d/1z4y93rp8lbopHjQt5KCavaG4K2kHLc4L/view?usp=sharing)

**Step to reproduce**
1. Scroll up and down the screen and observe the pickup and Hamburger 

**Actual Result** 
Current location and Hamburger are missing in home screen

**Expected Result**
Current location and Hamburger should visible.

**Comment by aryan-13** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Working

**Comment by AlluGowthami** [comment]
Working fine.
