### ISSUE TITLE
16/10/23_NY_Android_RideSeach_Animation is not proper/ after Splash screen, validating White Screen for a while.(Vivo) 

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3698]
#1980 

**Describe the bug**
Animation is not proper/ after Splash screen, validating White Screen for a while.

**To Reproduce**
-Launch the application
-Validate the Splash screen
- Validate the WHite screen for a while

**Expected behavior**

**Screenshots**
https://drive.google.com/file/d/12jj-srOdHO94sMambHNQwPQYcJnU5wHc/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by aryan-13** [comment]
Fixed

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1d2V0pUitygJ7QKLzcIlHSbGM3LSWA9zh/view?usp=sharing

Re-opening , Please check once.
