### ISSUE TITLE
16/10/23_NY_IPA_RideSeach_ When keypad is open, the recent message cannot be seen _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3699]
#1980 

When keypad is open, the recent messages cannot be seen

https://github.com/nammayatri/nammayatri/assets/138564517/8944393b-ef8d-4aae-a97a-ceed1d2dd8c6

**Comment by aryan-13** [comment]
@PraveenGongada Can you check this

**Comment by PraveenGongada** [comment]
Mostly an issue in framework, anyway the design is changed, will be fixed in next release

**Comment by rohanrp179** [comment]
fixed in recent release
