### ISSUE TITLE
16/10/23_NY_Android_Ridesearch_In "select location on map screen" Pointer is not pointing out the "pickup locations", when the user moves the pointer anywhere in the special location (Parent_Id - 1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3700]
#1980
[In "select location on map screen" location Pointer is not pointing to the "pickup locations", when the user moves the pointer anywhere in the special location](https://drive.google.com/file/d/196E2ViEseiGOOGWRhHHFYo5I0Fy54Vyn/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials 
2. Tap on "where to" / "Pick up location", and tap "select location on map"
3. In map go to any special location (Ex: Nexus mall, koramangala) 

**Expected Result**
Whenever the pointer is within the shape file of any special location then, the location pointer should automatically point to the pickup locations. 

**Actual Result**
The location pointer is not pointing to the pickup locations.

**Comment by aryan-13** [comment]
Fixed

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine
