### ISSUE TITLE
<16/10/23><NY><Android><Home page - Suggested Destinations list are displayed after complete the ride"<Parent id 1980>

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3701]
[Home page - Suggested Destinations list are displayed after complete the ride](https://drive.google.com/file/d/1JyZSeVD8xpQFprr89ftrO3RRRsLjECRu/view?usp=sharing)

Step the reproduce:-
1. Launch the app
2. Complete one ride 
3. Recent rides list are displayed in the home screen
4. Click on Recent ride.
5. Click on Edit option 
6. Search the ride and cancel it 
7. Suggested Destination list are displayed in the home screen instead of Recent ride.

Expected - Recent ride list should be displayed.

**Comment by aryan-13** [comment]
Fixed

**Comment by Rajaprabhu-Natrajan** [comment]
it's working fine
