### ISSUE TITLE
16/10/23_NY_IPA_Android_Faster tag is missing in estimate screen for kannada language_parent-id_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3707]
#1980
[Faster tag is missing in estimate screen for kannada language](https://drive.google.com/file/d/1iUz6pPiP22R5QJeMAostaN9BRvaq6hAe/view?usp=sharing)

Steps To reproduce
1.Launch the ipa 
2.Assign a ride.
3.Observe the estimate screen.

Expected Result
Tag should be there.

Actual Result
Tag is not there

**Comment by aryan-13** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,working fine
