### ISSUE TITLE
16/10/23_NY_Android_Home Screen_Unable to select booking preferences (Parent_Id - 1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#3708]
#1980
[Unable to select booking preferences](https://drive.google.com/file/d/1dilTwfLTqrqAXd6HqLmjGHiBRmAUuzHo/view?usp=sharing)

**Steps to Reproduce** 
1. Select destination
2. Tap on Booking preferences 
3. Select "Choose between driver"

**Actual Result**
Unable to select booking preferences

**Expected Result**
We should be able to select booking preferences

**Comment by aryan-13** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Working
