### ISSUE TITLE
<16/10/23><NY><Android><IPA><"Requesting ride" and "tap here to top auto requesting" texts are not changing to kannada font <Parent id 1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3711]
#1980 
Both in android and iOS

[Requesting ride" and "tap here to top auto requesting" texts are not changing to kannada font ](https://drive.google.com/file/d/1BjmmUyyyl-P6dstdbhZMA8tag9z3-N0V/view?usp=sharing)

steps:
1. change language to kannada
2. Complete one ride first
3. Click on the recent search  for completed ride 
4. Verify Requesting ride and tap here to top auto requesting font

Actual: Fonts are showing in english

**Comment by aryan-13** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine
