### ISSUE TITLE
16/10/23_NY_IPA_RideSearch_ The red color ballon icon are smaller than figma design and hence showing more empty space around in recent search on home screen _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3713]
#1980

The red color ballon icon are smaller than figma design and hence showing more empty space around

![IMG_0160](https://github.com/nammayatri/nammayatri/assets/138564517/c2d2359e-bfde-40cf-8c2b-a634b4caf3a6)

**Comment by aryan-13** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine
