### ISSUE TITLE
16/10/23_NY_Android_Ridesearch_In pickup location field, previously selected location is displaying even after clearing the location (Parent_Id - 1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3714]
#1980
[In pickup location field, previously selected location is displaying even after clearing the location](https://drive.google.com/file/d/1hH8PQcXgdTbrHiBbHy-sTLnvcpw0EsWU/view?usp=sharing)

**Steps to reproduce**
1. Launch the application and login with valid credentials 
2. Tap on pickup location and clear the location using "x" icon and search for any other location 
3. Then again clear the location using "x" icon >> Tap on "where to" and observe the issue

**Expected Result**
The previously selected location should not display 

**Actual result**
The previously selected location is displaying

**Comment by aryan-13** [comment]
@ashkriti is this expected?

**Comment by ashkriti** [comment]
Yes this is expected, we added it so that the source should never be empty.

**Comment by Rajaprabhu-Natrajan** [comment]
This is not an issue confirmed with dev. so I closed this issue
