### ISSUE TITLE
16/10/23_NY_Android_RideSeach_a.Android: Auto Requesting screen should not have option of "Booking Preference"  b. Android: If user booked "Choose between multiple drivers" and than same ride he is going through "Auto requesting" , it is taking as Choose b/w multiple drivers automatically. c.  In Auto Requesting mode, Zooming out is more_Parent Id: 1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3717]
#1980 

**Describe the bug**
a.Android: Auto Requesting screen should not have option of "Booking Preference"  
b. Android: If user booked "Choose between multiple drivers" and than same ride he is going through "Auto requesting" , it is taking as Choose b/w multiple drivers automatically. 
c.  In Auto Requesting mode, Zooming out is more_

**To Reproduce**

**Expected behavior**
a. Auto Requesting screen should not have option of "Booking Preference"   as per Figma
b. Ride should always in Auto Assign
c. Zooming of Source and destination should be same like as Normal mode.

**Screenshots**
https://drive.google.com/file/d/1e-CrtIPi-qzwjhNRa54zZovhEVJ6Oz6k/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by aryan-13** [comment]
Fixed

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1sk9eJJjuvbgMNWwIRbg2Qu2CSQUFLw9b/view?usp=sharing
 

Working as expected. Hence marking it as Done.

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1sk9eJJjuvbgMNWwIRbg2Qu2CSQUFLw9b/view?usp=sharing

Working as expected. Hence marking it as Done.
