### ISSUE TITLE
16/10/23_NY_IPA_RideSearch_ Recently done rides should be shown on top of recent rides list _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3723]
#1980 

[Recently done rides should be shown on top of recent rides list ](https://drive.google.com/file/d/1O2dTTiHYrVcWWf6ZmJC8frclob-dg9E0/view?usp=sharing)

Steps-
1. Book few rides so that there should be recent ride list
2. Now book another ride and complete
3. Observe the recent ride list on home screen

Expected-
The recently done ride should be shown on top of recent ride list

Actual-
It is shown at bottom of list

**Comment by aryan-13** [comment]
It won't always be on top. It is based on the frequency and recency of the ride.
