### ISSUE TITLE
<16/10/23><NY><Android><Request Auto ride screen is not displayed properly after changing the language "<Parent id 1980>

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3724]
[Auto request ride screen is not displayed properly after changing the language](https://drive.google.com/file/d/1nN7Wv1t-xaRZfN9oAWS9n8M1Mn4X9wRG/view?usp=sharing)

Step to reprduce:-
1. Launch the app
2. Change the language hindi, Kannada or English
3. Click on recent ride on home screen 
4. Request Auto ride screen is not displayed properly

Expected - Request Auto ride should display properly.

Note - After kill and relaunch then it's working fine.

**Comment by aryan-13** [comment]
Fixed

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine.
