### ISSUE TITLE
16/10/23_NY_IPA_Auto icon is not following the polyline_parent-id_1980 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3729]
#1980
[Auto icon is not following the polyline](https://drive.google.com/file/d/1TqLknGKrb8hEGC5bThR7plbWIGlLhE_h/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride & try to simulate before and after ride started

Expected Result
Auto symbol should follow the polyline.

Actual result
Auto symbol is not not following the polyline.

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by krupal-14** [comment]
Retested,Working fine.
