### ISSUE TITLE
16/10/23_NY_Android_RideSeach_Glitch after tapping on Saved Location_Parent Id: 1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3731]
#1980 

**Describe the bug**
Getting a Glitch/screen after Tapping on Saved Location for Ride before rendering to Ride Search

**To Reproduce**
Save a location under Home or Work tag
validate the Home Screen
Tap on Saved Location
Observe the Issue before navigating to Ride Search Screen 

**Expected behavior**
User should directly navigate to Ride SEARCH SCREEN 

**Screenshots**
https://drive.google.com/file/d/1BWx91gjuiJ9cUoTA75CbL46jPbeZ7WAY/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by aryan-13** [comment]
Fixed

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1usKnHgyjcMul317Pn8CnBMc6_U3F2WA8/view?usp=sharing

Now having Loader , marking it as Fix and closing this issue.
