### ISSUE TITLE
16/10/23_NY_Android_The markers are not as per Figma_Parent Id: 1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3733]
We #1980 

**Describe the bug**
The markers are not as per Figma
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
<img width="353" alt="image" src="https://github.com/nammayatri/nammayatri/assets/128033831/9e3770cb-2849-4c95-870b-9285940da7d4">

**Screenshots**
![Screenshot_20231016_180854 (1)](https://github.com/nammayatri/nammayatri/assets/128033831/ef4c39b1-e341-472b-ab7c-6f9b65691326)

**App (please complete the following information):**

**Additional context**

**Comment by S-PRAVINKUMAR** [comment]
@aryan-13  fixed in map. but I don't have the latest code of estimates card. so I not fixed that.

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1IoRYC3NbIzMZ6k-W__0okaDV8Y7vXbDA/view?usp=sharing

Raised markers UI fixed so marking it close.
