### ISSUE TITLE
<16/10/23><NY><Android><Recent ride list is cleared after Edit the recent ride list <Parent id 1980>

### ISSUE THREAD

**Issue by Rajaprabhu-Natrajan** [nammayatri/nammayatri#3735]
[Recent ride list is cleared after Edit the recent ride list](https://drive.google.com/file/d/1YNdCC5jH5vUQgEjxl1LlIKvm4FIlgm6T/view?usp=sharing)

Step to reproduce:-
Case 1:-
1. Launch the app
2. You have 2 or more recent ride list
3. Click anyone and edit the destination 
4. Complete the ride 
5. Observe the issue 

Case 2:-
1. Launch the app
2. You have 2 or more recent ride list
3. Click anyone and edit the destination 
4. Cancel the ride
5. Suggestion destination is displayed
6.  Again try the ride search and completed the ride
7. Pervious recent ride list data are cleared 
8. Only latest ride is displayed in Recent ride 

Expected - Recent ride list should display properly

**Comment by aryan-13** [comment]
Fixed

**Comment by Rajaprabhu-Natrajan** [comment]
It's working fine
