### ISSUE TITLE
16/10/23_NY_Android_Ride Search_Tip is not coming in ride search screen_(Parent_Id - 1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#3739]
#1980 
[Tip is not coming in ride search screen](https://drive.google.com/file/d/1hr4ettTNFFUf2xGAPnCawW_-r5vqT4vb/view?usp=sharing)

**Steps to reproduce**
1. Search for a ride
2. Wait until 50sec and observe the ride search screen

**Actual Result**
Tip is not coming in ride search screen

**Expected Result**
Tip should come in ride search screen.

**Comment by aryan-13** [comment]
Fixed
