### ISSUE TITLE
<16/10/23><YSP><ANDROID><subscription flow><Parent_Id-2096>>Plan Screen not as per Figma, Under daily per Ride, offer description should be there as per Figma>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3744]
#2096 

**Describe the bug**
Plan Screen not as per Figma, Under daily per Ride, offer description should be there as per Figma>

**To Reproduce**
Tap on Plan
Do android back Screen 
Observe the My Plan Screen

**Expected behavior**
<img width="412" alt="image" src="https://github.com/nammayatri/nammayatri/assets/128033831/c9578c09-04bf-464c-bae9-2ca87c52da20">

**Screenshots**
![Screenshot_20231016_201439](https://github.com/nammayatri/nammayatri/assets/128033831/88800b4e-76b8-45ab-a71d-d39a28ee4660)

**App (please complete the following information):**

**Additional context**

**Comment by prakharritik** [comment]
Updated.

**Comment by rohanrp179** [comment]
closing
