### ISSUE TITLE
16/10/23_YSP_Android_Subscription flow_ When driver login to app and after clicking 3 times new tag goes, then if driver login with another number then New tag is not shown_parent-id_2096

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3745]
#2096 

[When driver login to app and after clicking 3 times new tag goes, then if driver login with another number then New tag is not shown.](https://drive.google.com/file/d/1UPDfXNNk-QqFyABgX-wl0ZCFMe70zpPT/view?usp=sharing)

Steps-
1. Login with new number
2. Click on plans icon 3 times to remove new tag
3. Now login with another new number

Expected -
For another number New tag should be shown

**Comment by rohanrp179** [comment]
[Now when same user if gone to payment page and done payment and autopay is set active, then if he login for next time, is is showing New tag. This is not expected ](https://drive.google.com/file/d/1YwBGuOVX2gQhDxkddgIq9E28RAj77bme/view?usp=sharing)
@prakharritik

**Comment by prakharritik** [comment]
Updated the changes

**Comment by rohanrp179** [comment]
working as expected.
