### ISSUE TITLE
<16/10/23><YSP><ANDROID><subscription flow><Parent_Id-2096>>Taking time to get the confirmation after giving the payment>Major

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#3751]
#2096 

**Describe the bug**
Taking time to get the confirmation after giving the payment>Major

**To Reproduce**
- Set up the mandate 
- Complete the payment
- Validate the User side Screen |
- Observe it is taking time to display the payment confirmation screen

**Expected behavior**
Should receive payment confirmation pop up with no delay

**Screenshots**
https://drive.google.com/file/d/1m73CPmkkCpJJgw8WQ092awWnQQcslJns/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by prakharritik** [comment]
Webhooks were not configured for master. That is why this issue happened.

**Comment by rohanrp179** [comment]
closing as this is not occurring in prod
