### ISSUE TITLE
17/10/23_NYP_Android_Pop-up_ Cancel & Call support button of end ride screen is  not properly aligned in kannada langauge. _parent-id_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3770]
#1980 
[Cancel & Call support button of end ride screen is  not properly aligned in kannada langauge.](https://drive.google.com/file/d/1ZXe5DcSFJQUbqgvqdKalr0ixdzBmPFKH/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride -->complete a ride
4.Click on support icon in end ride screen and observe

Expected Result
Alignment of that pop-up should be proper

Actual Result
Alignment is not proper

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by krupal-14** [comment]
Retested,working fine
