### ISSUE TITLE
<17/10/23><NY><Android><popup>Logout font is not properly visible, showing as log in kannada font<parent-id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3774]
#1980 

Logout font is not properly visible, showing as log in kannada font
Steps:
1. launch user apk
2. Login
3. Change language to kannada
4. Click on loggout
5. verify logout button font

Device: Realme X

**Actual**: Only log is showing in kannada font
**Expected**: it should be "ಲಾಗ್ಔಟ್"

![Screenshot_2023-10-17-12-54-48-86_88a774e4ba75b7addb8b842e78164a94](https://github.com/nammayatri/nammayatri/assets/131981246/c8c3ce43-a0f0-4e96-bcdd-03d55c25f5d6)

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by Vinaykm999** [comment]
Retested, working fine
