### ISSUE TITLE
18/10/23_YSP_Android_CUG_Subscription flow_Back press is closing the app_parent-id_2096

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3809]
#2096 

Back press is closing the app on Fare collected screen

https://github.com/nammayatri/nammayatri/assets/138564517/e0f14b65-5ed9-400c-98db-d3aa54248004

**Comment by prakharritik** [comment]
Fixed

**Comment by rohanrp179** [comment]
working fine
