### ISSUE TITLE
18/10/23_YSP_Android_CUG_Subscription flow_Show/Get QR code is not shown_parent-id_2096

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3811]
#2096 

Show/Get QR code is not shown under my profile section

Steps-
1. Open app and go to My profile section
2. QR code should be shown 

Expected-
QR should be shown

Actual-
It is not shown

https://github.com/nammayatri/nammayatri/assets/138564517/e3250ea3-731d-43a2-9f1b-6c710ff096ac

**Comment by prakharritik** [comment]
Fixed.

**Comment by rohanrp179** [comment]
working fine
