### ISSUE TITLE
18/10/23_YSP_Android_CUG_Subscription flow_padding should be there in pujo offer description text_parent-id_2096

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#3816]
#2096 
Padding should be there in pujo offer description text

**Steps to Reproduce** 
1. Launch the app
2. Tap on My plans
3. And observe the PUJO subtext

**Actual Result** 
Padding is not there in pujo offer description text

**Expected Result**
Padding should be there in pujo offer description text

![Screenshot_20231018-122006_Yatri Sathi Driver](https://github.com/nammayatri/nammayatri/assets/139038923/c361f6a3-71c8-4543-8036-fe42e1d217f1)

**Comment by prakharritik** [comment]
Fixed.

**Comment by rohanrp179** [comment]
working fine
