### ISSUE TITLE
18/10/23_YSP_Android_CUG_Subscription flow_Contact support option is not working_parent-id_2096

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3821]
#2096 

Contact support option is not working when payment is not competed and payment pending pop up is shown

Steps-
1. Initiate a payment via PSP app
2. Go to app but do not complete the payment
3. Come back to YSP app and payment pending screen will come

https://github.com/nammayatri/nammayatri/assets/138564517/68d48ae6-062a-49ce-aa80-c6ed765846f3

**Comment by prakharritik** [comment]
Fixed

**Comment by rohanrp179** [comment]
working fine
