### ISSUE TITLE
18/10/23_YSP_Android_CUG_Subscription flow> Payment failed screen is showing in payment page and in my plans screen both<parent-id_2096

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3825]
#2096

[Payment failed screen is showing in payment page and in my plans screen both](https://drive.google.com/file/d/1XiYZk8gApT5i7yfNgUZ6nSOHd3oCc9xA/view?usp=sharing)

Steps:
1. launch app
2. Request for autopay setup
3. Decline from PSP
4. verify failed message in Payment screen
5. Navigate back to my plans
6. Verify failed message 
![Screenshot_20231018_123438_Yatri Sathi Driver](https://github.com/nammayatri/nammayatri/assets/131981246/b463ed81-2f9e-41c5-8560-1b37f127ede6)

**Comment by prakharritik** [comment]
Expected as per [figma](https://www.figma.com/file/EsEdRFRBD2GCA0Rsxd62iu/Beckn-Subscriptions?type=design&node-id=12%3A42054&mode=design&t=fcO8GSRSalXx42xs-1)

**Comment by krupal-14** [comment]
Working fine,Closing the issue
