### ISSUE TITLE
18/10/23_NY_APK_LocateOnMap_Recenter function is taking more time to perform _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3836]
#1980 

[Recenter function is taking more time to perform](https://drive.google.com/file/d/1NvUfiJsDUvAFJ3gPfplbiumFtkQOK1fR/view?usp=sharing)

**Comment by aryan-13** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine.
