### ISSUE TITLE
18/10/23_NY_APK_LocateOnMap_While shifting from Source to destination , if we shift bw these two fields then both the addresses are coming same _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3839]
#1980 

[While shifting from Source to destination , if we shift bw these two fields then both the addresses are coming same. Also the ballon mark is not moving to selected position as expected. 
i.e. when we click Source, the ballon should move to source loc and when we click in destination then ballon should move to destination selected loc](https://drive.google.com/file/d/1mUCcWrherkBsaja4CD7SWJrhL28rMymp/view?usp=sharing)

**Comment by aryan-13** [comment]
Fixed, removed animating the pointer from source to destination for this release as it will require app update
