### ISSUE TITLE
18/10/23_NY_APK_LocateOnMap_The feature of 20m while choosing on map is not working while saving favourites using choose on map _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3840]
#1980 

The feature of 20m while choosing on map is not working while saving favourites using choose on map

https://github.com/nammayatri/nammayatri/assets/138564517/0f3ea38d-f67f-402e-bc32-e0244c33fb0e

**Comment by aryan-13** [comment]
Expected

**Comment by krupal-14** [comment]
Closing as discussed with dev
