### ISSUE TITLE
19/10/23_NY_iPA_Wrong toast message should displaying when user perform cancel search_Parent Id - 1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3858]
#1980 
[Wrong toast message should displaying when user perform cancel search](https://drive.google.com/file/d/1rv--20xvL2XAIjfSP6AEjHb6C0BIdHhl/view?usp=sharing)

Steps To reproduce
1.launch  the apk.
2.Login with valid credentials.
3.Select src & dest 
4.perform cancel search &observe

Expected results
Proper toast message should display

Actual result
Wrong toast message displaying

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by krupal-14** [comment]
Retested,Working fine
