### ISSUE TITLE
19/10/23_NY_iPA_Kannada font is not showing foe english language in language selection screen  <Parent_ID_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3860]
#1980 
Kannada font is not showing foe english language in language selection screen

Steps:
1. launch user ipa
2. Login with number
3. Click on hamburger menu
4. Click on language 
5. Verify english language 

Expected: below english text, kannada font should also show

![File (3)](https://github.com/nammayatri/nammayatri/assets/131981246/16d0e2a9-f58e-45a6-aedf-b43148270170)

**Comment by rohanrp179** [comment]
Closing it as this is fixed
