### ISSUE TITLE
19/10/23_NY_iPA_Thunder symbol is not displaying in estimate screen faster tag_Parent Id - 1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3861]
#1980 
[Thunder symbol is not displaying in estimate screen faster tag](https://drive.google.com/file/d/1o4pUWqIfTgk3nZHANvxCBSQMGNW60Dt9/view?usp=sharing)

Steps to Reproduce
1.launch the apk.
2.login with valid credentials.
3.Book a ride & observe the estimate screen

Expected result
Thunder symbol should be there in estimate screen

Actual result
Thunder symbol is not displaying.

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by rohanrp179** [comment]
Closing as this is shown
