### ISSUE TITLE
19/10/23_NY_iPA> Driver addition table is missing in rate card <Parent_ID_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3863]
#1980 
[Driver addition table is missing in rate card ](https://drive.google.com/file/d/1ZYYim3ZAy4qeXCm8nsU_MLZMzugoWW9v/view?usp=sharing)

1. Launch ipa
2. Request for a ride
3. Click on rate card 
4. Click on Driver addition
5. Verify driver addition table

**Expected** :Driver addition table is not displayed

**Comment by rohanrp179** [comment]
Closing as working fine
