### ISSUE TITLE
19/10/23_NY_iPA_Address is not updating when user selecting a favourite location through select on map_Parent Id - 1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3864]
#1980 
[Address is not updating when user selecting a favourite location through select on map](https://drive.google.com/file/d/17fdfWCzC0nS2azN1nLVkGK2TiI4pNMqN/view?usp=sharing)

Steps To reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Click on hamburger-favourite -add favourites -select on map & drag

Expected Result
 Address should update

Actual result
Address is not updating

**Comment by S-PRAVINKUMAR** [comment]
@ashkriti  can you look this ?

**Comment by S-PRAVINKUMAR** [comment]
@dhruvSHA256  can you check this?

**Comment by krupal-14** [comment]
@S-PRAVINKUMAR  Any update on this issue.

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by krupal-14** [comment]
Retested,Working fine
