### ISSUE TITLE
19/10/23_NY_iPA_Added Emergency contacts and displaying number are not proper_Parent Id - 1980 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3867]
#1980 
[Added Emergency contacts and displaying number are not proper](https://drive.google.com/file/d/1SkX4-1CCHE5HDf_ygajSELPB5utRUf_6/view?usp=sharing)

Steps to Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Add emergency contacts.(Minimum 2)
4.Add one more click on back, remove one -->click on add contacts and observe

Expected Result
Emergency contacts numbers should display properly.

Actual Result
Emergency contacts numbers are not displaying properly

**Comment by S-PRAVINKUMAR** [comment]
fixed
