### ISSUE TITLE
19/10/23_NY_iPA_Yatri  auto is displaying when user cancels the ride_Parent Id - 1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3868]
#1980 
[Yatri  auto is displaying when user cancels the ride](https://drive.google.com/file/d/1dHy5EinxJ5eObVlAIwLHHyJADB2mv8xk/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.login with valid credentials.
3.Book a ride & try to cancel it from user & observe

Expected Result
Yatri auto should not display.

Actual Result
Yatri auto is displaying.

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by rohanrp179** [comment]
closing as this is fixed
