### ISSUE TITLE
19/10/23_NY_iPA> cross icon is not showing in inapp chat banner <Parent_ID_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3869]
#1980 
cross icon is not showing in inapp chat banner

Steps:
1. Assign ride
2. Send message from driver side
3. Verify banner in user side

Actual: Cross icon is not showing in message banner

![File (4)](https://github.com/nammayatri/nammayatri/assets/131981246/f5ff7de8-6075-40e2-961d-9d7d03147cd9)

**Comment by rohanrp179** [comment]
Closing as working fine
