### ISSUE TITLE
23/10/23_NY_Android_Ride Search Screen_In UI while loading google predictions glitch is there and lottie is not coming when user searching for source/destination _Parent_Id - 1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#3927]
#1980 
[In UI while loading google predictions some glitch is there when user searching for source/destination ](https://drive.google.com/file/d/1H3eCb-VwE9k0BxHfaUzufAvEpUznYfpg/view?usp=sharing)

**Steps to reproduce**
1. Tap on Where to?
2. Search for any locations and observe google predictions while loading 

**Actual Result**
In UI while loading google predictions some glitch is there when user searching for source/destination

**Expected Result**
Glitch should not be there

**Comment by aryan-13** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Working as expected
