### ISSUE TITLE
23/10/23_NY_Android_Home Screen_User is not getting poly line when they book ride from Repeat ride_Parent_Id - 1980)

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#3935]
#1980 
[User is not getting poly line when they book ride from "Repeat ride" Section](https://drive.google.com/file/d/1H-fWzAFGRLLHLysmWaEw4Ztuu9O1yGlE/view?usp=sharing)

**Steps to Reproduce**
1. Tap on My rides
2. Tap on Repeat rides

**Actual Result** 
User is not getting poly line when they book ride from Repeat ride

**Expected Result**
User should get poly line when they book ride from Repeat ride

**Comment by aryan-13** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Working as expected.
