### ISSUE TITLE
23/10/23_NY_Android> Showing wrong distance for one location in recent search<Parent_ID_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3939]
#1980 
[Showing wrong distance for one location in ride search screen](https://drive.google.com/file/d/1blZH_z1OJu9Bf2wA5ByCCBvGY3oDMb_o/view?usp=sharing)

Steps:
1. Open application
2. Click on where to?
3. Type jayanagar metro station
4. Verify distance in recent search

**Comment by aryan-13** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Working as expected.

![Screenshot_20231027-154226_Namma Yatri](https://github.com/nammayatri/nammayatri/assets/139038923/6e6982b7-f829-43a0-9949-b711bfefedc1)
