### ISSUE TITLE
23/10/23_NY_Android_Auto-triggering waiting charges_When ride search is cancelled, RR is not pulled back_parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3941]
#1980 

[When ride search is cancelled, RR is not pulled back.](https://drive.google.com/file/d/1qVThzfgfCRXRRj3YBhA8B0xu3WTraaIN/view?usp=sharing) 

Steps-
1. Activate Go To
2. Book a ride from user
3. While confirming Pick up location, use recenter button
4. Start a ride search and once RR is received by driver, cancel the ride search

Expected
The RR should be pulled away when ride search is stopped

Actual-
RR is not pulled away

**Comment by Rohit4997** [comment]
@ratnadeep-99 @DwivediAman-exe

**Comment by rohanrp179** [comment]
closing it as similar one is handled at 
https://github.com/nammayatri/nammayatri/issues/3948
