### ISSUE TITLE
23/10/23_NY_Android_Auto-triggering waiting charges_When One Go-To count is remaining and 30 min is over, count should decrease _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3942]
#1980

[When One Go-To count is remaining and 30 min is over, count should decrease to 0.](https://drive.google.com/file/d/1K4dwu_KW8Y7QkexlBcNEH1xaseihWdlC/view?usp=sharing)

**Comment by Rohit4997** [comment]
I think it is expected, Please check expected behavior with respective backend dev

**Comment by Rohit4997** [comment]
@ratnadeep-99
