### ISSUE TITLE
23/10/23_NY_Android_Auto-triggering waiting charges_There is lag in timer for driver compared to that with user _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3944]
#1980 

There is lag in timer for driver compared to that with user when driver is within 50 m while accepting RR

![IMG_20231023_205127](https://github.com/nammayatri/nammayatri/assets/138564517/1159a5f3-10a2-4c9f-87e3-1019c7084a9e)

**Comment by Rohit4997** [comment]
@rohanrp179  Please give the steps to reproduce

**Comment by rohanrp179** [comment]
not able to reproduce. hence closing this
