### ISSUE TITLE
23/10/23_NY_Android_Auto-triggering waiting charges_When driver accept ride with tip where driver is within 50 m range, it is taking more than 15 sec to start timer _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3945]
#1980 

[When driver accept ride with tip where driver is within 50 m range, it is taking more than 15 sec to start timer (Mobile data used)](https://drive.google.com/file/d/1VlHJdKhrhvOR3C9ICS3fTGIZPKGX0oBd/view?usp=sharing)

Steps-
1. Search a ride with Go To and tip for choose multiple driver case 
2. Accept the ride

Expected -
TImer should start as soon as RR is accepted

Actual-
TImer is taking time to start. Almost more than 15 sec

**Comment by Rohit4997** [comment]
Fixed

**Comment by rohanrp179** [comment]
As 15-20 sec is expected closing the issue @sidsethu
