### ISSUE TITLE
23/10/23_NY_Android_Auto-triggering waiting charges_When app is opened using widget, Lottie is shown for sometime which is not expected _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3947]
#1980 

[When app is opened using widget, Lottie is shown for sometime which is not expected](https://drive.google.com/file/d/1KSIl-RC_UeEJKpdoKD4cGsSlRbBR0KDV/view?usp=sharing)

**Comment by Rohit4997** [comment]
@rohanrp179  Can you check it with @witcher-shailesh  
I think it is expected.

**Comment by Rohit4997** [comment]
Fixed

**Comment by rohanrp179** [comment]
when app is minimised and opened loader is coming which is expected and when killed and opened then it is not coming. Closing the issue as this is expected behaviour now
