### ISSUE TITLE
23/10/23_NY_Android_Auto-triggering waiting charges_Even when driver moves less than 50 m, timer is not starting _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#3950]
#1980 

[Even when driver moves less than 50 m, timer is not starting](https://drive.google.com/file/d/1WIGsIFlkZWem3DgTur6FBKGw-Q09jb7W/view?usp=sharing)

**Comment by Rohit4997** [comment]
Fixed

**Comment by rohanrp179** [comment]
working fine. The issue is with distance shown on user side. If we compare with the dist shown on user app
