### ISSUE TITLE
26/10/23_NY_APK_ReverseGeocode_Location Suggestions are not displaying for both source and destination fields_Parent Id - 1980

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3978]
#1980 
[Location suggestions are not displaying in the source and destination fields](https://drive.google.com/file/d/1Om8WOIUk44SUTI7onoUeFU_B8CzblAaC/view?usp=sharing)

**Steps to Reproduce**
1. launch the application and login with valid credentials 
2. Tap any location from the recent searches in homescreen and observe the issue

**Expected Result**
When user taps on the location from recent searches then user should be redirected to the "Confirm pickup location" screen and when comes back to the location selection screen, then user should be able to change the location for both source and destination fields

**Actual Result**
When user taps on "recent searches", User is redirected to the location selection screen and also when the location in the source and destination fields are deleted, and if any keyword is typed, location suggestions are not displaying.

**Comment by aryan-13** [comment]
Fixed

**Comment by Sumedh-14** [comment]
Issue is fixed in the APK shared on 27/10 and hence closing this issue.
