### ISSUE TITLE
26/10/23_NY_APK_ ReverseGeocode_Conatct support is displaying in end ride screen_Parent Id - 1980 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3979]
#1980 
[Contact support icon is displaying in end ride screen](https://drive.google.com/file/d/1tshKrYNlSblbLVVL1-MSzn1AZmX_XKQY/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride
4.Complete a ride.
5.Observe the end ride screen.

Expected Result
Contact support icon should not display.

Actual Result
Contact support icon is displaying.

**Comment by aryan-13** [comment]
@MercyQueen

**Comment by Vinaykm999** [comment]
@MercyQueen @aryan-13 issue still exist.

**Comment by aryan-13** [comment]
Fixed

**Comment by Vinaykm999** [comment]
working fine
