### ISSUE TITLE
26/10/23_NY_APK_ReverseGeocode> Youtube audio is playing even user navigated back to homescreen from accessibility setup window <Parent Id - 1980

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#3981]
#1980 
[Youtube audio is playing even user navigated back to homescreen from accessibility setup window (05/05)](https://drive.google.com/file/d/1tKCK-jaOFPEJ6ht4k5f-bMPOatnInDMb/view?usp=sharing)

Steps:
1. launch the app
2. Click on disability banner displayed in homescreen
3. Verify youtube video
4. Click on Update profile
5. Come back to home screen without setup
6. Wait for 5-10 sec
7. verify audio

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
