### ISSUE TITLE
26/10/23_NY_APK_ReverseGeocode_Education pop-up slide 1 is not present among the education pop up slides_Parent Id - 1980

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3982]
#1980 
[Education pop-up slide 1 is not present among the education pop up slides](https://drive.google.com/file/d/1ALFtueYZB0ZbkoYaWdWaCVR86BsN8teA/view?usp=sharing)

**Steps To Reproduce**
1. Launch the application and login with valid credentials 
2. Tap on the "disability banner" 

**Expected Result**
All the education pop up slides should display as per figma - [Figma Attachment
](https://drive.google.com/file/d/1fPF4ATscWUZ4yxjwBwkRfE197GSPYwaE/view?usp=sharing)
**Actual Result**
Education pop up slide 1 is not displaying

**Comment by MercyQueen** [comment]
This is replaced by the YouTube video. 
Hence its expected.

**Comment by Sumedh-14** [comment]
Done and Closing this issue.
