### ISSUE TITLE
26/10/23_NY_APK_ReverseGeocode_Location tracking icon is not displaying for the user when the ride is assigned and also after the ride is started_Parent Id - 1980

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3988]
#1980
[Location tracking icon is not displaying for the user when the ride is assigned and also after the ride is started](https://drive.google.com/drive/folders/1LXJscVwPLhdZToP7aqQQlMx9y5JWJgw1?usp=sharing)

**Steps To reproduce**
1. launch the application and login with valid credentials 
2. Initiate a ride and accept it by driver 

**Expected Result**
Location tracking icon should display in the ride assigned screen and also in ride started screen

**Actual Result**
Location tracking icon is not displaying

**Comment by ashishsingh101** [comment]
expected
