### ISSUE TITLE
26/10/23_NY_APK_ReverseGeocode_Location is displaying wrongly in "confirm pickup location" screen_Parent Id - 1980

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3992]
#1980 
[Location is displaying wrongly in "confirm pickup location" screen](https://drive.google.com/file/d/1-nuKg-87AMDnrLPTc8mM5hpMOFLLzJ5P/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with valid credentials 
2. Tap on "source field" and search any special location (ex: Nexus mall koramangala) and select it from suggested list
(Note : The current location should be different from source location ex: Ejipura)
3. Select any destination location 
4. In confirm pick up location screen, tap on the " Recenter" icon and observe 

**Expected Result**
When the user moves to the current location, then the location should change. Here in this case, the location should change from "Nexus mall koramangala" to "Ejipura" 

**Actual Result** 
The location is still displaying as "Nexus mall Koramangala" and also when initiated ridesearch, the ride is searched with the source location as "Nexus mall koramangala".

**Comment by aryan-13** [comment]
Fixed

**Comment by Sumedh-14** [comment]
Retested, it is Working fine and hence closing this issue.
