### ISSUE TITLE
26/10/23_NY_APK_ ReverseGeocode_Special location gates drop down should be in user selected language_Parent Id - 1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3993]
#1980 
[Special location gates drop down should be in user selected language](https://drive.google.com/file/d/1PsjdKy2HgOIpelgMkxPSaUzqieP0QAWM/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Select any language other then english.
4.Book a ride from special location& observe

Expected Result
Gates name  should be in user selected language.

Actual Result
Gates names are in english languages.

**Comment by ashishsingh101** [comment]
expected

**Comment by krupal-14** [comment]
As per dev comment closing the issue.
