### ISSUE TITLE
26/10/23_NY_APK_ ReverseGeocode_Two "Try Again" pop up screens are displaying for the user_Parent Id - 1980

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#3994]
#1980 
[Two "Try Again" pop up screens are displaying for the user](https://drive.google.com/file/d/14D4TiTILOqPMbi2x_5tL4-afsRnmeQRp/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with the valid credentials 
2. Search for a ride with "Auto-assign mode" and wait until "Try again" screen is displaying 
3. Tap on "Home" 

**Expected Result**
The user should be redirected to the "Home" screen

**Actual Result**
Another "try again" screen is displaying (Refer the video after 2:50 duration)

**Comment by aryan-13** [comment]
@S-PRAVINKUMAR Can you check this

**Comment by aryan-13** [comment]
Fixed
