### ISSUE TITLE
26/10/23_NY_APK_ ReverseGeocode_when ride assigned the actual path displaying in fake gps & the distance displaying in app is varied by 20m_Parent Id - 1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#3998]
Steps to produce
1.Launch the apk.
2.Login with valid credentials.
3. Book a ride with some pickup distance 
4. simulate the driver to pickup & observe the distance

**Comment by aryan-13** [comment]
@S-PRAVINKUMAR Can you check this

**Comment by aryan-13** [comment]
Expected

**Comment by Vinaykm999** [comment]
@aryan-13 As per dev comments it is expected, hence resolving this.
cc @rohanrp179 @krupal-14
