### ISSUE TITLE
26/10/23_NY_Android_Auto-triggering waiting charges_Options under report issues are missing _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4000]
#1980 

[Options under report issues are missing](https://drive.google.com/file/d/1JwFBL8C0huaD-NBaB-DbCh8Wculoeb8H/view?usp=sharing)

Also if we submit any issue, then Ongoing issues option is missing

**Comment by AlluGowthami28** [comment]
Issue fixed.
