### ISSUE TITLE
26/10/23_NY_Android_Auto-triggering waiting charges_Go To related changes are missing from app when driver logout and login from ride assigned state _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4002]
#1980 

[Go To related changes are missing from app when driver logout and login from ride assigned state](https://drive.google.com/file/d/1epDbaSQe7NCVy7kNh2DUo6Kyq84cHfZj/view?usp=sharing)

Steps-
1. Log out from driver side when ride is assigned
2. Login back
3. Exchange messages and cancel ride

Expected-
Go To option should be present on Home screen

Actual-
Go To option is missing from Home screen

**Comment by Rohit4997** [comment]
Fixed

**Comment by AlluGowthami28** [comment]
Working as expected.
