### ISSUE TITLE
27/10/23_NY_APK_ ReverseGeocode_Tip options are not displaying in the try again pop up screen & Cab icon is displaying in try agin pop-up _Parent Id - 1980

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#4019]
#1980 
[Getting Try again pop up screen without tip in the below mentioned case](https://drive.google.com/file/d/1-YajPjw25Bi9Q8DAurqNXRAq8Q38bk2k/view?usp=sharing)

**Steps To Reproduce**
1. Launch the application and login with valid credentials 
2. Initiate a ridesearch in "select multiple drivers" mode 
3. Accept the ride request by the driver before getting the "tip option" in user side
4. For user in driver quotes screen, tap on "x" so that the driver quotes won't get selected and then wait until try again screen and observe.

**Expected Result**
Try again should display along with the "tip" option

**Actual Result** 
Tip options are not displaying 
Cab icon is displaying try again screen

**Comment by aryan-13** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
