### ISSUE TITLE
special zone - UI Driver

### ISSUE THREAD

**Issue by Rohit4997** [nammayatri/nammayatri#402]
Frontend: Special zone driver

**Comment by SrinivasNaikB** [comment]
Updated the task- https://github.com/nammayatri/nammayatri/issues/577
with new API integration details..
Backend [PR](https://github.com/nammayatri/nammayatri/pull/978) is raised and will be merged today(6 June).

Please re-start frontend task and complete it be next front-end release.
@Rohit4997
