### ISSUE TITLE
27/10/23_NY_APK_ ReverseGeocode_Youtube Audio in profile screen is running in background even though the video pop up screen is closed_Parent Id - 1980

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#4020]
#1980 
[Youtube Audio in profile screen is running in background even though the video pop up screen is closed](https://drive.google.com/file/d/1ZAX2HYXAc7_ynVLia1Oq9sdJOXvl0VnT/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with the valid credentials 
2. Go to profile screen > edit > Select "yes" in Disability option >>select any disability option  and save it
3. In profile screen tap on the "Learn how Namma Yatri caters to your needs" option and in the pop up screen tap on "Got it" even before the video is loaded and observe 

**Expected Result**
The pop up screen should be closed and also audio should not be played and user should stay in the profile screen.

**Actual Result**
Even after closing the pop up, the audio is played in the background. (Kindly play the video Attachment with audio)

**Comment by aryan-13** [comment]
@MercyQueen

**Comment by aryan-13** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
