### ISSUE TITLE
27/10/23_NY_APK_ ReverseGeocode> Request ride button is showing as disabled and button is not working <Parent Id - 1980

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4023]
#1980 
[Request ride button is showing as disabled and button is not working
](https://drive.google.com/file/d/1BA1t1U18_uORoyGBkk2xnhqmXs8ndQgH/view?usp=sharing)
Steps:
1. request metro tide
2. Assign ride
3. Cancel the ride from user side
4. Search same metro ride
5. Verify request ride button

**Comment by aryan-13** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
