### ISSUE TITLE
27/10/23_NY_APK_ ReverseGeocode> Car icon is showing in user apk, once ride assigned <Parent Id - 1980

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4026]
#1980 
Car icon is showing in user apk, once ride assigned (02/10)

**Steps**:
1. request metro tide
2. Assign ride
3. Cancel the ride from user side
4. Search same metro ride
5. Verify request ride button
6. select multiple driver option
7. Request and accept the ride
8. Verify the car icon 

**Note**: Not reproducible every time

![Screenshot_20231027_165701](https://github.com/nammayatri/nammayatri/assets/131981246/15e835fd-68a8-4d0f-974a-415a36eb997c)

**Comment by aryan-13** [comment]
Fixed @Vignesh-772

**Comment by Vinaykm999** [comment]
Unable to reproduce this, It was happening some times, We did sanity for the lates CUG till now not observed this issue, Hence resolving this
