### ISSUE TITLE
27/10/23_NY_APK_ ReverseGeocode_confirm location displaying twice if user edit the src address special location_Parent Id - 1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4028]
#1980 
[confirm location displaying twice if user edit the src address special location](https://drive.google.com/file/d/1pR2Kc28ZzIYhMGYiFQNKSKlprGRH9LPO/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Select src & dest.(Normal src & dest)-->Continue till estimate screen.
4.Click back edit src to special location address(Nexus mall Koramangala).--click continue--select any gate--click continue
5.edit src address--choose through map--select some other gate--continue & observe

Expected Result
One time confirm location should display.

Actual result
Two times confirm location is displaying.

**Comment by aryan-13** [comment]
Fixed @ashishsingh101

**Comment by krupal-14** [comment]
Retested,Working fine.
