### ISSUE TITLE
27/10/23_NY_Android_DriverInfo card and chat changes_ SOS button is missing before and after ride start _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4031]
#1980

SOS button is missing before and after ride start

![Screenshot_20231027-184646](https://github.com/nammayatri/nammayatri/assets/138564517/c38b1815-9549-4a8c-9363-542b3c15a041)

**Comment by PraveenGongada** [comment]
Namma Safety will be added here once ready
