### ISSUE TITLE
27/10/23_NY_Android_DriverInfo card and chat changes_ When keyboard is up during chat, OTP and share option should be hidden behind _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4033]
#1980

When keyboard is up during chat, OTP and share option should be hidden behind as per figma

https://github.com/nammayatri/nammayatri/assets/138564517/6ada778b-4e72-462a-962b-fbd938018469

**Comment by PraveenGongada** [comment]
Expected

**Comment by Gowthami1309** [comment]
Working as expected.
