### ISSUE TITLE
27/10/23_NY_Android_DriverInfo card and chat changes_ When chat box is open, upper part of app is not accessible _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4034]
#1980

When chat box is open, upper part of app is not accessible

https://github.com/nammayatri/nammayatri/assets/138564517/357f2de3-8a51-4a4f-adee-239eda85ccd0

**Comment by PraveenGongada** [comment]
Fixed

**Comment by Gowthami1309** [comment]
Issue fixed
