### ISSUE TITLE
27/10/23_NY_Android_DriverInfo card and chat changes_ When driver cancel the ride, user is not receiving any cancellation FCM _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4036]
#1980

[When driver cancel the ride, user is not receiving any cancellation FCM](https://drive.google.com/file/d/1HB1HiG53CrLGsJoDltxknfcrw6TJev4M/view?usp=sharing)

Steps-
1. Search for ride
2. Accept from driver side
3. After 15-20 sec cancel from driver side

Expected-
User should receive FCM saying driver cancelled the ride

Actual-
User is not receiving any FCM

**Comment by PraveenGongada** [comment]
can you try uninstalling and reinstalling, it would be device token issue

**Comment by Gowthami1309** [comment]
Fixed
