### ISSUE TITLE
31/10/23_NY_iPA_CUG_When ride is assigned/started, the map is showing (0,0) ocean location _parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4090]
#1980

When ride is assigned, the map is showing (0,0) ocean location

Steps-
1. Assign a ride
2. Wait for sometime and map will automatically show (0,0)
3. Or kill and open  the app
4. This happens even when ride is started

Expected-
The map should show auto and pick up route

Actual-
It is showing ocean area

https://github.com/nammayatri/nammayatri/assets/138564517/1528df43-4e20-42ac-bcd4-b5800aa6d6b5

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
Working as expected.
