### ISSUE TITLE
31/10/23_NY_iPA_CUG_ipa is crashing when user edit the src address with special location address_parent-id_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4091]
#1980 
[ipa is crashing when user edit the src address with special location address](https://drive.google.com/file/d/1bjJ2gs6aX6hUgDASMoiS2gHoCZWL60jJ/view?usp=sharing)

Steps To Reproduce
1.Launch the ipa.
2.Login with valid credentials.
3.Enter src & dest (Normal src & dest)
4.Navigate to estimate screen-->Click on back button-->click cross button of src
5.Enter special location & observe.

Expected Result
Ipa should not crash.

Actual Result
Ipa is crashing

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Workign fine
