### ISSUE TITLE
31/10/23_NY_iPA_CUG_Current location text is not left aligned when address is changed and recenter button is used_parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4092]
#1980

Current location text is not left aligned when address is changed and recenter button is used

Steps-
1. Search for any location
2. Move ballon pin to change address in address field
3. Now click recenter

Expected-
Current location text should be left aligned

Actual-
It should be left aligned

https://github.com/nammayatri/nammayatri/assets/138564517/b5fb5bab-bee6-44bb-b5e9-b32cf2629843

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
Working fine.
