### ISSUE TITLE
31/10/23_NY_iPA_CUG_Loader shown at time of search is too small_parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4099]
#1980

Loader shown at time of search is too small

https://github.com/nammayatri/nammayatri/assets/138564517/f3d9d953-82d3-44d5-b2e1-4530d9785aa6

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
Working  fine
