### ISSUE TITLE
31/10/23_NY_iPA_CUG_Polyline is disappearing before pickup & after ride started _parent-id_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4101]
#1980 
[Polyline is disappearing before pickup & after ride started ](https://drive.google.com/file/d/1zZiaKUs1lTWOf_Vl1jnH9tTjvy1iv4Vk/view?usp=sharing)

Steps To Reprdouce
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride.
4.Observe the polyline before pickup & after ride started.

Expected result
Polyline should not disappear 

Actual result
Polyline is disappearing.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
