### ISSUE TITLE
31/10/23_NY_iPA_CUG_When destination text is edited, and if completely removed then recent searches are not shown_parent-id_1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4102]
#1980

When destination text is edited, and if completely removed then recent searches are not shown

Steps-
1. Make sure that there are some recent searches shown on ride search screen
2. Now search for a ride and come back to ride search screen from Confirm pickup screen
3. Edit few letters of text in destination and wait till auto suggestions are updated
4. Now remove all text from destination

Expected-
When whole text is removed, the auto suggestions should go and recent searches should be shown

Actual-
It is showing auto suggestions which it shown before removing whole text from destination

https://github.com/nammayatri/nammayatri/assets/138564517/ac378b45-1cc0-4c43-a72c-3dba87eb2353

**Comment by MercyQueen** [comment]
Fixed.

**Comment by rohanrp179** [comment]
working as expected
