### ISSUE TITLE
03/11/23_YP_Android_BookingOptions_Confirm&Change button is displaying in the booking option screen_parent-id_1594

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#4129]
#1594 
[Confirm&Change button is displaying in the booking option screen](https://drive.google.com/file/d/1FeY1uJnDJVyMjqUHnMUwqRHWaxM5M9nj/view?usp=sharing)

**Steps To Reproduce**
1. Launch the application and login with the valid credentials 
2. Go to Profile > Booking Options and observe the screen 

**Expected Result**
"Confirm & Change" Button should not display.

**Actual Result**
"Confirm & Change" Button is displaying.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
