### ISSUE TITLE
03/11/23_YP_Android_BookingOptions_ Plans options are not yet introduced hence should not show plans tab _parent-id_1594

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4131]
#1594 

Plans options are not yet introduced hence should not show plans tab

![Screenshot_20231103-131928](https://github.com/nammayatri/nammayatri/assets/138564517/ec5fe17f-114e-4d26-9896-42b6598391d4)

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
