### ISSUE TITLE
03/11/23_YP_Android_BookingOptions_ When we click on Contest or Alerts icon form navbar, previous icons are highlighted _parent-id_1594

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4132]
#1594 

When we click on Contest or Alerts icon form navbar, previous icons are highlighted

https://github.com/nammayatri/nammayatri/assets/138564517/cbf2b3c3-f024-4edf-a65d-c63f3a3fc7ad

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
