### ISSUE TITLE
07/11/23_NYP_Android_Profile Image> Full photo is not capturing when driver tries to upload selfie photo> <parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4169]
#1980 

[Full photo is not capturing when driver tries to upload selfie photo
](https://drive.google.com/file/d/1sZZWjgVmDVzZTz0ATOfrVRAiLMxhZyG4/view?usp=sharing)
Steps:
1.  Launch driver apk
2. Click on profile icon>>profile photo
3. Select full photo
4. Verify uploaded photo

Actual: Full photo(whichever comes under the circle ) is not covering

**Comment by Rohit4997** [comment]
@Vinaykm999  This is expected we need to crop the image.

**Comment by rohanrp179** [comment]
closing this as it is expected
