### ISSUE TITLE
07/11/23_YS_APK_ReverseGeocode_When 60 min of time starts for special zone ride, the time starts late from 59.55 sec instead of 60.00 _Parent Id - 2096

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4179]
#2096

[When 60 min of time starts for special zone ride, the time starts late from 59.55 sec instead of 60.00](https://drive.google.com/file/d/1UoShJCOutyRJ3oXaLjUhAEmoCZVEvDrD/view?usp=sharing)

**Comment by ashishsingh101** [comment]
fine
