### ISSUE TITLE
07/11/23_YS_APK_ReverseGeocode_Showing Auto icon in Disability carousel_Parent Id - 2096

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4182]
#2096 

Steps to reproduce:
1. launch the application 
2. Tap on Disability banner on the home screen
3. Observe the screen

Expected result:

User should be able to see cab icon in the carousel slider

Actual result:

User is getting Auto icon in Disability carousel slider

Repro: 5/5

![Screenshot_20231107_163626](https://github.com/nammayatri/nammayatri/assets/129082995/2864731f-903d-4f6b-9798-f9b629643915)

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Gowthami1309** [comment]
Issue resolved.
