### ISSUE TITLE
07/11/23_YS_APK_ReverseGeocode_UI Issues in Disability carousel_Parent Id - 2096

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4183]
#2096 

Steps to reproduce:
1. Launch the application
2. Tap on Disability Banner on the home screen
3. Observe the carousel

Expected Result:
1. "." Should be the at there end of the text
2. Carousel Slider should be in rectangular shape as per the figma

Actual result:
1. "." Shouldn't be there at the end of the text
2. Carousel Slider is in circle shape as per the figma

Repro:5/5

![IMG_20231107_163831](https://github.com/nammayatri/nammayatri/assets/129082995/e5f418b7-4dcc-4391-a0e8-f03528cc953a)

**Comment by MercyQueen** [comment]
1. Fixed.
2. Expected.

**Comment by vinod96424** [comment]
If the 2nd one is expected, pls ask designers to change it. this will create confusion here. Ask them to do proper design review from now on.
