### ISSUE TITLE
07/11/23_YS_APK_ReverseGeocode_When 60 min of time starts and if screen is off for long time, if we go back to app the time is not updated. We need to kill and open to update _Parent Id - 2096 

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4187]
#2096

[When 60 min of time starts and if screen is off for long time, if we go back to app the time is not updated. We need to kill and open to update](https://drive.google.com/file/d/14DEo30oSBfD37G9DaEbyYn7ZabbMZqt0/view?usp=sharing)

Steps-
1. Start spec zone ride for YS
2. Off the screen for 5-10 min.
3. On the screen 

Expected-
The time should adjust as per actual time left for OTP expiry

Actual-
Until app is killed and opened again, time is not updated

**Comment by Gowthami1309** [comment]
Working fine
