### ISSUE TITLE
special zone - UI User

### ISSUE THREAD

**Issue by ashishsingh101** [nammayatri/nammayatri#419]
add tags for special zone / flat fare like metro and hospitals which is to be shown in estimate screen, ride card, rating screen and ride lists

add special location tags icons in route address title marker

**Comment by SrinivasNaikB** [comment]
Updated the task- https://github.com/nammayatri/nammayatri/issues/577
with new API integration details..
Backend [PR](https://github.com/nammayatri/nammayatri/pull/978) is raised and will be merged today(6 June).

Please re-start frontend task and complete it be next front-end release.
@ashishsingh101
