### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding>City name is changing even before confirming<parent_id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4195]
#1980 
[City name is changing even before confirming](https://drive.google.com/file/d/1SuAcyQNF9eKzGK-YS1dQGl8cDGiVKZxy/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give location permission.
3.Click on change city & select one valid city
4.Click on back & observe

Expected Result
City name should not update.

Actual Result
City name is updating.

**Comment by ashkriti** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,working fine
