### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding> Screen flickers when driver selects change city <parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4196]
#1980 
[Screen flickers when driver selects change city 
](https://drive.google.com/file/d/1Nj1emUZhRSLfU8kiojSHXL05ImdQINlT/view?usp=sharing)
Steps:
1. Open application
2. Give language permission
3. Select city
4. Click on Change city
5. Verify screen

**Comment by Rohit4997** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
