### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding><language is also changing even before confirming it><parent_id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4197]
#1980
[language is also changing even before confirming it](https://drive.google.com/file/d/1acCqb-RnEmxn_4vN210mRK2L8WuShHaW/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give location permission.
3.Click on change language & select any language & click back
4.Observe

Expected result
Language is not updating.

Actual Result
Language is updating.

**Comment by ashkriti** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine
