### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding><Cash paid rupees 100 is not displayed in carousel screen  ><parent_id_1980> 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4198]
#1980 
[Cash paid rupees 100 is not displayed in carousel screen when driver chooses tamil langauge ](https://drive.google.com/file/d/1iXOSUxcL18c4YWXH-cr49i3wdP5yH72W/view?usp=sharing)

Steps To reproduce
1.Launch the apk.
2.Give location permission.
3.Select valid city & choose language as tamil click confirm & observe

Expected Result
Carousel screen should be according to figma

Actual result
Text is missing in carousel screen.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
