### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding> Telugu language is not there in select language screen as per figma<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4199]
#1980 
Telugu language is not there in select language screen

Steps:
1. open application
2. Give language permission
3. Select city
4. Click on change language 
5. Verify telugu language 

![Screenshot_20231107_195100_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/7cebda82-e989-4688-9ed5-6d940fac23fa)

<img width="882" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/a0ebe29c-4766-4581-843b-46b3f8558a16">

**Comment by ashkriti** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
