### ISSUE TITLE
07/11/23_NYP_Android_Onboarding_If we are entering details in first text field, second text field starts showing error message_Parent Id - 1980

### ISSUE THREAD

**Issue by rohanrp179** [nammayatri/nammayatri#4201]
#1980

If we are entering details in first text field, second text field starts showing error message

Steps-
1. Login with new number
2. Go to Driving licence details
3. Start entering details in first text field

Expected-
When data in input in first text field, the next textbox should not give error message

Actual-
It is giving error message when data is entered in first text box

https://github.com/nammayatri/nammayatri/assets/138564517/cb386cfb-e68f-4be3-ad6a-798b082c7dd2

**Comment by krupal-14** [comment]
Retested,Working fine
