### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding>Carousal description is not as per figma<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4202]
#1980 
Carousal description is not as per figma

Steps:
1. Open application
2. Give language permission
3. Select city
4. Click on change language
5. Confirm 
6. Slide for 3rd screen
7. Verify description text and figma text

Apk image
![Screenshot_20231107_201438_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/19d073f0-4cf6-428a-89bd-0ee2970f2bd6)

Figma image
<img width="910" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/15c1a01f-3892-4665-a01f-37fd298d669e">

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
