### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding><Location permission screen is displaying again even though we given the access ><parent_id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4204]
#1980 
[Location permission screen is displaying again even though we given the access](https://drive.google.com/file/d/1St5UZW5EcLtQdzkjxFiMexBOSbwMxkQF/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give location permission.
3.Select valid city & language click on confirm
4.Click on get started 
5.Click on back button in enter mobile number screen

Expected Result
Again location permission access screen should not display.

Actual result
Location permission screen is displaying.

**Comment by Rohit4997** [comment]
Not reproducible
Please mention the Proper steps

**Comment by krupal-14** [comment]
Clear app data 
1.Launch the apk.
2.Give location permission.
3.Select valid city & language
4.Click on confirm & Click on get started.
5.Enter mobile number & click on continue.
6.click on back button & observe

Kindly refer the below video
https://drive.google.com/file/d/1DKSsYAdfKktCY0NQIAXGBJYtt027QQ0t/view?usp=sharing

**Comment by Rohit4997** [comment]
@ashkritidewan2000 @ashkriti  Is this issue fixed? I'm not able to reproduce in the current branch

**Comment by prakharritik** [comment]
yes this was fixed

**Comment by krupal-14** [comment]
Retested,Working fine
