### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding>App is opening at First screen(Location and language)when driver kill and relaunch from driver education screen<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4205]
#1980 
[App is opening at First screen(Location and language)when driver kill and relaunch from driver education screen](open application
Give language permission
Select city
Click on change language)

Steps:
1. Open application
2. Give language permission
3. Select city
4. Click on change language
5. Confirm
6. Navigate to 3rd carousel screen
7. Kill and relaunch
8. Verify screen

**Comment by Rohit4997** [comment]
@prakharritik  @ashkritidewan2000  Is this expected ?

**Comment by Vinaykm999** [comment]
Working fine now
