### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding> The permission screen icons in Figma are different from the app <parent_id_1980>

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#4206]
#1980 
The permission screen icons in Figma are different from the app.

**Actual Result**
The permission screen icons in Figma are different from the app.

**Expected Result**
The permission screen icons should be as per in Figma.

![Screenshot_20231107_201536](https://github.com/nammayatri/nammayatri/assets/139038923/68b2d512-691a-4590-90e5-4a036cdc7ca2)

**Comment by prakharritik** [comment]
fixed

**Comment by Gowthami1309** [comment]
Fixed
