### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding>+91 is missing in mobile number field<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4208]
#1980 
+91 is missing in mobile number field

Steps:
1. Open application
2. Be in Mobile number screen
3. verify +91

**Actual**: +91 is not present in mobile number field 

![Screenshot_20231107_202952_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/2949866f-353d-4006-bb0e-58325eef89c0)

<img width="945" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/a20a876e-67d0-4fa2-b44b-bc46be5045fd">

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
