### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding> In upload RC screen image is not clear and how to upload sub text should be as per figma   <parent_id_1980>

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#4209]
#1980
In upload RC screen image is not clear and how to upload sub text should be as per figma

![Screenshot_20231107_201800](https://github.com/nammayatri/nammayatri/assets/139038923/21eabf35-7d8d-4569-a919-fb0b5e1a84fb)

**Comment by Gowthami1309** [comment]
Fixed
