### ISSUE TITLE
07/11/23><NYP> <Android><Onboarding>Placeholder text should be numeric in mobile number screen<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4210]
#1980 
Placeholder text should be numeric in mobile number screen

Steps:
1. Open application
2. Be in mobile number screen
3. Verify placeholder text in mobile number field 

**Expected**: Mobile number placeholder should display as per figma

![image (34)](https://github.com/nammayatri/nammayatri/assets/131981246/1dc3fa00-9d4b-43f0-8f12-e904b9a3c863)

![Screenshot_20231107_202952_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/f06665be-f67d-45b2-92a5-d116738e76a9)

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
