### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding> Continue button is keep on loading in mobile number screen<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4219]
#1980 
[Continue button is keep on loading in mobile number screen
](https://drive.google.com/file/d/1sWQEIDfkNyiKJzgrtbvf0HMtTCbJgyix/view?usp=sharing)

**Steps**:
1. Open application
2. Be in mobile number screen
3. Enter driver mobile number
4. click on continue 
5. Be in OTP screen
6. Navigate back to mobile number screen
7. Verify continue button

**Comment by MercyQueen** [comment]
Duplicate issue. same as #4220
