### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding>Continue button is not displaying in enter mobile number screen<parent_id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4220]
#1980 
[Continue button is not displaying in enter mobile number screen](https://drive.google.com/file/d/1kFBwurGvol0hhqds4yZe3M13p4TM17Kt/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give location access.
3.Select valid City & language.
4.Click on confirm& click on get started.
5.Enter valid mobile number & click on continue.
6.click on back again follow the same observe the enter mobile number scren.

Expected Result
Continue button in enter mobile number screen should display.

Actual result
Continue button is not displaying in enter mobile number screen.

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine
