### ISSUE TITLE
8/11/23><NYP> <Android><Onboarding> Didn’t  receive an OTP? message should display in OTP screen <parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4224]
#1980 

Didn’t  receive an OTP? message should display in OTP screen 

**Steps**:
1. Open application
2. Be in mobile number screen
3. Enter driver mobile number
4. click on continue
5. Wait for 15 seconds
6. Verify resend OTP

**Expected**: "Didn’t  receive an OTP?" this message should display before resend OTP link

![Screenshot_20231108_122059_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/2db10bde-1d61-4d6a-bbc2-f37b0ac702ef)

![image](https://github.com/nammayatri/nammayatri/assets/131981246/f798167e-737f-4510-9e7e-6a78b721a6c3)

**Comment by ashkriti** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
