### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding>Language detected is selecting  english as default but driver selected different language <parent_id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4225]
#1980 
[Language detected is selecting  english as default but driver selected different language](https://drive.google.com/file/d/1PgjGkN9aIh2nYOOFZZLCqSLM4e2Srubg/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give location permission acess.
3.Select valid city & language other then english.
4.Click on confirm & Click on get started 
5.Enter valid mobile number & click on continue.
6.Click on back & give location permission access.
7.And observe the language detected.

Expected Result
Language detected should be driver selected language.

Actual Result
Language detected is by default in english.

**Comment by ashkriti** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine
