### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding>Namma yatri plans text & start earning in 4 simple steps is not properly translated in kannada lnaguage<parent_id_1980> 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4226]
#1980 
[Namma yatri plans text & start earning in 4 simple steps is not properly translated in kannada lnaguage](https://drive.google.com/file/d/14mfsYq_0JV_Wxz771z66RJFyB5cEy_7C/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give location permission access.
3.Select Valid city & kannada language.
4.Click on confirm & get started.
5.Enter valid mobile number & Otp
6.And observe the mentioned text

 Expected Result
Namma yatri plans(ನಮ್ಮ ಯಾತ್ರಿ ಯೋಜನೆಗಳು)
start earning in 4 simple steps(4 ಸರಳ ಹಂತಗಳಿಂದ ಗಳಿಸಲು ಪ್ರಾರಂಭಿಸಿ)

Actual result
Text is not properly translated.

**Comment by Rohit4997** [comment]
@krupal-14  Please give correct translation

**Comment by krupal-14** [comment]
Namma yatri plans(ನಮ್ಮ ಯಾತ್ರಿ ಯೋಜನೆಗಳು)
start earning in 4 simple steps(4 ಸರಳ ಹಂತಗಳಿಂದ ಗಳಿಸಲು ಪ್ರಾರಂಭಿಸಿ)

**Comment by Rohit4997** [comment]
Thanks

**Comment by krupal-14** [comment]
Issues Still exist.
https://juspay.slack.com/files/U048PG24YQP/F064ZUQ8CTY/screenshot_20231110_154211_namma_yatri_partner.jpg

**Comment by Gowthami1309** [comment]
fixed.
