### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding> "Confirm and upload" button should be align at the bottom of the screen and text should be in tittle case while uploading both DL and RC <parent_id_1980>

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#4227]
#1980 
Confirm and upload" button should be align at the bottom of the screen and text should be in tittle case while uploading both DL and RC 

**Actual Result**
Confirm and upload" not aligned properly while uploading both DL and RC 

**Expected Result**
Confirm and upload" button should be align at the bottom of the screen and text should be in tittle case while uploading both DL and RC 

![Screenshot_20231107_201908](https://github.com/nammayatri/nammayatri/assets/139038923/0c2d0778-1cb0-43ac-b2f7-0b05ec638bdb)

**Comment by Gowthami1309** [comment]
Fixed
