### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding>Enter vehicle Registration details page text is not according to figma<parent_id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4232]
#1980 
[Enter vehicle Registration details page text is not according to figma](https://drive.google.com/file/d/1zWLmtu-1zPnak11VM932sx4x70ao3g6y/view?usp=sharing)

Steps to Reproduce
1.Launch the apk.
2.Give permission-->select city& langauge-->Enter mobile number-->OTP
3.Click on vehicle registration certification & observe

Expected result
Text should be according to figma

Actual Result
Text is not according to figma

**Comment by ashkriti** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine.
