### ISSUE TITLE
8/11/23><NYP> <Android><Onboarding>Got an OTP? text should be in kannada font when driver selected language is kannada <parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4233]
#1980 
Got an OTP? text should be in kannada font when driver selected language is kannada 

Steps:
1. Open application
2. Change language in kannada
3. Be in mobile number screen
4. Enter driver mobile number
5. click on continue
6. Verify Got an OTP? in top left corner

Expected: "OTP ಸಿಕ್ಕಿತೇ?" should add this
![Screenshot_20231108_123833_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/3b4b6328-62df-483d-bb7c-c18728c16cdb)

**Comment by ashkriti** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Issue still exist, hence reopening this

**Comment by Gowthami1309** [comment]
Issue resolved.
