### ISSUE TITLE
8/11/23><NYP> <Android><Onboarding> kannada font is missing in Language selection screen <parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4234]
#1980 
 kannada font is missing in Language selection screen
 
 Steps:
1.  Open application
2.  Change language in kannada
3.  Verify "Select the location where you want to take rides" in kannada

**Expected**: ನೀವು ಸವಾರಿ ಮಾಡಲು ಬಯಸುವ ಸ್ಥಳ

![Screenshot_20231108_123400_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/bc67484b-ad6c-4893-b2da-e0011e84d90e)

**Comment by ashkriti** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,Working fine
