### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding> City auto detection is not working in this apk due that unable to check city flow<parent_id_1980> 

### ISSUE THREAD

**Issue by AlluGowthami28** [nammayatri/nammayatri#4235]
#1980 
City auto detection is not working in this apk due that unable to check city flow

**Actual Result**
City auto detection is not working in this apk due that unable to check city flow

**Expected Result**
City detection should work

![Screenshot_20231108_125823](https://github.com/nammayatri/nammayatri/assets/139038923/468c0209-c495-447b-9cd5-96925a226c9a)

**Comment by Rohit4997** [comment]
@ashkritidewan2000 You are working on it ?

**Comment by Gowthami1309** [comment]
Working now.
