### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding>Back button should not display in registration screen<parent_id_1980> 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4237]
#1980 
[Back button should not display in registration screen](https://drive.google.com/file/d/1d2kuh3oOwYaFkxRKT1a-g8pTAPySYq5e/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give permission-->select city& langauge-->Enter mobile number-->OTP
3.Observe the registration screen

Expected Result
Back button should not be there according to figma

Actual result
Back button is displaying

**Comment by Rohit4997** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
