### ISSUE TITLE
8/11/23><NYP> <Android><Onboarding>Background screen is showing blank when driver is in logout popup - background screen should be grayedout<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4239]
#1980 
Background screen is showing blank when driver is in logout popup - background screen should be grayed out

Steps:

1. Open application
2. Change language in kannada
3. Be in mobile number screen
4. Enter new driver mobile number
5. click on continue
6. Enter OTP
7. Be in registration page
8. Click on logout
9. Verify logout popup

Expected: background should be garyed out when popup is showing as per figma

![Screenshot_20231108_132459_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/1e04a34e-ad6e-44f4-9b42-de95e2f95063)

**Comment by Rohit4997** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,working fine
