### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding>Notification button is not displaying in grant permission screen<parent_id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4240]
#1980 
[Notification button is not displaying in grant permission screen](https://drive.google.com/file/d/1NUC4h0eIZL8QvilGsVplvjS21VkwX7JL/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give permission-->select city& langauge-->Enter mobile number-->OTP
3.Click on Grant permission & observe

Expected Result
Notification button should display 

Actual result
Notification button is not displaying 

Note: whether it is because of android 13. i am checking in android 12 please clarify.

**Comment by prakharritik** [comment]
Yes @krupal-14 this will only be visible in android 13 and later verisons

**Comment by Vinaykm999** [comment]
As per dev comments it is expected, so resolving  this
