### ISSUE TITLE
8/11/23><NYP> <Android><Onboarding>Old logout popup is showing in  Driver licence details screen<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4242]
#1980 

Old logout popup is showing in  Driver licence details screen

Steps:

1. Open application
2. Change language in kannada
3. Enter new driver mobile number
4. click on continue
5. Enter OTP
6. Click on Driving License tab
7. Click on logout 
8. Verify logout popup

Actual: Old popup is showing

![Screenshot_20231108_140812_Namma Yatri Partner](https://github.com/nammayatri/nammayatri/assets/131981246/f6bd4f54-4e19-4c00-b162-e7700a46e5cc)

**Comment by Rohit4997** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
