### ISSUE TITLE
08/11/23><NYP> <Android><Onboarding>Screen is flickering when driver is clicking on logout from registration screen<parent_id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4243]
#1980 
[Screen is flickering when we logout from registration screen](https://drive.google.com/file/d/11m4hV62xQ-qE0ow8VdGaUcJOkTt_7lsR/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Give permission-->select city& langauge-->Enter mobile number-->OTP
3.Click on logout & observe

Expected Result
Screen should not flicker 

Actual result
Screen is flickering

**Comment by Rohit4997** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested,working fine
