### ISSUE TITLE
8/11/23><NYP> <Android><Onboarding>App is navigating to first screen when driver click on outside the logout popup screen<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4244]
#1980 
[App is navigating to first screen when driver click on outside the logout popup screen](https://drive.google.com/file/d/1C3OrPk4XEvU5jpQ-Ha5LfuWHRfQw3sIP/view?usp=sharing)

Steps:

1. Open application
2. Change language in kannada
3. Enter new driver mobile number
4. click on continue
5. Enter OTP
6. Click on Driving License tab
7. Click on logout
8. Verify logout popup
9. Click outside the screen
10. Verify screen

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine
