### ISSUE TITLE
09/11/23_YSD_APK_Chat changes> UI Issues <parent-id_2096>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4261]
#2096 

1. Share ride icon is not showing in user screen, when ride has started
2. Namma safety button should be display in place of Emergency help

![Screenshot_2023-11-09-16-56-42-86_421cf1a694c0c6595cc86111492ae90a](https://github.com/nammayatri/nammayatri/assets/131981246/57621c06-ce54-4c3c-a106-cdc2f75ccbe3)

3. Wait time text is there instead of expires text

![IMG_20231109_160738 (2)](https://github.com/nammayatri/nammayatri/assets/150240985/d198e73e-42ee-49fb-85f0-5befccc3c691)

4. **Quick chats** text should be there

![IMG_20231109_170347](https://github.com/nammayatri/nammayatri/assets/150240985/e53695d0-e359-4f2f-9b0e-4391a18a9e72)

5. [Shimmering is going out of the box in OTP button in Special location.](https://drive.google.com/file/d/18yOBef9KwB0SysdJF40ab8W2_iXoZhOs/view?usp=sharing)

6. [AC taxi is not coming when AC ride is assigned for special location
](https://drive.google.com/file/d/11I45NdEpqJ0glZGkdsj_n-kJ_q9aNuOL/view?usp=sharing)

7. [Wrong text message is showing when driver arrived at destination](https://drive.google.com/file/d/1a9Xs1RyGRoJbdNLR0fS1V9Nl0B3_dTD3/view?usp=sharing)
Actual: Arriving at your destination in

**Comment by Gowthami1309** [comment]
1 - need check in Namma Yatri 
2,3,4,5,6,7 fixed.

**Comment by krupal-14** [comment]
1- Tested in Namma Yatri working fine.
