### ISSUE TITLE
09/11/23_YS_APK_Chat changes> Wrong chat suggestions are displaying <parent-id_2096>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4263]
#2096 
Wrong chat suggestions are displaying 

**Steps**:
1. Assign ride
2. Are u starting ?>> Finishing a trip, coming soon>>How long?>>5mins

**Expected**: User should get default suggestions. 
**Actual**: Getting are you starting? and Urgent come soon, suggestions

**Comment by Gowthami1309** [comment]
Fixed.
