### ISSUE TITLE
09/11/23_YS_APK_Chat changes> User should receive  initial suggestions, when driver is at pickup<parent-id_2096>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4264]
#2096 
User should receive  initial suggestions, when driver is at pickup

**Steps**:
1. Assign a ride
2. User should get initial suggestions at pickup- when driver is at pick-up 

**Actual**: Initials  suggestions are not coming

**Expected**: At Pickup, On my way, call me, You're unreachable

**Comment by PraveenGongada** [comment]
Expected since driver Messaged
