### ISSUE TITLE
09/11/23_YS_APK_Chat changes_same suggestions are displaying twice <parent-id_2096>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4265]
#2096 
 same suggestions are displaying twice

steps To reproduce
1.Assign a ride
2.urgent,come soon-->won't cancel,please come --road block/traffic,please wait & observe the suggestions.

Expected Result-->ok & how long suggestion should display.
Actual Result-->Ok-->How long?-->How long? is displaying

**Comment by Gowthami1309** [comment]
Fixed.
