### ISSUE TITLE
09/11/23_YS_APK_Chat changes_Codes are displaying in chat suggestions  <parent-id_2096>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4266]
#2096 
Codes are displaying in chat suggestions 

Steps:
1. Assign ride
2. Urgent come soon >>Call me, you're unreachable>>Won’t cancel, pleas come>>Waiting, will you come?
3. `Finishing a trip, coming soon`
4. Verify Codes in user suggestions 

**Actual**: Codes are coming in suggestion **(cis3ds4cs4BP)**
**Expected**: Code should not come

**Comment by Gowthami1309** [comment]
Fixed.
