### ISSUE TITLE
09/11/23_YSP_APK_Chat changes_Getting same chat suggestions twice in driver side <parent-id_2096>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4267]
#2096 
Getting same chat suggestions twice in driver side 

**Steps**:
1. Assign ride
2. Are you starting>>Call me unreachable 
3. `In traffic, please chat`
4. `Can’t chat please call`
5. Verify suggestions in driver

**Actual**: same suggestions are coming twice

**Expected**:  5mins and ok should display

![Screenshot_20231109_191427](https://github.com/nammayatri/nammayatri/assets/131981246/1b2b1e83-854d-43d2-9358-f2dd93b3b214)

**Comment by Gowthami1309** [comment]
Working as expected.
