### ISSUE TITLE
09/11/23_YS_APK_Chat changes_ Chat suggestions are not correct at pickup in user <parent-id_2096>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4270]
#2096 

 Chat suggestions are not correct at pickup in user 
 
 Steps:
 1. Assign ride
 2. Move driver location to pickup location
 3. Verify chat suggestions in user side - after i've arrived message
 
 **Expected**: At Pick-up, Call me you're unreachable, is there.
 
 **Actual**: At Pick-up, On my way, Call me you're unreachable, should be there

**Comment by PraveenGongada** [comment]
Invalid
