### ISSUE TITLE
10/11/23><NYP> <Android><Onboarding><>In the UI, we should receive a proper error message when a driver with an already linked driver's license attempts to upload it again.<parent_id_1980>

### ISSUE THREAD

**Issue by Gowthami1309** [nammayatri/nammayatri#4284]
#1980 
[In the UI, we should receive a proper error message when a driver with an already linked driver's license attempts to upload it again.](https://drive.google.com/file/d/1KPB-Q7ERhCbYH9SYhneMbV-RX7PM7lQi/view?usp=sharing)

![Screenshot 2023-11-10 at 6 10 06 PM (1)](https://github.com/nammayatri/nammayatri/assets/150240985/7a4102f7-52bd-4961-95df-c6a9408ead7e)

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Gowthami1309** [comment]
Working fine.
