### ISSUE TITLE
14/11/23_YS_APK_Chat changes> After Ride Assigned, the Sliding Screen is keep on sliding up & down direction when user silde it 4-5 times in start<parent-id_2096>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#4302]
**Describe the bug**
After Ride Assigned, the Sliding Screen is keep on sliding up & down direction when user silde it 4-5 times in start

**To Reproduce**
Make a Ride Booking
Confirm the Sliding Screen 
Slide it 4-5 times 
Observe the Issue

**Expected behavior**
should slide up or down only when user did it.

**Screenshots**
https://drive.google.com/file/d/1Ky8mOCGmcxnzrLDzytUxt8lMQ_bxtXw_/view?usp=sharing

**App (please complete the following information):**
 - Device: MI Android 9 device

**Additional context**

**Comment by krupal-14** [comment]
Retested,Working fine
