### ISSUE TITLE
14/11/23_YS_APK_Chat changes> tapping multiple times on chat widget open chat box<parent-id_2096> 

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#4305]
**Describe the bug**
tapping multiple times on chat widget open chat box

**To Reproduce**
Assign a ride
give a message from driver side and validate the chat widget at user side 
tap on widget once and observe 
tap on widget multiple times and observe

**Expected behavior**
should open chat box with in no time after tapping on widget once
**Screenshots**
https://drive.google.com/file/d/1-00CCvNMz1iWyqkNzsFcwlF81ixrHfl7/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by PraveenGongada** [comment]
Fixed

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1QERUuzetE8cLJ4F66LcO9vdCJ3i0DPdq/view?usp=sharing

Re-tested the Fix. Working as expected so closing this issue.
