### ISSUE TITLE
14/11/23_YS_APK_Chat changes> There is a glitch in the UI when the user is swiping up the bottom sheet<parent-id_2096>

### ISSUE THREAD

**Issue by Gowthami1309** [nammayatri/nammayatri#4306]
[There is a glitch in the UI when the user is swiping up the bottom sheet](https://drive.google.com/file/d/1-Xzrs7lCzVL_m5AQ7CxdEIz0lZhGjkTV/view?usp=sharing)

**Steps to reproduce**
1. Once ride got assigned 
2. Close the chat layout
3. Swipe up the bottom sheet and observe the screen.

**Actual Result**
There is a glitch in the UI when the user is swiping up the bottom sheet

**Expected Result**
Glitch should not be there in UI when the user is swiping up the bottom sheet

**Comment by PraveenGongada** [comment]
Fixed
