### ISSUE TITLE
14/11/23_YS_APK_Chat changes> In hindi language, at feedback screen, driver name (sedan - normal) should be at first <parent-id_2096>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#4308]
**Describe the bug**
In hindi language, at feedback screen, driver name (sedan - normal) should be at first
**To Reproduce**
End the RIde

**Expected behavior**
In hindi language, at feedback screen, driver name (sedan - normal) should be at first. Like : "sedan normal k sath ride rate kare"

**Screenshots**
https://drive.google.com/file/d/1AE4GPJ0NSqBqkCNoBCeF3P6jPEMlHoPK/view?usp=sharing.

**App (please complete the following information):**

**Additional context**

**Comment by PraveenGongada** [comment]
Fixed in chat screen, driver name

**Comment by 123ajay1994** [comment]
![re-test_drivername](https://github.com/nammayatri/nammayatri/assets/128033831/ed3e98de-4c53-4404-8d9a-f8d88af5abe6)

Re-opening this as fix is not validated. Driver name should be at first. moving this to backlog. 
@PraveenGongada

**Comment by 123ajay1994** [comment]
![Image](https://github.com/nammayatri/nammayatri/assets/128033831/fa8c87c2-f8cc-4a83-ba56-72963f2b3f40)

Retested, marking it done.So closing this issue.
