### ISSUE TITLE
14/11/23_YS_APK_Chat changes> After ride starts, screen shows text "you have arrived at your destination" instead ride is just started and destination is far away<parent-id_2096> #4308

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#4309]
**Describe the bug**
 After ride starts, screen shows text "you have arrived at your destination" instead ride is just started and destination is far away
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
https://drive.google.com/file/d/1P3Yds5BdNqL8uBdMnhfEJwQo9q92ocel/view?usp=sharing

**App (please complete the following information):**

**Additional context**
Happened twice

**Comment by PraveenGongada** [comment]
Fixed

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/11h_RPIzjGqugl7BctQY_gLYo5_ZfEn4S/view?usp=sharing
https://drive.google.com/file/d/1AqPJnBEmx-95ixOSI26uJ31dtpt_u0U9/view?usp=sharing

hi @PraveenGongada re-tested and validated the Fix.
