### ISSUE TITLE
17/11/23_NY_ Android_Issue-Report> Unable to see uploaded images and audio record as soon as submit the issue <parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4339]
#1980 
[Unable to see uploaded images and audio record as soon as submit the issue. User is navigating back to Report and Lost screen](https://drive.google.com/file/d/1-3xJP2qUU8X9CLc7QAN7l6Nys3eQlZfz/view?usp=sharing)

Steps:

- Complete one ride
- Click on help
- Click on Lost and found
- Click on any completed ride
- Click on report lost item to support
- Click on add voice note
- click ok
- Click on add image
- upload image
- Click on submit issue
- Verify

**Expected**: user should be retain in chat screen and should able to see uploaded details

**Comment by Sumedh-14** [comment]
Issue still exists -> https://drive.google.com/file/d/12HV5pWXq0x0GFRdMKbjCk1fzO7a-0Hr0/view?usp=sharing

**Comment by VD321** [comment]
We don't have the option to call customer support anymore, this has been removed please recheck.

**Comment by Vinaykm999** [comment]
Working fine
