### ISSUE TITLE
17/11/23_NY_ Android<Issue-Report> Android back key is not working when the user is navigating back from "Your reports" option <parent_id_1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4343]
#1980 

[Android back key is not working when the user is navigating back from "Your reports" option](https://drive.google.com/file/d/12OGXmsMFVc2rbnh9dZPxWuOW-cjt57PN/view?usp=sharing)

Steps to reproduce:
1. Launch the application
2. Tap on Hamburger>Help>Reported issues
3. Tap on Android back key and observe the screen

Expected result:

User should be navigate back to the previous screen by tapping on Android back key

Actual Result:

Android back key is not working when the user is navigating back from "Your reports" option

Repro:5/5

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by Sumedh-14** [comment]
Retested on 7/12 APK ->Working Fine
