### ISSUE TITLE
17/11/23_NY_ Android_Issue-Report> Not getting your call was successful? after call to  driver<parent_id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4344]
#1980
[Not getting your call was successful? after call to  driver
](https://drive.google.com/file/d/1GOG2Nwc0MkuPkQik4yGHyskga8RHn-hY/view?usp=sharing)
Steps:
1. Complete one ride
2. Click on help
3. Click on Lost and found
4. Click on any completed ride
5. Click on call the driver
6. navigate back from dailer pad
7. Verify screen

Expected: User should receive your call was successful? message

<img width="473" alt="image" src="https://github.com/nammayatri/nammayatri/assets/131981246/a8484e35-c420-42ef-9e89-7ededa5bf193">

**Comment by S-PRAVINKUMAR** [comment]
@Vinaykm999  this is backend issue.  @VD321 can you add this message also ?

**Comment by Sumedh-14** [comment]
Still the issue exists -> Kindly find the attachement [here](https://drive.google.com/file/d/1h8fNx6oWOzQEjytcXGGHqKO3j0lMhWs5/view?usp=sharing)

**Comment by S-PRAVINKUMAR** [comment]
this is backend issue. @VD321  please check this issue. we want to get `was your call successful?` instead of `still have issue?`

**Comment by VD321** [comment]
We don't have the option to call customer support anymore, this has been removed please recheck.

**Comment by Vinaykm999** [comment]
Working fine
