### ISSUE TITLE
17/11/23_NY_ Android_Issue-Report> Keyboard is displaying when the user taps on back/ outside of the add image pop up screen <parent_id_1980>

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#4346]
#1980
[Keyboard is displaying when the user taps on back/ outside of the add image pop up screen](https://drive.google.com/file/d/1pqQ_kkiEa5iskgUZxqX6Dg2b9i96BIF2/view?usp=sharing) 

**Steps To Reproduce**
1. Launch the application and login with the valid credentials 
2. Tap on hamburger menu and tap on "help" option 
3. Tap on any issue category in which "image" / "audio" upload option will display
4. Tap on the issue description text area > Keyboard will display and then tap back. 
5. Now tap on "image" at the bottom of the screen 
     (Ex: Tap on ride related issue > Excess amount received option) 
6. Tap on the image option at the bottom of the screen 
7. "Add image" pop up screen will display 
8. Tap on "add image" option 
9. Tap on anywhere outside of the recommended apps / Tap on the android back button and observe 

**Expected Result**
User should be in "add image" pop up screen and keyboard should not display 

**Actual Result**
Mobile keyboard is displaying.

**Comment by S-PRAVINKUMAR** [comment]
@Sumedh-14  not able to reproduce this. can you check whether it is device specific ?

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by Sumedh-14** [comment]
Retested in the APK shared on 8/12 > Working Fine - https://drive.google.com/file/d/1idRln1XiEawlt1yf4FZjThZ0FXp-X5V5/view?usp=sharing
