### ISSUE TITLE
23/11/23_YS_APK_Chat changes> UI Issues <parent-id_2096>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4427]
#2096 

1.[ ETA is showing at pickup location, it should show at vehicles point (Driver location side)- as per figma](https://drive.google.com/file/d/1CNkC1k-TmcO_S5Xy0DDuTb_D21cA1CD-/view?usp=sharing)
Figma [Link](https://drive.google.com/file/d/1DTz78nvwdv6z9KjWfpjK5PgJSflKeolU/view?usp=sharing)

**Comment by PraveenGongada** [comment]
Expected since edit pickup is not done

**Comment by PraveenGongada** [comment]
Expected, it will be done with another feature
