### ISSUE TITLE
25/11/23_NYP_APK_Changes_ Welcome splash screen of city coming in 2nd app re-launch<parent-id_1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4452]
#1980 
[Welcome splash screen of city coming in 2nd app re-launch for ](https://drive.google.com/file/d/1BU1GmtkoC4gz-DuwcCs3GeIJz88NB_H1/view?usp=sharing)

Steps To Reprdouce
1.Launch the apk.
2.Give location access.
3.Let valid city detect & select valid language, Click on confirm location.
4.Kill the app & relaunch.
5.Observe the splash screen.

Expected Result
After 1st Kill re launch splash screen should change according to the location detected.

Actual Result
After 2nd kill re launch the splash screen is changing.

Additional info:

1.Reproducibility rate is - 5/5
2.Reproducing in vivo Y21 & Android 9(redmi) and Android 12(samsung)

**Comment by witcher-shailesh** [comment]
Expected
