### ISSUE TITLE
25/11/23_NYP_APK_Changes_ Showing Location unserviceable in city selection screen for outside bengaluru(inside karanataka) location <parent-id_1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4455]
#1980 
Showing Location unserviceable in city selection screen for outside bengaluru(inside karanataka) location 

Steps:
1. Launch the driver apk in outside bengaluru
2. Verify city selection screen
![Screenshot_2023-11-25-18-49-04-68_e59db0565d3dc5de047672455dd79cdf](https://github.com/nammayatri/nammayatri/assets/131981246/ec57094b-cb03-493c-8c2f-f9636f56a3e1)

**Comment by witcher-shailesh** [comment]
Expected
