### ISSUE TITLE
<30/11/23><NYP><ANDROID><Yatri Coins><Yatri coins are reflecting on Home screen only by killing the application><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4503]
#1980 

[Yatri coins are reflecting on Home screen only by killing the application](https://drive.google.com/file/d/1QYF-18aAz-ucBQPBlAgj9dRA_FuKVnPM/view?usp=sharing)

Steps to reproduce:

1. Launch the application
2. Completed One ride with more than 1KM 
3. Observe the coins  by navigating to coins screen
4. Check the coins in Home screen

Expected result:

Coins should be added by navigating to any screen

Actual result:

Yatri coins are reflecting on Home screen only by killing the application

Repro:5/5

**Comment by vinod96424** [comment]
@DwivediAman-exe 

[Now Yatri coins are not displaying on Home screen even by kill & relaunch the app](https://drive.google.com/file/d/1ggwjSfFQL_WO7jQf1x-mXrVuqW0A13Bs/view?usp=sharing)

**Comment by krupal-14** [comment]
Working fine
https://drive.google.com/file/d/1uXHFgJq2CBZU6gGe3ntRe711JjZ8D0AG/view?usp=sharing
