### ISSUE TITLE
<30/11/23><NYP><ANDROID><Yatri coins> Date filter in ride history is affecting for both tabs Earning and Yatri coins<parent id 1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4507]
#1980 
[Date filter in ride history is affecting for both tabs Earning and Yatri coins](https://drive.google.com/file/d/1_35N4Yk7_FujsYBef8nHkqKmHjmYm2cW/view?usp=sharing)

Steps:
1. Be in yatri coins screen
2. Select the date in ride history in earning 
3. Navigate to yatri coins tab
4. Verify the date

Actual: Date is changing for both tabs

**Comment by vinod96424** [comment]
Working fine.
