### ISSUE TITLE
<30/11/23><NYP><ANDROID><Yatri Coins><Kannada Transaltion><parent id 1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4508]
1. [Used coins transaltion in kannnda can be better ](https://drive.google.com/file/d/126SOI2fH7qlDMYb4nVyVNN7ajQsu-u8v/view?usp=sharing)
[Figma](https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=79477-24215&mode=design&t=Xi91Hh4KSCM5A3Tk-0)
Expected Result: ಬಳಸಲಾದ ನಾಣ್ಯಗಳು

2.[Minimum 250 coins are required for conversion](url)
[Figma](https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=89594-78611&mode=design&t=Xi91Hh4KSCM5A3Tk-0)
Expected Result: ಪರಿವರ್ತನೆಗೆ ಕನಿಷ್ಠ 250 ನಾಣ್ಯಗಳ ಅಗತ್ಯವಿದೆ

**Comment by vinod96424** [comment]
Working fine
