### ISSUE TITLE
<30/11/23><NYP><ANDROID><Earnings><UI issues in Earnings><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4510]
#1980 

Issues
1. Proper date should be there in Ride history As per figma

![Screenshot_20231129_154206](https://github.com/nammayatri/nammayatri/assets/129082995/c7c55848-3ea9-45d3-b828-edd9562e9d5f)

2. 4 Slidadable circles should be there

![Screenshot_20231130_131920](https://github.com/nammayatri/nammayatri/assets/129082995/f8a0fc1f-1794-43ec-9531-2a8292f35b44)

3. Forward/backward arrow marks should be highlited

![Screenshot_20231130_131920](https://github.com/nammayatri/nammayatri/assets/129082995/81450973-ee25-46a4-9cdb-74ab4797d4ae)

4. User is unable to swipe the carousals

**Comment by Shikhar-24** [comment]
1. to be updated in Figma.
2. Ready
3. Expected as per Figma
4. To be added later.

**Comment by vinod96424** [comment]
Working fine
