### ISSUE TITLE
<30/11/23><NYP><ANDROID><Yatri coins> Date is selecting without clicking on Apply button<parent id 1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4512]
#1980 

[Date is selecting without clicking on Apply button](https://drive.google.com/file/d/1f12k75-LwLtdDj_-sablxJcZoJzc2H7M/view?usp=sharing)

Steps:
1. Be in yatri coins screen
2. Select the date in calendar 
3. Click on cancel button
4. Verify date selected

Actual. Without confirming date is selecting

**Comment by vinod96424** [comment]
Working fine
