### ISSUE TITLE
<30/11/23><NYP><ANDROID><Earnings><Earnings screen is navigating back to Home screen by switching the network><parent id 1980> 

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4513]
#1980 

[Earnings screen is navigating back to Home screen by switching the network](https://drive.google.com/file/d/1TaTR6OHPZY4TNA57G97PsOtNtDbrQEXv/view?usp=sharing)

Steps to reproduce:

1. launch the application
2. Tap on Earnings and Switch between the networks
3. Observe the screen

Expected result:

Earnings screen shouldn't navigate back to Home screen by switching the network

Actual result:

Earnings screen is navigating back to Home screen by switching the network

Repro:5/5

**Comment by DwivediAman-exe** [comment]
expected
