### ISSUE TITLE
<30/11/23><NYP><ANDROID><Yatri Coins><Minimum balance glider is performing some action although the convert button is disable.  ><parent id 1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4514]
#1980 
[Minimum balance glider is performing some action although the convert button is disable. ](https://drive.google.com/file/d/1LTCsI5UPkfpEsy-a4mEXmYo7ZawTYDB3/view?usp=sharing)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Click on earning -->Click on yatri coins
4.Make sure u don’t have enough coins to convert-- click on convet button
5.Observe the set coin range glider.

Expected Result
It should not perform any action.

Actual Result
It is beating when we click on convert button.

Reproducibility rate: 5/5
Device details: Vivo Y21(Android 12)

**Comment by vinod96424** [comment]
Working fine
