### ISSUE TITLE
<30/11/23><NYP><ANDROID><Earnings><Bar graph is displaying old user data><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4517]
#1980 

[Bar graph is displaying old user data](https://drive.google.com/file/d/1h4x5D_pSwY4jo7vQ9QQ1QHUPjlNibCwI/view?usp=sharing)

Steps to reproduce:

1. Launch the application
2. Login with **x** mobile number
3. check the bar graph
4. Logout & login with **Y** number
5. Observe the data in the bar graph

Expected result:

Bar graph should display new user data

Actual result:

Bar graph is displaying old user data

Repro:5/5

**Comment by Shikhar-24** [comment]
fixed

**Comment by vinod96424** [comment]
Working fine
