### ISSUE TITLE
<30/11/23><NYP><ANDROID><Earnings><Bar graph is displaying incorrect data><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4519]
#1980 

[Bar graph is displaying incorrect data](https://drive.google.com/file/d/1h4x5D_pSwY4jo7vQ9QQ1QHUPjlNibCwI/view?usp=sharing)

Steps to reproduce:

1. Launch the application
2. Select today's date and observe the graph
3. check the video~20sec

Expected result:

Bar graph should display the correct data as per the bar

Actual result:

Bar graph is displaying incorrect data

Repro:5/5

**Comment by Shikhar-24** [comment]
fixed

**Comment by vinod96424** [comment]
Working fine
