### ISSUE TITLE
<30/11/23><NYP><ANDROID><Used Coin Screen><usage Coin history have "- - 5" value displayed.><parent id 1980>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#4526]
#1980 

**Describe the bug**
-> usage Coin history have "- - 5" value displayed

**To Reproduce*
- make a penalty rides
- have - 5 coins credit 
- check in coin usage history 

**Expected behavior**
Even if having negative coins for now, should not have  negative in start of negative value. can be only "-5". 

**Screenshots**
![Screenshot_20231130-135650_Namma Yatri Partner (1)](https://github.com/nammayatri/nammayatri/assets/128033831/38888d88-ccdd-444f-8a49-c0f39457baf0)

**App (please complete the following information):**

**Additional context**

**Comment by DwivediAman-exe** [comment]
AS discussed, I had removed the limit for tester to convert coins. It is not a bug as it will never happen.

**Comment by vinod96424** [comment]
Working fine
