### ISSUE TITLE
<30/11/23><NYP><ANDROID><Home Screen><In Hindi language, Text is different as compared to English for "What is Extra earning?"><parent id 1980>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#4528]
#1980 

**Describe the bug**
In Hindi language, Text is different as compared to English for "What is Extra earning?"

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
"अतिरिक्त कमाई वह अतिरिक्त राशि है जो आपने पिकअप शुल्क, ग्राहक टिप्स और ड्राइवर अतिरिक्त के रूप में मीटर चार्ज से ऊपर अर्जित की है। अतिरिक्त अर्जित राशि आपकी कुल कमाई का हिस्सा है।"
**Screenshots**
![Screenshot_2023-11-30-16-46-50-948_in juspay nammayatripartner debug (1)](https://github.com/nammayatri/nammayatri/assets/128033831/7becdd27-388a-4dca-b1a5-3166048e7cb9)
![image (16)](https://github.com/nammayatri/nammayatri/assets/128033831/5f399e57-7c64-4546-8b0f-96c2cd716bef)

**App (please complete the following information):**

**Additional context**

**Comment by DwivediAman-exe** [comment]
Again not changed by yatri coins feature. It is as it was previously

**Comment by vinod96424** [comment]
Dev has changed the design as per the previous one. Hence this is expected, closing this
