### ISSUE TITLE
<30/11/23><NY><IPA><Waiting time> chats are cropped when user sends more characters <parent id 1980>

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4542]
#1980 

inapp banner is displaying a bit when user scroll down OTP screen

**Steps**:
1. Request a ride
2. Accept a ride
3. Send more characters chat from driver and user both
4. verify User chat screen 

**Actual**: Chat messages are cropping, not showing full messages

![IMG_0433](https://github.com/nammayatri/nammayatri/assets/131981246/e5961f77-49d4-4baf-8c46-705eb2ac21e5)

**Comment by krupal-14** [comment]
Retested,Workinf fine.


![Image](https://github.com/nammayatri/nammayatri/assets/132905061/cf052a73-bd54-4623-9b1f-da72fee7b2ff)
