### ISSUE TITLE
04/12/23_NY_IPA_String_Text is cropping in ride search screen when user assigning a ride with tip_parent id 1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4584]
#1980 
[Text is cropping in ride search screen when user assigning a ride with tip](https://drive.google.com/file/d/11DcY5FUb1OA1XG8i9Z8L6N8cqFzCe6E-/view?usp=sharing)

Steps To Reprdouce
1.Launch the ipa.
2,Login with credentials.-->select kannada language
3.Book a ride--wait until  tip display.
4.Select any tip and observe the button.

Expected Result
Text should not corp

Actual Result
Text is cropping in search with tip button

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested,Working fine.
