### ISSUE TITLE
6/12/23_Y_UIREVAMP_ View more is not showing user home screen _ Parent_id_1594

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4622]
#1594 
[View more is not showing user home screen after finishing 3 rides](https://drive.google.com/file/d/1rx7jtsqG_z7FD8h18opPOywdJxPOr8kE/view?usp=sharing)

Steps:
1. Launch apk
2. Finish 3 rides
3. Verify view more/Less in home screen

**Actual**: View more is not showing

**Comment by aryan-13** [comment]
Fixed

**Comment by Gowthami1309** [comment]
Working
