### ISSUE TITLE
6/12/23_Y_UIREVAMP_ Even though the user has completed 3 rides in the same location, only one ride is showing in the UI _ Parent_id_1594

### ISSUE THREAD

**Issue by Gowthami1309** [nammayatri/nammayatri#4625]
#1594 
[Even though the user has completed 3 rides in the same location, only one ride is showing in the UI](https://drive.google.com/file/d/1_BzlxMTWdX5ZpbZIZAgKLye6rmSFO2_A/view?usp=sharing)

**Steps to reproduce** 
1. Complete 3 or more rides from same source to different destinations
2. Observe the Recent rides in Home screen 

**Actual Result**
In Home screen only one recent ride is showing. 

**Expected Result**
Minimum 2 rides + view more rides should be shown

**Comment by aryan-13** [comment]
Fixed

**Comment by Gowthami1309** [comment]
Working as expected.

https://github.com/nammayatri/nammayatri/assets/150240985/3a294243-f02e-4872-9e5c-bd8c60bb850d
