### ISSUE TITLE
6/12/23_Y_UIREVAMP_ Previous 2 Recent searches are clearing and updating one latest recent search when user take Auto ride _ Parent_id_1594

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4626]
#1594 

[Previous 2 Recent searches are clearing and updating one latest recent search when user take Auto ride
](https://drive.google.com/file/d/1ZRoc6WALIPe-JoigvcNRfrxGmWlcZS5Q/view?usp=sharing)
**Steps**:
1. Complete 2 diff rides with any variant in car
2. Verify 2 recent searches
3. Take same ride with auto variant 
4. Finish the ride
5. Verify the recent search in home screen

Actual : Old recent searches are not showing and latest only one ride is showing in how screen

**Comment by aryan-13** [comment]
Fixed

**Comment by Gowthami1309** [comment]
Working as expected.
