### ISSUE TITLE
6/12/23_Y_UIREVAMP_ Namma yatri text is showing in User profile Assistance required section_ Parent_id_1594

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4629]
#1594 
[Namma yatri text is showing in User profile Assistance required section](https://drive.google.com/file/d/1bOVLgL8CjMdmNKogQzQKbMat0_Vsu5YB/view?usp=sharing)

Steps:
1. Open user apk
2. Select disability in profile section
3. Click on the Assistance required link for all disability 
4. Verify namma yatri text in popup

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Gowthami1309** [comment]
Issue resolved.


![Image](https://github.com/nammayatri/nammayatri/assets/150240985/0f74865a-dcf6-496e-b448-6af24a97e6f2)
