### ISSUE TITLE
11/12/23_YS_SAFETY_ UI Issues _ Parent_ID_2096

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4678]
#2096 
1. [Namma Yatri text is displaying in Yatri Saathi home screen](https://drive.google.com/file/d/1gpmMESl3mMZHB8IrhAGQMyO8QyAmzbld/view?usp=sharing)
2. [Bengaluru;s most loveable app text is displaying in home screen of Yatri Saathi apk](https://drive.google.com/file/d/1o9bChcSz0_rUq9GSWL9qnWX93-RxSS8k/view?usp=sharing)
3. [Text is cropping in about safety+ screen](https://drive.google.com/file/d/19s-3k5lbwyWb81bNnKSakXbFYEi9l_3N/view?usp=sharing)
4. Record video is not asper the figma ([Here](https://drive.google.com/file/d/1on2U8lzV2kFJH6R_QlsZajN8kaqSh0Xn/view?usp=sharing))
[Figma](https://drive.google.com/file/d/15L9RRhbZaGyD6n-_Um1gV31Q_MhHjdJ5/view?usp=sharing)
5. Red dot is not showing for new numbers in Safety+ option([Here](https://drive.google.com/file/d/1YIzN0q4CcBVzq8CLm_V2HX2ZuYD2U4Jb/view?usp=sharing))
[Figma](https://drive.google.com/file/d/1SeUGE9oH0OiMCG7MSOTMjrpI8GU9QU3X/view?usp=sharing)
6. [Safety symbol is not according to figma](https://drive.google.com/file/d/115qzUkPAuz3I5-FYiS7odthz52M9ClSV/view?usp=sharing)
7. [Emergency contact layout box is cropping](https://drive.google.com/file/d/19jX3fFDxG6yIIK2MK7FFuGrxpAwFaJO8/view?usp=sharing)
8. Namma yatri text is showing after saftey+ setup finishes ([Here](https://drive.google.com/file/d/1MZrng8-X4esTUINxrdZNZOYYN39UJi_z/view?usp=sharing))
9. Activate SOS is showing in app, it should show Activate ([Here](https://drive.google.com/file/d/1S0BAg81EjxwfWwQjxOXrc3x8arlPVHFA/view?usp=sharing))
[Figma](https://drive.google.com/file/d/15PdcIbv8U7YfiVZzLvrdaMaRs6qZEVmE/view?usp=sharing)
10. Call our support is showing in emergency request screen, it should be call yatri saathi support([Here](https://drive.google.com/file/d/1xlf27Vj3EJPLMf3EHPPfUe9PcbycWueS/view?usp=sharing))
[Figma](https://drive.google.com/file/d/1NJf4G91ulSinKWZw0Pd10CDpf_ZS7i7s/view?usp=sharing)
11. Showing Safety mode in Activation popup screen ([Here](https://drive.google.com/file/d/1zmV-V6JCSo7BGcaN8ZxewndFHv2CrbpH/view?usp=sharing))
[Figma](https://drive.google.com/file/d/1avq5ttWInolyw17iZzsX1rj_xntyBCDJ/view?usp=sharing)
12.["Your away from your current location pop-up "message is displaying in bangla language even though the user selected hindi language](https://drive.google.com/file/d/1FSQNQZIxqxDg7ouxPXr84kbhgmsi06Gp/view?usp=sharing)

**Comment by krupal-14** [comment]
1,2,

**Comment by krupal-14** [comment]
[Content of the screen is not according to figma ]([here](https://drive.google.com/file/d/1L861AzDq3dpCV1sHvZfdO9RBEqQvUOHZ/view?usp=sharing))

**Comment by krupal-14** [comment]
Retested issues 1,2- fixed
issue 3 -UI design changed for home screen so not able to retest.
