### ISSUE TITLE
12/12/23_NY-Bangalore_SAFETY_ Safety+ button is displaying inside hamburger only user is on the ride _ Parent_ID_1980 

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4699]
#1980 

[Safety+ button is displaying inside hamburger only user is on the ride](https://drive.google.com/file/d/1M5MiH3o_5jqtInQlfmxS0o5LN-hMxYa0/view?usp=sharing)

Steps to reproduce:

1. Launch the application
2. Check the Safety+ inside Hamburger menu
3. Book the ride & kill and relaunch
4. Observe the Safety+ button

Expected result:

User can able to see Safety+ irrespective of ride status

Actual result:

User is unable to see safety+ inside hamburger

Repro: 5/5

**Comment by Gowthami1309** [comment]
Working as expected.
