### ISSUE TITLE
<12/12/23><NY><Android><Reallocation>The driver is not receiving the sub-address in the re-allocation ride request pop-up<parent id 1980>

### ISSUE THREAD

**Issue by Gowthami1309** [nammayatri/nammayatri#4710]
#1980

**Describe the bug** 
The driver is not receiving the sub-address in the re-allocation ride request pop-up

**To Reproduce**

Make 2 drivers and 1 User
Search RR from User side in "Multiple Driver offer" mode
complete booking from D1
cancel the Ride from D1
observe the D2 RR.

**Expected behavior**
---> D2 should receive ride request with full address.

**Screenshots**
https://drive.google.com/file/d/1Zg4F0P0Hixs6nC8IMmG1JqmzWnnnh5r2/view?usp=sharing

**App (please complete the following information):**

Device: All
Version All

**Comment by 123ajay1994** [comment]
Re-tested after fix from @prashant601 
Validated the fix with same Source and destination 
Validated the full Address instead of "NULL" in re-allocation 
Hence Marking it as Closed.
PFA: https://drive.google.com/file/d/1qpim5xmy4jL2SzicV2O7cZKr4uPB4yAi/view?usp=sharing
