### ISSUE TITLE
<12/12/23><NY><Android><Reallocation>'Looking for another ride' screen is not appearing when the ride is being reallocated. <parent id 1980>

### ISSUE THREAD

**Issue by Gowthami1309** [nammayatri/nammayatri#4711]
#1980

**Describe the bug**
'Looking for another ride' screen is not appearing when the ride is being reallocated

**To Reproduce**

Make 2 drivers and 1 User
Search RR from User side in "Multiple Driver offer" mode
complete booking from D1
cancel the Ride from D1
observe the User side screen and D2 RR.

**Expected behavior**
---> user side Screen should be of Ride Search with "Looking for another ride" text

Attachment 
https://drive.google.com/file/d/1mm03QOvJf4dbgD_8_2iaY4amFm627yBi/view?usp=sharing

App (please complete the following information):

Device: All
Version All

**Comment by 123ajay1994** [comment]
Closed with related bug: https://github.com/nammayatri/nammayatri/issues/4768
