### ISSUE TITLE
14/12/23_YS_SAFETY_ Timer is having an issue, as soon as record emergency video, video is getting saved and shared_ Parent_ID_2096

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#4749]
#2096 
1. Timer is having an issue, as soon as record emergency video, video is getting saved and shared
2. and also error message is showing when we cancel uploading video
[Proof Link](https://drive.google.com/file/d/1vgZLlUszvqsOae7ylBlHFDykJPwPe0HX/view?usp=sharing)

Steps: 

- Enable safety 
- Start Record
- Verify

**Comment by 123ajay1994** [comment]
This issue has been validated successfully in re-testing. 
PFA: https://drive.google.com/file/d/14xDNbvkrC0usvojsGRl1nGit5IBslX5D/view?usp=sharing

Closing this.
