### ISSUE TITLE
<13/12/23><NYP><ANDROID><Yatri coins><Getting Yatri coins option when the user logged from Hyderabad city><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4758]
#1980 

[Getting Yatri coins option when the user logged from Hyderabad city](https://drive.google.com/file/d/1J04lzFjJfMRc7rMiH1w1b1OS_AkfXB3d/view?usp=sharing)
Steps to reproduce:

1. Launch the application
2. Login in Hyderabad location
3. Observe the Yatri coins pop & Yatri coins screen

Expected result: 

Yatri coins pop/ Yatri coins screen shouldn't come when the user logged in from Different city except Bangalore

Actual result:

Getting Yatri coins option when the user logged from Hyderabad city

Repro: 5/5

**Comment by krupal-14** [comment]
Retested,Working fine.
