### ISSUE TITLE
<13/12/23><NYP><ANDROID><Yatri coins><Coins are not reducing after converting them><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4760]
#1980 

[Coins are not reducing after converting them](https://drive.google.com/file/d/17fuX35CVS-semjL-tDK5s4yiJhDLcn_c/view?usp=sharing)

Steps to reproduce:

1. Launch the application
2. Convert the coins to rupees
3. And observe the screen even after re launching

Expected result:

Coins should be reduced by the convertion

Actual result:

Coins are not reducing after converting them

Repro: 5/5

**Comment by krupal-14** [comment]
Retested, Working fine.
