### ISSUE TITLE
<13/12/23><NYP><ANDROID><Yatri coins><Translation Issues><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4764]
1. Telugu translation issues on Below screen
![Screenshot_20231214_170135](https://github.com/nammayatri/nammayatri/assets/129082995/efd0d85f-ea02-4e5c-9268-c69a25f22104)

a. 50rs will be adjusted against your subscription plan--> 50రూ మీ సబ్‌స్క్రిప్షన్ ప్లాన్‌కు సర్దుబాటు చేయబడుతుంది

![Screenshot_20231214_185836](https://github.com/nammayatri/nammayatri/assets/129082995/bea2bfb4-388d-430d-a723-74925e6e7150)

b. What will my coins be converted to?--> నా నాణేలు దేనికి మార్చబడతాయి?

c. Yatri coins will be converted into discounts that you can avail against your subscription plan. -->యాత్రి నాణేలు మీ సబ్‌స్క్రిప్షన్ ప్లాన్‌కు మీరు పొందగలిగే డిస్కౌంట్‌లుగా మార్చబడతాయి

<img width="306" alt="Screenshot 2023-12-14 at 7 04 52 PM" src="https://github.com/nammayatri/nammayatri/assets/129082995/bd391bb4-5eb5-4afb-99ff-7af8d62b04c9">

d. 75rs will be adjusted in your future subscription plans.-->మీ భవిష్యత్ సబ్‌స్క్రిప్షన్ ప్లాన్‌లకు 75 రూపాయలు అడ్జస్ట్ చేయబడతాయి

2. Images should be as per figma
3. 'Ok' button is missing in Tamil language
4. "₹" Symbol is missing on the text
5. Remove the decimal number in the amount
![Screenshot_20231214_190815](https://github.com/nammayatri/nammayatri/assets/129082995/fa43fe61-f680-4021-b2f3-b422d0b73ff8)

**Comment by Sumedh-14** [comment]
Issue 5 is fixed.

**Comment by DwivediAman-exe** [comment]
@vinod96424 i need fixed transalations :
for 
1. will be adjusted in your future subscription dues
2. has been adjusted in your subscription dues

**Comment by DwivediAman-exe** [comment]
fixed
