### ISSUE TITLE
<13/12/23><NYP><ANDROID><Yatri coins><Telugu language option is missing in Redmi device><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4765]
#1980 

[Telugu language option is missing in Redmi device](https://drive.google.com/file/d/1GTKTaPXk_F1CP7LFAAwDtMmsYmWct059/view?usp=sharing)

Steps to reproduce:
1. Launch the application
2. Go to Language screen and observe

Expected result: 

Telugu language also should be there

Actual result:

Telugu language option is missing

Repro: 5/5

**Device: Redmi Note 5 Pro, Android 9**

**Comment by Sumedh-14** [comment]
Working Fine. Hence closing this issue . [[here](https://drive.google.com/file/d/1uYNnLdwUEE34gb5aG6H6MnowGytPRu6E/view?usp=sharing)]
