### ISSUE TITLE
<14/12/23><NY><Android><Reallocation><Cancel option is not there in Re-allocation><parent id 1980>

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#4768]
#1980 
Iteration 2
**Describe the bug**
Cancel option is not there.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
<img width="318" alt="image" src="https://github.com/nammayatri/nammayatri/assets/128033831/1850bede-fe43-4738-a862-c7f061655f8d">

**Screenshots**
![Screenshot_20231214-192244](https://github.com/nammayatri/nammayatri/assets/128033831/42f79b88-29b1-4936-8229-908e584d3aad)

**App (please complete the following information):**

**Additional context**

**Comment by ashishsingh101** [comment]
@123ajay1994 should we show cancel option there can be edge cases which can break the flow

**Comment by 123ajay1994** [comment]
@ashishsingh101 Can we Include Concern PM here to confirm if we can add "cancel" as mentioned in Figma.

**Comment by 123ajay1994** [comment]
<img width="1034" alt="image" src="https://github.com/nammayatri/nammayatri/assets/128033831/9d97db61-723b-4946-8f5d-3c351c0e20c2">
Marking it as Expected as per confirm discussion.
Hence Closing this ticket.
