### ISSUE TITLE
15/12/23_NYP_Mascot_The Driver mascot is not updating on the home screen _ Parent_ID_1980

### ISSUE THREAD

**Issue by Gowthami1309** [nammayatri/nammayatri#4773]
#1980 

[After changing the gender in the profile screen, the Driver mascot is not updating on the home screen. It only updates after killing and re-launching the app](https://drive.google.com/file/d/1f3Rd5zKSL23HzSGjjDXbS5O_GO-7Pud4/view?usp=sharing)

**Steps to reproduce:**
1. Launch the application
2. Goto driver profile screen
3. Change the gender
4. Go back to home screen and observe the driver mascot 

**Actual Result**
After changing the gender in the profile screen, the Driver mascot is not updating on the home screen. It only updates after killing and re-launching the app

**Expected Result**
The mascot image should be updated immediately on the home screen after changing the gender in the profile screen

**Reproduced** 
5/5

**Comment by ashkriti** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine
