### ISSUE TITLE
15/12/23_NYP_Mascot_There is a referral code screen instead of a leaderboard for Bangalore city _ Parent_ID_1980

### ISSUE THREAD

**Issue by Gowthami1309** [nammayatri/nammayatri#4774]
#1980
[There is a referral code screen instead of a leaderboard for Bangalore city](https://drive.google.com/file/d/1OXRPlkmVY_LNeYsG6mOmPwKfPffd1l_l/view?usp=sharing)

**Steps to reproduce:**
1. Launch the application
2. Tap on "Contest" and observe the screen

**Actual Result**
There is a referral code screen instead of a leaderboard for Bangalore city

**Expected Result**
 Leaderboard should be there for Bangalore city

**Comment by krupal-14** [comment]
Retested ,Working fine.
https://drive.google.com/file/d/1gygY7mzpyEG85Dtq2e2hZ2IMudlpLAYe/view?usp=sharing
