### ISSUE TITLE
<14/12/23><NYP><ANDROID><Yatri coins><UI issues in Coins><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4777]
#1980 

The below screens are not working in the APK

<img width="470" alt="Screenshot 2023-12-15 at 1 50 39 PM" src="https://github.com/nammayatri/nammayatri/assets/129082995/3f8d1d73-0919-4097-9b05-2dccefaa9e05">

**Comment by Shikhar-24** [comment]
lottie is not provided for first screen.
and second is screen is to be changed.   cc:@tejkranthi

**Comment by DwivediAman-exe** [comment]
1st Lottie screen is done. 
2nd popup is removed in the product requirement for now.

**Comment by Sumedh-14** [comment]
Working fine.
