### ISSUE TITLE
15/12/23_NYP_Mascot_Whenever double tap is made in the registration screen, the application gets minimized_Parent_Id_1980

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#4786]
#1980
[Whenever double tap is made in the registration screen, the application gets minimized](https://drive.google.com/file/d/1y4eGYAahJZ-KYe5Ecs-y7TMJgtWmr6te/view?usp=sharing)

**Steps To Reproduce**
1. Launch the application 
2. Login with the new driver number (Unregistered Driver) 
3. In registration screen, Double tap on the screen and observe (before uploading any doc)
Or

   Upload DL and RC then try to  tap anywhere on the screen. ([PFA](https://drive.google.com/file/d/15jwsWNNFAh8b9YbXZr3Ae0uMOHJn3PdC/view?usp=sharing))

**Expected Result**
User should stay in the application 

**Actual Result**
The application gets minimized.

(Reproducability Rate - 5/5)

**Comment by ashkriti** [comment]
Fixed by @Rohit4997

**Comment by Sumedh-14** [comment]
Working Fine and  Hence closing this issue
