### ISSUE TITLE
15/12/23_NYP_Mascot_The driver is getting a male mascot image in the cancel ride screen irrespective of gender._ Parent_ID_1980

### ISSUE THREAD

**Issue by Gowthami1309** [nammayatri/nammayatri#4788]
#1980

[The driver is getting a male mascot image in the cancel ride screen irrespective of gender.](https://drive.google.com/file/d/1peLLrNNRMi_Qtv5qqLWde9HH_XAummhi/view?usp=sharing)

**Steps to reproduce**
1. Launch the app
2. Accept a ride request
3. Cancel ride request and observe the image

**Actual Result**
The driver is getting a male mascot image in the cancel ride screen irrespective of gender.

**Expected Result**
The driver should get mascot image in the cancel ride screen respective of gender updated in profile.

**Comment by kavya-shree-s** [comment]
Closed this issue as its not required now
