### ISSUE TITLE
19/12/23_NYP_Mascot_Change language is displaying in tamil lanaguge even the selected location is Mysore_Parent_ID_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4817]
@1980
[Change language is displaying in tamil lanaguge even the selected location is Mysore](https://drive.google.com/file/d/1JAlmGxCN2KPrA-L7yLsTwbGtINQA6Osr/view?usp=sharing)

Steps to Reproduce
1.Launch the apk.
2.select the location mysore
3.Observe the **change language** text in the bracket().

Expected Result
The particular text(**change language**) should display in kannnada.

Actual Result
The particular text is displaying in tamil language.

**Comment by ashkriti** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested, working fine.
