### ISSUE TITLE
<19/12/23><NYP><ANDROID><Yatri coins><Help Section translation issues for all the languages><parent id 1980>

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#4820]
#1980

Tamil Translation : 
- "[Yatri Coins FAQs](https://drive.google.com/file/d/17UKo4H3oq2Jtwxmk3usrQb8JqkRpa2bz/view?usp=sharing)" in headers should be translated to "[யாத்ரி நாணயங்கள் குறித்த கேள்விகள்](https://drive.google.com/file/d/1QOhkEGy0gpy8T9brbQgTJtR928KdR357/view?usp=sharing)"
- ["What are Yatri Coins](https://drive.google.com/file/d/17UKo4H3oq2Jtwxmk3usrQb8JqkRpa2bz/view?usp=sharing)" should be translated to **யாத்ரி நாணயங்கள் என்றால் என்ன?**
- "[What is the eligibility to earn and use yatri coins](https://drive.google.com/file/d/17UKo4H3oq2Jtwxmk3usrQb8JqkRpa2bz/view?usp=sharing)" should be translated to "**யாத்ரி நாணயங்களை சம்பாதிப்பதற்கும் பயன்படுத்துவதற்கும் என்ன தகுதி  பெற வேண்டும்**?"
- "[learn about yatri coins](https://drive.google.com/file/d/17UKo4H3oq2Jtwxmk3usrQb8JqkRpa2bz/view?usp=sharing)" should be translated to "**யாத்ரி நாணயங்கள் பற்றி அறியவும்**"
- "[Yatri Coins are the rewards you earn on day-to-day activities on Namma Yatri like rides, referrals, good ratings, etc.](https://drive.google.com/file/d/1Wd8A8fv78zSB_u5JJ9udOm1Mge3CpcAm/view?usp=sharing)" should be translated to "யாத்ரி நாணயங்கள் என்பது நம்ம யாத்ரியில் சவாரிகள், பரிந்துரைகள், நல்ல மதிப்பீடுகள் போன்ற அன்றாட நடவடிக்கைகளில் நீங்கள் சம்பாதிக்கும் வெகுமதிகளாகும்."
- "[Earned coins can be used to avail discounts(Example:Discounts in purchasing subscription plans using coins)](https://drive.google.com/file/d/1Wd8A8fv78zSB_u5JJ9udOm1Mge3CpcAm/view?usp=sharing)" should be translated to  "சம்பாதித்த நாணயங்களை, தள்ளுபடிகள்  பெறப் பயன்படுத்தலாம்.( எடுத்துக்காட்டு: நாணயங்களைப் பயன்படுத்தி சந்தா திட்டங்களை வாங்குவதில் தள்ளுபடிகள் பெறலாம்"
- "[Each Yatri Coin can be converted to a discount of Rs. 0.10 and can be used for availing discounts on subscription plans. More avenues to avail discounts will be added in the future](https://drive.google.com/file/d/1Wd8A8fv78zSB_u5JJ9udOm1Mge3CpcAm/view?usp=sharing)" should be translated to "ஒவ்வொரு யாத்ரி நாணயத்தையும் ரூ. 0.10 தள்ளுபடியாக மாற்றலாம் மற்றும் சந்தா திட்டங்களில் தள்ளுபடியைப் பெற பயன்படுத்தலாம். தள்ளுபடிகளைப் பெறுவதற்கான கூடுதல் வழிகள் எதிர்காலத்தில் சேர்க்கப்படும்"
- ["What are Yatri Coins](https://drive.google.com/file/d/1Wd8A8fv78zSB_u5JJ9udOm1Mge3CpcAm/view?usp=sharing)" text in headers should be translated to **யாத்ரி நாணயங்கள் என்றால் என்ன?**
- "[You must complete your first ride with Namma Yatri to start earning Yatri Coins.](https://drive.google.com/file/d/17CywsJCqRKa40h_-hyO3MF3BqGxrf6U7/view?usp=sharing)"should be translated to "யாத்ரி நாணயங்களைப் பெற, நம்ம யாத்ரியுடன் உங்கள் முதல் பயணத்தை முடிக்க வேண்டும்."
- "[The Yatri Coins section will be disabled until you complete your first ride.](https://drive.google.com/file/d/17CywsJCqRKa40h_-hyO3MF3BqGxrf6U7/view?usp=sharing)" should be translated to "உங்கள் முதல் பயணத்தை முடிக்கும் வரை யாத்ரி நாணயங்கள் பிரிவு முடக்கப்படும்."
- "[8+ rides in a day](https://drive.google.com/file/d/1QXvTuAQdSxJz1jhd_ekFRlNJ2YmCxMTf/view?usp=sharing)" should be translated to "ஒரு நாளில் 8+ சவாரிகள்"
- "[1 or 2 star ratings for the trip](https://drive.google.com/file/d/1QXvTuAQdSxJz1jhd_ekFRlNJ2YmCxMTf/view?usp=sharing) should be translated to  "பயணத்திற்கான 1 அல்லது 2 நட்சத்திர மதிப்பீடுகள்"

**Comment by Gowthami1309** [comment]
**Telugu Translation**

1. Yatri Coins FAQs - యాత్రి నాణేలు తరచుగా అడిగే ప్రశ్నలు
2. How many coins do I gain or lose for various actions? - వివిధ చర్యల కోసం నేను ఎన్ని నాణేలను పొందగలను లేదా కోల్పోతాను?
3. Each Yatri Coin can be converted to a discount of Rs. 0.10 and can be used for availing discounts on subscription plans. More avenues to avail discounts will be added in the future - ప్రతి యాత్రి కాయిన్‌ని రూ 0.10 తగ్గింపుగా మార్చుకోవచ్చు మరియు సబ్‌స్క్రిప్షన్ ప్లాన్‌లపై డిస్కౌంట్‌లను పొందేందుకు ఉపయోగించవచ్చు. భవిష్యత్తులో డిస్కౌంట్‌లను పొందేందుకు మరిన్ని మార్గాలు జోడించబడతాయి
4. Customer Referral - కస్టమర్ రెఫరల్
5. Leaderboard - Weekly Top 500 - లీడర్‌బోర్డ్ - వారంవారీ టాప్ 500
6. 8+ rides in a day - ఒక రోజులో 8+ రైడ్‌లు
7. 5-Star Rating for the Trip - ట్రిప్ కోసం 5-స్టార్ రేటింగ్
8. Booking Cancellation -బుకింగ్ రద్దు

**Comment by Shikhar-24** [comment]
done

**Comment by Sumedh-14** [comment]
Above mentioned translation issues are fixed for both the tamil and telugu languages. 

New issue: 
1. When tamil language is selected then "Help" text is translated in telugu instead of tamil. [[Here](https://drive.google.com/file/d/1vJfOF-n-roRW2OZ5xEjA2u_ctNsBQCue/view?usp=sharing)]
2. When telugu language is selected then "Help" text is translated in tamil instead of telugu. [[Here](https://drive.google.com/file/d/1d0h7xxFaVn_7WND7YxIepxevBt-7o0gh/view?usp=sharing)]
3. In tamil language, "Booking Cancellation" text can be translated to "சவாரி ரத்து"

**Comment by DwivediAman-exe** [comment]
fixed

**Comment by Sumedh-14** [comment]
i,ii,iii are closed. hence closing this ticket
