### ISSUE TITLE
<19/12/23><NYP><ANDROID><Yatri coins><Old drivers are receiving the message 'Complete the first ride to unlock coins' on their first launch><parent id 1980>

### ISSUE THREAD

**Issue by Gowthami1309** [nammayatri/nammayatri#4829]
#1980
[Old drivers are receiving the message 'Complete the first ride to unlock coins' on their first launch](https://drive.google.com/file/d/1GfSRUQJ8F5IoaCZ8GQgGPG1jW9VYOdAf/view?usp=sharing)

**Steps to reproduce** 

1. Login into the app
2. Tap on **Earrings** 
3. Tap on **Yatri coins** and observe the screen

**Actual Result**
Old drivers are receiving the message 'Complete the first ride to unlock coins' on their first launch.

**Expected Result**
Old drivers should able to see earned Yatri coins screen

**Comment by Shikhar-24** [comment]
fixed

**Comment by Sumedh-14** [comment]
Working fine
