### ISSUE TITLE
<28/12/23><NYP><ANDROID><Yatri coins> Background action is happening when we click on android back button<parent id 1980>

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#4897]
#1980
[Background action is happening when we click on android back button](https://drive.google.com/file/d/1y7KwnzBkNz1AW95MOqqap_rwzfCcpGQd/view)

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.navigate to yatri coins-->click on use coins.
4.Click on i button of convert coins
5.Click android back button & observe

Expected result
Pop-up should disappear.

Actual Result
Pop-up is as it is background action is happening.  

Device details : Vivo Y21 (Android 12)
Frequency : 5/5.

**Comment by DwivediAman-exe** [comment]
fixed

**Comment by krupal-14** [comment]
Retested,Working fine.
