### ISSUE TITLE
17/01/24_NY_iPA_ Booking preference is not clickable _Parent Id_1980 

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#5065]
#1980 
[Booking preference is not clickable](https://drive.google.com/file/d/18_vhgBHkoWZk1f7g7UtC9a64yxTH460E/view?usp=sharing)

1. Launch ipa
2. Search for a ride
3. Click on booking option

**Actual**: Booking preference is not clickable

**Comment by Shikhar-24** [comment]
done

**Comment by Vinaykm999** [comment]
Working fine
