### ISSUE TITLE
17/01/24_NY_iPA_ UI Issues _Parent Id_1980

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#5066]
#1980 

1. View Rate card icon is not showing in estimates screen [Here](https://drive.google.com/file/d/1bCtX4xzzMF6ePdHl5MV1s0gQtZ97YOZo/view?usp=sharing)
2. Auto capacity (No of users) icon is not showing in estimates screen ([Here](https://drive.google.com/file/d/1sIrEO1D_68GGseBAD60gl2hujbg1TThP/view?usp=sharing))
3. Suggested destination and recent rides icon is missing and 1click icon is also missing ([Here](https://drive.google.com/file/d/1dMf_PnFyOXN7cp89LL1zcUKwatDmo14T/view?usp=sharing))
4. "Namma yatri" icon is cropping when user clicks on where to & clicks back ([Here](https://drive.google.com/file/d/1ShZdO9Nw1ZN-LLOttNqlEhE71XFtzMqK/view?usp=sharing))
5. Recent rides Are not aligned properly ([Here](https://drive.google.com/file/d/1twx4-Ny6cB0Lqe3_CZFUMnpLhD38YBlo/view?usp=sharing))

**Comment by Shikhar-24** [comment]
1,2,3 done

**Comment by Vinaykm999** [comment]
@Shikhar246 
4th issue is still exist in iPhone SE devices

**Comment by Shikhar-24** [comment]
4,5 also done

**Comment by krupal-14** [comment]
Issues 1,4- working fine

**Comment by Vinaykm999** [comment]
3, 5 fixed
