### ISSUE TITLE
17/01/24_NY_iPA_ Address is not updating _Parent Id_1980 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5067]
#1980
[Address is not updating when user is selecting address from locate on map](https://drive.google.com/file/d/1G84ELGCVNn6oVJSQwO63jWndNCltuvjN/view?usp=sharing)

Steps To Reproduce
1.Login with valid credentials.
2.Click on where to
3.click on select on map.
4.drag the pointer and observe.

Expected Result
Address should update.

Actual Result
Address is not updating

**Comment by 123ajay1994** [comment]
https://drive.google.com/file/d/1Vy6Y7ACi467iokQHBSc3S_QyVjiWCbck/view?usp=sharing

This issue is still exists in latest revised IPA. 
Kindly consider is "Re-open".

**Comment by krupal-14** [comment]
Retested, Adress is updating
