### ISSUE TITLE
17/01/24_NY_iPA_Wrong OTP error message is not displaying when user enters wrong OTP _Parent Id_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5068]
#1980
[Wrong OTP error message is not displaying when user enters wrong OTP](https://drive.google.com/file/d/1md5GFFO3BlGLXs0hMTfr89t6d4yhHUnP/view?usp=sharing)

Steps To Reproduce
1.Launch the ipa.
2.Enter the mobile number.
3.Enter wrong OTP & observe.

Expected Result
Wrong otp error message should display.

Actual Result
Navigating to the enter mobile number screen.

**Comment by Vignesh-772** [comment]
Expected. This number might be blocked because of multiple retries.

**Comment by krupal-14** [comment]
No @Vignesh-772  for new number this issue is coming.
