### ISSUE TITLE
17/01/24_NY_iPA_ Hamburger menu is opening when user clicks on recenter icon _Parent Id_1980

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#5069]
#1980 
[Hamburger menu is opening when user clicks on recenter icon ](https://drive.google.com/file/d/1IhmbB5eo3Ew0EzYRCyrr6sVsRmZcyITP/view?usp=sharing)

**Steps:**
1. Click on hamburger menu
2. Click on my rides
3. Click on View details
4. Navigate back to home screen
5. Tap on recenter icon
6. Verify 

**Actual:** Hamburger is opening on click of recenter icon

**Comment by Shikhar-24** [comment]
done

**Comment by Vinaykm999** [comment]
Working fine
