### ISSUE TITLE
17/01/24_NY_iPA_ Auto icon is not showing in polyline before and after start ride _Parent Id_1980

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#5072]
#1980 

[ Auto icon is not showing in polyline before and after start ride](https://drive.google.com/file/d/1sHxkyOFP4ZcTX4sAEoGr9asT_eNGblk4/view?usp=sharing)

Steps:
1. Assign ride
2. Verify auto icon and polyline as well
3. Start the ride and verify polyline and auto icon

**Note:** Polyline is also not updating

**Comment by krupal-14** [comment]
Retested,Working fine
