### ISSUE TITLE
17/01/24_NY_iPA_ App crashing while doing Repeat Ride_Parent Id_1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#5073]
#1980 

**Describe the bug**
App crashing while doing Repeat Ride

**To Reproduce**
- launch the application 
- Tap on hamburger
- validated Ride List
- Tap on "Repeat Ride"
- Observe the Issue

**Expected behavior**
App should not crash

**Screenshots**
https://drive.google.com/file/d/1wRzbRLGCQVETdMLvhGf3b5OQ1_dM2R1V/view?usp=sharing
in.juspay.nammayatri.debug_issue_0cf1d712bcc60667e6d74919c3bba31d_crash_session_eae78e8d483e4d4da2be755f7aa4ae5f_DNE_0_v2_stacktrace.txt

<img width="1289" alt="image" src="https://github.com/nammayatri/nammayatri/assets/128033831/a149b439-c4b4-4d72-add4-b0e5bca93dbd">

**App (please complete the following information):**
 - Device: [iPhone SE]

**Additional context**
-device Specific
- 10/10

**Comment by 123ajay1994** [comment]
in.juspay.nammayatri.debug_issue_0cf1d712bcc60667e6d74919c3bba31d_crash_session_eae78e8d483e4d4da2be755f7aa4ae5f_DNE_0_v2_stacktrace.txt

**Comment by 123ajay1994** [comment]
Hi @Shikhar-24 This crash is still happening but now with below patteren:
- Tap on repeat ride
- cancel auto fetching booking
- tap backpress
- navigate to "My Rides" again and tap on repeat ride again.
- Observe the issue

PFA Link: https://drive.google.com/file/d/12o4P_LiLc1a0tmUPjPF64ICvcnv73lpL/view?usp=sharing

Kindly consider this Issue "Re-Open".

**Comment by 123ajay1994** [comment]
[in.juspay.nammayatri.debug_issue_0cf1d712bcc60667e6d74919c3bba31d_crash_session_dac736edbd394287a9971798114f1f87_DNE_0_v2.log](https://github.com/nammayatri/nammayatri/files/13987450/in.juspay.nammayatri.debug_issue_0cf1d712bcc60667e6d74919c3bba31d_crash_session_dac736edbd394287a9971798114f1f87_DNE_0_v2.log)
[in.juspay.nammayatri.debug_issue_0cf1d712bcc60667e6d74919c3bba31d_crash_session_dac736edbd394287a9971798114f1f87_DNE_0_v2_stacktrace.txt](https://github.com/nammayatri/nammayatri/files/13987451/in.juspay.nammayatri.debug_issue_0cf1d712bcc60667e6d74919c3bba31d_crash_session_dac736edbd394287a9971798114f1f87_DNE_0_v2_stacktrace.txt)

**Comment by Shikhar-24** [comment]
done

**Comment by krupal-14** [comment]
Retested,Working fine
