### ISSUE TITLE
17/01/24_NY_iPA_ Previously reported issue images and recording is showing in another issue report option _Parent Id_1980 

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#5076]
#1980 
[Previously reported issue images and recording is showing in another issue report option](https://drive.google.com/file/d/1a9JvPzlc5WzvfS7aeNcGhX6LHkjX2Ysu/view?usp=sharing)

Steps:
1. Report issue for lost and found with 3 images and one voice recording
2. Report the issue
3. Report issue under safety 
4. Tap on any one safety issue
5. Verify the issue report screen

**Actual:** Previously uploaded images and recordings are showing

**Comment by S-PRAVINKUMAR** [comment]
fixed

**Comment by Vinaykm999** [comment]
Working fine
