### ISSUE TITLE
19/01/24_NY_iPA_  Screen after start ride, buttons are not clickable after a pattern _Parent Id_1980

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#5120]
#1980 

**Describe the bug**
"Real Time Tracking" & share button are not visible at first than after kill and relaunch & tapping multiple times on "Real Time Tracking",  Any buttons on screen are not clickable 

**To Reproduce**
- book a ride
- start a ride
- Observe the Screen, "Real Time Tracking"  will not be displayed.
- Kill and re-launch the app and observe the "Real Time Tracking" and share button. 
- Do multiple tapping on ""Real Time Tracking" " and than try to tap on any buttons(share app, hamburger, emergency )

**Expected behavior**
Other buttons should be clickable. 

**Screenshots**
https://drive.google.com/file/d/1JY3r_DqQDIx9Y3lvLK4rHQdJh-9KwXgt/view?usp=sharing

**App (please complete the following information):**
 - Device: [ALL]

**Additional context**
note: "Real Time Tracking" , backend is failing here. "/driver/location" EP.

**Comment by Shikhar-24** [comment]
screen blocking is fixed
"Real Time Tracking" not being displayed is due to api failure (backend issue).

**Comment by krupal-14** [comment]
Retested this issue in CUG (1.8.192)- working fine
