### ISSUE TITLE
28/01/24_NY_Android_ Sos flow and Follow ride flow _Home Screen_Safety Banner not swipeable as per figma_ Parent Id_1980 

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#5188]
#1980 
**Describe the bug**
Safety Banner not swipeable as per figma

**To Reproduce**
-log in after Onboarding
- validate Home Screen
- Observe Safety banner

**Expected behavior**
<img width="314" alt="image" src="https://github.com/nammayatri/nammayatri/assets/128033831/397ab8f8-226f-4456-801f-bad9d70c91bb">

**Screenshots**
![Screenshot_20240128-161020](https://github.com/nammayatri/nammayatri/assets/128033831/9a97e5b4-0454-4811-b292-e752cbd5fc93)

**App (please complete the following information):**

**Additional context**

**Comment by Vignesh-772** [comment]
This is expected. As carousel is not added in customer.
