### ISSUE TITLE
28/01/24_NY_Android_ Sos flow and Follow ride flow _Safety Screen-  "Learn about safety" screen_Learn More have 3 videos which are not related with videos heading _ Parent Id_1980 

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#5189]
#1980 
**Describe the bug**
a.Learn More have 3 videos which are not related with videos heading
b.Improper font of videos heading
c. in hindi , videos headings are in english

**To Reproduce**
- tap on hambergur
- go to "safety"
- tap on learn more 
- Observe the 3 videos and their heading from "Learn about safety"

**Expected behavior**
should have info about Namma yatri along with Safety Measure & about SOS in related videos info

**Screenshots**
https://drive.google.com/file/d/1rioK0mVrzSKsb1CR39wTOyXGrYy7vkUA/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by prakharritik** [comment]
Videos will be uploaded to config prior to release. We can verify once then.

**Comment by krupal-14** [comment]
Retested,Working fine
