### ISSUE TITLE
28/01/24_NY_Android_ Sos flow and Follow ride flow _App is not opening when app is in killed state and user try to open thr drill notification_Parent Id_1980 #5194

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#5196]
#1980 
**Describe the bug**
App is not opening when app is in killed state and user try to open the drill notification

**To Reproduce**
kill the app
send the drill notification from another user
try to open the app from the notification 

**Expected behavior**
app should be open with drill notification and alarm should triggered. 

**Screenshots**
https://drive.google.com/file/d/1Lwk9d45ZUQWKjQZegW6hpUlZnSapO_zq/view?usp=sharing
**App (please complete the following information):**

**Additional context**

**Comment by Vignesh-772** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested the above issue working fine.[PFA](https://drive.google.com/file/d/1TSHCPapbc3CZ7Zc4dLL9wM-5K-5VkuaD/view?usp=sharing)
Device : Realme narzo(Android 12)
