### ISSUE TITLE
28/01/24_NY_Android_ Sos flow and Follow ride flow _figma have "dial police" button & in app, it is "call police"_Parent Id_1980 

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#5198]
#1980 

**Describe the bug**

figma have "dial police" button & in app, it is "call police"
**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20240128-194600](https://github.com/nammayatri/nammayatri/assets/128033831/d4f82300-64a5-4dc8-90f7-51d7d7a41219)

**App (please complete the following information):**

**Additional context**

**Comment by vinod96424** [comment]
![Image](https://github.com/nammayatri/nammayatri/assets/129082995/acc8c3d1-393f-4ce2-9312-94e510de9987)


"Dial Now" is missing here

**Comment by vinod96424** [comment]
Working fine
