### ISSUE TITLE
30/01/24_NY_Android_ Sos flow and Follow ride flow > Test drill banner is displaying once app is killed and relaunch and also disappearing once app is kill and relaunch  _Parent Id_1980

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#5236]
#1980 
[Test drill banner is displaying once app is killed and relaunch and also disappearing once app is kill and relaunch ](https://drive.google.com/file/d/1mNTt3bN6eQUEIbytKm1b7hUHMjUNKPGO/view?usp=sharing)

Steps:
1. Onboard user and verify 
2. Tap on safety banner
3. Start setup and finish setup
4. Go to home screen
5. Verify banner - banner should display
6. Kill and relaunch 
7. Verify banner
8. Finish test drill
9. Mark ride as safe
10. navigate to home screen
11. Verify banner - Banner should not display
12. kill and re launch apk and verify banner

**Comment by Sumedh-14** [comment]
Validated the above issue. Working Fine 
[PFA](https://drive.google.com/file/d/1evbZJ8zztbjA0rtdRzOZmFcCh9JNg4kP/view?usp=sharing)
