### ISSUE TITLE
31/01/24_NY_Android_ Sos flow and Follow ride flow _No flow when SOS is not marked safe and driver ended the ride_Parent Id_1980 

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#5248]
#1980 

**Describe the bug**
a. No flow when SOS is not marked safe and driver ended the ride, we are showing the Ride without Map.
b. Still showing Following ride in same secession when SOS triggered before start of Ride and ride is cancelled from Driver side or User side with or without marking safe.

**To Reproduce**
a.Book the ride
Trigger the SOS
End the Ride from Driver End
Observe the Issue at the Other User side

b. Book a ride
trigger sos
mark safe/not mark safe
cancel the ride from User side or Driver side.

**Expected behavior**
Should have some flow for this case.

**Screenshots**
![Screenshot_20240131-124127 (1)](https://github.com/nammayatri/nammayatri/assets/128033831/f8cef2df-52a3-4150-9c13-b2dfde7ff052)

**App (please complete the following information):**

**Additional context**

**Comment by krupal-14** [comment]
#5298 issue same scenario
Closing this issue.
