### ISSUE TITLE
31/01/24_NY_Android_ Sos flow and Follow ride flow _"Reached destination" pop us coming in loop along with ride follow bar at home screen in until another secession_Parent Id_1980 

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#5255]
#1980 

**Describe the bug**
"Reached destination" pop us coming in loop along with ride follow bar at home screen in until another secession

**To Reproduce**
-Book a ride
-trigger the SOS
- mark it safe
-end the ride
- validate the "Reached destination pop up" at the another user side
-mark it Done 
- validate the follow ride bar at the Home screen
- Tap on it again
- validate the "Reached the destination" safely again
- mark irt done
- observe the issue 

**Expected behavior**
- Should clear the top notification on the screen after the ride is ended and user have observe the "Reached destination" 

**Screenshots**
https://drive.google.com/file/d/1AVhDULQg01O5qECnpP6FxoE03R1122uK/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by krupal-14** [comment]
Retested,Working fine
