### ISSUE TITLE
31/01/24_NY_Android_ Sos flow and Follow ride flow _There are no videos inside Learn about safety in Hindi Language_Parent Id_1980

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#5259]
[There are no videos inside Learn about safety in Hindi Language](https://drive.google.com/file/d/1bk_bSeceP8r51Fe0HRD5f2buYun3yTKE/view?usp=sharing)

Steps to reproduce:

1. Launch the app
2. Change the user language to Hindi
3. Book the ride 
4. Tap on safety center >Learn about safety
5. Observe the screen

Expected result:

videos should be there inside Learn about safety irrespective of user selected language

Actual result:

There are no videos inside Learn about safety in Hindi Language

Repro:5/5

**Comment by prakharritik** [comment]
Videos are not added yet in config, thats why this issue. Videos will be added prior to release

**Comment by krupal-14** [comment]
Retested,Working fine
