### ISSUE TITLE
31/01/24_NY_Android_ Sos flow and Follow ride flow _ Following recipient is not getting the SOS drill_Parent Id_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5263]
#1980 
[User 2 is not getting the SOS drill when User 1 trigger the SOS but User 2 receiving the Sos FCM](https://drive.google.com/file/d/1GxG6dsX5a7gXQpUUGvxE9YIrIFNt6o0z/view?usp=sharing)

Steps To Reproduce

- User 2: 
1. Launch the apk.
2.Login with valid credentials.
3.Book a ride & be in that screen.

- User 1:
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride
4.Make sure User 2 number is already saved in the emergency contact of User 1.
5.Trigger the SOS
6.Observe User 2 screen.

Expected Result
User 2 should get the FCM & the blue color banner 

Actual Result
User 2 is getting the FCM but not getting the Mock drill sound.

Additional information : 
User 1: The user who triggers the SOS
User 2: The following recipient. 

Device details:
Realme X

**Comment by Vinaykm999** [comment]
Working fine
