### ISSUE TITLE
02/01/24_NY_Android_ Sos flow and Follow ride flow _ Current location is not being updating in the call police screen_Parent Id_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5301]
#1980 
[ Current location is not being updating in the call police screen]

Steps To Reproduce
1.Launch the apk
2.Login with valid credentials.
3.Book & Start a ride.
4.Trigger the SOS
5. Click the Call police icon
6. Observe the current location
7.Move the driver from fake location.
8.observe the current location again

Expected Result
Current location has to update when driver moves

Actual Result
Current location is not updating automatically ---->Updating when user kill & relaunch the apk.

**Comment by 123ajay1994** [comment]
It is updating now in same secession , user have to navigate till home screen and than again go to the call police section.
