### ISSUE TITLE
02/01/24_NY_Android_ Sos flow and Follow ride flow _ Test mock drill button is not displaying at safety screen _Parent Id_1980 #5301

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5309]
#1980

[User is Not getting the "Test safety drill" button]

Steps to Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Book a ride & start a ride.(User 1)
4. Trigger the SOS(User 1)--> Don’t mark the ride as safe.
5.Driver end the ride.
6. Book a ride again (User 1)
7.While ride assign state-->Click on safety
8.Observe the "Test safety drill" 

Expected Result
User should get the "Test safety drill" button

Actual Result
User is not getting the "Test safety drill"

**Comment by 123ajay1994** [comment]
it has been fixed, followed the steps and able to validate the "Test drill"

https://drive.google.com/file/d/1mRHsvkEmu0LLmCKBtUcMqdS9ANdPDLXD/view?usp=sharing
