### ISSUE TITLE
09/02/24_NY_iOS_ Sos flow and Follow ride flow _Mark Ride as Safe text is missing in SOS screen_Parent Id_1980

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#5425]
[Mark Ride as Safe text is missing in SOS screen](https://drive.google.com/file/d/1wEd8Lvjn5yye4PQp8DQowEVIyib7bT6w/view?usp=sharing)

Steps to reproduce:

1. Launch the iPA
2. Book and start the ride
3. Tap on Safety center
4. Click on SOS
5. Observe the screen

Expected result:

Mark Ride as Safe text should be there in SOS screen

Actual result:

Mark Ride as Safe text is missing in SOS screen

Repro: 5/5

**Comment by krupal-14** [comment]
Retested,Working fine
