### ISSUE TITLE
09/02/24_NY_iOS_ Sos flow and Follow ride flow _Green tick mark is missing _Parent Id_1980

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#5429]
Green tick mark is missing

![Image](https://github.com/nammayatri/nammayatri/assets/129082995/8e8d3a40-c8da-40a7-bf49-f638031f7441)

Steps to reproduce:

1. Launch the iPA
2. Book the ride and start
3. Trigger the SOS and mark as safe and complete the ride
4. Observe the recipient device

Expected result:

Green tick mark should be there

Actual result:

Green tick mark is missing

Repro: 5/5

**Comment by krupal-14** [comment]
Retested,Working fine
