### ISSUE TITLE
09/02/24_NY_iOS_ Sos flow and Follow ride flow _Ride tracking & Share ride buttons are not clickable_Parent Id_1980 #

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#5443]
[Ride tracking & Share ride buttons are not clickable](https://drive.google.com/file/d/1E97dVMkrfkF5e3P2bQnCVe6b2UWW8R4n/view?usp=sharing)

Steps to reproduce:

1. Launch the iPA
2. Book and start the ride 
3. Click on Ride tracking & Share ride app

Expected result:

Ride tracking & Share ride buttons should be clickable

Actual result:

Ride tracking & Share ride buttons are not clickable

Repro: 5/5

Device: iPhone XR, iOS 16.3

**Comment by krupal-14** [comment]
Retested,Both buttons are clickable
