### ISSUE TITLE
09/02/24_NY_iOS_ Sos flow and Follow ride flow _User is not navigating to Follow ride screen_Parent Id_1980

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#5444]
[User is not navigating to Follow ride screen](https://drive.google.com/file/d/1P7kOFGGsuwQKd0s9tljFsd4owrb9-2RP/view?usp=sharing)

Steps to reproduce:

1. Launch the iPA
2. Book and start the ride
3. Share the ride with other user
4. Tap on follow ride and observe the screen

Expected result:

User should navigate to Follow ride screen

Actual result:

User is not navigating to Follow ride screen

Repro: 5/5

**Comment by krupal-14** [comment]
Retested.Working fine
