### ISSUE TITLE
16/02/24_NY_Prod _Two source/destination pointers are displaying at confirm source location screen _Parent Id_1980

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5557]
#1980
[Two source/destination pointers are displaying at confirm source location screen](https://drive.google.com/file/d/18VFrwrJ74zBTKYEyWySyboxNVb6V1V5H/view?usp=sharing)

Steps To Reproduce
1.Add any one near to current location as a favorite location.
2.Click on where to--> Click on all favorites --> select the recently added favorite location.
3.Navigate till estimate screen 
4. Click on back button--> click on home/work button.(Make sure no favorites are added to those tags)
5.Add current location as favorite -->confirm it
6. Select that recently added location & observe the screen

Expected Result
Two pointers should not be display

Actual Result
Only source & destination  pointer should display.

**Comment by Vinaykm999** [comment]
Working fine
