### ISSUE TITLE
04/03/24_NY_Android_TIP Design_"No Tip" button is not highlighted when user selected no tip option_(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5806]
#1980
"No Tip" button is not highlighted when user selected no tip option.[[here](https://drive.google.com/file/d/1a7pE7tL2JgL7dlphBLSisslmBsxWIgIi/view?usp=sharing)]

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3. search for a ride.
4. click on add now button
5. Select  50Rs tip, click again "Add now" button validate whether it is highlighted or no. click again and see 
6.Select No Tip button click again "Add now" button validate whether it is highlighted or no. click again and see.

Expected result
No Tip button should also highlight 

Actual Result
No tip button is not highlighting 

Frequency: 3/3
Device details : Vivo Y21(Android 12)

**Comment by PraveenGongada** [comment]
Expected

**Comment by krupal-14** [comment]
Its not expected @PraveenGongada 
@Prithivirajkota  Can u confirm this once.

**Comment by PraveenGongada** [comment]
Expected confirmed by @Prithivirajkota
