### ISSUE TITLE
04/03/24_NY_Android_TIP Design_ "Continue search with X amount" button is flickering sometimes_(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5807]
#1980
"Continue search with X amount" button is flickering sometimes.[[Here](https://drive.google.com/file/d/1-qfbCd58kHbXlcCvNZB6jI1K6iqpQpQ5/view?usp=sharing)]

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Search for a ride without a tip.
4. Wait untill tip option comes .
5.Click randomly on all the tip options quite fast & observe the  "Continue search with X amount" button

Expected Result
"Continue search with X amount"  button should not flicker

Actual Result
 "Continue search with X amount" button is flickering

Frequency : 2/2
Device details: Vivo Y21(Android 12)

**Comment by PraveenGongada** [comment]
Clicked two times on the button, Expected

**Comment by krupal-14** [comment]
As per dev comment closing this issue
