### ISSUE TITLE
04/03/24_NY_Android_TIP Design_ Progress bar is not starting from start when user initiate a new ride request with different tips_(Parent id_1980) 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5810]
#1980
Progress bar is not starting from start when user initiate a new ride request with different tips.[[here](https://drive.google.com/file/d/12hjD7Iovhu4pJDcygddFOTVmyy1Kg9ZT/view?usp=sharing)]

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Search for a ride with no tip
4.After some X seconds  add 20 Rs Tip
5.After some time add 3- Rs tip and observe the progress bar

Expected Result
progress bar should start from start when user add new tip

Actual Result
Progress bar is not starting from start when user add the new tip

Frequency: 3/3
Device details: Vivo Y21(Android 12)

**Comment by PraveenGongada** [comment]
Expected

**Comment by Sumedh-14** [comment]
As it is marked as expected, Closing this issue.
