### ISSUE TITLE
04/03/24_NY_Android_TIP Design_For chennai operating city we are getting Bengaluru tip values_(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5819]
#1980 
For chennai operating city we are getting Bengaluru tip values.[[Here](https://drive.google.com/file/d/1OJ4GdhWLQ3efExq--5Fd95Jo5cM-mGHa/view?usp=sharing)]

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.search for chennai location
4.Observe the tip options 

Expected Result
we have to get chennai tip values

Actual result
We are getting Bengaluru tip values

Frequency : 5/5
Device details: Vivo Y21(Android 12)
Mobile no: 9222222221

**Comment by PraveenGongada** [comment]
Backend issue, working fine in prod

**Comment by krupal-14** [comment]
@PraveenGongada  This issue still there in master & as mentioned above that 50 Rs is enabled for chennai city in master and so closing this issue.
