### ISSUE TITLE
04/03/24_NY_Android_TIP Design_ without selecting the tip "Continue ride with 10 Rs " button is displaying_(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#5820]
#1980
without selecting the tip "Continue ride with 10 Rs " button is displaying.[[Here](https://drive.google.com/file/d/1omPLa6b_wyI-7jB1viexd0uAfmbX458r/view?usp=sharing)]

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials
3.Search for a ride without tip & observe the ride search screen

Expected Result
Without selecting the tip button should not display.

Actual Result
Without selecting the tip the button is displaying 

Frequency : 2/2
Device details: vivo Y21(Android 12)
Mobile no- 9222222221

**Comment by PraveenGongada** [comment]
cannot reproduce this please test in new APK, if the issue still exits please provide steps

**Comment by krupal-14** [comment]
Not able to reproduce, closing this issue
