### ISSUE TITLE
06/03/24_NY_Android_TIP Design_ In estimates screen, the Autorickshaw image and the estimated amount are getting cropped_(Parent id_1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#5845]
#1980 
[ In estimates screen, the Autorickshaw image and the estimated amount are getting cropped](https://drive.google.com/file/d/1HgmeshoR13eL93MWHQRd6VGsGVJrpq5d/view?usp=sharing)

**Steps To reproduce**
1. Launch the application and login with the valid credentials 
2. Search for a ride and go to estimates screen and observe 

**Expected Result**
The estimates screen should display as per figma. The image and the estimated amount should display 

**Actual Result**
The image and the estimated amount are not displaying initially. The image and estimated amount part is scrollable which is not expected

Device details 
Samsung A51

**Comment by PraveenGongada** [comment]
will be fixed in the release now

**Comment by krupal-14** [comment]
Design changed, retested ,working fine([PFA](https://drive.google.com/file/d/1DbSYQadH_za9FV_pS39uYLU_j7MQYtD9/view?usp=sharing))
