### ISSUE TITLE
21/03/24_NY_Android_Changelog(21/03) _[BLOCKER]Showing last changed location of source instead of Current location by using edit pickup location_ (Parent id_1980)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#6052]
#1980 

**Describe the bug**
Showing last changed location of source instead of Current location by using edit pickup location

**To Reproduce**
1-Select the Destination
-Edit the pickup location to and select some other location (ie. Current location : JP Nagar, Changed location: koramangala)
-Edit again and clear the changed location (clear koramangala)
-Validate Current location tab at the bottom
-Tap on Current location
-Observe the issue

2- edit the location to special zone (Nexus mall)
- tap on current location icon
- observe the location text after being marker at current location
- confim the location
- observe the source tab 
- Validate the RR (RR have source as Nexus mall but driver is at JP nagar)
**Expected behavior**
Should always enter the current Location address(ie. JP nagar)

**Screenshots**
https://drive.google.com/file/d/1LQN6VitDoi-te6ch8H6q2x7hDf6fKeGt/view?usp=sharing

https://drive.google.com/file/d/17x3ZmrBoftBNatI8_uS1YgQja0apdzzL/view?usp=sharing

**App (please complete the following information):**
 - Device:Samsung galaxy A21s
 - Version Android 12

**Additional context**

**Comment by kavya-shree-s** [comment]
@yashikakaushik Can you check this

**Comment by vinod96424** [comment]
[Issue is still reproducing](https://drive.google.com/file/d/16Rxa5Nkm0p36eaeEq1QkSC06thsOgp_a/view?usp=sharing)

**Comment by Vignesh-772** [comment]
Where you checked?

**Comment by vinod96424** [comment]
As this is the fix from backend, I discussed with Yashika she told me to check in previously shared APK. I have checked there

**Comment by Vignesh-772** [comment]
This is not a backend fix,it is handled in frontend. Please validate it from latest main.

**Comment by vinod96424** [comment]
Working fine
