### ISSUE TITLE
21/03/24_NY_Android_Changelog(21/03)Current location is not updating when tapping on recenter in Confirm pickup location screen (Parent id_1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#6060]
#1980
[Current location is not updating when tapping on recenter in Confirm pickup location screen ](https://drive.google.com/file/d/1yNXXBV4Kewt2TjgGSu12P6-FPClTPu2Z/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with the valid credentials 
2. Tap source > search for a location and select it 
3. Select any destination 
4. In confirm pick up location screen, tap on the recenter icon and observe 

**Expected Result**
Current location should update when recenter is tapped

**Actual Result**
The selected source location is displaying.

**Comment by kavya-shree-s** [comment]
@yashikakaushik Can you check this issue

**Comment by vinod96424** [comment]
[Issue is still reproducing](https://drive.google.com/file/d/1L2gFY1cxhnPnJOiLLZq-EUCk_o8MY28L/view?usp=sharing)

**Comment by Vignesh-772** [comment]
In Which APK you check this?

**Comment by vinod96424** [comment]
As this is the fix from backend, I discussed with Yashika she told me to check in previously shared APK. I have checked there
[APK link](https://juspay.slack.com/archives/C03QT2B1KDE/p1711025265878399?thread_ts=1711021705.579289&cid=C03QT2B1KDE)

**Comment by Vignesh-772** [comment]
This is also not a backend fix it is handled in frontend. Please validate it from latest main.

**Comment by vinod96424** [comment]
Working fine
