### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_ UI Issues _(Parent id_1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#6151]
1. . For user, "Pick up" address is getting cropped when banners are displaying in the ride details screen- [PFA](https://drive.google.com/file/d/1UfjFGszA60LpAmx6PcUJKXJ_l8K4TmPZ/view?usp=sharing)  

2.Red colour pointer is displaying at pickup location when user booking intercity ride([PFA](https://drive.google.com/file/d/1mj7de3iLbFNm34MJ09-3AFxwyPKAVLcn/view?usp=sharing))

3.Double destination pointers are displaying at destination.([PFA](https://drive.google.com/file/d/1eaf0tpoK1u-jJ-ZXeSJhN57m2cpdV66m/view?usp=sharing)). ([PFA](https://drive.google.com/file/d/1Nbq4zGpEr2Lc1UFf68f8vXKIfBa2HYea/view?usp=sharing))

4.Auto icon is not displaying at the user end.Once user starts the intercity ride[[Here](https://drive.google.com/file/d/1mHKxk5dnK0b-UmOb0pug20GfurAsYtuo/view?usp=sharing)]

5.Real time tracking button is not working once the intercity ride is started.[[Here](https://drive.google.com/file/d/1v1UVDFTYKFWtmVb6p9O1o-ZZmS72Za4n/view?usp=sharing)]

6. Assets are missing in ride schedule screen.[[PFA](https://drive.google.com/file/d/1Z9EbPiRj6FnxItB38UPET9XZ5IPhPswQ/view?usp=sharing)]

**Comment by slow-codex** [comment]
Fixed :-1,5,6

**Comment by krupal-14** [comment]
Issue status :
Fixed Issue: 1,5,6
Backlog: 2,3,4

**Comment by MercyQueen** [comment]
Fixed : 2,3,4,9

**Comment by max-keviv** [comment]
@krupal @Vinaykm999 8 is not a issue as we don't want to show stop before ride started

**Comment by max-keviv** [comment]
fixed 7

**Comment by krupal-14** [comment]
Issues: 
2,3,4,7,9- working fine
