### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_ App is getting struck  _(Parent id_1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#6154]
#1980 

[App is getting struck](https://drive.google.com/file/d/1p2qt8ECKDe1hLyoQyCcExXSrvZDiUAp6/view?usp=sharing)

Steps:
1. Request rentak ride
2. Navigate back to home screen
3. Tap on the screen
4. verify the screen

**Comment by 123ajay1994** [comment]
@slow-codex Please change status to "Ready" after fixing the issue. 
Once re-testing is done and working as expected, than ticket will be marked as "Done" .

**Comment by Vinaykm999** [comment]
Working as expected, hence resolving this issue.
