### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_ Auto Icon is missing after adding stop and ride got assigned _(Parent id_1980)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#6157]
#1980 

**Describe the bug**
Auto Icon is missing after adding stop and ride got assigned. 

**To Reproduce**
- Book a rental with stop
- make driver little away 
- observe the screen at the User side

**Expected behavior**
Auto icon should appear at one side of polyline

**Screenshots**
![Screenshot_20240401-185314](https://github.com/nammayatri/nammayatri/assets/128033831/7bec2ef4-cab6-4e0b-a49a-9978d91a2e32)

**App (please complete the following information):**

**Additional context**

**Comment by MercyQueen** [comment]
Fixed.

**Comment by krupal-14** [comment]
Retested, Working fine
