### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_ Address is not updating while adding next stop with locate on map _(Parent id_1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#6158]
#1980 
[Address is not updating while adding next stop with locate on map ](https://drive.google.com/file/d/1tcbbrN_Z1qnG4o7TdRmUdDZQOL4Odupv/view?usp=sharing)

Steps:
1. Book rental ride
2. Add next using locate on map
3. Verify

**Comment by MercyQueen** [comment]
Fixed.

**Comment by Vinaykm999** [comment]
Working fine, hence resolving this
