### ISSUE TITLE
01/04/24_NYP_Android_Chennai(Rental)_ For intercity rides the Intercity tag is not displaying in the RR  _(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6160]
#1980

Driver is not getting intercity tag in the ride request pop-up.[[Here](https://drive.google.com/file/d/1u1rMbLWfJJVfBgcGkiyaEqVIu75VjwSF/view?usp=sharing)]

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Search for a intercity ride
4.Observe the driver RR.

Expected Result
Intericty tag should display

Actual Result
Intercity tag is not displaying.

**Comment by max-keviv** [comment]
@krupal-14 The 'City,State' combination of the source and destination should be different. Eg: (Kolkata, West Bengal) and (AnyCity, West Bengal)
can you please try that if that is still not working then please inform

**Comment by krupal-14** [comment]
Retested, Working fine
