### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_ Previous sent chat of same session is getting displayed on User side chat screen _(Parent id_1980)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#6163]
#1980 

**Describe the bug**
Previous sent chat of same session is getting displayed on User side screen

**To Reproduce**
-book a ride
-Validate the chat option
-send the chat "hello" and observe the screen
- send again "hello1" and observe the screen

**Expected behavior**
-Messages should be displayed on chat screen just after sending the message

**Screenshots**
https://drive.google.com/file/d/1W1MSdCQIQn7cQ1bKLfk6PEN6nqUr-K-O/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by MercyQueen** [comment]
Not able to reproduce

**Comment by krupal-14** [comment]
Chat icon is not there at user side after ride started.[[Here](https://drive.google.com/file/d/1_UxMlrUHIXCL9DDOrVgPmuuakdwnPL1c/view?usp=sharing)]

**Comment by krupal-14** [comment]
This is fixed, working fine.
Device: Vivo Y21
