### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_ Getting location unserviceable for most of the location in tamilnadu for intercity ride _(Parent id_1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#6164]
#1980 

[Getting location unserviceable for most of the location in tamilnadu for intercity ride ](https://drive.google.com/file/d/1vxr_M5NsGaB83r0Kw5bM-LQx4Gi6i3uy/view?usp=sharing)

Steps:
1. Book intercity ride from Chennai to Kumbakonam /iruvannamalai - more than 100km from source
2. verify unserviceable error

**Comment by MercyQueen** [comment]
getting unserviceable from backend.

**Comment by Vinaykm999** [comment]
Working fine now
