### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_ Not able to book the schedule intercity ride(BLOCKER) _(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6166]
#1980
Not able to book the schedule intercity ride.[[Here](https://drive.google.com/file/d/1NRg2Es8g0LOFgQLlwFC9SPQAZCJqZ3ib/view?usp=sharing)]

Steps To reproduce
1.Launch the apk.
2.Login with valid credentials.
3.Try to book the intercity ride with scheduling.

Expected Result
Should allow to book intercity ride.

Actual Result
Not able to book intercity schedule ride.

**Comment by slow-codex** [comment]
@krupal-14 Given the source and destination, this is not an intercity ride, thus scheduling is not allowed. Can we validate a proper intercity scheduling? I am unable to get any proper outstation destination for Chennai which is serviceable.

**Comment by krupal-14** [comment]
Retested, working fine
