### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_ Double Marker while edit the stop(with autocomplete) & app is crashed _(Parent id_1980)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#6167]
#1980 

**Describe the bug**
Double Marker while edit the stop(with autocomplete) & app is crashed

**To Reproduce**
- add the stop while booking the rental ride
- Validate "edit" on On Ride screen
- tap on ":edit" 
- validate the screen 
- type any location name 
- select any location
- observe the issue

**Expected behavior**
Only one marker should be there.

**Screenshots**

CrashLog: 
<img width="1355" alt="image" src="https://github.com/nammayatri/nammayatri/assets/128033831/25c89810-7da0-48cb-a26e-9a5dc50f560c">
PFA of issue: https://drive.google.com/file/d/1AYA2OARZImduwP0tn2McqqkKaL3eF04O/view?usp=sharing
**App (please complete the following information):**

**Additional context**

**Comment by MercyQueen** [comment]
Fixed

**Comment by krupal-14** [comment]
Retested, Working fine
