### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_ Not updated to next screen after start of ride(lead to 2 destination markers & kill- relaunch not displayed auto icon) & End Ride OTP is not at all coming _(Parent id_1980) #6167

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#6173]
#1980 

**Describe the bug**
Not updated to next screen after start of ride(lead to 2 destination markers) & End Ride OTP is not at all coming

**To Reproduce**
-book a rental ride
- start the ride from driver end after entering the OTP
-observe the screen 
- kill and relaunch the app 
- observe Auto Icon is missing 
- tap on End OTP Screen 
- observe the issue 
- Kill and relaunch 
- tap on OTP 
- observe the issue 

**Expected behavior**
Screen should updated after entering the ride start OTP and no 2 markers should be there and end ride OTP should be displayed. 

**Screenshots**
https://drive.google.com/file/d/1HmzptaCARH0b3NM5432vv8kGxVHQ9_gJ/view?usp=sharing

**App (please complete the following information):**

**Additional context**

**Comment by krupal-14** [comment]
Retested, Working fine
