### ISSUE TITLE
15/04/24_NY_Android_ProdRegressionChennai _Home screen data is keep on loading _(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6402]
#1980 
Home screen data is keep on loading.([PFA](https://drive.google.com/file/d/11B4UO8dsyxRB4hQ5pDMTyxGpNOYAvw50/view?usp=sharing))

Steps To Reproduce
1.Login with valid credentials.
2.Click on where to- navigate back to home screen
3.Click on check on live status. --> do this for muiltiple times & observe

Expected: 
Screen data should load .

Actual Result
Data is not getting loaded untill user kill & relaunch the user apk.

Device details: Vivo Y21 (Android 12)
Frequency : 3/2

**Comment by MercyQueen** [comment]
Fixed.

**Comment by vinod96424** [comment]
Issue is reproducing in latest bundle 1.9.84. Re opening the ticket.

**Comment by saikrishnateja12** [comment]
Re-tested in the master. Working as expected.
Hence resolving this. -[ PFA](https://drive.google.com/file/d/1t0iwCm1pS9CEYi66xPpwaevS0rkvGXsf/view?usp=sharing)
