### ISSUE TITLE
15/04/24_NY_Android_ProdRegressionChennai _ Driver waited for 5 min, Rs 3 is getting added for cab ride_(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6407]
#1980
 Driver waited for 5 min, Rs 3 is getting added for cab ride.[[PFA](https://drive.google.com/file/d/178RMX-snf1r0MwhZHyhkzv19QC6Ps09Q/view?usp=sharing)]
 
 Steps to reproduce
1. Login with valid credentials.
2. Book a ride -- wait for more then 5min.
3 start a ride & complete it 
4.Observe the invoice for waiting charges.

Expected Result:
For cabs the waiting time free window is 5min after that Rs 1 will be added.

Actual result
Waited for 5 min Rs 3is getting added for cab rides.

**Comment by vishal13d** [comment]
Retested in master, working fine
