### ISSUE TITLE
15/04/24_NYP_Android_ProdRegressionChennai _Auto icon is showing in ride list for CAB rides_(Parent id_1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#6410]
#1980 
[Auto icon is showing in ride list for CAB rides] [[PFA](https://drive.google.com/file/d/1ovUD_QFUih_ujcpHvNFjlTRk9-bCP3P8/view?usp=sharing)]

Steps:
1. Complete cab ride
2. Check My rides
3. Verify the icon

**Actual:** For cab rides Auto icon is showing

**Comment by vinod96424** [comment]
Working fine in latest bundle(1.9.84), hence closing the ticket.

**Comment by vinod96424** [comment]
Working fine in latest bundle(1.9.84), hence closing the ticket.
