### ISSUE TITLE
15/04/24_NY_Android_ProdRegressionChennai _UserSide_Lottie is keep loading instead of showing the results & app is stucked.(Parent id_1980) 

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#6412]
#1980 

**Describe the bug**
Lottie is keep loading instead of showing the results & app is stucked.

**To Reproduce**
-tap on where to
-enter 3-4 words of destination 
-observe the issue

**Expected behavior**
should show location results

**Screenshots**
https://drive.google.com/file/d/13vEObWjKhNt0GSgB9y7ZzvOjn43g2x4E/view?usp=sharing

**App (please complete the following information):**
 - Device: one plus android 12

**Additional context**
frequency: 2/10

**Comment by vishal13d** [comment]
Working fine in master, https://drive.google.com/file/d/1J80mVkN2jWVCoBQyv90DKW_PGn74ZFym/view?usp=sharing
