### ISSUE TITLE
16/04/24_NY_Android_ProdRegressionHyderabad _Incorrect waiting charges are displaying in User OTP screen for auto _(Parent id_1980) 

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#6428]
[Incorrect waiting charges are displaying in User OTP screen for auto ](https://drive.google.com/file/d/1NlZw9dc4fsZkAQH4xCrCfMXdFnrO-Vn9/view?usp=sharing)

Steps to reproduce:

1. Launch the application
2. Book the auto ride
3. Tap on "i" icon in user OTP screen
4. Observe the price

Expected result:

User should be able to see 2 rupee per min as a waiting charge text for auto ride

Actual result:

User is getting 1.5 rupee per min as a waiting charge text for auto ride

Repro: 5/5

**Comment by saikrishnateja12** [comment]
I have retested this through master it is working fine[ PFA](https://drive.google.com/file/d/1ct3lC-5eSVlZ2EnXnPI-4UIVRk_75Zl9/view?usp=drivesdk)
Since I am closing the issue
