### ISSUE TITLE
16/04/24_NY_Android_ProdRegressionHyderabad _Safety videos are not displaying in mana yatri application _(Parent id_1980)

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#6430]
[Safety videos are not displaying in mana yatri application](https://drive.google.com/file/d/1F1IEv4YTAsN7UckQwJmqa28JAZ4KUwif/view?usp=sharing)

Steps to reproduce:

1. Launch the application
2. Book and start the ride
3. Tap on safety center> Learn about safety
4. observe the screen

Expected result:

Safety videos should be displayed in mana yatri application

Actual result:

Safety videos are not displaying in mana yatri application

Repro: 5/5

**Comment by Ranit-Bandyopadhyay** [comment]
Hi I am new to open source. Can i contribute to it

**Comment by vinod96424** [comment]
I have tested this in Master APK, Issue is working fine. hence closing the ticket.
