### ISSUE TITLE
 16/04/24_NY_Android_ProdRegressionHyderabad _Getting Far from pickup location popup even after cancel the ride search _(Parent id_1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#6447]
#1980 
[[Getting Far from pickup location popup even after cancel the ride search]
](https://drive.google.com/file/d/1U6fMpSKC47BqM_bY3LioAtvf9FoPo1u_/view?usp=sharing)
Steps:
1. Do ride search for mana yatri
2. Click Book ride button in far from pickup location popup
3. Cancel ride from ride search screen
4. Verify the far from pickup location popup again

**Actual:** Getting Far from pickup location popup even after cancel the ride search.

**Expected:** Popup shouldn’t display again when user trying to cancels the ride search

**Comment by vinod96424** [comment]
Working fine in build number 1.9.84, hence closing the ticket.
