### ISSUE TITLE
26/04/24_NY_Android_ProdRegressionBangalore_ Tip options in try again screen design is changing _(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6568]
#1980 
[Tip options in try again screen design is [changing.]](https://drive.google.com/file/d/1BlN6hp6eTr4YvNqd6eJ2wVoAMJJa104N/view?usp=sharing)

Steps To Reproduce.
1.Login with valid credentials.
2.Try to book a ride.
3. Wait untill try again screen & open the app observe the screen

Expected Result
Tip options design is should be according to figma.

Actual Result
Tip design is being changed.

Note: I tried to book the ride no driver was accepting  the RR.meanwhile i was watching cricket match & NY apk was running in background.

Device : Poco X3 (Android 12)
Frequency: 2/2.
User bundle version**: 1.4.16 [1.9.49]**

**Comment by vishal13d** [comment]
This is working fine. https://drive.google.com/file/d/1BpKRfCWNZU23GSz4B23uddQd1U5CyC1e/view?usp=sharing
