### ISSUE TITLE
Adding Customer Device in various tables for Data Analytics- Frontend changes

### ISSUE THREAD

**Issue by SrinivasNaikB** [nammayatri/nammayatri#658]
**Describe the bug**
Backend changes are done, Frontend changes are to be done to complete this.
Fields to be added:
- Adding "Estimated Duration" and "Device" (iOS/Android) in BAP tables- Search Request
- "Device" (iOS/Android) in BPP Search Request Table
- "Estimated Distance", "Estimated Duration" and "Device" in Estimate table as well

Backend task: https://github.com/nammayatri/nammayatri/issues/465
Backend Commit- https://github.com/nammayatri/nammayatri/commit/c0ea60b4fedf458cc35ed3ce1d0cc2f0786faef8`

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**App (please complete the following information):**

**Additional context**

**Comment by witcher-shailesh** [comment]
sure @SrinivasNaikB, we'll be adding the following items in every API headers :-

- 'x-device-brand' [like samsung, apple, oneplus]
- 'x-device-model' [like M31, M53, S22]
- 'x-device-os' [android 13, 12, 11]
- 'x-device' [for platform ios or android]
- 'x-device-ram' [Need to check if possible]
- 'x-device-s-size' [in inches]
- 'x-device-resolution' [axb in pixels]

@aryanguptaSG Can you add these super quickly and raise the PR?

**Comment by SrinivasNaikB** [comment]
@aryanguptaSG please sync with @saurav2401 to understand which header key to be used to send 'Device' information so that his code(which is already merged) can consume it?

**Comment by witcher-shailesh** [comment]
I missed this :- ```Then 'Device' should be- "Xiaomi Redmi/Note 12/Android v12/4 GB/6.67 inches (16.94cm)/1080 x 2400 px"```

Now I got the requested change, we will send everything in at once with a common key 'x-device'

@AmritpalSingh6749 can you take this up and add these above mentioned data in API headers?

**Comment by AmritpalSingh6749** [comment]
Sure @witcher-shailesh
