### ISSUE TITLE
29/04/24_NY_Android_BookAny_ Selecting two estimates for a sec when driver clicks on bookany & other varinats _(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6602]
#1980
Selecting two estimates for a sec when driver clicks on bookany & other variants.[[Here](https://drive.google.com/file/d/142RcFbb1epHmivlcEI2EF1BKMQxtJWHh/view?usp=sharing)]

Steps to reproduce
1.Launch the apk.
2.Login with valid credentials.
3. Book a ride navigate to estimate screen.
4.Click on bookany--Again click on any other vehicle variant. do the same thing few times & observe

Expected Result
Delay should not be there,Only one variaat should select.

Actual Result
Delay is there & for a sec two variants are selected.

**Note: The selection between 2 vehicle variants are not smooth.**

**Comment by PraveenGongada** [comment]
Expected

**Comment by Vinaykm999** [comment]
Working as expected. Hence resolving this. - [PFA](https://drive.google.com/file/d/1fgpgB0sQiWWiSkkM_g0UZOeUPj7qQ-e-/view?usp=sharing)
