### ISSUE TITLE
29/04/24_NY_Android_BookAny_ Vehicle varinats are available still in the book any option no price range is coming as null(-) _(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6605]
#1980
 Vehicle variants are available still in the book any option no price range is coming as null(-).([Here](https://drive.google.com/file/d/13wrVGf5JDMNzSKBnXKjmNaRCDGeZjdZr/view?usp=sharing))
 
 Steps to reproduce
 1.Launch the apk.
 2.Login with valid credentials.
3. Try to book any ride Observe the estimate screen.

Expected Result
If any vehicle variants are available then in book any option those vehicle variants along with price range should display.

Vehicle available are: 1 SUV not downgraded & 1 Auto
Device details: Vivo Y21(Android 12)

**Comment by PraveenGongada** [comment]
Fixed

**Comment by Vinaykm999** [comment]
Working fine now, hence resolving this. - [PFA](https://drive.google.com/file/d/1NddVnnj1eyNzHexwhafbter4o37TC3WR/view?usp=sharing)
