### ISSUE TITLE
29/04/24_NY_Android_BookAny_ App is getting stuck in the estimates screen _(Parent id_1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#6606]
#1980 
[App is getting stuck in the estimates screen](https://drive.google.com/file/d/1YSNMjwJGkJ2F7HgZgWAug95hIBw9kuKN/view?usp=sharing)

**Steps to Reproduce**
1. Launch the application and login with the valid credentials 
2. Search for a ride in a location in which driver is not there 
3. we will get "No drivers available toast message" 
4. Again search for a ride, then observe the estimates screen 

**Expected Result**
User should get "No drivers available" toast message

**Actual Result**
User is getting stuck in the estimates screen

**Comment by PraveenGongada** [comment]
Not Reproducing now

**Comment by Vinaykm999** [comment]
Working as expected, hence resolving this. - [PFA](https://drive.google.com/file/d/14kTEBqLrtcDhWQ0JR_y0-H-2tDAgkVIf/view?usp=sharing)
