### ISSUE TITLE
29/04/24_NY_Android_BookAny_ Book any Option is selected in estimates screen but getting "Book Sedan" option in the button at the bottom of the screen and also when requesting for a ride by selecting "Book any", request is going as a sedan request _(Parent id_1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#6618]
#1980 
[Book any Option is selected in estimates screen but getting "Book Sedan" option in the button at the bottom of the screen and also when requesting for a ride by selecting "Book any", request is going as a sedan request](https://drive.google.com/file/d/1J94NDDtbDeYIYCRnfZgJZgqccb-yd01M/view?usp=sharing), 

**Steps To Reproduce**
1. Launch the application and login with the valid credentials 
2. Select Book any option in estimates and complete one ride with any one of the selected variants. (Note : Here selected Ac mini, Sedan, Non-Ac mini and completed a ride with the sedan variant)
3. Now the recent ride will display in the home screen, tap on that. 
4. User will get estimates screen, there we will get the variant with which we completed the ride.
5. Tap on "change" option near the variant name 
6. Now observe the estimates screen. 

**Expected Result**
If Book Any option is selected then  "book Any" option should display at the bottom of the screen and also when requesting for a ride. It should be requested in a "Book any" flow

**Actual Result**
 In estimates screen, "Book Any" option is selected and "Book Sedan" option is displaying at the bottom of the screen. When proceeded for a rideSearch the request is going as a sedan request.

**Comment by PraveenGongada** [comment]
Fixed

**Comment by Sumedh-14** [comment]
Retested on 3/05. It is working Fine and so marking this issue as closed ([Here](https://drive.google.com/file/d/1CTp5dEgYo9_rsbk2VAjPPGWRzikgxe_L/view?usp=sharing))
