### ISSUE TITLE
29/04/24_NY_Android_BookAny_ Try again screen is not dsiplaying _(Parent id_1980) 

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6622]
#1980
Try again screen is not displaying.[[Here](https://drive.google.com/file/d/1IixkiJ94AW8qKIeP8LKILfxW1PZmomG7/view?usp=sharing)]

Steps To Reproduce.
1.launch the apk.
2.Login with valid credentials.
3. Book a ride with tip--> Driver accepts a ride--Driver cancels the ride
4.Reallocation starts-->No driver accepted.
5.Observe the user screen for 2 to 3 min.

Expected Result
Try again screen should come after some time.

Actual Result
Try again screen is not displaying.

**Comment by PraveenGongada** [comment]
Not Happening in main now, Recheck in other APK

**Comment by Vinaykm999** [comment]
Unable to check this issue since auto rickshaw variant’s are not showing!!



![Image](https://github.com/nammayatri/nammayatri/assets/131981246/9b8525af-2692-4e79-ac7f-1d1032ce5c1f)

estimates are showing in logs in UI auto estimates are not showing

**Comment by Vinaykm999** [comment]
Working fine now. Hence resolving this - [PFA](https://drive.google.com/file/d/1ks-c1AxactW7LbiIemoj3acRxW6pfFN-/view?usp=sharing)
