### ISSUE TITLE
30/04/24_NY_iOS_ProdRegressionBangalore_The source pointer & the address which is displaying are not matching _(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#6635]
#1980 
The source pointer & the address which is displaying are not matching.([[Here](https://drive.google.com/file/d/1EDzWrqY0DNoh8OEhotIFEkt1xSj73gUp/view?usp=sharing)]

Steps To Reproduce
1.Launch the ipa.
2. Login with valid credentials.
3. Click on where to-> Select any dest through favourites.-->While confirm src location edit the source location to some other location & observe.

Expected Result
Source pointer & address should be in sync.

Actual Result
Source pointer pointing for current location but  address which is displaying is address.

Device : iphone 13.
frequency: 5/5

**Comment by MercyQueen** [comment]
This issue is fixed.

**Comment by vinod96424** [comment]
Working fine in latest bundle(1.9.84), hence closing the ticket.
