### ISSUE TITLE
16/05/24_NY_Android_ProdRegressionBangalore_ The driver is on ride, but 'OnRide' flag is updated to false and getting New RideRequests _(Parent id_1980)

### ISSUE THREAD

**Issue by vishal13d** [nammayatri/nammayatri#6903]
#1980 
[ The driver is on ride, but 'OnRide' flag is updated to false and getting New RideRequests]
(url - https://drive.google.com/file/d/10eDeclyBF5lNxEAk3vvE2_12fvQ76-x9/view?usp=sharing
https://drive.google.com/file/d/1M0hnbhHb0FqxJ20c8R9jm9YXSJgPwOq7/view?usp=sharing
https://drive.google.com/file/d/1zC22x4OnwGKBZwC6ad0i1XtJdp1eOBZR/view?usp=sharing    )

**Steps To Reproduce.**
1.Login with valid credentials.
2.Try to book a ride.
3. accept the ride 
4. Enter otp
5. End the ride and observe

**Expected Result**
User and Driver side, the ride should be ended and it should go to Home page.

**Actual Result**
For Driver side it went to Home screen but at Customer side still showing the ride assigned page

_**Note: In BPP dashboard it is showing status as "Ongoing" but at UI side, the driver is not getting the Ride Assigned screen, and getting new ride request.

- Validated in RideList and Profile API of Driver in which the driver is getting ride details but in driver Profile the "Onride" status is coming as False.
- Driver is getting multiple ride request, and when driver accepted the ride request and cancelled the ride request, after that it is showing the Ride Assigned screen of this ride, and after completing the ride again, there is difference in fair also.
https://drive.google.com/file/d/1vYiEC5rtFE2HP35tVQy3T5qlcOqP2GKM/view?usp=sharing 
**_

bpp rideId - f8033238-5c6f-4c2f-b2bf-dffb3b63352c

Driver no. - 6378299816
Customer no. - 6378299816
User bundle version**: 1.3.16 [1.9.81]**

**Comment by vinit-j13** [comment]
Working Fine
