### ISSUE TITLE
17/05/24_NY_iOS_ProdRegressionBangalore_ Select Favourite screen is loading twice_(Parent id_1980) 

### ISSUE THREAD

**Issue by saikrishnateja12** [nammayatri/nammayatri#6918]
[Select Favourite screen is loading twice](https://drive.google.com/file/d/1klnoyE3ARHW28EG1vNCyu0OXneaIaQnz/view?usp=sharing)
**Steps to Produce:**
1.Go to ride search page 
2.Click on favourites 
3.Observe the Screen
**Actual Result:** Screen is loading twice
**Expected Result**:Screen should not load twice
**Repro**:3/3
**Device**:i phone SE, i phone XR

**Comment by vishal13d** [comment]
It is tested and working fine now. (https://drive.google.com/file/d/18ucg5-gj5VIWr2ihJK818VVis_QY4eKS/view?usp=sharing)
