### ISSUE TITLE
21/05/24_NY_Android_ProdRegressionBangalore_estimates on the estimate screen are truncated. _(Parent id_1980)

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#6980]
In the user app for NY, estimates on the estimate screen are truncated. [here []](
https://drive.google.com/file/d/1X7lw-vihwQ04YrwDlivQdwzWMDGqmU0Q/view?usp=sharing)

Steps to produce
1. Launch the application
2. Login with the valid credentials
3. Search for a ride
4. Estimate screen appears
5. Scroll down the estimatess
6.  In the user app for NY, estimates on the estimate screen are truncated. 

Device details : Redmi Note 5 Pro , Android 9
Frequency : 5/5

**Comment by prakharritik** [comment]
Is this with increased display size?

**Comment by saikrishnateja12** [comment]
Retested in master, Working Fine [PFA](https://drive.google.com/file/d/1iI6tD1FvfzVRTXcNIrZhLS2pClVWs898/view?usp=sharing)
Hence I'am closing it
