### ISSUE TITLE
21/05/24_NY_Android_ProdRegressionDelhi_ in the "book any" option, the auto icon color appears as black instead of green_(Parent id_1980)

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#6981]
In the estimates screen for Delhi location only, in the "book any" option, the auto icon color appears as black instead of green. [[link ]](https://drive.google.com/file/d/1C5jacSDHV9eufoJOcpbgOHH8OaGykn4a/view?usp=sharing)
 
 
 Steps to produce
 
1.Launch the application
2.Login with the valid credentials
3.Search for a ride in Delhi location 
4.Estimate screen appears 
5.See only auto in Book any option 
6.   In the estimates screen for Delhi location only, in the "book any" option, the auto icon color appears as black instead of green.
Device details : Redmi Note 5 Pro , Android 9
Frequency : 5/5

**Comment by vishal13d** [comment]
Working fine in master - https://drive.google.com/file/d/1WvOoBU8TN06ocsQpoOhdoM-GEyIKkMxo/view?usp=sharing
