### ISSUE TITLE
23/05/24_NY_Android_ProdCUG(1.9.85)Chennai _ Validated Rs.10 selected tip always in "Try again" screen even applied Tip was Rs.10 or no tip applied in earlier search_(Parent id_1980)

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#7026]
#1980 
**Describe the bug**
a. Validated Rs.10 selected tip always in "Try again" screen even applied Tip was Rs.10 or no tip applied in earlier search
b. For Chennai, we are not having "Add tip option" in auto variant at Estimate Screen. As it is there for Bengaluru

**To Reproduce**
-start searching for a ride
-Do not get assigned with any ride 
- Either not apply any tip or apply any tip rather than Rs.10
- validate "Try again" Screen
- Validate the AutoFocus on "Try again" Screen for "No tip" Option.
-

**Expected behavior**
Should be Focused on basis of earlier searched Tip or no tip.
**Screenshots**

**App (please complete the following information):**

**Additional context**

**Comment by vinit-j13** [comment]
Working fine
