### ISSUE TITLE
pre-commit hook ormolu doesn't work on Ubuntu (`version GLIBC_2.34 not found`)

### ISSUE THREAD

**Issue by DonDokidon** [nammayatri/nammayatri#717]
**Describe the bug**
When i run `git commit` in terminal, ormolu check doesn't work (coz ormolu itself doesn't work).
When i hit commit button in VSCode everything is fine though, ormolu works just fine.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Should work in both cases

**App (please complete the following information):**
 - Device: Acer Nitro-AN517-52
 - OS:  Ubuntu Unity 
 - Version: 22.04.1

**Additional context**

<details>
<summary>Output from terminal</summary>
beckn/Backend on  backend/refactoring/refactor-fare-policy [✘+⇣] via λ 8.10.7 via ❄️  impure (nix-shell-env) took 16s 
❯ git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
hpack....................................................................Passed
nil..................................................(no files to check)Skipped
overlapping-migrations...............................(no files to check)Skipped
statix...............................................(no files to check)Skipped
trailing-ws..............................................................Passed
treefmt..................................................................Failed
- hook id: treefmt
- exit code: 1

[INFO]: Error using formatter #ormolu:
• [STDOUT]:

• [STDERR]:
/nix/store/yv3j7wib5fphylg9j2zan37w3xczr129-ormolu-0.1.4.1-bin/bin/ormolu: /nix/store/0xxjx37fcy2nl3yz6igmv4mag2a7giq6-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0)

[ERR]: #ormolu's formatter failed: exit status 1
[INFO]: Error using formatter #ormolu:
• [STDOUT]:

• [STDERR]:
/nix/store/yv3j7wib5fphylg9j2zan37w3xczr129-ormolu-0.1.4.1-bin/bin/ormolu: /nix/store/0xxjx37fcy2nl3yz6igmv4mag2a7giq6-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0)

[ERR]: #ormolu's formatter failed: exit status 1
[INFO]: Error using formatter #ormolu:
• [STDOUT]:

• [STDERR]:
/nix/store/yv3j7wib5fphylg9j2zan37w3xczr129-ormolu-0.1.4.1-bin/bin/ormolu: /nix/store/0xxjx37fcy2nl3yz6igmv4mag2a7giq6-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0)

[ERR]: #ormolu's formatter failed: exit status 1
[INFO]: Error using formatter #ormolu:
• [STDOUT]:

• [STDERR]:
/nix/store/yv3j7wib5fphylg9j2zan37w3xczr129-ormolu-0.1.4.1-bin/bin/ormolu: /nix/store/0xxjx37fcy2nl3yz6igmv4mag2a7giq6-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0)

[ERR]: #ormolu's formatter failed: exit status 1
[INFO]: Error using formatter #ormolu:
• [STDOUT]:

• [STDERR]:
/nix/store/yv3j7wib5fphylg9j2zan37w3xczr129-ormolu-0.1.4.1-bin/bin/ormolu: /nix/store/0xxjx37fcy2nl3yz6igmv4mag2a7giq6-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0)

[ERR]: #ormolu's formatter failed: exit status 1
[INFO]: Error using formatter #ormolu:
• [STDOUT]:

• [STDERR]:
/nix/store/yv3j7wib5fphylg9j2zan37w3xczr129-ormolu-0.1.4.1-bin/bin/ormolu: /nix/store/0xxjx37fcy2nl3yz6igmv4mag2a7giq6-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0)

[ERR]: #ormolu's formatter failed: exit status 1
[INFO]: Error using formatter #ormolu:
• [STDOUT]:

• [STDERR]:
/nix/store/yv3j7wib5fphylg9j2zan37w3xczr129-ormolu-0.1.4.1-bin/bin/ormolu: /nix/store/0xxjx37fcy2nl3yz6igmv4mag2a7giq6-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0)

[ERR]: #ormolu's formatter failed: exit status 1
[INFO]: Error using formatter #ormolu:
• [STDOUT]:

• [STDERR]:
/nix/store/yv3j7wib5fphylg9j2zan37w3xczr129-ormolu-0.1.4.1-bin/bin/ormolu: /nix/store/0xxjx37fcy2nl3yz6igmv4mag2a7giq6-glibc-2.33-123/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0)

[ERR]: #ormolu's formatter failed: exit status 1

direnv: loading ~/Haskell/beckn/.envrc
direnv: using flake
warning: Git tree '/home/phantom/Haskell/beckn' is dirty
warning: Git tree '/home/phantom/Haskell/beckn' is dirty
direnv: nix-direnv: renewed cache
pre-commit-hooks.nix: hooks up to date

### ️🔨 Welcome to the Nix devshell ###

Available commands:

## Backend

  , backend-new-service  : Create a new Haskell package locally
  , docs                 : Run Hoogle server for Haskell packages.
  , ghcid                : Compile the given local package using ghcid.
  , hpack                : Run hpack to generate cabal files.
  , run-mobility-stack   : Run the nammayatri backend components via "cabal run".

## Backend - Docker

  , run-monitoring       : Run monitoring stack - Prometheus and grafana in docker containers
  , run-pgadmin          : Run pgadmin stack - Pgadmin in a docker container
  , run-svc              : Setup and run DB, redis and passetto instances in docker containers
  , stop-all-containers  : Stop all docker containers

(Run ',' to display this menu again)

direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +DETERMINISTIC_BUILD +FLAKE_ROOT +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_CFLAGS_COMPILE +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_LDFLAGS +NIX_STORE +NM +OBJCOPY +OBJDUMP +PYTHONHASHSEED +PYTHONNOUSERSITE +PYTHONPATH +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +_PYTHON_HOST_PLATFORM +_PYTHON_SYSCONFIGDATA_NAME +__structuredAttrs +buildInputs +buildPhase +builder +cmakeFlags +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +dontAddDisableDepTrack +mesonFlags +name +nativeBuildInputs +out +outputs +patches +phases +preferLocalBuild +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH ~XDG_DATA_DIRS
</details>

<details>
<summary>Output from VSCode </summary>
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
hpack....................................................................Passed
nil..................................................(no files to check)Skipped
overlapping-migrations...............................(no files to check)Skipped
statix...............................................(no files to check)Skipped
trailing-ws..............................................................Passed
treefmt..................................................................Failed
- hook id: treefmt
- exit code: 1
- files were modified by this hook

[INFO]: #ormolu: 3 files processed in 373.46ms

traversed 5 files
matched 5 files to formatters
left with 3 files after cache
of whom 3 files were re-formatted
all of this in 375ms
        

formatted files:
#ormolu:
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Select.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/SendSearchRequestToDrivers/Handle/Internal/SendSearchRequestToDrivers.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
[ERR]: fail-on-change
[INFO]: #ormolu: 5 files processed in 292.10ms

traversed 5 files
matched 5 files to formatters
left with 5 files after cache
of whom 2 files were re-formatted
all of this in 294ms
        

formatted files:
#ormolu:
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Estimate.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/FarePolicy.hs
[ERR]: fail-on-change
[INFO]: #ormolu: 1 files processed in 556.17ms

traversed 5 files
matched 4 files to formatters
left with 1 files after cache
of whom 1 files were re-formatted
all of this in 558ms
        

formatted files:
#ormolu:
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
[ERR]: fail-on-change
[INFO]: #ormolu: 4 files processed in 310.27ms

traversed 5 files
matched 5 files to formatters
left with 4 files after cache
of whom 4 files were re-formatted
all of this in 313ms
        

formatted files:
#ormolu:
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/FareParameters.hs
- /home/phantom/Haskell/beckn/Backend/app/rider-platform/rider-app/Main/src/Beckn/ACL/OnSearch.hs
- /home/phantom/Haskell/beckn/Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/OnUpdate.hs
- /home/phantom/Haskell/beckn/Backend/app/rider-platform/rider-app/Main/src/Storage/Tabular/Estimate/Instances.hs
[ERR]: fail-on-change
[INFO]: #ormolu: 5 files processed in 388.06ms

traversed 5 files
matched 5 files to formatters
left with 5 files after cache
of whom 3 files were re-formatted
all of this in 390ms
        

formatted files:
#ormolu:
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/FarePolicy.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/Merchant.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/static-offer-driver-app/Main/src/Storage/Tabular/Merchant/TransporterConfig.hs
[ERR]: fail-on-change
[INFO]: #ormolu: 3 files processed in 394.70ms

traversed 5 files
matched 5 files to formatters
left with 3 files after cache
of whom 3 files were re-formatted
all of this in 397ms
        

formatted files:
#ormolu:
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Search.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/static-offer-driver-app/Main/src/Beckn/ACL/OnSearch.hs
[ERR]: fail-on-change
[INFO]: #ormolu: 4 files processed in 413.78ms

traversed 5 files
matched 5 files to formatters
left with 4 files after cache
of whom 4 files were re-formatted
all of this in 416ms
        

formatted files:
#ormolu:
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/Estimate.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/FarePolicy/SlabsFarePolicyDetails/SlabsFarePolicyDetailsSlab.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/static-offer-driver-app/Main/src/Domain/Types/Merchant/TransporterConfig.hs
[ERR]: fail-on-change
[INFO]: #ormolu: 4 files processed in 398.83ms

traversed 5 files
matched 5 files to formatters
left with 4 files after cache
of whom 4 files were re-formatted
all of this in 401ms
        

formatted files:
#ormolu:
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/QuoteSpecialZone.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/CachedQueries/FarePolicy.hs
- /home/phantom/Haskell/beckn/Backend/app/provider-platform/static-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide.hs
- /home/phantom/Haskell/beckn/Backend/app/rider-platform/rider-app/Main/src/Domain/Types/Estimate.hs
[ERR]: fail-on-change

</details>

**Comment by DonDokidon** [comment]
@srid

**Comment by srid** [comment]
@DonDokidon Can you paste the output of the `env` command from nix direnv shell?
