### ISSUE TITLE
07/06/24_NY_Android_Prod<Regression>Bangalore_ default special zone gate is being selected for chennai marina beach_(Parent id_1980)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#7172]
#1980
default special zone gate is being selected for chennai marina beach.([HERE](https://drive.google.com/file/d/1ntWdPxm1Z0OPMvm8pHnCv_Qi9RmYWaCQ/view?usp=sharing))

Steps To Reproduce
1.Launch the apk.
2.Login with valid credentials.
3. Click on where to
4. Select src as special zone (Vivekananda gate)
5. Select any destination.
6.While confirming the src location again default gate will be selected.

Expected Result
User selected special gate should select.

Actual Result
Default gate is being selected.

**Comment by vinit-j13** [comment]
Working  fine
