### ISSUE TITLE
Adding safeBottomMargin + a bottom padding of 24 pixels in all screens in iOS(customer app) and Android(customer and driver app)

### ISSUE THREAD

**Issue by SrinivasNaikB** [nammayatri/nammayatri#721]
**Describe the bug**
Go through all the screens, bottom-sheets, etc, in driver(android) and customer app(iOS and android) where the margin below the bottom-most CTA is less.
- The margin should be 24pixel above and in-addition to the bottomSafeMargin which is provided by the respective OS's standard.

We made a list(this list is in-complete, please go through all app flows to complete this list) in the thread- where there is this issue: https://juspay.slack.com/archives/C01FFBNAR1R/p1682507287233829
**Some sample screenshots(in-App invoice screen does not have 24pixel padding)**
<img width="453" alt="image" src="https://user-images.githubusercontent.com/126464614/235081947-2c4e420a-0792-4c68-b40d-ca95d58c548c.png">

There are also issues of the bottom CTA having different size, different internal padding which has to be standardised.
**Sample Screenshots below(Add new Favourite button is bigger in size(breadth) comparitively)**
<img width="450" alt="image" src="https://user-images.githubusercontent.com/126464614/235081392-d2c8dd92-f9e1-4d53-ba42-8782bb9e095a.png"> <img width="451" alt="image" src="https://user-images.githubusercontent.com/126464614/235081438-cbaff79a-8045-4ac8-8a52-c33b9123e706.png">

**To Reproduce**
Steps to reproduce the behaviour- go through complete flow of production apps(driver(android), customer(iOS and android) all screens and bottom-sheets) to check and understand where there is issue and make the CTAs and bottom margin standardised.

**Comment by AmritpalSingh6749** [comment]
I have done changes in the following screens
[Screens.zip](https://github.com/nammayatri/nammayatri/files/11495051/Screens.zip)
