### ISSUE TITLE
11/06/24_<NY><Android><Master> <Others-RideFlow>Tapping on "Where to" is focusing the Source tab from ride Search screen (Parent id_1980) 

### ISSUE THREAD

**Issue by 123ajay1994** [nammayatri/nammayatri#7219]
#1980 

**Describe the bug**
Tapping on "Where to" is focusing the Source tab from ride Search screen 
Should Focus on the Destination tab. 

**To Reproduce**
- Log in to the Application. 
- Validate the Home Screen. 
- Tap on the "Where to" 
- Obsreve the issue. 

**Expected behavior**
Auto focus should point to the Destination tab. 

**Screenshots**

**App (please complete the following information):**

**Additional context**

**Comment by Vinaykm999** [comment]
Working as excepted, Hence resolving this.

Please find the proof



![Image](https://github.com/nammayatri/nammayatri/assets/131981246/1719caad-0594-43ef-9949-08e57ee0d562)
