### ISSUE TITLE
11/06/24_<NY><Android><Master> <others>The location is not updating  when selecting a location on  the map(Parent id_1980)

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#7220]
#1980
The location is not updating when selecting a location on the map. [[here](https://drive.google.com/file/d/1HO8BOHcM9OAD9O04VNLqk9BEgchl9oK-/view?usp=sharing)]

Steps to reproduce  
 
 1. Launch the application 
 2. Login with the valid credentials 
 3. When a user attempts to add a location by selecting it on the map.
 4. The location is not updating when selecting a location on the map  
 
 Device details : Redmi Note 5 Pro, Android 9 
 Frequency : 5/5

**Comment by Vinaykm999** [comment]
Working fine...Hence resolving this.
