### ISSUE TITLE
11/06/24_<NYP><Android><Master> <others>An AC  pop-up appears when they  log in(Parent id_1980) 

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#7225]
#1980
 For auto drivers, an AC pop-up appears when they log in.[[here](https://drive.google.com/file/d/1xhBF2MmYf4L-Mvxkem2rt4pIhJsU6dFK/view?usp=sharing)] 
 
Steps to reproduce

1. Launch the application
2. Login with the valid credentials
3. For auto drivers, an AC pop-up appears when they log in.

Device details : Redmi Note 7 Pro, Android 10
Frequency : 5/5

**Comment by 123ajay1994** [comment]
this issue is fixed. 
Checked In re test. 
So marking it close.
