### ISSUE TITLE
11/06/24_<NYP><Marker><Android><Master> Booking preferences screen is flickering when driver downgrade or upgrade the variants (Parent id_1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#7226]
#1980 

[Booking preferences screen is flickering when driver downgrade or upgrade the variants](https://drive.google.com/file/d/1piDxmvqr8FnSSSRuaDAw3NZb6eHiLwF1/view?usp=sharing)

**Steps:**

1. Launch driver apk
2. navigate to booking preference 
3. Change the variants 
4. Verify the screen

**Comment by saikrishnateja12** [comment]
I have retested in master this is working fine.SInce Iam closing this issue [PFA](https://drive.google.com/file/d/1NcSxdhSTRis-lzrTfLaE8XrjULywJFVX/view?usp=sharing)
