### ISSUE TITLE
11/06/24_<NY><Android><Master> <Accessibility fixes > In estimates screen, Talkback is reading the estimated min and max Fare values wrongly (Parent id_1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#7248]
#1980 
[ In estimates screen, Talkback is reading the estimated min and max Fare values wrongly](https://drive.google.com/file/d/1a8XoCw2DQ7DTee4d5Gh7oqTeIavwW_z0/view?usp=sharing)

**Steps To Reproduce**
1. Turn on the talkback and Launch the application >  login with the valid credentials
2. Book for a ride and proceed until estimates screen and observe the talkback when it gives the estimated details 

**Expected Result**
It should read the vehicle variant, Capacity and the estimated amount as X To Y. 

**Actual Result**
It is reading estimated amount as X to Y and also it again reads it as X - Y.

**Comment by Shikhar-24** [comment]
fixed

**Comment by Sumedh-14** [comment]
Validated the above fix. It is working Fine hence closing this issue. 

PFA - https://drive.google.com/file/d/1QgEgHJvu7pMdF274KaacKUg7e8vpQ_Cm/view?usp=sharing
