### ISSUE TITLE
11/06/24_<NY><Android><Master> <Accessibility fixes > In booking Preferences options, the talkback is reading certain options as unlabeled (Parent_Id - 1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#7250]
[In booking Preferences options, the talkback is reading certain options as unlabeled ](https://drive.google.com/file/d/1gFsnaxsIotOs--YWebaLC0-MIVSXM1gm/view?usp=sharing)

**Steps To Reproduce**
1. Turn on the talkback > Launch the application and login with the valid credentials 
2. Search for a ride and proceed until the estimates screen. 
3. Select the "booking preferences" options and slide through the options and observe 

**Actual Result**
It is reading the radio buttons as unlabeled. Is this expected? 
It is reading the  "select multiple drivers" info button as unlabeled. 

**Expected Result**
It should read it as "select multiple drivers info" button.

**Comment by Shikhar-24** [comment]
booking preferences option is disabled in case of accessibility.

**Comment by Sumedh-14** [comment]
As mentioned this is expected. Closing the issue as fixed
