### ISSUE TITLE
11/06/24_<NYP><Android><Master> <Added condition to show pickup and wait time>Even after starting the ride, the pickup distance is still appearing on the driver's ride assigned screen.( Parent id_1980)

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#7253]
# 1980
Even after starting the ride, the pickup distance is still appearing on the driver's ride assigned screen.[[here]](https://drive.google.com/file/d/1j2IE3745w4aoXOtW_8-b9reoNUR-1nM1/view?usp=sharing)

Steps to reproduce

1.Launch the application
2.Login with the valid credentials
3. Accept the ride request 
4. Start the ride 
5. Even after starting the ride, the pickup distance is still appearing on the driver's ride assigned screen. 

Device details : Redmi Note 7 Pro, Android 10
Frequency : 5/5

**Comment by Rohit4997** [comment]
It's bacause location was not updated locate on map

**Comment by spoorthipbhat** [comment]
Issue resolved,Therefore, I am closing this issue. -    [PFA](https://drive.google.com/file/d/1rGOiwlh8N9VHe7Hlhu-XGxM6T_sG1W7y/view?usp=sharing)
