### ISSUE TITLE
11/06/24_<NY><Android><Master> <others>When the user downloads the invoice PDF, the  letter "W" in the waiting charge is  missing .(Parent id_1980)

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#7265]
#1980
When the user downloads the invoice PDF, the  letter "W" in the waiting charge is  missing .[[here] ](https://drive.google.com/file/d/1SfTCvzf7sBb2jalQmm7-NQxYBIMHxJnM/view?usp=sharing)

Steps to reproduce

1.Launch the application 
2.Login with the valid credentials 
3.Book a ride.
4.Complete the ride
5. Download the invoice
6.  When the user downloads the invoice PDF, the  letter "W" in the waiting charge is  missing .

Device details : Redmi Note 5 Pro, Android 9
Frequency : 5/5

**Comment by 123ajay1994** [comment]
Fixed, 
![Screenshot_20240618-125437](https://github.com/nammayatri/nammayatri/assets/128033831/f2025e49-eae5-4840-a56b-8b9cb5d06dc9)

marking it close.

**Comment by spoorthipbhat** [comment]
When the user downloads the invoice PDF, the letter "W" in the waiting charge is missing . - [PFA](https://drive.google.com/file/d/1Rm0ZaThHeN84T_Vfmp4WLI-cJpA1NPik/view?usp=sharing)
