### ISSUE TITLE
11/06/24_<NY><Android><Master> <Added instructions screen for airport>The user is not receiving the instructions screen for the airport when at Terminal 1.(Parent id_1980)

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#7267]
#1980
The user is not receiving the instructions screen for the airport when at Terminal 1. [[[here]](https://drive.google.com/file/d/1sCu_TUER2al-LT_Kftf676Sd-mdAw5dM/view?usp=sharing) 

Steps to reproduce

1.Launch the application
2.Login with the valid credentials
3. Book a ride from the airport Terminal 1 
4. Check  the ride assigned screen. 
5. The user is not receiving the instructions screen for the airport when at Terminal 1. 

Device details : Redmi Note 5 Pro, Android 9
Frequency : 5/5

**Comment by Rohit4997** [comment]
It's because location was not updated locate on map, Relating this issue to following issue
https://github.com/nammayatri/nammayatri/issues/7220

**Comment by spoorthipbhat** [comment]
The user is receiving the instructions screen for the airport when at Terminal 1. Therefore, I am closing this issue. -[PFA](https://drive.google.com/file/d/10bEBsJbEtaem7JN7PIv-1ivhK8kzykVM/view?usp=sharing)
