### ISSUE TITLE
11/06/24_<NY><Android><Master> <others>In the user app, when the user downloads the invoice PDF, the waiting charges description does not appear.(Parent id_1980)

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#7269]
#1980
In the user app, when the user downloads the invoice PDF, the waiting charges description does not appear.[[[here]](https://drive.google.com/file/d/1gvXjzU7IwxEK42dJ7kuJ9Q3KouqZ_imA/view?usp=sharing) 

Steps to reproduce

1.Launch the application
2.Login with the valid credentials
3.When a user attempts to add a location by selecting it on the map.
4.The location is not updating when selecting a location on the map 

Device details : Redmi Note 5 Pro, Android 9
Frequency : 5/5

**Comment by saikrishnateja12** [comment]
I have retested the apk in master.It is working fine.So Iam moving it to done state [PFA](https://drive.google.com/file/d/1mCyzyR59lGELkaoZyMyGCiyPPHpXppbm/view?usp=sharing)
