### ISSUE TITLE
11/06/24_<NYP><Marker><Android><Master> Saying seatbelt and AC turn on sound notification for Non AC driver (Parent id_1980)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#7276]
#1980 

[Saying seatbelt and AC turn on sound notification for Non AC driver when ride got started ](https://drive.google.com/file/d/1r_9uVSiN0EraTwoSfL1CsljnmvvdDPnz/view?usp=sharing)

1. Take NON AC ride 
2. Start the ride
3. Verify the notification sound

**Comment by PraveenGongada** [comment]
It is coming as AC Ride, that is the reason for sound

**Comment by 123ajay1994** [comment]
re tested and booked for Non Ac Ride. 
Now it is not coming. 
Checked for AC Ride and Non AC ride as well. 
It is working fine now so closing this ticket. 
https://drive.google.com/file/d/1_qLWIRB9nMF-vLNmKDYLSo5KIkih657j/view?usp=sharing
