### ISSUE TITLE
11/06/24_<NY><Android><Master> <others> The skip button for the referral code is cropped.(Parent id_1980)

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#7279]
#1980
The skip button for the referral code is cropped.[[here](https://drive.google.com/file/d/1ouOA4IVShkmhxl1YtDx95rg7FxsYqQLQ/view?usp=sharing)]

Steps to reproduce

1.Launch the application
2.Login with the valid credentials
3.Click on the referral code located on home page
4.The skip button for the referral code is cropped. 

Device details : Redmi Note 7 Pro , Android 10
Frequency : 5/5

**Comment by Vinaykm999** [comment]
Working as expected .Checked in redmi device. Hence resolving this.



![Image](https://github.com/nammayatri/nammayatri/assets/131981246/5b9e33a5-bc30-4354-b99d-1caa3c035ddc)
