### ISSUE TITLE
11/06/24_<NY><Android><Master> <others>Referral code is accepting inappropriate values(Parent id_1980)

### ISSUE THREAD

**Issue by spoorthipbhat** [nammayatri/nammayatri#7280]
#1980
The referral code for Yatri users must be a combination of six alphanumeric characters. However, it's currently accepting codes that are solely six alphabetical characters, numerical characters, alphabetic characters with dots, or numeric characters with dots.[[here](https://drive.google.com/file/d/1ouOA4IVShkmhxl1YtDx95rg7FxsYqQLQ/view?usp=sharing)]

Steps to reproduce

1. Launch the application
2. Login with valid credentials
3. Click on referral code located on the home page
4. Enter referral code for Yatri users must be a combination of six alphanumeric characters. However, it's currently accepting codes that are solely six alphabetical characters, numerical characters, alphabetic characters with dots, or numeric characters with dots. 

Device details : Redmi Note 8 Pro
Frequency : 5/5

**Comment by saikrishnateja12** [comment]
I have re-tested the issue.The issue still exists.Since I'am moving it to backlog[ PFA](https://drive.google.com/file/d/1lD1HvrZ-8FgnAz60LqLKUmMygcIOYSHP/view?usp=sharing)

**Comment by MercyQueen** [comment]
. won't be accepted now.
if user enters only numbers or only alphabets that is also acceptable

**Comment by spoorthipbhat** [comment]
Issue resolved, Therefore, I am closing this issue.
