### ISSUE TITLE
13/06/24_<NY><Android><Master> <others>When there is only one vehicle in estimates it is showing too much white space.(Parent id_1980)

### ISSUE THREAD

**Issue by vishal13d** [nammayatri/nammayatri#7306]
**Describe the bug**
When there is only one vehicle in estimates it is showing too much white space in estimate screen

**To Reproduce**

1. login to NY
2. enter source and destination
3. tap on book the ride
4. scroll the estimate page
5. obseve the screen

**Expected behavior**
It should not show white space if there is only one vehicle

**Screenshots**
https://drive.google.com/file/d/1v9hgaWQExOpeUG2mFBpg5zndnRS6MnTy/view?usp=sharing

**Comment by aryan-13** [comment]
Expected
