### ISSUE TITLE
13/06/24_<NY><Android><Master> <others>In Booking Preferences for XL cab, it displays hatchback AC and non-AC options. When the toggle is turned off, the non-AC mini variant is not visible.(Parent id_1980)

### ISSUE THREAD

**Issue by saikrishnateja12** [nammayatri/nammayatri#7311]
[In Booking Preferences for XL cab, it displays hatchback AC and non-AC options. When the toggle is turned off, the non-AC mini variant is not visible.](https://drive.google.com/file/d/1BnK-Fga8yPFTRNBjEy11RdnPKZkcPCnh/view?usp=sharing)
Steps to Produce:
1.Log in with credentials
2.Go to booking preferences screen 
3.Observe variants you have 
4.And turn of the XL variant 
Frequency:5/5

**Comment by witcher-shailesh** [comment]
Will recheck this once in PROD once to verify
