### ISSUE TITLE
16/06/24_<NY><Android><Master> In Ride Assigned Screen, Getting Green location pointer for destination instead of Red pointer (Parent id_1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#7374]
#1980 
[Getting Green location pointer for destination instead of Red pointer in ride Assigned Screen](https://drive.google.com/file/d/17jposnsKRADJPZj8YeZz2Zf-eRZ6wA_n/view?usp=sharing)

**Steps To Reproduce**
1. Launch the application and login with the valid credentials 
2. Assign and start the ride and observe the issue in the ride assigned screen 

**Expected Result**
Once the ride got started, user should get red color pointer as the destination location marker

**Actual Result**
Getting Green color pointer as the destination marker

**Comment by 123ajay1994** [comment]
Duplicate hence Closing
