### ISSUE TITLE
 24/06/24_YS_Android_ProdRegressionKolkata _Customer tip is not coming in YS_Parent id_2096)

### ISSUE THREAD

**Issue by saikrishnateja12** [nammayatri/nammayatri#7515]
**Description of  the bug**
[Customer tip is not coming in YS](https://drive.google.com/file/d/14MHPQLuSg5NtJsT0BTXmychFaZZwP_m6/view?usp=sharing)
**Steps To Reproduce**

1. log in  to the app
2. Search for a ride dont accept any ride
3. observe the screen you will not get customer tip 

**Expected behavior**
customer tip should get

**Comment by Arun12Deepak** [comment]
Working Fine [PFA](https://drive.google.com/file/d/1MiMtq_RfDDYJHvP9hvFFC7ly8qAzWyDi/view?usp=sharing)
