### ISSUE TITLE
24/06/24_YS_Android_ProdRegressionKolkata _ cross button was not working for chat (device specific)_Parent id_2096)

### ISSUE THREAD

**Issue by saikrishnateja12** [nammayatri/nammayatri#7526]
**Description of the bug**
[cross button was not working for chat ](https://drive.google.com/file/d/1QjVrkI5BbDwpNlONBboNraY0xA8Sc2qP/view?usp=sharing)
**To Reproduce**

1. book a ride.Don't start the ride 
2. when the chat comes try to click cross button it will not work

**Expected behavior**
cross button should work

**Device:**
 - Device: Techno pop 7 pro
 - OS: Andriod 12
 - Version 12

**Comment by Arun12Deepak** [comment]
Working Fine [PFA](https://drive.google.com/file/d/10fuk8sPZlO30LQdYXs03M7uC5hsjljmZ/view?usp=sharing)
