### ISSUE TITLE
25/06/24_YS_Android_ProdRegressionKolkata _For user side "driver is waiting at pickup"text is coming in two lines _Parent id_2096)

### ISSUE THREAD

**Issue by saikrishnateja12** [nammayatri/nammayatri#7532]
**Describe the bug**
[For user side "driver is waiting at pickup"text is coming in two lines](https://drive.google.com/file/d/1suLS7CD-4blyUjPasRqA7_SnpxQbQ3Xb/view?usp=sharing)
**To Reproduce**
Steps to reproduce the behavior.
1. book a rental ride
2. observe the line "driver is waiting for you"

**Expected behavior**
It should come in single line 

**Device:**
 - Device: Techno pop 7 pro
 - OS: Andriod
 - Version 12

**Additional context**

**Comment by Arun12Deepak** [comment]
Working Fine - [PFA](https://drive.google.com/file/d/1x73YhyhAklYqwc0TSR2UIKtByEVh_iV7/view?usp=sharing)
