### ISSUE TITLE
25/06/24_YS_Android_For rentals start and end otp was not coming in the screen it is coming only in the chatting  _Parent id_2096)

### ISSUE THREAD

**Issue by saikrishnateja12** [nammayatri/nammayatri#7536]
**Describe the bug**
For rentals start and end otp was not coming in the screen it is coming only in the chatting   
[Link1](https://drive.google.com/file/d/1bAeTb9WbCVy-K_xpk9RpSqRzz83A4Qzb/view?usp=sharing)
[Link2](https://drive.google.com/file/d/1snaWrDBMKeqhjHa1U30UckkSQIxACWoH/view?usp=sharing)
**To Reproduce**
Steps to reproduce the behavior.

1. book a rental ride 
2. observe the user side otp will be there in the chatting screen and start the ride 
3. end ride otp also will not come in the scree it will come in the chat 

**Expected behavior**
otp should come in screen

**App (please complete the following information):**

-  Device: Techno pop 7 pro
- OS: Andriod
- Version 12

**Comment by Arun12Deepak** [comment]
Working Fine    [PFA](https://drive.google.com/file/d/1wl33qUOJelxtSh0GsyZm-UAEZ3SHlUgT/view?usp=sharing)
