### ISSUE TITLE
01/07/24_YS_Android_ProdRegressionKolkata _Waiting time analog is not displaying in user side _Parent id_2096)

### ISSUE THREAD

**Issue by saikrishnateja12** [nammayatri/nammayatri#7612]
**Describe the bug**
[Waiting time analog is not displaying in user side](https://drive.google.com/file/d/1oOjNFn1EHeudeic20FuFixXxsbXsQEet/view?usp=sharing)

**To Reproduce**

1. log in with valid valid credentials
2. after assigning the ride wait for the analog to come
3. now observe the customer side analog will not display

**Expected behavior**
It should show analog in the display for customer side

**Comment by Arun12Deepak** [comment]
Working Fine    [PFA](https://drive.google.com/file/d/1AT3NInwOwqANin8ajCnhzIDraaKV0YJz/view?usp=sharing)
