### ISSUE TITLE
01/07/24_YS_Android_ProdRegressionKolkata _Waiting time is 2min in the ui it is showing 2rupee but in the invoice it is adding 8rupee _Parent id_2096)

### ISSUE THREAD

**Issue by saikrishnateja12** [nammayatri/nammayatri#7613]
**Describe the bug**
[Waiting time is 2min in the ui it is showing 2rupee but in the invoice it is adding 8rupee](https://drive.google.com/file/d/1-s07CgZ4vQpI5137grYNln_T9YJB88Td/view?usp=sharing)

**To Reproduce**

1. log in with valid credentials 
2. after assigning the ride 
3. wait for 7 min
4. complete the ride 
5. now observe the invoice 

**Expected behavior**
waiting time charges should display correctly

**Comment by Arun12Deepak** [comment]
1.In user side waiting time is not displaying but in invoice Waiting Charges are displayed

**Comment by Arun12Deepak** [comment]
Working fine [PFA](https://drive.google.com/file/d/11ZAYvegUBsE-7-S6C_nh6_CORAXcrjXV/view?usp=sharing)

**Comment by Arun12Deepak** [comment]
Working fine [PFA](https://drive.google.com/file/d/11ZAYvegUBsE-7-S6C_nh6_CORAXcrjXV/view?usp=sharing)

**Comment by Arun12Deepak** [comment]
Working fine [PFA](https://drive.google.com/file/d/11ZAYvegUBsE-7-S6C_nh6_CORAXcrjXV/view?usp=sharing)
