### ISSUE TITLE
01/07/24_YS_Android_ProdRegressionKolkata _For user it is not showing location text when confirming the location _Parent id_2096)

### ISSUE THREAD

**Issue by vishal13d** [nammayatri/nammayatri#7617]
**Describe the bug**
When user selecting, special zone as drop location at that time, text for confirm location is coming as blank

**To Reproduce**
Select the pickup location
select any special zone as drop location 
then tap on confirm 
observe the screen

**Expected behavior**
It should show the pickup location address while confrim the loction

**Screenshots**
https://drive.google.com/file/d/1bNaTdwslBeYe3GzQyYz3QiWYqjaSrmIB/view?usp=sharing

**Comment by Arun12Deepak** [comment]
Working Fine  [PFA](https://drive.google.com/file/d/1cFLFV9GmBLt4H5W1sWXros8e_8PeZ6FN/view?usp=sharing)
