### ISSUE TITLE
01/07/24_YSP_Android_ProdRegressionKolkata _When user click on "Yatri Sathi Parivaar ka hisssa bane" banner at that page, text is in every language except Bengali _Parent id_2096)

### ISSUE THREAD

**Issue by vishal13d** [nammayatri/nammayatri#7620]
**Describe the bug**
When user click on "Yatri Sathi Parivaar ka hisssa bane" banner at that page, text is in every language except Bengali

**To Reproduce**
Open the apk
click on "Yatri Sathi Parivaar ka hisssa bane" banner
observe the screen

**Expected behavior**
Text should come in Bengali language also

**Screenshots**
https://drive.google.com/file/d/1YoOPvx11d7_Ql0dYy-MN3g0Y81hMKIj2/view

**Comment by Kuldeepkumawat144** [comment]
Its not reproducing 
@krupal-24 @vishal13d

**Comment by slow-codex** [comment]
@vishal13d It is expected, as the screenshot you showed is the yatri sathi driver whatsapp channel description (As per external communication)
