### ISSUE TITLE
01/07/24_YSP_Android_ProdRegressionKolkata _ After starting thr ride driver getting "sakkath" word in PN_Parent id_2096)

### ISSUE THREAD

**Issue by vishal13d** [nammayatri/nammayatri#7622]
**Describe the bug**
After starting thr ride driver getting "sakkath" word in PN

**To Reproduce**
Accept the ride
enter the otp
check the pn

**Expected behavior**
it should not show word "sakkath"

**Screenshots**
https://drive.google.com/file/d/11iFIFzffSSkAWXbvTfzcxw6KuqF8Z2tk/view?usp=sharing

**Comment by slow-codex** [comment]
Already fixed in current main, will go live with the release of backend

**Comment by srijanidas-ny** [comment]
@vishal13d backend release is done. It should be fixed now. Please confirm

**Comment by vishal13d** [comment]
Checked in CUG working fine - https://drive.google.com/file/d/1GnPUAaOsspqKqS9JT6sugrSqkJ4GRRoq/view?usp=sharing
Version - v1.4.23-[1.8.392]
