### ISSUE TITLE
01/07/24_YS_Android_ProdRegressionKolkata _Reallocation is not happening in rentals for YS _Parent id_2096)

### ISSUE THREAD

**Issue by saikrishnateja12** [nammayatri/nammayatri#7634]
**Describe the bug**
Reallocation is not happening in rentals for YS

**To Reproduce**

1. log in with valid credentials
2. try to book. rental ride 
3. do reallocation
4. and observe the user side screen

**Expected behavior**
reallocation should happen

**Comment by Arun12Deepak** [comment]
Working Fine  [PFA](https://drive.google.com/file/d/15kAJ8PmP5iBS1gCy3wZSTu5tV5mjWOre/view?usp=sharing)
